- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration/Binding/BindingWorkflow.cs
Remove workflow steps (and associated tests) related to Additional Files.
> [SVS-35] Remove Additional Files

- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration.UnitTests/VsShellUtilsTests.cs
- src/Integration/Binding/BindingWorkflow.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
- src/Integration/VsShellUtils.cs
- src/TestInfrastructure/VsObjectModelMocks/SolutionMock.cs
#SVS-36
Misc: modified execution preference of one of the steps.
> [SVS-36] Save (with prompt) before binding and after (without prompt)

- src/Integration.UnitTests/Binding/ProjectRuleSetWriterTests.cs
Test failed after rebase from PR19 and wasn't caught before merging into master.
> [Technical] Fix failing test; rebase issues caused missing commit

- src/Integration/Connection/BasicAuthenticationCredentialsValidator.cs
- src/Integration/Connection/UI/ConnectionInfoDialogView.xaml
- src/Integration/Connection/UI/ConnectionInfoDialogViewModel.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
Tokens don't require a password. This validation prevented the use of tokens.
> [SVS-49] Don't require password with username

- src/Integration.UnitTests/Binding/ProjectBindingOperationTests.cs
- src/Integration/Binding/ProjectBindingOperation.cs
Support existing null/empty/etc rulesets
> [SVS-55] Fix regression introduced by SVS-17

- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/LocalServices/RuleSetInspectorTests.cs
- src/Integration/Constants.cs
- src/Integration/Integration.csproj
- src/Integration/LocalServices/IRuleSetInspector.cs
- src/Integration/LocalServices/RuleConflictInfo.cs
- src/Integration/LocalServices/RuleSetInspector.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
- src/TestInfrastructure/Framework/ConfigurableVsShell.cs
- src/TestInfrastructure/TestInfrastructure.csproj
Focused only on detection.
More to follow: 
* Fixing (I described how I plan to do it in the code comments)
* Integrating with VS 
All of which I plan to do as separate PR.
> [SVS-7] 1st part - detect "conflicts" with the ruleset from SQ

- src/Integration.UnitTests/Binding/ProjectBindingOperation.WriterTests.cs
- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/LocalServices/RuleSetInspectorTests.cs
- src/Integration.UnitTests/RuleSetHelperTests.cs
- src/Integration/Binding/ProjectBindingOperation.Writer.cs
- src/Integration/Integration.csproj
- src/Integration/LocalServices/IRuleSetInspector.cs
- src/Integration/LocalServices/RuleConflictInfo.cs
- src/Integration/LocalServices/RuleSetInspector.cs
- src/Integration/RuleSetHelper.cs
- src/TestInfrastructure/Helpers/RuleSetAssert.cs
Implemented and tested the fix logic.
I also had to move some of the rule set manipulation logic into a common helper (along with the tests).
> [Svs-7] 2nd part - fix conflicts in-memory

- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration.Vsix/Telemetry/SonarLintIntegrationPackage.IOleCommandTarget.cs
- src/Integration.Vsix/Telemetry/TelemetryLogger.cs
- src/Integration/TeamExplorer/SectionController.cs
+ Fix double entry for browse commands
> [SVS-75] Support vs/core/extension/used telemetry in addition to vs/command/core

- src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
Missed pushing a commit addressing some minor comments from [this](https://github.com/SonarSource-VisualStudio/sonarlint-visualstudio/pull/52) pull request.
Address Eyal's comments.
> [SVS-78] Fix issue with request URL construction (missing commit)

- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/LanguageTests.cs
- src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs
- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration.UnitTests/ProfileConflicts/FixedRuleSetInfoTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleConflictInfoTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleSetInspectorTests.cs
- src/Integration.UnitTests/Service/ConnectionInformationTests.cs
- src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
- src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
- src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs
- Language.ForProject
- ConnectionInformation.Ctor
- SectionController
- SonarQubeServiceWrapper
- SolutionBindingOperation
- SolutionRuleSetsInformationProvider
- Various (null arg checks)
> Add test coverage for various components to meet quality gate

- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/LocalServices/ProjectSystemHelperTests.cs
- src/Integration.UnitTests/LocalServices/RuleSetSerializerTests.cs
- src/Integration.UnitTests/ProfileConflicts/ProjectRuleSetConflictTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleSetInformationTests.cs
- src/Integration.UnitTests/SonarAnalyzer/ActiveSolutionBoundTrackerTests.cs
- src/Integration.UnitTests/VsSessionHostTests.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/SonarAnalyzer/SonarAnalyzerDeactivationManagerTests.cs
- src/Integration.Vsix.UnitTests/Telemetry/TelemetryLoggerTests.cs
- src/Integration/Integration.csproj
- src/Integration/LocalServices/ProjectSystemFilter.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/TestInfrastructure/TestInfrastructure.csproj
- src/TestInfrastructure/TestInfrastructure.ruleset
- src/TestInfrastructure/VsObjectModelMocks/CommandsMock.cs
- src/TestInfrastructure/VsObjectModelMocks/DTEMock.cs
There were minor changes in product code, nothing that resets testing (I've raised explicit comments)
> Fix test gaps for quality gate compliance

- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
- src/Integration.UnitTests/RuleSetHelperTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/Integration.csproj
- src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
- src/Integration/LocalServices/SolutionBindingInformationProvider.cs
- src/Integration/RuleSetHelper.cs
- src/Integration/VsShellUtils.cs
- src/TestInfrastructure/Framework/ConfigurableRuleSetSerializer.cs
At the moment we only discover based on binding information and rule sets
> [SVS-9] Add a service that discovers bound projects.

- src/Integration/TeamExplorer/CommonStyles.xaml
- src/SonarQube/SolutionBinding.sqconfig
- src/SonarQube/sonarlint-visualstudioCSharp.ruleset
This has already been LGTM'd in previous PR #78
> [SVS-21] [Again] Allow to scroll in the SonarQube projects lists when binding

- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> [SVS-59] [Again] Update "Username" label to "Username/Token"

- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration/Binding/BindingWorkflow.cs
that's very similar to our client pull request, but we should be able to report progress on nuget installing too
> SVS-123: Unexpected error during workflow execution: Invalid range. Expected [X, Y]

- build.cmd
- build/build.ps1
- src/Integration.UnitTests_2017/app.config
- src/Integration.Vsix.UnitTests_2017/app.config
- src/Integration.Vsix/packages.config
- src/Integration.Vsix_2017/packages.config
- src/TestInfrastructure_2017/app.config
> Provide a digital signature to the extension

- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# v5.11

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embeds SonarC# 6.1

- src/Integration/Telemetry/TelemetryManager.cs
- src/Integration/Telemetry/TelemetryPayload.cs
> Add Visual Studio version to telemetry data

- src/Integration.Vsix/SonarLintDaemonPackage.cs
> Make the Daemon package non-async

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# 6.4

- src/Integration.UnitTests/Suppression/ChecksumCalculatorTests.cs
- src/Integration/Suppression/ChecksumCalculator.cs
> Added checksum calculator

- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/Suppression/DelegateInjectorTests.cs
- src/Integration.Vsix.UnitTests/packages.config
- src/Integration.Vsix.UnitTests_2017/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests_2017/packages.config
- src/Integration.Vsix/Suppression/DelegateInjector.cs
- src/Integration.Vsix/Suppression/SuppressionManager.cs
- src/TestInfrastructure/Helpers/TestDomainWrapper.cs
> Implemented suppression delegate injector

- src/Integration/MefServices/MefSonarQubeService.cs
> Add a hacky way to be connected on load

- src/Integration.UnitTests/Connection/ConnectControllerTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.Vsix/Settings/SonarLintSettings.cs
- src/Integration/Connection/ConnectionController.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/MefServices/ISonarLintSettings.cs
- src/Integration/MefServices/MefSonarQubeService.cs
- src/SonarQube.Client.Tests/Services/SonarQubeClientTests.cs
- src/SonarQube.Client.Tests/Services/SonarQubeServiceTests.cs
- src/SonarQube.Client/Services/ISonarQubeClient.cs
- src/SonarQube.Client/Services/ISonarQubeClientFactory.cs
- src/SonarQube.Client/Services/SonarQubeClient.cs
- src/SonarQube.Client/Services/SonarQubeClientFactory.cs
- src/SonarQube.Client/Services/SonarQubeService.cs
- src/TestInfrastructure/Framework/ConfigurableIntegrationSettings.cs
With these changes it is now possible to have a working binding.
> Various fixes

- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
Fix for debug assert that was occurring during manual testing (assertion that we'd failed to retrieve the GUID for a project file).
The live issue factory can be created when a solution has opened but is not fully loaded. In this case, some of the projects will still be marked as unloaded (i.e. not yet fully loaded). Simple fix - just include unloaded projects when building the mapping.
This does mean that a project that is really unloaded (because the user has explicitly chosen to unload it using the context menu) will still be included in the mapping. However, that won't cause any issues at runtime. Analyzers won't be run against unloaded projects, so we'll just have an entry in the mapping that won't every be matched against.
> Fix issue generating project file -> guid mapping

- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/TeamExplorer/SectionController.cs
With these changes the background connections for the error list and suppressions work correctly with the TE.
> Fix SQ server connection issues

- src/Integration.UnitTests/Suppression/ChecksumCalculatorTests.cs
- src/Integration.Vsix.UnitTests/Helpers/FileUtilitiesTests.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/Suppression/DelegateInjectorTests.cs
- src/Integration.Vsix.UnitTests/packages.config
- src/Integration.Vsix.UnitTests_2017/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests_2017/packages.config
- src/Integration.Vsix/Helpers/FileUtilities.cs
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration.Vsix/Suppression/DelegateInjector.cs
- src/Integration.Vsix/Suppression/LiveIssue.cs
- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
- src/Integration.Vsix/Suppression/SuppressionManager.cs
- src/Integration.Vsix/packages.config
- src/Integration/Integration.csproj
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/Suppression/ChecksumCalculator.cs
- src/Integration/Suppression/ISonarQubeIssuesProvider.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/Integration/packages.config
- src/Progress/Progress.csproj
- src/Progress/packages.config
- src/ProgressVS/ProgressVS.csproj
- src/ProgressVS/packages.config
- src/SonarQube.Client/SonarQube.Client.csproj
- src/SonarQube.Client/SonarQube.Client.ruleset
- src/SonarQube.Client/packages.config
- src/SonarQube/sonarlint-visualstudioCSharp.ruleset
- src/TestInfrastructure/Helpers/TestDomainWrapper.cs
> SonarLint should not show issues marked as FP, Won't Fix or Fixed

- src/SonarQube.Client.Tests/Services/SonarQubeClientFactoryTests.cs
- src/SonarQube.Client.Tests/Services/SonarQubeClientTests.cs
- src/SonarQube.Client.Tests/Services/SonarQubeServiceTests.cs
- src/SonarQube.Client/Services/SonarQubeService.cs
> Improve Code Coverage for SonarQube Client

- src/Integration.Vsix/Suppression/LiveIssue.cs
- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
> Handle suppression of issues at file level

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
Added more unit tests for the issue provider
> Changed GetIssues to wait for initial issues fetch to complete

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
Amended existing tests to fix timing issues
> Tests for errors on background threads when fetching issues

- build/build.ps1
> Update the build script to provide the new analysis parameters

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/TeamExplorer/SectionController.cs
> Pressing Disconnect from the UI now disconnects SonarQubeService

- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/Suppression/DelegateInjectorTests.cs
- src/Integration.Vsix.UnitTests/app.config
- src/Integration.Vsix.UnitTests/packages.config
- src/Integration.Vsix.UnitTests_2017/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests_2017/app.config
- src/Integration.Vsix.UnitTests_2017/packages.config
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Suppression/DelegateInjector.cs
- src/Integration.Vsix/Suppression/LiveIssue.cs
- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
- src/Integration.Vsix/Suppression/SuppressionManager.cs
- src/Integration.Vsix/app.config
- src/Integration.Vsix/packages.config
- src/Integration.Vsix_2017/Integration.Vsix.csproj
- src/Integration.Vsix_2017/app.config
- src/Integration.Vsix_2017/packages.config
- src/TestInfrastructure/TestInfrastructure.csproj
- src/TestInfrastructure/app.config
- src/TestInfrastructure/packages.config
- src/TestInfrastructure_2017/TestInfrastructure.csproj
- src/TestInfrastructure_2017/app.config
- src/TestInfrastructure_2017/packages.config
Fix #345 
System.Collections.Immutable is not directly related to this feature but I had to do this rollback in order to avoid some crash. This is a bug we introduced 10 months ago but that didn't impacted us until now.
>  Handle project-level issues

- src/Integration.Vsix/SonarLintNotificationsPackage.cs
> fix notifications to appear after reopening solution

- src/Integration/Notifications/NotificationIndicator.xaml
Address part of @christophelevis comments.
Remove "Latest" from the header, "Congratulations" from the message when there are no events, and an indentation in first line of the message.
> Tweaks to notification tooltip layout

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
The fix is simple: the slow part was adding the tests.
BTW I noticed that the ErrorListBarController is also directly calling _this.host.ActiveSection.DisconnectCommand_. I'll send a separate PR for that.
> Fixed #369 - not disconnecting on solution close

- src/Integration.UnitTests/Notifications/SonarQubeNotificationServiceTests.cs
- src/Integration/Notifications/SonarQubeNotificationService.cs
Addressing remaining PM comments.
> Do not trace notification failures if they are disabled

- src/Integration.UnitTests/Notifications/SonarQubeNotificationServiceTests.cs
Caused by Visual Studio hiccup, or more likely, PEBKAC.
> fix broken test

- src/SonarQube.Client.Tests/Services/SonarQubeServiceTests.cs
- src/SonarQube.Client/Services/SonarQubeService.cs
> Adding OrganizationKey to the project search API request

- src/SonarQube.Client.Tests/Services/SonarQubeClientTests.cs
- src/SonarQube.Client/Services/SonarQubeClient.cs
> Improve handling of errors to not fail with NullPointerException

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
Removed obsolete TODO from code and commented out checks from tests.
> Cleaned up solution tracker tests

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
Initial fetch task is cancelled on dispose
> Fix issues provider tests

- .github/ISSUE_TEMPLATE.md
Requested more info: SQ server version and languages being used
> Amended issues template

- src/Integration.Vsix.UnitTests/Suppression/LiveIssueFactoryTests.cs
- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
- src/Integration.Vsix/Suppression/SuppressionManager.cs
> Correctly handle duplicate solution folders

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Fixed #427: updated embedded SonarC# and SonarVB

- src/Integration.UnitTests/LanguageTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration/Language.cs
- src/Integration/LocalServices/IProjectSystemHelperExtensions.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/ProjectToLanguageMapper.cs
* language -> project is not a 1-1 mapping
> Remove project type from Language class

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Update SonarLint Daemon to version 2.18.0.1070

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Update SonarLint Daemon to version 3.0.0.1140

- src/Integration.UnitTests/Binding/ProjectBindingOperationTests.cs
- src/Integration.UnitTests/LanguageTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration/Language.cs
- src/Integration/LocalServices/IProjectSystemHelper.cs
- src/Integration/LocalServices/IProjectSystemHelperExtensions.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
- src/Integration/MefServices/ProjectPropertyManager.cs
- src/Integration/ProjectToLanguageMapper.cs
- src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs
- src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs
> Enable .Net Core support for Connected Mode

- src/SonarQube.Client.Tests/Services/SonarQubeServiceTests.cs
- src/SonarQube.Client/Messages/RoslynExportProfileRequest.cs
- src/SonarQube.Client/Services/SonarQubeService.cs
> Connected mode always fetches the default quality profile for SQ6.6+

- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
> Send days_since_installation=0 on the installation day

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC#/SonarVB 6.7.1

- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration/Binding/BindingWorkflow.cs
- src/SonarQube.Client.Tests/Services/SonarQubeServiceTests.cs
- src/SonarQube.Client/Messages/RoslynExportProfileRequest.cs
- src/SonarQube.Client/Services/ISonarQubeService.cs
- src/SonarQube.Client/Services/SonarQubeService.cs
> Fix custom Quality Profile sync with SonarQube with organizations

- src/Integration.Vsix.UnitTests/DeprecationManagerTests.cs
- src/Integration.Vsix/InfoBar/InfoBarManager.cs
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration/DeprecationManager.cs
- src/Integration/MefServices/IInfoBarManager.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBar.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBarManager.cs
Fix #476
Screenshot of the message bar:
Screenshot of the output window:
> Add user notification when using VS 2015 < U3

- src/Integration.Vsix.UnitTests/SonarLintTracker/IssuesSnapshotTests.cs
- src/Integration.Vsix/SonarLintTagger/IssuesSnapshot.cs
> Fix the help link for additional languages

- src/Integration.Vsix.UnitTests/Commands/ProjectSonarLintMenuCommandTests.cs
- src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs
- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlTests.cs
- src/Integration.Vsix/Commands/ProjectSonarLintMenuCommand.cs
- src/Integration.Vsix/InfoBar/InfoBarManager.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/Integration/MefServices/IInfoBarManager.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBarManager.cs
Minor refactoring of the info bar controller
> Improve code coverage

- src/Integration.Vsix.UnitTests/SonarLintTracker/IssuesSnapshotTests.cs
- src/Integration.Vsix/SonarLintTagger/IssuesSnapshot.cs
> Append the severity to the issue type in the category column

- src/Integration.Vsix.UnitTests/SonarLintDaemon/LegacyInstallationCleanupTests.cs
- src/Integration.Vsix/SonarLintDaemon/LegacyInstallationCleanup.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemonPackage.cs
- src/Integration/Helpers/IO/DirectoryWrapper.cs
- src/Integration/Helpers/IO/IDirectory.cs
- src/Integration/Telemetry/TelemetryDataRepository.cs
Fix #470 - don't install the daemon to the roaming profile
> Fix #470 - don't install the daemon to the roaming profile

- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.Vsix.UnitTests/DeprecationManagerTests.cs
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/DeprecationManager.cs
- src/Integration/Helpers/VisualStudioHelpers.cs
- src/Integration/Service/DataModel/MinimumSupportedServerPlugin.cs
> Do not allow to install new major version SonarC# / SonarVB on old VS

- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
- src/Integration/LocalServices/ISolutionRuleSetsInformationProvider.cs
- src/Integration/LocalServices/SolutionBindingInformationProvider.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/NewConnectedMode/ConnectionMode.cs
- src/Integration/NewConnectedMode/IConfigurationProvider.cs
- src/Integration/NewConnectedMode/LegacyConfigurationProviderAdapter.cs
- src/Integration/NewConnectedMode/SonarLintMode.cs
- src/Integration/ProfileConflicts/ConflictsManager.cs
- src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs
New pull request for the same changes, but this time targeting the correct dev branch.
> Added IConfigurationProvider

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Embed sonarlint daemon version 3.1.0.1376

- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
- src/Integration/LocalServices/SolutionBindingInformationProvider.cs
- src/Integration/NewConnectedMode/IConfigurationProvider.cs
- src/Integration/NewConnectedMode/LegacyConfigurationProviderAdapter.cs
- src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs
- src/TestInfrastructure/Framework/ConfigurableServiceProvider.cs
- src/TestInfrastructure/Framework/ConfigurableSolutionBindingInformationProvider.cs
Refactoring of existing code and unit tests
> Modified ErrorListController to only operate in legacy mode

- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration/ProfileConflicts/ConflictsManager.cs
> Changed conflicts manager to only run in legacy connected mode

- src/Integration.Vsix/SonarLintIntegrationPackage.cs
Not sure it is/was worth testing the class so I have added it to the exclusion list.
> Exclude package from code coverage

- src/Integration.UnitTests/NewConnectedMode/ConfigurationProviderTests.cs
- src/Integration.UnitTests/NewConnectedMode/InMemoryConfigurationProviderTests.cs
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/NewConnectedMode/ConfigurationProvider.cs
- src/Integration/NewConnectedMode/IConfigurationProvider.cs
- src/Integration/NewConnectedMode/InMemoryConfigurationProvider.cs
Modified the serialization for the new connected mode to write the config to the .suo file.
> Write the binding config to the .suo file

- build/build-utils.ps1
If this works, I'll check the other build scripts.
> Fixed build script to use TLS v1.2

- src/Integration.Vsix/Delegates/SonarAnalyzerConnectedWorkflow.cs
- src/Integration/Binding/BindingWorkflow.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Helpers/IServiceProviderExtensions.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/Integration/NewConnectedMode/NewBindingWorkflow.cs
Conditional(DEBUG) methods still count towards code coverage.
Changed all of the Conditional(DEBUG) methods that were only called once with #if DEBUG blocks instead.
> Changed most occurrences of Conditional(DEBUG) to #if DEBUG

- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration/Telemetry/TelemetryData.cs
Test was broken by the change to daylight saving time
> Fixed failing unit test

- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
- src/Integration/Binding/BindingWorkflow.cs
- src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
- src/Integration/LocalServices/SolutionBindingInformationProvider.cs
- ISolutionBindingInformationProvider.GetBoundProjects was not used. Removed declaration and implementation and fixed up tests.
- Miscellaneous: added documentation to binding workflow
> Removed redundant interface method

- src/Integration.UnitTests/NewConnectedMode/ConfigurationSerializerTests.cs
- src/Integration.Vsix.UnitTests/Telemetry/BoundSolutionAnalyzerTests.cs
- src/Integration.Vsix/BoundSolutionAnalyzer.cs
- src/Integration/NewConnectedMode/ConfigurationSerializer.cs
- src/Integration/Persistence/SolutionBindingSerializer.cs
... to .slconfig.
Fixed up legacy telemetry to detect new connected mode solutions.
> Changed new config file extension

- src/Integration.UnitTests/LocalServices/ProjectSystemHelperTests.cs
- src/Integration.Vsix/BoundSolutionAnalyzer.cs
- src/Integration.Vsix/Delegates/SonarAnalyzerWorkflowBase.cs
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/NewConnectedMode/BindingConfiguration.cs
Minor issues: removing unused fields, sealing a class and adding a call to _GC.SuppressFinalization(this)_
> Fix leak period issues

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Update daemon to version 3.4.0.1536

- src/Integration.UnitTests/Telemetry/ShortIsoDateTimeOffsetConverterTests.cs
- src/Integration/Telemetry/ShortIsoDateTimeOffsetConverter.cs
> Fix telemetry dates by handling properly cultures

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC#/SonarVB 7.2

- src/Integration.UnitTests/Helpers/VsShellUtilsTests.cs
- src/Integration/Helpers/VsShellUtils.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
- src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs
> Handle configuration manager being null

- src/Integration/Helpers/ILoggerExtensions.cs
- src/Integration/Helpers/LoggingHttpClientHandler.cs
- src/Integration/MefServices/MefSonarQubeService.cs
- src/SonarQube.Client/Services/RequestFactory.cs
Not much to test here as the logging is DEBUG-only
> Add logging for SonarQube requests when compilation is DEBUG

- src/Integration.Vsix.UnitTests/SonarLintDaemon/CFamilyTest.cs
- src/Integration.Vsix/SonarLintDaemon/CFamily.cs
- src/Integration.Vsix/SonarLintTagger/ISonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/SonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Fixed issues analysing C++ header files and files not in a project #674 (v2)

- src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
- src/SonarQube.Client/Api/DefaultConfiguration.cs
- src/SonarQube.Client/Api/Requests/V5_10/GetIssuesRequest.cs
- src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs
- src/SonarQube.Client/Models/SonarQubeIssue.cs
> Use api/issues/search to retrieve suppressed issues for SQ >= 7.2

- README.MD
> Update feedback section

- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTelemetryPackage.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
- src/Integration/Telemetry/ITelemetryManager.cs
- src/Integration/Telemetry/TelemetryManager.cs
> Convert telemetry package to load asynchronously

- src/Integration.UnitTests/Notifications/SonarQubeNotificationServiceTests.cs
- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
- src/Integration/Notifications/SonarQubeNotificationService.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/Integration_2017/Integration.csproj
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
- src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs
- src/TestInfrastructure/Framework/TestLogger.cs
Miscellaneous: adding logging output to the suppression manager
> Fixed #699 - suppressions not being fetched in SQ7.2

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC#/SonarVB 7.3

- src/Integration.UnitTests/WPF/ProjectViewModelToBindingArgsConverterTests.cs
- src/Integration/TeamExplorer/ConnectSectionView.xaml
- src/Integration/WPF/ProjectViewModelToBindingArgsConverter.cs
This ticket wasn't originally part of the sprint, but I've added it since it was an easy fix and the bug was annoying me (I was binding to a lot of projects as part of testing the other fixes).
> Fixed #642: double-click to bind

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Update SonarC# version

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarAnalyzer C# and VB.Net 7.5

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Embed SonarLint Daemon 3.9.0.1892

- src/Integration.UnitTests/app.config
- src/Integration.UnitTests_2017/app.config
- src/Integration.Vsix.UnitTests/app.config
- src/Integration.Vsix.UnitTests_2017/app.config
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Properties/AssemblyInfo.cs
- src/Integration.Vsix/app.config
- src/Integration.Vsix/packages.config
- src/Integration.Vsix_2017/Integration.Vsix.csproj
- src/Integration.Vsix_2017/app.config
- src/Integration.Vsix_2017/packages.config
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
- src/SonarQube.Client/SonarQube.Client.csproj
- src/SonarQube.Client/packages.config
- src/TestInfrastructure/app.config
- src/TestInfrastructure_2017/app.config
> Embed SonarC# and SonarVB 7.6

- src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
- src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs
> Fix NRE and wrong module key for module level issues

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.7.0.7192

- src/Integration.Vsix.UnitTests/SonarLintDaemon/CFamilyTest.cs
- src/Integration.Vsix/SonarLintDaemon/CFamily.cs
> Allow empty string values for some C++ compiler options

- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Added unit tests for TextBufferIssueTracker

- src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration.Vsix/SonarLintTelemetryPackage.cs
> Converted SonarLintIntegrationPackage to an asynchronous package

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.10.0.7896

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
Fix #763 
Simple smoke test seems to pass - C++ and JavaScript issues are shown in the error list and are underlined.
> Embed daemon version 4.0.2

- src/Integration.UnitTests/Service/ConnectionInformationTests.cs
- src/SonarQube.Client/Models/ConnectionInformation.cs
> Do not redirect when connecting to sonarcloud.io

- src/Integration.UnitTests/LocalServices/SourceControlledFileSystemTests.cs
- src/Integration/LocalServices/SourceControlledFileSystem.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
- src/TestInfrastructure/Framework/ConfigurableVsQueryEditQuerySave2.cs
> [DO NOT SQUASH] Fix #801: updating a bound solution failed in TfVC

- src/Integration/MefServices/MefSonarQubeService.cs
- src/SonarQube.Client.Tests/Api/DefaultConfiguration_Configure.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_Ctor.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetAllModulesAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetAllOrganizationsAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetAllPluginsAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetAllProjectsAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetAllPropertiesAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetNotificationEventsAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetProjectDashboardUrl.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetQualityProfileAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetRoslynExportProfileAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_HasOrganizationsFeature.cs
- src/SonarQube.Client.Tests/Api/SonarQubeService_TestBase.cs
- src/SonarQube.Client.Tests/Services/RequestFactoryTests.cs
- src/SonarQube.Client.Tests/TestLogger.cs
- src/SonarQube.Client/Api/PagedRequestBase.cs
- src/SonarQube.Client/Api/RequestBase.cs
- src/SonarQube.Client/Api/Requests/V5_10/GetIssuesRequest.cs
- src/SonarQube.Client/Api/Requests/V5_20/GetQualityProfilesRequest.cs
- src/SonarQube.Client/Api/Requests/V6_60/GetNotificationsRequest.cs
- src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs
- src/SonarQube.Client/Api/SonarQubeService.cs
- src/SonarQube.Client/Helpers/Logging/ILogger.cs
- src/SonarQube.Client/Services/RequestFactory.cs
> Add logging in SonarQube.Client

- build/ci-build.ps1
- ci-build.cmd
SonarQube-Next no longer supports sonar.analysis.mode=...
The scripts now use the same properties as the dotnet repo scripts.
> Modified build scripts to fix PR integration

- src/Integration.UnitTests/Binding/BindingControllerTests.cs
- src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/HostedCommandControllerBase.cs
- src/Integration/TeamExplorer/SectionController.cs
... rather than the TF IOleCommandTarget
> Converted commands to reference VS IOleCommandTarget

- .gitignore
- src/Integration.UnitTests/State/StateManagerTests.cs
- src/Integration/TeamExplorer/ConnectSectionViewModel.cs
- src/Integration/TeamExplorer/IConnectSectionView.cs
- src/Integration/TeamExplorer/IConnectSectionViewModel.cs
- src/Integration/TeamExplorer/ISectionController.cs
- src/Integration/TeamExplorer/SectionController.cs
- src/TestInfrastructure/Framework/ConfigurableSectionController.cs
> Introduced missing interfaces for Team Explorer components

- src/Integration.Vsix.UnitTests/SonarLintDaemon/CFamilyTest.cs
- src/Integration.Vsix/SonarLintDaemon/CFamily.cs
> Add support for cpp platform toolset v142

- Jenkinsfile
- build/ci-build.ps1
- build/poms/SonarLint.VSIX/pom.xml
- build/vs2017.bat
- build/vs2019.bat
- ci-build.cmd
- src/Integration.TeamExplorer.UnitTests/Integration.TeamExplorer.UnitTests.csproj
- src/Integration.TeamExplorer.UnitTests/ReferencesTests.cs
- src/Integration.TeamExplorer/Integration.TeamExplorer.csproj
- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/ReferencesTests.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration/Integration.csproj
- src/SonarLint.VSSpecificAssemblies.props
- src/TestInfrastructure/TestInfrastructure.csproj
> Update process so that our VS2017 CI machine produces the VS2019 artifact

- src/Integration.TeamExplorer.UnitTests/ReferencesTests.cs
- src/Integration.TeamExplorer.UnitTests/app.config
- src/Integration.UnitTests/ReferencesTests.cs
- src/Integration.UnitTests/app.config
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix.UnitTests/app.config
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Properties/AssemblyInfo.cs
- src/Integration.Vsix/packages.config
- src/Integration/app.config
- src/TestInfrastructure/Helpers/AssemblyHelper.cs
- src/TestInfrastructure/app.config
> Remove binding redirects

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.12.0.8217

- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Improve daemon error handling

- src/Integration.Vsix/Manifests/VS2015/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2015_v3Manifest/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- tools/uninstallSLVS.bat
> Fix manifests to export code fixes as MEF components

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.13.0.8313

- README.MD
Waffle is shutting down in 2 weeks
> Remove waffle from readme

- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.ruleset
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration/Integration.csproj
- src/Progress.TestFramework/Progress.TestFramework.csproj
- src/Progress.TestFramework/Progress.TestFramework.ruleset
- src/Progress.UnitTests/Progress.UnitTests.csproj
- src/Progress.UnitTests/Progress.UnitTests.ruleset
- src/Progress/Progress.csproj
- src/ProgressVS/ProgressVS.csproj
* referenced the solution-level ruleset directly unless the local ruleset contains additional settings.
> Tidy up project rulesets

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.14.0.8411

- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/TestInfrastructure/EnvironmentVariableScope.cs
> Added environment variable to specify daemon download URL

- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonInstaller.xaml
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonInstaller.xaml.cs
* prevent dialogue from being resized
* improve error messages/logging
> Minor improvements to the downloader

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Change daemon download location to use binaries.sonarsource.com

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
Fixed #819
Contains:
* Cfamily plugin version 6.3.0.11371
* JavaScript plugin version 4.0.0.5862
> Update daemon to version 4.3.0.2475

- src/Integration.UnitTests/WPF/IsValidOrganizationKeyConverterTests.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Connection/UI/IsValidOrganizationKeyConverter.cs
- src/Integration/Connection/UI/OrganizationSelectionWindow.xaml
- src/Integration/Connection/UI/OrganizationSelectionWindow.xaml.cs
> Updated organization UI to separate selection of own/public orgs

- src/Integration.Vsix/SonarLintDaemon/CFamily.cs
Breaks code coverage on QG which is blocking the release; code needs to be refactored to make it testable -> postponed for now.
> Revert debug-friendly changes

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Embed SonarC# and SonarVB 7.15.0.8572

- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Connection/UI/OrganizationSelectionWindow.xaml.cs
> Update binding to use SonarQubeService.HasOrganizations

- .gitignore
- SonarLint.VisualStudio.Integration.sln
- build/DownloadCFamilyPlugin/DownloadAndExtract.cs
- build/DownloadCFamilyPlugin/DownloadCFamilyPlugin.csproj
- src/Integration.Vsix/Integration.Vsix.csproj
> Custom build steps to embed CFamily files

- src/Integration.Vsix.UnitTests/CFamily/RulesLoaderTest.cs
- src/Integration.Vsix/CFamily/RulesLoader.cs
Based on #951 but unit tests are not passing since JSON files are not found.
> Load rules config from JSON files

- build/DownloadCFamilyPlugin/DownloadAndExtract.cs
- src/Integration.Vsix.UnitTests/CFamily/RulesLoaderTest.cs
- src/Integration.Vsix/CFamily/RulesLoader.cs
> Load rules metadata from the CFamily Json files

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonInstallerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/SonarLintDaemon/ISonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Call subprocess.exe for CFamily analysis

- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Updated daemon version to v4.3.2.2521

- src/Integration.Vsix.UnitTests/SonarLintDaemon/AnalyzerControllerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonInstallerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/AnalyzerController.cs
- src/Integration.Vsix/SonarLintDaemon/ISonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
* removed analyzer-specific knowledge from the analyzer controller (e.g. the list of languages supported by each analyzer).
* added unit tests
> Added IAnalyzer interface

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
- src/Integration.Vsix.UnitTests/CFamily/RulesMetadataCacheTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/RulesLoader.cs
- src/Integration.Vsix/CFamily/RulesMetadataCache.cs
> Use the cached rules configuration

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/MsvcDriver.cs
- src/Integration.Vsix/CFamily/Protocol.cs
> Call CLang analzyer on non-UI thread

- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonSplashscreen.xaml
> Removed references to C/C++ from options and download UI

- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
- src/Integration.Vsix/CFamily/PortedFromJava/ReadMe.txt
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
* separated ported into files to more closely match the originals
* fixed some minor analysis issues
> Code cleanup

- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
- src/Integration.Vsix/SonarLintDaemon/AnalyzerController.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/ISonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemonPackage.cs
* removed all existing calls to daemon.Start()
* added IDaemonAnalyzer to handle delay-start code
Fixed #926
> Delay starting the daemon until analysis is requested

- .gitignore
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/License
- src/Integration.Vsix/CFamily/RulesLoader.cs
- src/Integration.Vsix/Integration.Vsix.csproj
* added license file
* changed embedded directory to lib
Fixes #934
> CFamily licensing changes

- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintDaemonPackage.cs
- src/Integration/MefServices/IActiveSolutionTracker.cs
> Stop the daemon when a solution closes

- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/Helpers/DummySonarLintDaemon.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/SonarLanguage.cs
- src/Integration/Helpers/KnownUIContextsWrapper.cs
- src/Integration/Language.cs
- src/Integration/SonarLanguageKeys.cs
- src/Integration/Telemetry/ITelemetryManager.cs
- src/Integration/Telemetry/TelemetryClient.cs
- src/Integration/Telemetry/TelemetryData.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/Integration/Telemetry/TelemetryPayload.cs
> Added language analyzed telemetry

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
> Handle PrecompiledHeader setting "NotUsing"

- src/Integration.Vsix.UnitTests/CFamily/ProcessRunnerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/ProcessRunner.cs
* reduced verbosity of process runner logging
> Added minimal logging for CLangAnalyzer to match SonarLintDaemon

- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
- src/Integration.Vsix/SonarLintDaemonPackage.cs
> Fixed daemon download UI bugs

- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/Helpers/DummySonarLintDaemon.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
> Fix crash caused by daemon.Start race condition

- src/Integration.Vsix.UnitTests/SonarLintTagger/CancellableJobRunnerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/SingleFileMonitor.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTagger/CancellableJobRunner.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Trigger re-analysis when user settings file changes

- src/Integration.Vsix.UnitTests/SonarLintDaemon/DisableRuleCommandTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/SonarLint.vsct
- src/Integration.Vsix/SonarLintDaemon/DaemonCommands.vsct
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.Designer.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.resx
- src/Integration.Vsix/SonarLintDaemon/DisableRuleCommand.cs
- src/Integration.Vsix/SonarLintDaemonPackage.cs
> Added UI command to disable rules

- src/Integration.Vsix.UnitTests/SonarLintDaemon/SingleFileMonitorTests.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.Designer.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.resx
- src/Integration.Vsix/SonarLintDaemon/SingleFileMonitor.cs
- src/Integration.Vsix/SonarLintDaemon/UserSettingsProvider.cs
> Ensure settings directory exists

- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlTests.cs
- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogPageTests.cs
- src/Integration.Vsix.UnitTests/Settings/OpenSettingsFileWpfCommandTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/UserSettingsProviderTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
- src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs
- src/Integration.Vsix/Settings/OpenSettingsFileWpfCommand.cs
- src/Integration.Vsix/SonarLintDaemon/UserSettingsProvider.cs
> Added UI command to open user settings file in VS

- src/Integration.Vsix.UnitTests/Framework/ConfigurableVsStatusbar.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/StatusBarReanalysisProgressHandlerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.Designer.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonStrings.resx
- src/Integration.Vsix/SonarLintTagger/StatusBarReanalysisProgressHandler.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Added status bar progress while re-analysing

- src/Integration.Vsix.UnitTests/SonarLintDaemon/StatusBarDownloadProgressHandlerTests.cs
Test clean up only. No product changes.
> Changed existing tests to use ConfigurableVsStatusbar

- build/Version.props
- src/AssemblyInfo.Shared.cs
> Tweaked setting of versioning info

- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.CSharp.csproj
- src/SonarAnalyzerEmbedder/SonarAnalyzerEmbedder.VisualBasic.vbproj
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.CSharp.config
- src/SonarAnalyzerEmbedder/packages.SonarAnalyzerEmbedder.VisualBasic.config
> Updated embedded analyzers to v8.0.0.9566

- src/Integration.Vsix.UnitTests/SonarLintTagger/SinkManagerTests.cs
- src/Integration.Vsix/SonarLintTagger/SinkManager.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Handle errors from external ITableDataSinks

- SonarLint.VisualStudio.Integration.sln
- src/Integration.TeamExplorer/Integration.TeamExplorer.csproj
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration/Integration.csproj
- src/TestInfrastructure/TestInfrastructure.csproj
> Changed sln to use the SDK-style sonarqube-webclient projects

- src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
- src/Integration.UnitTests/Binding/BindingControllerTests.cs
- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration.UnitTests/Connection/ConnectControllerTests.cs
- src/Integration.UnitTests/Connection/ConnectDialogViewModelTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/Helpers/VsShellUtilsTests.cs
- src/Integration.UnitTests/Notifications/NotificationIndicatorViewModelTests.cs
- src/Integration.UnitTests/Persistence/SolutionBindingSerializerTests.cs
- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration.UnitTests/State/StateManagerTests.cs
- src/Integration.UnitTests/TeamExplorer/ProjectViewModelTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix.UnitTests/Delegates/SonarAnalyzerWorkflowBaseTests.cs
- src/Integration.Vsix.UnitTests/Settings/OpenSettingsFileWpfCommandTests.cs
- src/Progress.UnitTests/ProgessController/SequentialProgressControllerTests.cs
- src/Progress.UnitTests/ProgressObserver/ProgressObserverTests.cs
- src/TestInfrastructure/Framework/ConfigurableSectionController.cs
Fixed IDE0017 in test code: "Object initialization can be simplified"
> Test code cleanup

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
> Added env var to set CFamily analysis timeout

- src/Integration.UnitTests/Connection/ConnectionInformationDialogTests.cs
- src/Integration/Connection/ConnectionInformationDialog.cs
> Hide existing user name/token in new connection dialogue

- src/Integration/Connection/UI/OrganizationSelectionWindow.xaml.cs
> Changed organization dialogue base class

- src/Integration.TeamExplorer/CommonStyles.xaml
- src/Integration.TeamExplorer/ConnectSectionView.xaml
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/TeamExplorer/ServerViewModel.cs
> Fix virtualization of Team Explorer treeview control

- src/Integration.TeamExplorer/Integration.TeamExplorer.csproj
- src/Integration.TeamExplorer/SectionController.cs
> Added VS2019-specific tweak to suppress TE scrollbar

- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/Settings/OpenSettingsFileWpfCommandTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs
- src/Integration.Vsix/Settings/OpenSettingsFileWpfCommand.cs
Fixes #1071
NB changes to other settings (e.g. logging level) are not saved
> Bug #1071 Close Options dialogue when showing settings file

- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
> Force solution ruleset name to lower case

- src/Integration.Vsix.UnitTests/SonarLintDaemon/AnalyzerControllerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/Helpers/DummySonarLintDaemon.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/SonarLanguageRecognizerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/AnalyzerController.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/IAnalyzerController.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/AnalysisLanguage.cs
- src/Integration.Vsix/SonarLintTagger/ISonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/SonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
* done to help differentiate it from the "Language" class and makes its purpose more obvious
> Renamed SonarLanguage enum to AnalysisLanguage

- src/Core/IRulesConfigurationProvider.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/DotNetRulesConfigurationProviderTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/Binding/BindingProcessImpl.cs
- src/Integration/Binding/DotNetRuleConfigurationProvider.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Extracted code to fetch rules configuration

- src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs
* no product changes
* tests were supposed to be testing different project types but were actually only testing C# projects
> Fixed existing ProjectSystemHelper tests

- src/Core.UnitTests/LanguageTests.cs
- src/Core/Language.cs
- src/Core/Strings.Designer.cs
- src/Core/Strings.resx
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/Connection/MinimumSupportedSonarQubePluginTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Connection/MinimumSupportedSonarQubePlugin.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/ProjectToLanguageMapper.cs
TODO: fetch the QP and create rules config
Relates to #1097
> Modified connection to recognise Cpp projects as bindable

- src/Core.UnitTests/CFamily/CFamilyRulesConfigurationFileTests.cs
- src/Core.UnitTests/CFamily/CFamilyRulesConfigurationProviderTests.cs
- src/Core.UnitTests/Helpers/WebServiceHelperTests.cs
- src/Core/CFamily/CFamilyRulesConfigurationFile.cs
- src/Core/CFamily/CFamilyRulesConfigurationProvider.cs
- src/Core/Helpers/WebServiceHelper.cs
- src/Core/InternalsVisibleTo.cs
> Added CFamily rules config provider

- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
- src/Integration/LocalServices/SolutionBindingInformationProvider.cs
TODO: still need to handle missing C language settings
Relates to #1110
> Fix unbound project detection to include C++

- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/Connection/MinimumSupportedSonarQubePluginTests.cs
- src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests_ProjectLevelConfig.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Connection/MinimumSupportedSonarQubePlugin.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
Test cleanup, and tweaked plugin class
> Tweaked plugin class to support multiple languages per plugin

- src/Integration.UnitTests/CFamily/CFamilyRuleConfigProviderTests.cs
- src/Integration/CFamily/CFamilyRulesConfigProvider.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Modified CFamily config provider to choose correct settings

- src/Integration.Vsix.UnitTests/SonarLintDaemon/DisableRuleCommandTests.cs
- src/Integration.Vsix/SonarLintDaemon/DisableRuleCommand.cs
> Disable "disable rule" command in connected mode

- src/Core.UnitTests/CFamily/CFamilyBindingConfigFileTests.cs
- src/Core.UnitTests/CFamily/DynamicCFamilyRulesConfigTests.cs
- src/Core.UnitTests/UserSettingsSerializerTests.cs
- src/Core/CFamily/DynamicCFamilyRulesConfig.cs
- src/Core/CFamily/ICFamilyRulesConfig.cs
- src/Core/UserSettings.cs
- src/Integration.UnitTests/CFamily/CFamilyRuleConfigProviderTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/TestInfrastructure/CFamily/DummyCFamilyRulesConfig.cs
> CFamily: override rule defaults in standalone/connected mode

- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorTests.cs
- src/Core/CFamily/DynamicCFamilyRulesConfig.cs
- src/Core/CFamily/EffectiveRulesConfigCalculator.cs
- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
- src/Integration/CFamily/CFamilyRulesConfigProvider.cs
NB only works for standalone mode currently
> Added simple caching for effective CFamily rule configuration

- src/Integration.Vsix/CFamily/FileConfig.cs
> Fix exception fetching LanguageStandard in VS2015

- src/Integration.Vsix/SignVsixes.targets
> Timestamp VSIX when signing

- src/Integration.Vsix/SignVsixes.targets
* now the same as the Scanner for MSBuild
Relates to #1166
> Modified VSIX signing to use SHA256 timestamp

- src/EmbeddedSonarAnalyzer.props
> Updated embedded versions of SonarC#/VB to 8.2

- build/DownloadCFamilyPlugin/DownloadAndExtract.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
> Update embedded CFamily analyzer to v6.6

- src/EmbeddedSonarAnalyzer.props
> Update embedded SonarC#/VB to v8.1

- build/DownloadCFamilyPlugin/DownloadAndExtract.cs
- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
Second attempt: using sonar-dotnet v8.1 rather than v8.2
> Merge changes for v4.16

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
> Fix test assertion

- src/EmbeddedSonarAnalyzer.props
> Embed SonarC# 8.3 and SonarVB 8.3

- Directory.Build.props
- Directory.Build.targets
- build/Signing.targets
- src/Integration.TeamExplorer/Integration.TeamExplorer.csproj
- src/Integration.Vsix/Integration.Vsix.csproj
> Tidy up signing targets

- src/EmbeddedSonarAnalyzer.props
> Embed SonarC# 8.4 and SonarVB 8.4

- README.MD
Fixes #1221
Thanks to @christianbumann
> Updated readme to mention connected mode

- src/Integration.Vsix.UnitTests/Analysis/SingleFileMonitorTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/CancellableJobRunnerTests.cs
- src/TestInfrastructure/Framework/TestLogger.cs
Added logging for flaky tests.
Related to #1238
> Improved logging in flaky tests

- src/Integration.Vsix.UnitTests/Suppression/LiveIssueFactoryTests.cs
- src/Integration.Vsix/Suppression/LiveIssueFactory.cs
> Guard against diagnostic location not being found in text buffer

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix/Integration.Vsix.csproj
> Update embedded CFamily analyzer to v6.7

- src/Integration.UnitTests/LocalServices/ServiceGuidTestProjectIndicatorTests.cs
- src/Integration/LocalServices/TestProjectIndicators/ServiceGuidTestProjectIndicator.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> 1263 [Test projects] Projects tagged with test service GUID are not recognized as test projects

- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonIssueAdapterTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/IssueToFilterableIssueConverterTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintDaemon/DaemonIssueAdapter.cs
- src/Integration.Vsix/SonarLintTagger/IssueToFilterableIssueConverter.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Apply issues filtering to the returned issues

- src/Integration.Vsix.UnitTests/Suppression/RoslynSuppressionHandlerTests.cs
- src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
- src/Integration.Vsix/Suppression/LiveIssue.cs
- src/Integration.Vsix/Suppression/RoslynSuppressionHandler.cs
- src/Integration/Suppression/SuppressedIssueMatcher.cs
> Refactored Roslyn suppressions to use ISuppressedIssueMatcher

- src/Integration.UnitTests/Suppression/SuppressedIssueMatcherTests.cs
- src/Integration/Suppression/SuppressedIssueMatcher.cs
File-level issues should not match non-file-level issues
> Fix file-level issue comparison bug

- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorCacheTests.cs
- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorTests.cs
- src/Core/CFamily/EffectiveRulesConfigCalculator.cs
> Refactor effective rules calculator

- src/Core.UnitTests/CFamily/DynamicCFamilyRulesConfigTests.cs
- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorTests.cs
- src/Core/CFamily/DynamicCFamilyRulesConfig.cs
- src/Core/CFamily/EffectiveRulesConfigCalculator.cs
- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
> Ensures CFamily project-level rules are disabled in SonarLint

- src/Core.UnitTests/CFamily/CFamilyBindingConfigFileTests.cs
- src/Core.UnitTests/CFamily/CFamilyBindingConfigProviderTests.cs
- src/Core.UnitTests/CFamily/DynamicCFamilyRulesConfigTests.cs
- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorCacheTests.cs
- src/Core.UnitTests/CFamily/EffectiveRulesConfigCalculatorTests.cs
- src/Core.UnitTests/RuleSettingsSerializerTests.cs
- src/Core/CFamily/CFamilyBindingConfigFile.cs
- src/Core/CFamily/CFamilyBindingConfigProvider.cs
- src/Core/CFamily/CFamilySonarWayRulesConfigProvider.cs
- src/Core/CFamily/DynamicCFamilyRulesConfig.cs
- src/Core/CFamily/EffectiveRulesConfigCalculator.cs
- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
- src/Core/IUserSettingsProvider.cs
- src/Core/RulesSettings.cs
- src/Core/RulesSettingsSerializer.cs
- src/Core/UserSettings.cs
- src/Integration.UnitTests/CFamily/CFamilyRuleConfigProviderTests.cs
- src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
- src/Integration.Vsix.UnitTests/Analysis/UserSettingsProviderTests.cs
- src/Integration.Vsix.UnitTests/Analysis/UserSettingsTests.cs
- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogPageTests.cs
- src/Integration.Vsix/Analysis/DisableRuleCommand.cs
- src/Integration.Vsix/Analysis/UserSettingsProvider.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
- src/Integration/CFamily/CFamilyRulesConfigProvider.cs
- src/Integration/Suppression/SuppressedIssuesProvider.cs
- src/TestInfrastructure/Framework/ConfigurableSolutionRuleSetsInformationProvider.cs
> Merge bug-fix branch to master

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Pass SonarLint flag to Subprocess.exe

- src/EmbeddedSonarAnalyzer.props
> Update embedded CFamily analyzer to v6.8.0.16475

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
> Increase the subprocess.exe timeout value 

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Port fix to MSVC driver

- src/Integration.Vsix.UnitTests/Analysis/AnalyzerControllerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/Helpers/DummySonarLintDaemon.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/Analysis/AnalyzerController.cs
- src/Integration.Vsix/Analysis/IAnalyzerController.cs
- src/Integration.Vsix/CFamily/CFamilyAnalyzerOptions.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/FileConfig.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
- src/TestInfrastructure/VsObjectModelMocks/ConfigurationMock.cs
- src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs
> Support setting analyzer options and reproducer flag 

- src/Core/IAnalysisRequester.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisRequesterTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyReproducerCommandTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
- src/Integration.Vsix/Analysis/AnalysisRequester.cs
- src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
Relates to #1295 
TODO:
* modify the TaggerProvider to handle the new requester event args
> Modified analysis requestor and repro commands

- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Change TaggerProvider to pass through analyzer options

- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
> #1295 - Write reproducer to Temp folder

- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix/SonarLintTagger/IIssueTracker.cs
- src/Integration.Vsix/SonarLintTagger/IssueTagger.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
Relates to #1295 
Two separate commits:
1) factored out IIssueTracker
2) added issue filtering to the TaggerProvider
> Factored out IIssueTracker interface

- src/Integration.Vsix.UnitTests/CFamily/ProcessRunnerTests.cs
> Disable flaky test

- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Modified output message

- src/Core.UnitTests/Binding/CompositeBindingConfigProviderTests.cs
- src/Core.UnitTests/CFamily/CFamilyBindingConfigProviderTests.cs
- src/Core/Binding/CompositeBindingConfigProvider.cs
- src/Core/Binding/IBindingConfigProvider.cs
- src/Core/CFamily/CFamilyBindingConfigProvider.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/DotNetBindingConfigProviderTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/Binding/BindingProcessImpl.cs
- src/Integration/Binding/DotNetBindingConfigProvider.cs
> Pass binding configuration to binding config providers

- src/Core.UnitTests/Helpers/PathHelperTests.cs
- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
- src/Core/Helpers/PathHelper.cs
- src/Integration.UnitTests/Binding/ProjectBindingOperation.WriterTests.cs
- src/Integration.UnitTests/Helpers/PathHelperTests.cs
- src/Integration.UnitTests/Helpers/RuleSetUpdaterTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleSetInspectorTests.cs
- src/Integration/Binding/ProjectBindingOperation.Writer.cs
- src/Integration/Binding/ProjectBindingOperation.cs
- src/Integration/Helpers/RuleSetUpdater.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Move PathHelper to Core

- src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
- src/Core/CSharpVB/RuleSetGenerator.cs
It's probably worth looking at the commits separately. The first is just minor cleanup of the existing tests.
> Set rule severity based on QP severity

- src/Integration.Vsix.UnitTests/SonarLintTagger/IssuesSnapshotTests.cs
- src/Integration.Vsix/SonarLintTagger/IssuesSnapshot.cs
Fixes #1384 (connected mode)
Fixes #1386 (standalone mode)
> Fix issue severity for CFamily

- src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
- src/Core/CSharpVB/ISonarLintConfigGenerator.cs
- src/Core/CSharpVB/SonarLintConfigGenerator.cs
* added interface and changed from static class
* changed the `language` parameter from a string to the `Language` type
> Tweaks to SonarLintConfigGenerator

- src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
- src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
- src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
- src/Core/CSharpVB/NuGetPackageInfoGenerator.cs
- src/Core/CSharpVB/RoslynPluginRuleKeyExtensions.cs
- src/Core/CSharpVB/RuleSetGenerator.cs
- src/Integration.UnitTests/Binding/DotNetBindingConfigProviderTests.cs
- src/Integration/Binding/DotNetBindingConfigProvider.cs
Move existing C#/VB rule filtering to the config provider.
> Moved unsupported rule filtering to the config provider

- src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
> Fixed up unit test mocks to check for specific project key

- src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
- src/Integration/Binding/CSharpVBBindingConfigProvider.cs
> Exclude hotspots from C# and VB config

- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration.UnitTests/Binding/CSharpVBProjectBinderTests.cs
- src/Integration.UnitTests/Binding/RuleSetReferenceCheckerTests.cs
- src/Integration/Binding/CSharpVBBindingOperation.cs
- src/Integration/Binding/CSharpVBProjectBinder.cs
- src/Integration/Binding/IRuleSetReferenceChecker.cs
- src/Integration/Binding/RuleSetReferenceChecker.cs
> Don't update ruleset declarations that already reference solution ruleset

- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration/Binding/CSharpVBBindingOperation.cs
> Add unconditional ruleset when binding for the first time

- src/Integration.UnitTests/Helpers/DateTimeOffsetExtensionsTests.cs
- src/Integration/Helpers/DateTimeOffsetExtensions.cs
Now takes the local time-zone into account
> Fixed bug in IsSameDay

- src/EmbeddedSonarAnalyzer.props
> Embed SonarC# 8.8 and SonarVB 8.8

- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/TelemetryManager.cs
> Patch up invalid days_of_use telemetry

- src/Integration.TeamExplorer.UnitTests/Integration.TeamExplorer.UnitTests.csproj
- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration/Integration.csproj
- src/SonarLint.VSSpecificAssemblies.props
No code changes.
* moved reference to shared props file
* fixed package reference
> Fixed project refs to Alm.Auth package

- src/Core/Analysis/AnalysisIssue.cs
- src/Core/Analysis/IAnalysisIssue.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/Helpers/IssueConverterTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonIssueAdapterTests.cs
- src/Integration.Vsix.UnitTests/SonarLintDaemon/SonarLintDaemonTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/IssueToFilterableIssueConverterTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/Helpers/IssueConverter.cs
- src/Integration.Vsix/SonarLintDaemon/DaemonIssueAdapter.cs
- src/Integration.Vsix/SonarLintDaemon/ISonarLintDaemon.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/Integration.Vsix/SonarLintTagger/IssueMarker.cs
- src/Integration.Vsix/SonarLintTagger/IssueToFilterableIssueConverter.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
- src/TestInfrastructure/DummyAnalysisIssue.cs
* removed the daemon Issue type from all interfaces
* fixed up unit tests
Relates to #1470
> Added common issue interface and implementation

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/CFamily/FileConfig.cs
@duncanp-sonar recently a user complained about this issue https://community.sonarsource.com/t/failed-to-execute-analysis-sonarlint-visual-studio-2017/26386
> Remove double quotations from additional options

- src/Integration.Vsix.UnitTests/SonarLintTagger/IssueMarkerFactoryTests.cs
- src/Integration.Vsix/SonarLintTagger/IIssueMarkerFactory.cs
- src/Integration.Vsix/SonarLintTagger/IssueMarkerFactory.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
No code changes
* Moved tagger-specific types to Tagger subfolder
* Renamed types
> Moved and renamed tagger-specific types

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/CFamily/FileConfig.cs
This reverts commit 3f1fda011ac278b8d15ad096c8945ace77e75e1a.
> Revert "Remove double quotations from additional options (#1481)"

- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/SonarLintTagger/README.md
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
Only comment changes.
Added comments related to tagging, the error list, and handling document updates about things that are not obvious from the current state of the code.
> Added comments and design notes about doc editing

- src/Core.UnitTests/CFamily/CFamilyAnalyzerOptionsTests.cs
- src/Core/Analysis/IAnalyzerOptions.cs
- src/Core/CFamily/CFamilyAnalyzerOptions.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProcessRunnerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/SchedulerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/IProcessRunner.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
- src/Integration.Vsix/CFamily/ProcessRunner.cs
- src/Integration.Vsix/CFamily/ProcessRunnerArguments.cs
- src/Integration.Vsix/SonarLintTagger/IScheduler.cs
- src/Integration.Vsix/SonarLintTagger/Scheduler.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Use IO streams to communicate with subprocess.exe #1466

- src/Integration.Vsix.UnitTests/SonarLintTagger/ISpanCalculatorTests.cs
- src/Integration.Vsix/SonarLintTagger/IIssueSpanCalculator.cs
- src/Integration.Vsix/SonarLintTagger/IssueSpanCalculator.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
* changed to IIssueSpanCalculator
> Refactor IIssueMarkerFactory

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/CFamily/FileConfig.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
> Fix double quoted compilation flags

- src/Integration.Vsix.UnitTests/CFamily/ProcessRunnerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/ProcessRunner.cs
Part of #1510 - Log "analysis finished" status in the Output window.
> Add "analysis finished" message

- src/Integration.Vsix/SonarLintTagger/AccumulatingIssueConsumer.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
* remove the misleading suppressed issues count message
> UX: clear error list immediately

- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
> Ignore issues without filename

- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/ProcessRunner.cs
This message provides no value to the user, and might even be scary.
> Change message to debug

- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
Change CLangAnalyzer to stream issues
* removed message about suppressed issues
Fixes #1471
> Change CLangAnalyzer to stream issues

- src/Integration/Binding/BindingStrings.Designer.cs
- src/Integration/Binding/BindingStrings.resx
> Clarify wording of conflict SonarLint.xml warning message

- .sonarlint/SonarLint.VisualStudio.Integration.slconfig
- .sonarlint/sonarlint-visualstudio/CSharp/SonarLint.xml
- .sonarlint/sonarlint-visualstudioCSharp.ruleset
- src/Integration/Binding/AdditionalFileConflictChecker.cs
Fixes #1516 
New QP: https://sonarcloud.io/organizations/sonarsource/quality_profiles/show?language=cs&name=C%23+QP+for+SonarLint
> Use SLVS QP on SonarCloud

- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration.UnitTests/Binding/CSharpVBProjectBinderTests.cs
- src/Integration.UnitTests/Binding/RuleSetReferenceCheckerTests.cs
- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration/Binding/CSharpVBBindingOperation.cs
- src/Integration/Binding/CSharpVBProjectBinder.cs
- src/Integration/Binding/ProjectBinderFactory.cs
- src/Integration/Binding/RuleSetReferenceChecker.cs
- src/Integration/LocalServices/RuleSetDeclaration.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Don't try to fetch ruleset path when CodeAnalysisProperty is null or whitespace

- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
- src/Integration.UnitTests/LocalServices/CredentialStoreTests.cs
- src/Integration/LocalServices/CredentialStore.cs
- src/Integration/MefServices/VsSessionHost.cs
Relates to #1209, provides more information to the user when an exception occurs.
> Log Win32 error code when Win32Exception is thrown

- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration/Telemetry/TelemetryClient.cs
Fixes #1539
Miscellaneous test code cleanup
> Changed telemetry URL

- src/Integration/LocalServices/RuleSetDeclaration.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Fix log message

- src/Integration.Vsix.UnitTests/CFamily/CFamilyReproducerCommandTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/SonarLanguageRecognizerTests.cs
- src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
- src/Integration.Vsix/SonarLintTagger/ISonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/SonarLanguageRecognizer.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> Simplify the parameters of -SonarLanguageRecognizer

- src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
- src/Integration.Vsix/Helpers/RunOnUIThread.cs
> Extract RunOnUIThread

- src/Integration.Vsix.UnitTests/Helpers/ActiveDocumentLocatorTests.cs
- src/Integration.Vsix.UnitTests/Helpers/TextDocumentProviderTests.cs
- src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
- src/Integration.Vsix/Helpers/ActiveDocumentLocator.cs
- src/Integration.Vsix/Helpers/TextDocumentProvider.cs
> Extract text document retrival logic from ActiveDocumentLocator

- src/Core/CFamily/CFamilyAnalyzerOptions.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
> Pass PCH parameters to ClangAnalyzer

- src/Core/Analysis/IAnalysisStatusNotifier.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix.UnitTests/Helpers/StatusBarNotifierTests.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.resx
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/Helpers/IStatusBarNotifier.cs
> Unify output window and status bar analysis messages

- src/Core/CFamily/CFamilyAnalyzerOptions.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/PreCompiledHeadersEventListenerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/PreCompiledHeadersEventListener.cs
> Pass PCH file location when executing the analysis

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
> Don't pass rules config when creating pch files

- src/Core/Analysis/AnalysisIssue.cs
- src/Core/Analysis/IAnalysisIssue.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CLangAnalyzerTestFile_OneIssue_HasSecondaryLocations.txt
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CLangAnalyzerTestFile_OneIssue_HasSecondaryLocations_response.json
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
- src/TestInfrastructure/DummyAnalysisIssue.cs
> Add secondary locations property

- src/IssueViz.UnitTests/TableControls/IssueTablesSelectionMonitorTests.cs
- src/IssueViz/TableControls/IssueTablesSelectionMonitor.cs
> Update issue service when error list issue changes

- src/Core.UnitTests/RuleHelpLinkProviderTests.cs
- src/Core/RuleHelpLinkProvider.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
Move GetHelpLink to Core so it could used in IssueViz panel.
> Move Rule GetHelpLink to Core 

- src/IssueViz.UnitTests/Commands/NavigationCommandsTests.cs
- src/IssueViz.UnitTests/Selection/AnalysisIssueNavigationTests.cs
- src/IssueViz/Commands/Constants.cs
- src/IssueViz/Commands/IssueVisualizationToolWindowCommand.cs
- src/IssueViz/Commands/IssueVizPackage.vsct
- src/IssueViz/Commands/NavigationCommands.cs
- src/IssueViz/IssueVizPackage.cs
- src/IssueViz/Resources.Designer.cs
- src/IssueViz/Resources.resx
- src/IssueViz/Selection/AnalysisIssueNavigation.cs
> Implement keyboard navigation 

- src/Core/Analysis/IAnalysisIssue.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/ISpanCalculatorTests.cs
- src/Integration.Vsix/SonarLintTagger/IIssueSpanCalculator.cs
- src/Integration.Vsix/SonarLintTagger/IssueSpanCalculator.cs
- src/TestInfrastructure/DummyAnalysisIssueLocation.cs
Refactored `IAnalysisIssue` to implemented `IAnalysisIssue`.
Modified `IIssueSpanCalculator` to accept and `IAnalysisIssueLocation` instead.
> Changed IAnalysisIssue to implement IAnalysisIssueLocation

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelper_CaptureTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
- src/Integration.Vsix/CFamily/FileConfig.cs
> Set working directory to ProjectDir

- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
- src/Integration.Vsix/ErrorList/ISonarErrorListDataSource.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
... Split IssueSnapshot tests
No functional changes
> Changed ISonarErrorListDataSource to use strongly-typed factory

- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/ErrorList/SnapshotFactory.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
Modified SnapshotFactory to use the new interface
> Added IIssuesSnaphot interface

- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
> (1) Added file-retrieval methods to IIssuesSnapshot

- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/ErrorList/ISonarErrorListDataSource.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
Means we can tell the error list which factory has updated, rather than it checking them all
> (2) Added factory parameter to RefreshErrorList(...)

- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
- src/IssueViz/Editor/LocationTagging/IIssueLocationStore.cs
* implemented GetLocations and refresh of error list
Relates to #1661
> (3) Added IIssueLocationStore interface

- src/IssueViz.UnitTests/Editor/LocationTagging/IssueLocationTagTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/SelectedIssueLocationTagTests.cs
- src/IssueViz/Editor/LocationTagging/IssueLocationTag.cs
- src/IssueViz/Editor/SelectedIssueTagging/SelectedIssueLocationTag.cs
Added buffer-level tag classes.
This will make it easier to work on the taggers in parallel.
> Added skeleton buffer tags

- src/IssueViz.UnitTests/Editor/Common/CommonTaggerProviderTestsBase.cs
- src/IssueViz.UnitTests/Editor/Common/CommonViewTaggerProviderTestsBase.cs
- src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
- src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTaggerTests.cs
- src/IssueViz.UnitTests/Editor/FilteringTaggerBaseTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Buffer/SelectedIssueLocationTaggerTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Highlighting/IssueHighlightTagTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Highlighting/IssueHighlightViewTaggerProviderTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Highlighting/IssueHighlightViewTaggerTests.cs
- src/IssueViz/Editor/SelectedIssueTagging/Highlighting/IssueHighlightTag.cs
- src/IssueViz/Editor/SelectedIssueTagging/Highlighting/IssueHighlightTagger.cs
- src/IssueViz/Editor/SelectedIssueTagging/Highlighting/IssueHighlightViewTaggerProvider.cs
> Added selected issue location highlighting

- src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTaggerProviderTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTaggerTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Highlighting/IssueHighlightViewTaggerTests.cs
- src/IssueViz.UnitTests/IssueViz.UnitTests.csproj
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornment.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTagger.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTaggerProvider.cs
> Added selected location adornment

- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
- src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
> Fix cursor bug when editing

- src/IssueViz.UnitTests/TableControls/VSTableEventProcessorTests.cs
- src/IssueViz/TableControls/VSTableEventProcessorProvider.cs
> Select only issues with secondary locations

- src/IssueViz.UnitTests/Editor/FilteringTaggerBaseTests.cs
- src/IssueViz/Editor/FilteringTaggerBase.cs
> Fix object disposed exception thrown intermittently by tagger

- src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTaggerTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTagger_CacheTests.cs
- src/IssueViz.UnitTests/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTests.cs
- src/IssueViz/Editor/FilteringTaggerBase.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornment.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTagger.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTagger_Cache.cs
> Added adornment caching

- src/IssueViz.UnitTests/Editor/LocationTagging/LocationTaggerTests.cs
- src/IssueViz/Editor/LocationTagging/LocationTagger.cs
> Calculate affected span

- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/IssueViz.UnitTests/Editor/Common/CommonTaggerProviderTestsBase.cs
- src/IssueViz.UnitTests/Editor/Common/CommonViewTaggerProviderTestsBase.cs
- src/IssueViz.UnitTests/Editor/LocationTagging/LocationTaggerProviderTests.cs
- src/IssueViz.UnitTests/Editor/SingletonDisposableTaggerManagerTests.cs
- src/IssueViz.UnitTests/Editor/SingletonDisposableTaggerManager_FlyweightTests.cs
- src/IssueViz/Editor/ErrorTagging/ErrorTaggerProvider.cs
- src/IssueViz/Editor/LocationTagging/LocationTaggerProvider.cs
- src/IssueViz/Editor/SelectedIssueTagging/Adornment/IssueLocationAdornmentTaggerProvider.cs
- src/IssueViz/Editor/SelectedIssueTagging/Buffer/SelectedIssueLocationTaggerProvider.cs
- src/IssueViz/Editor/SelectedIssueTagging/Highlighting/IssueHighlightViewTaggerProvider.cs
- src/IssueViz/Editor/SingletonDisposableTaggerManager.cs
- src/IssueViz/Editor/SingletonDisposableTaggerManager_Flyweight.cs
> Changed dependant taggers to be per-request rather than per-buffer/view

- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Changed TextBufferIssueTracker to be a singleton-per-buffer

- src/IssueViz.UnitTests/Editor/LocationTagging/LocationTaggerTests.cs
- src/IssueViz/Editor/LocationTagging/LocationTagger.cs
> Recalculate location span when buffer changes

- src/IssueViz.UnitTests/Editor/LocationTagging/LocationTaggerTests.cs
- src/IssueViz/Editor/LocationTagging/LocationTagger.cs
> Fix tooltip bug

- src/IssueViz/IssueVizPackage.cs
> Dock Visualization ToolWindow by default

- src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
- src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTaggerTests.cs
- src/IssueViz/Editor/ErrorTagging/ErrorTagger.cs
> Add rule key prefix to tooltips

- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationControlTests.cs
- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml.cs
- src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
> Allow navigation to already selected items + add keypress events

- src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
- src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceTests.cs
- src/IssueViz/Editor/QuickActions/DeselectIssueVisualizationAction.cs
- src/IssueViz/Editor/QuickActions/IssueLocationActionsSource.cs
- src/IssueViz/Editor/QuickActions/IssueLocationActionsSourceProvider.cs
> Dismiss lightbulb session when tags change

- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_FileRenameHandlingTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
- src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
- src/IssueViz/Selection/IAnalysisIssueSelectionService.cs
> Fix selection bugs when issue is selected using suggested action lightbulb

- src/Integration.Vsix/Helpers/ActiveDocumentLocator.cs
- src/Integration.Vsix/Helpers/DocumentEvents/ActiveDocumentTracker.cs
- src/Integration.Vsix/Helpers/IStatusBarNotifier.cs
- src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceTests.cs
- src/IssueViz/Editor/QuickActions/IssueLocationActionsSource.cs
- src/IssueViz/Helpers/RunOnUIThread.cs
> Run DismissSession on the UI thread

- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Support error list filter 'Current Project'

- src/IssueViz/Editor/FilteringTaggerBase.cs
> Use callerSnapshot instead of currentSnapshot when calling GetSpans

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyTestUtility.cs
- src/Integration.Vsix.UnitTests/CFamily/FileConfigTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/FileConfig.cs
> Improve error messages about files that cannot be analyzed

- .sonarlint/SonarLint.VisualStudio.Integration.slconfig
- .sonarlint/sonarlint-visualstudioCSharp.ruleset
Enabled rules:
https://rules.sonarsource.com/csharp/RSPEC-100
https://rules.sonarsource.com/csharp/RSPEC-1109
https://rules.sonarsource.com/csharp/RSPEC-121
https://rules.sonarsource.com/csharp/RSPEC-1694
https://rules.sonarsource.com/csharp/RSPEC-2302
https://rules.sonarsource.com/csharp/RSPEC-2357
https://rules.sonarsource.com/csharp/RSPEC-3532
https://rules.sonarsource.com/csharp/RSPEC-3962
> Enable additional rules

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyTestUtility.cs
- src/Integration.Vsix.UnitTests/CFamily/FileConfigTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/FileConfig.cs
> Support header files

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Support Tc and Tp options

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Fix request with no file bug by ignoring the argument of ignored option

- src/Core.UnitTests/ExecuteOnDisposeTests.cs
- src/Core/ExecuteOnDispose.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
> Move ExecuteOnDispose to Core

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssueMatcherTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
> Sync webclient to get issues flows and GetHotspot API

- src/IssueViz.UnitTests/Editor/LocationTagging/IssueLocationStoreAggregatorTests.cs
- src/IssueViz.UnitTests/Editor/LocationTagging/LocationTaggerProviderTests.cs
- src/IssueViz.UnitTests/IssueViz.UnitTests.csproj
- src/IssueViz/Editor/LocationTagging/IssueLocationStoreAggregator.cs
- src/IssueViz/Editor/LocationTagging/LocationTaggerProvider.cs
> Add LocationsStore aggregator

- src/IssueViz.Security.UnitTests/HotspotsList/HotspotTableEntryTests.cs
- src/IssueViz.Security/HotspotsList/TableDataSource/HotspotTableEntry.cs
> Hotspots table: support empty span

- src/IssueViz.Security.UnitTests/OpenInIDE/Http/HttpListenerFactoryTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Http/OwinPipelineProcessorTests.cs
- src/IssueViz.Security/OpenInIDE/Http/OwinPipelineProcessor.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.Designer.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.resx
> Added pipeline message processing

- src/Core/InfoBar/IInfoBar.cs
- src/Core/InfoBar/IInfoBarManager.cs
- src/Core/SonarLintImageMoniker.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.Vsix.UnitTests/DeprecationManagerTests.cs
- src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs
- src/Integration.Vsix/InfoBar/InfoBarManager.cs
- src/Integration.Vsix/SonarLintIntegrationPackage.cs
- src/Integration/DeprecationManager.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBar.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBarManager.cs
> Move IInfoBarManager to Core

- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration.UnitTests/Persistence/LegacySolutionBindingPathProviderTests.cs
- src/Integration/LocalServices/ISolutionRuleSetsInformationProvider.cs
- src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Persistence/LegacySolutionBindingPathProvider.cs
- src/TestInfrastructure/Framework/ConfigurableSolutionRuleSetsInformationProvider.cs
> Remove dependency on ISolutionRuleSetsInformationProvider

- src/Integration.UnitTests/LocalServices/CredentialStoreTests.cs
- src/Integration/LocalServices/CredentialStore.cs
- src/Integration/MefServices/VsSessionHost.cs
> MEF export ICredentialStoreService

- src/Core/IOutputWindowService.cs
- src/Integration.UnitTests/Helpers/OutputWindowServiceTests.cs
- src/Integration/Helpers/OutputWindowService.cs
> Add OutputWindowService

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIdeStateValidatorTests.cs
- src/IssueViz.Security/HotspotsList/HotspotsToolWindow.cs
- src/IssueViz.Security/OpenInIDE/Api/IOpenInIDEStateValidator.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.Designer.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.resx
> Show infobar with SQ request failures

- src/Core/IToolWindowService.cs
- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/ToolWIndowService.cs
> Added IToolWindowService

- src/IssueViz.Security.UnitTests/OpenInIDE/Http/OwinPipelineProcessorTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Http/ShowHotspotOwinRequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Http/IOwinPathRequestHandler.cs
- src/IssueViz.Security/OpenInIDE/Http/OwinPipelineProcessor.cs
- src/IssueViz.Security/OpenInIDE/Http/ShowHotspotOwinRequestHandler.cs
> Fix web listener ApiPath bug

- src/Core/IToolWindowService.cs
- src/Integration.UnitTests/Helpers/OutputWindowServiceTests.cs
- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/OutputWindowService.cs
- src/Integration/Helpers/ToolWIndowService.cs
> Modified OutputWindowService to use IToolWindowService

- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/ToolWIndowService.cs
- src/IssueViz.Security.UnitTests/Commands/HotspotsToolWindowCommandTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIdeStateValidatorTests.cs
- src/IssueViz.Security/Commands/HotspotsToolWindowCommand.cs
- src/IssueViz.Security/HotspotsList/HotspotsToolWindow.cs
- src/IssueViz.Security/OpenInIDE/Api/IOpenInIDEStateValidator.cs
- src/IssueViz.Security/Resources.Designer.cs
- src/IssueViz.Security/Resources.resx
* modified tool window service to force-create the window
Relates to #1865
> Refactored the show Hotspot list command to use tool window service

- src/IssueViz.UnitTests/Commands/IssueVisualizationToolWindowCommandTests.cs
- src/IssueViz/Commands/IssueVisualizationToolWindowCommand.cs
- src/IssueViz/IssueVisualizationControl/IssueVisualizationToolWindow.cs
- src/IssueViz/Resources.Designer.cs
- src/IssueViz/Resources.resx
Relates to #1865
Apply the same changes as #1870 but this time for the "Show secondary locations commands"
> Modified "show flow window" command to use tool window service

- src/IssueViz.UnitTests/Commands/IssueVisualizationToolWindowCommandTests.cs
Fewer than half the tests used the instance test variables, and for most of them Mock.Of<X> would do instead. The tests now don't shared any data i.e. completely isolated.
> Test cleanup

- src/IssueViz.Security/OpenInIDE/OpenInIDEPackage.cs
> Change HttpListener port range to 64120-64130 (end-inclusive)

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIdeStateValidatorTests.cs
- src/IssueViz.Security/OpenInIDE/Api/IOpenInIDEStateValidator.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDEFailureInfoBar.cs
Note: the new class isn't used anywhere yet. It will be used by the show hotspots orchestrator.
> Extracted OpenInIDE info bar handling to separate class

- src/Core/IAbsoluteFilePathLocator.cs
- src/Integration.UnitTests/Helpers/AbsoluteFilePathLocatorTests.cs
- src/Integration/Helpers/AbsoluteFilePathLocator.cs
> Create AbsoluteFilePathLocator service

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/HotspotToIssueVisualizationConverterTests.cs
- src/IssueViz.Security/OpenInIDE/Api/IHotspotToIssueVisualizationConverter.cs
> Convert SQ hotspot relative file path to an absolute file path

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDEFailureInfoBar.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
> Changed failure info toolbar to accept the target tool window id

- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
Fix for the immediate bug to improve the dogfooding experience while I look at refactoring the underlying services.
Related to #1888
> Quick fix for bug clearing gold bar

- src/IssueViz.UnitTests/Editor/DocumentNavigatorTests.cs
- src/IssueViz/Editor/DocumentNavigator.cs
> Run document navigator on UI thread

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/IssueViz.Security/OpenInIDE/Api/IHotspotToIssueVisualizationConverter.cs
> Use normalized SQ file paths

- src/IssueViz.Security/IssueVizSecurityPackage.cs
> Ensure hotspots toolwindow is not open on startup

- src/IssueViz.UnitTests/Helpers/RunOnUIThreadTests.cs
- src/IssueViz/Helpers/RunOnUIThread.cs
> Added RunOnUIThread.RunAsync

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDEFailureInfoBar.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
- src/IssueViz.UnitTests/Helpers/RunOnUIThreadTests.cs
- src/IssueViz/Helpers/RunOnUIThread.cs
> Modified failure infobar method to be async

- src/IssueViz.Security.UnitTests/HotspotsList/HotspotsControlTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/HotspotsToolWindowTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security.UnitTests/SelectionService/HotspotsSelectionServiceTests.cs
- src/IssueViz.Security/HotspotsList/HotspotsControl.xaml.cs
- src/IssueViz.Security/HotspotsList/HotspotsToolWindow.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
- src/IssueViz.Security/SelectionService/HotspotsSelectionService.cs
> Select requested hotspot in the hotspots list

- src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs
- src/Integration.Vsix/InfoBar/InfoBarManager.cs
> Added UI thread checks to InfoBarManager

- src/Core/IIDEWindowService.cs
- src/Integration.UnitTests/Helpers/IDEWindowServiceTests.cs
- src/Integration/Helpers/IDEWindowService.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
Relates #1800
TODO: service implementation
> Add "bring to front" interface; added calls to it

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/StatusRequestHandlerTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Http/StatusOwinRequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
- src/IssueViz.Security/OpenInIDE/Api/StatusRequestHandler.cs
- src/IssueViz.Security/OpenInIDE/Contract/IStatusRequestHandler.cs
- src/IssueViz.Security/OpenInIDE/Http/StatusOwinRequestHandler.cs
> Return real data in SQ status request

- src/Core/CFamily/DynamicCFamilyRulesConfig.cs
- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/FileConfig.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16423
> Update embedded CFamily analyzer to v6.14.0.23970

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
> Fix the order of secondary location in case  partsMakeFlow is set to true

- src/Core/Analysis/AnalysisLanguage.cs
- src/IssueViz.UnitTests/Editor/LanguageDetection/SonarLanguageRecognizerTests.cs
- src/IssueViz/Editor/LanguageDetection/SonarLanguageRecognizer.cs
> Add support for Roslyn in SonarLanguageRecognizer

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIdeStateValidatorTests.cs
- src/IssueViz.Security/OpenInIDE/Api/IOpenInIDEStateValidator.cs
> Fixed server URL comparison

- src/IssueViz.Security.UnitTests/OpenInIDE/Api/HotspotToIssueVisualizationConverterTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security/OpenInIDE/Api/IHotspotToIssueVisualizationConverter.cs
> Update submodule to include new GetHotspotRequest fields

- src/IssueViz.Security/OpenInIDE/Api/IOpenInIDEStateValidator.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.Designer.cs
- src/IssueViz.Security/OpenInIDE/OpenInIDEResources.resx
> Add link to documentation when Hotspots request fails

- src/IssueViz.Security.UnitTests/Models/HotspotTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/HotspotToIssueVisualizationConverterTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security.UnitTests/Store/HotspotsStoreTests.cs
- src/IssueViz.Security/Models/IHotspot.cs
- src/IssueViz.Security/OpenInIDE/Api/IHotspotToIssueVisualizationConverter.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
- src/IssueViz.Security/Store/HotspotsStore.cs
> Add Hotspot to the list only once

- src/Core.UnitTests/SystemAbstractions/ProcessWrapperTests.cs
- src/Core/SystemAbstractions/IProcess.cs
- src/Integration.Vsix.UnitTests/Helpers/IDEWindowServiceTests.cs
- src/Integration.Vsix/Helpers/IDEWindowService.cs
> Stop caching window handle in "bring to front" code

- src/IssueViz.Security/HotspotsList/HotspotsControl.xaml
> Fix datagrid double-click sensitivity

- src/IssueViz.Security.UnitTests/Store/HotspotsStoreTests.cs
- src/IssueViz.Security/Store/HotspotsStore.cs
> Ignore tagging for hotspots without file paths 

- src/IssueViz.Security.UnitTests/HotspotsList/HotspotViewModelTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/SecurityCategoryDisplayNameProviderTests.cs
- src/IssueViz.Security/HotspotsList/HotspotsControl.xaml
- src/IssueViz.Security/HotspotsList/ViewModels/HotspotViewModel.cs
- src/IssueViz.Security/HotspotsList/ViewModels/SecurityCategoryDisplayNameProvider.cs
- src/IssueViz.Security/HotspotsList/ViewModels/SecurityCategoryDisplayNames.cs
> Display security category in Hotspots list

- src/IssueViz.Security/HotspotsList/HotspotsControl.xaml
> Better navigability indication

- src/IssueViz.Security.UnitTests/Commands/HotspotsToolWindowCommandTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/HotspotViewModelTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/HotspotsControlViewModelTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/HotspotsToolWindowTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/PriorityToBackgroundConverterTests.cs
- src/IssueViz.Security.UnitTests/HotspotsList/SecurityCategoryDisplayNameProviderTests.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
- src/IssueViz.Security/Commands/HotspotsToolWindowCommand.cs
- src/IssueViz.Security/IssueVizSecurityPackage.cs
- src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
- src/IssueViz.Security/UI/HotspotsList/HotspotsControl.xaml
- src/IssueViz.Security/UI/HotspotsList/HotspotsControl.xaml.cs
- src/IssueViz.Security/UI/HotspotsList/HotspotsToolWindow.cs
- src/IssueViz.Security/UI/HotspotsList/PriorityToBackgroundConverter.cs
- src/IssueViz.Security/UI/HotspotsList/ViewModels/HotspotViewModel.cs
- src/IssueViz.Security/UI/HotspotsList/ViewModels/HotspotsControlViewModel.cs
- src/IssueViz.Security/UI/HotspotsList/ViewModels/SecurityCategoryDisplayNameProvider.cs
Fixed up test usings. No code changes.
> Changed hotspot namespaces to make folder structure

- src/IssueViz.Security/Hotspots/HotspotsStore.cs
> Use the same readonly wrapper

- src/IssueViz.Security.UnitTests/IssueStoreObserverTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintStoreTests.cs
- src/IssueViz.Security/IssueStoreObserver.cs
- src/IssueViz.Security/Taint/TaintStore.cs
> Add TaintStore

- src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotViewModelTests.cs
- src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
- src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsToolWindowTests.cs
- src/IssueViz.Security.UnitTests/IssueVizDisplayPositionCalculatorTests.cs
- src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
- src/IssueViz.Security/IssueVizDisplayPositionCalculator.cs
Extracting common code that will be used by the taint view model
> Extracted display position calculation from the hotspot view model

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssueViewModel.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Added initial taint view model implementations

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintToolWindowTests.cs
- src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
- src/IssueViz.Security/SharedUI/SharedResources.xaml
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/TaintVulnerabilitiesControl.xaml
- src/IssueViz.Security/Taint/TaintList/TaintVulnerabilitiesControl.xaml.cs
> Added simple columns to taint list

- src/Core/Binding/BoundSolutionUIContext.cs
- src/Core/Binding/BoundSolutionVsUiContext.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
> Add VS UI context for connected mode indication

- src/IssueViz.Security/IssueViz.Security.csproj
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml.cs
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
* TaintVuilnerabilitiesControl -> TaintIssuesControl
No code changes
> Renamed taint control for consistency with VM names

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesBindingMonitorTests.cs
- src/IssueViz.Security/Taint/TaintIssuesBindingMonitor.cs
> Add TaintIssuesBindingMonitor

- src/IssueViz.Security/IssueVizSecurityPackage.cs
- src/IssueViz.Security/Resources.Designer.cs
- src/IssueViz.Security/Resources.resx
- src/IssueViz.Security/Taint/TaintIssuesBindingMonitor.cs
> Start taint services when bound solution is open

- src/Infrastructure.VS.UnitTests/ActiveDocumentLocatorTests.cs
- src/Infrastructure.VS/ActiveDocumentLocator.cs
- src/Infrastructure.VS/TextDocumentProvider.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyReproducerCommandTests.cs
- src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
Prep for #2032 
Affected & tested areas: CFamily reproducer command.
> Move ActiveDocumentLocator to Infrastructure.VS

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Clear Taint list when the binding changes

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssueMatcherTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
* Fixed up tests.
* No product changes
Prep for #1976 and #2042
> Updated submodule to get additional SonarQubeIssue fields

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
- src/IssueViz.Security/Taint/TaintResources.Designer.cs
- src/IssueViz.Security/Taint/TaintResources.resx
> Don't try to fetch taint issues when SQ server is not connected

- src/IssueViz.Security.UnitTests/Taint/Models/TaintIssueTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
- src/IssueViz.Security/Taint/Models/ITaintIssue.cs
- src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
> Add TaintIssue class

- src/IssueViz.Security.UnitTests/ShowInBrowserServiceTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/SharedUI/ShowInBrowserService.cs
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Add ShowInBrowser command

- src/IssueViz.Security.UnitTests/Taint/Models/TaintIssueTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
- src/IssueViz.Security/Taint/Models/ITaintIssue.cs
- src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
Related to #2042
TODO: sorting
> Added creation column

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/Models/ITaintIssue.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Sort taint list by creation date

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Tidy up view model tests

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Ignore issues without file path when filtering for active document

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/IssueVizSecurityPackage.cs
- src/IssueViz.Security/Taint/TaintIssuesExistUIContext.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Dp/taint UI context

- src/Core/IToolWindowService.cs
- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/ToolWIndowService.cs
> Added IToolWindowService.EnsureToolWindowExists

- src/Core/Telemetry/ITelemetryManager.cs
- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/TelemetryData.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/Integration/Telemetry/TelemetryPayload.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Add telemetry to Taint vulnerabilities

- src/IssueViz.Security.UnitTests/ShowInBrowserServiceTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/SharedUI/ShowInBrowserService.cs
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Add overlay to Taint list when solution is not connected to a supported server

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintToolWindowTests.cs
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Change taint window caption dynamically

- src/IssueViz.UnitTests/Selection/IssueSelectionServiceTests.cs
- src/IssueViz/Selection/IssueSelectionService.cs
> Add single selection service

- src/IssueViz.UnitTests/Selection/SelectedVisualizationValidityMonitorTests.cs
- src/IssueViz/Selection/SelectedVisualizationValidityMonitor.cs
> Use IssueSelectionService in SelectedVisualizationValidityMonitor

- src/IssueViz.UnitTests/Editor/QuickActions/DeselectIssueVisualizationActionTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/SelectIssueVisualizationActionTests.cs
- src/IssueViz/Editor/QuickActions/DeselectIssueVisualizationAction.cs
- src/IssueViz/Editor/QuickActions/IssueLocationActionsSource.cs
- src/IssueViz/Editor/QuickActions/IssueLocationActionsSourceProvider.cs
- src/IssueViz/Editor/QuickActions/SelectIssueVisualizationAction.cs
> Use IssueSelectionService in lightbulb actions

- src/Core.UnitTests/WPF/NullToBooleanConverterTests.cs
- src/Core/WPF/NullToBooleanConverter.cs
- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
- src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
> Don't clear secondary locations panel when primary location is non-navigable

- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
- src/IssueViz.UnitTests/Selection/AnalysisIssueSelectionServiceTests.cs
- src/IssueViz.UnitTests/Selection/IssueSelectionServiceTests.cs
- src/IssueViz/Selection/AnalysisIssueSelectionService.cs
- src/IssueViz/Selection/IAnalysisIssueSelectionService.cs
- src/IssueViz/Selection/IssueSelectionService.cs
> Remove the setter from IAnalysisIssueSelectionService

- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
> Change overlay message not to mention the error list

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Add secondary locations selection to taint list

- src/Core.UnitTests/RuleHelpLinkProviderTests.cs
- src/Core/RuleHelpLinkProvider.cs
> Fix the help link for taint issues

- src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
- src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationExtensionsTests.cs
- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
- src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
- src/IssueViz/Models/AnalysisIssueVisualization.cs
> Add note in secondary locations panel when steps become non-navigable

- src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
- src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
> Reverse taint issue's secondary locations

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Change ActiveDocumentFilter to track secondary locations

- src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
- src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
- src/IssueViz.UnitTests/IssueVisualizationControl/FileNameLocationListItemTests.cs
- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
- src/IssueViz/IssueVisualizationControl/ViewModels/FileNameLocationListItem.cs
- src/IssueViz/Models/AnalysisIssueLocationVisualization.cs
> Display missing file names in Secondary Locations panel

- src/IssueViz.UnitTests/Models/AnalysisIssueLocationVisualizationTests.cs
- src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
- src/IssueViz/Models/AnalysisIssueLocationVisualization.cs
- src/IssueViz/Models/AnalysisIssueVisualization.cs
> Invalidate spans of locations in files that could not be resolved

- src/IssueViz/TableControls/VSTableEventProcessorProvider.cs
> Support setting Error List selection for C# issues

- src/Core.UnitTests/WPF/DateTimeConverterTests.cs
- src/Core/WPF/DateTimeConverter.cs
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
> Support regional datetime settings in Taint List

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security.UnitTests/Taint/TaintStoreTests.cs
- src/IssueViz.Security/Taint/AnalysisInformation.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
- src/IssueViz.Security/Taint/TaintStore.cs
> Add disclaimer to taint list

- src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
Fixes #1760.
Styling similar to the combo boxes in the error list.
> Add flows picker to secondary locations panel

- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_FileRenameHandlingTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
> Clear issue selection when live issue's span becomes non navigable

- src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTagTooltipProviderTests.cs
- src/IssueViz/Editor/ErrorTagging/ErrorTagTooltipProvider.cs
> Re-use NavigateToRuleDescriptionCommand

- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
- src/IssueViz/IssueVisualizationControl/ViewModels/Commands/NavigateToDocumentationCommand.cs
> Re-use NavigateToDocumentationCommand

- src/Integration/Notifications/VisualStudioStatusBarHelper.cs
> Display notifications icon in VS2019

- src/Integration.UnitTests/Telemetry/ServerNotificationsTelemetryManagerTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/IServerNotificationsTelemetryManager.cs
- src/Integration/Telemetry/Payload/Analysis.cs
- src/Integration/Telemetry/Payload/IdeVersionInformation.cs
- src/Integration/Telemetry/Payload/ServerNotifications.cs
- src/Integration/Telemetry/Payload/ShowHotspot.cs
- src/Integration/Telemetry/Payload/TaintVulnerabilities.cs
- src/Integration/Telemetry/Payload/TelemetryPayload.cs
- src/Integration/Telemetry/TelemetryData.cs
- src/Integration/Telemetry/TelemetryDataRepository.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
> Add server notifications fields to telemetry payload

- src/Integration.UnitTests/Integration.UnitTests.csproj
- src/Integration.UnitTests/Telemetry/ServerNotificationsTelemetryManagerTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/IServerNotificationsTelemetryManager.cs
- src/Integration/Telemetry/Payload/ServerNotifications.cs
> Change notification counters to be a dictionary

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
> Normalize path of newly created header files

- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Catch project guid exceptions

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Tidy up code and behaviour in taint synchronizer

- src/Infrastructure.VS.UnitTests/ActiveDocumentTrackerTests.cs
- src/Infrastructure.VS/DocumentEvents/ActiveDocumentChangedEventArgs.cs
- src/Infrastructure.VS/DocumentEvents/ActiveDocumentTracker.cs
- src/Integration.Vsix.UnitTests/CFamily/PreCompiledHeaders/PreCompiledHeadersEventListenerTests.cs
- src/Integration.Vsix/CFamily/PreCompiledHeaders/PreCompiledHeadersEventListener.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
- src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
* fix up listeners to handle null event args
Prep for fixing #2091
> Rename ActiveDocumentTracker event class and update comments

- src/Infrastructure.VS.UnitTests/ActiveDocumentTrackerTests.cs
> Cleanup test code

- src/Infrastructure.VS.UnitTests/ActiveDocumentTrackerTests.cs
- src/Infrastructure.VS/DocumentEvents/ActiveDocumentTracker.cs
> Fix ActiveDocumentTracker bugs

- src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
> Update Taint tool window caption on the UI thread

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
> CFamily: improve messages for unsupported options

- build/Signing.targets
- src/Integration.Vsix/Integration.Vsix.csproj
> Moved reference to VSIX signing package to VSIX project

- Directory.Build.props
- build/DownloadCFamilyPlugin/packages.lock.json
- src/Core.UnitTests/packages.lock.json
- src/Core/packages.lock.json
- src/Infrastructure.VS.UnitTests/packages.lock.json
- src/Infrastructure.VS/packages.lock.json
- src/Integration.TeamExplorer.UnitTests/packages.lock.json
- src/Integration.TeamExplorer/packages.lock.json
- src/Integration.UnitTests/packages.lock.json
- src/Integration.Vsix.UnitTests/packages.lock.json
- src/Integration.Vsix/packages.lock.json
- src/Integration/packages.lock.json
- src/IssueViz.Security.UnitTests/packages.lock.json
- src/IssueViz.Security/packages.lock.json
- src/IssueViz.UnitTests/packages.lock.json
- src/IssueViz/packages.lock.json
- src/Progress.TestFramework/packages.lock.json
- src/Progress.UnitTests/packages.lock.json
- src/Progress/packages.lock.json
- src/ProgressVS/packages.lock.json
- src/TestInfrastructure/packages.lock.json
> Generate package.json.lock files

- nuget.config
NB expecting this build to fail.
The nuget.config has been updated, but the feed does not yet contain all of the required packages.
> Updated nuget.config to only use Azdo package feed

- src/Infrastructure.VS.UnitTests/VsVersionProviderTests.cs
- src/Infrastructure.VS/VsVersion/ISetupConfigurationProvider.cs
- src/Infrastructure.VS/VsVersion/VsVersionProvider.cs
> Try-catch instantiation of SetupConfiguration

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
- src/Integration.Vsix.UnitTests/packages.lock.json
- src/Integration.Vsix/Integration.Vsix.csproj
> Moved SonarAnalyzer imports and references out of version props file

- .gitignore
- SonarLint.VisualStudio.Integration.sln
- src/EmbeddedSonarAnalyzer.props
- src/EmbeddedVsix/EmbeddedVsix.csproj
- src/EmbeddedVsix/ReadMe.txt
- src/EmbeddedVsix/packages.lock.json
- src/EmbeddedVsix/source.extension.vsixmanifest
- src/Integration.Vsix.UnitTests/packages.lock.json
- src/Integration.Vsix/Integration.Vsix.csproj
- src/Integration.Vsix/Manifests/VS2015/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2015_v3Manifest/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- src/Integration.Vsix/packages.lock.json
* new VSIX will be embedded in the main VSIX
Relates to #2246
> Added another VSIX for additional files

- src/TypeScript.UnitTests/EslintBridgeClient/AnalysisConfigurationTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/Contract/InitLinterRequest.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/IAnalysisConfiguration.cs
> Add InitLinter endpoint

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeHttpWrapperTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeHttpWrapper.cs
> Support cancellation in EslintBridgeClient

- src/EmbeddedVsix.UnitTests/TypeScriptPathsProviderTests.cs
- src/EmbeddedVsix/EmbeddedVsix.csproj
- src/EmbeddedVsix/TypeScriptPathsProvider.cs
> Add TypeScript metadata file exporter

- src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
- src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
> Add EslintBridgeIssueConverter

- src/TypeScript.UnitTests/Rules/ActiveJavaScriptRulesProviderTests.cs
- src/TypeScript/Rules/ActiveJavaScriptRulesProvider.cs
> Added JavaScript active rules config provider

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
> [1] Use rule definition in issue conversion

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
> Add telemetry for JavascriptAnalyzer

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16661
> Update embedded CFamily analyzer to v6.18.0.29274

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
> Handle EslintBridgeProcess failures

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
> Handle init-linter request failures

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16723
> Update embedded CFamily analyzer to v6.19.0.30153

- src/TypeScript.UnitTests/Rules/RuleDefinitionsProviderTests.cs
- src/TypeScript/Rules/RulesRepository.cs
Fixes the bug calculating the help link
Fixes #2301
> Change JS rule key to include repo id

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
> Change ArgumentException to InvalidOperationException

- src/TypeScript.UnitTests/Rules/ActiveJavaScriptRulesProviderTests.cs
> Minor cleanup of ActiveJavaScriptRulesProviderTests

- src/Core/IActiveSolutionTracker.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/Integration/MefServices/ActiveSolutionTracker.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs
> Move IActiveSolutionTracker to Core

- src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
> Add ConfigChanged event

- src/Core.UnitTests/SonarCompositeRuleIdTests.cs
- src/Core/SonarCompositeRuleId.cs
> Added SonarCompositeRuleId helper class

- src/Core/Analysis/IAnalysisConfigMonitor.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalyzerControllerTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
- src/Integration.Vsix/Analysis/AnalyzerController.cs
> Move IAnalysisConfigMonitor to Core

- src/Core/Analysis/IAnalysisConfigMonitor.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalyzerControllerTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
- src/Integration.Vsix/Analysis/AnalyzerController.cs
- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
> Stop EslintBridge process when analysis config changes

- src/Core.UnitTests/SonarCompositeRuleIdTests.cs
- src/Core/SonarArtefactKeys.cs
- src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
- src/Integration.Vsix/Analysis/DisableRuleCommand.cs
> Allow disabling JS rules in standalone and connected mode

- src/Core.UnitTests/CFamily/CFamilyBindingConfigTests.cs
- src/Core.UnitTests/RuleSettingsSerializerTests.cs
- src/Core/RulesSettings.cs
- src/TypeScript.UnitTests/Rules/ActiveJavaScriptRulesProviderTests.cs
- src/TypeScript/Rules/ActiveJavaScriptRulesProvider.cs
> Add setting to disable JavaScript analysis

- src/Core.UnitTests/Binding/CompositeBindingConfigProviderTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/Payload/TelemetryPayload.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/TestInfrastructure/Helpers/MefTestHelpers.cs
- src/TypeScript.UnitTests/Rules/ActiveJavaScriptRulesProviderTests.cs
>  Added disabledLanguages data to telemetry payload

- src/Core.UnitTests/SonarCompositeRuleIdTests.cs
- src/Core/SonarCompositeRuleId.cs
- src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
- src/Integration.Vsix/Analysis/DisableRuleCommand.cs
Settings file should contain the whole composite rule key, not just the Sonar rule key part.
Fixes bug in #771
> Fix bug in disabling rule

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
> Ensure the script path argument is quoted

- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlTests.cs
- src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogPageTests.cs
- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
- src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs
- src/Integration/WPF/RelayCommand.cs
- src/Integration/WPF/RelayCommandBase.cs
Added hyperlink to show the wiki in a browser.
Fixes #2349
> Update text in options window

- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
Fixes #2318
Note: this should be merged after 6.18 that why I'm setting "branch-updateAnalyzers" as a base branch
> Add support for C++20 ("/std:c++latest")

- README.MD
> Added link to false positive section in forum

- src/TypeScript.UnitTests/Rules/ActiveRulesCalculatorTests.cs
- src/TypeScript.UnitTests/Rules/ActiveRulesProviderTests.cs
- src/TypeScript/Rules/ActiveRulesCalculator.cs
- src/TypeScript/Rules/ActiveRulesProviders.cs
> Added TypeScript active rules provider

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/Resources.Designer.cs
- src/TypeScript/EslintBridgeClient/Resources.resx
> Implement new-tsconfig method

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/Contract/AnalysisResponse.cs
- src/TypeScript/EslintBridgeClient/Contract/TSConfigResponse.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
> Implement tsconfig-files method

- src/TypeScript.UnitTests/Rules/RuleProviderTests.cs
- src/TypeScript.UnitTests/Rules/RulesProviderFactoryTests.cs
- src/TypeScript.UnitTests/Rules/RulesProviderTests.cs
- src/TypeScript/Rules/RulesProviderFactory.cs
- src/TypeScript/Rules/RulesProviders.cs
No changes to existing code - purely additive
> Added IRulesProvider and factory

- src/Core/Analysis/AnalysisLanguage.cs
- src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
> Add initial TypeScriptAnalyzer

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientFactoryTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeHttpWrapperTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessFactoryTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClientFactory.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeHttpWrapper.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcessFactory.cs
> Make EslintBridgeProcess multi-instance

- src/IssueViz.UnitTests/Editor/LanguageDetection/SonarLanguageRecognizerTests.cs
- src/IssueViz/Editor/LanguageDetection/SonarLanguageRecognizer.cs
> Detect "TypeScript" AnalysisLanguage

- src/EmbeddedVsix.UnitTests/TypeScriptRuleDefinitions_SanityChecks.cs
- src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/Rules/RulesProviderFactoryTests.cs
- src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
... rather that IJavaScriptRulesDefinitionProvider
> Changed EslintBridgeIssueConverter to use IRulesProvider

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
> Add analyze-ts method

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16739
> Update embedded CFamily analyzer to v6.20.0.31240

- src/TypeScript.UnitTests/TsConfig/TsConfigProviderTests.cs
- src/TypeScript/TsConfig/TsConfigProvider.cs
> Implement TSConfig provider

- src/Integration.Vsix/SonarLintTelemetryPackage.cs
> Move SonarLintTelemetryPackage init code inside try-catch

- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
> Updated webclient to get fix for #2406

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeHttpWrapperTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClientFactory.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeHttpWrapper.cs
> Move EslintBridgeProcess into EslintBridgeClient

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
> Ensure InitLinter is called when new EslintBridgeProcess is spawned

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/JavaScriptEslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/TypeScriptEslintBridgeClientTests.cs
- src/TypeScript.UnitTests/TsConfig/TsConfigProviderTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/JavaScriptEslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/TypeScriptEslintBridgeClient.cs
- src/TypeScript/TsConfig/TsConfigProvider.cs
> Create MEF-exportable TypeScriptEslintBridgeClient and JavaScriptEslintBridgeClient

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
> Stop running EslintBridgeProcess when solution closes

- src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerFactoryTests.cs
- src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs
- src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs
- src/TypeScript/Analyzer/EslintBridgeAnalyzerFactory.cs
> Create generic EslintBridgeAnalyzer

- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
> Use IEslintBridgeAnalyzer in JavaScriptAnalyzer

- src/Core/Analysis/IAnalysisStatusNotifier.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierTests.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.resx
- src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/Resources.Designer.cs
- src/TypeScript/Analyzer/Resources.resx
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
> Use IEslintBridgeAnalyzer in TypeScriptAnalyzer

- src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
> Collect telemetry in TypescriptAnalyzer

- src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
- src/Integration.Vsix/Analysis/DisableRuleCommand.cs
> Support disabling TypeScript rules

- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
> Update option page text to refer to TypeScript

- src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs
- src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs
> Don't shutdown eslint-bridge process when settings are updated

- src/TypeScript/EslintBridgeClient/EslintBridgeHttpWrapper.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
- src/TypeScript/EslintBridgeClient/Resources.Designer.cs
- src/TypeScript/EslintBridgeClient/Resources.resx
- added process id to all EsLintBridgeProcess messages
- removed debug messages from resource files
> Tidy up eslintbridge logging

- src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.resx
> Always request analysis when user settings change

- src/TypeScript.UnitTests/TsConfig/TsConfigProviderTests.cs
- src/TypeScript/TsConfig/Resources.Designer.cs
- src/TypeScript/TsConfig/Resources.resx
- src/TypeScript/TsConfig/TsConfigProvider.cs
> Process projectReferences in tsconfig.json files

- src/TypeScript.UnitTests/TsConfig/TsConfigProviderTests.cs
- src/TypeScript/TsConfig/TsConfigProvider.cs
> Support directory path in project references

- src/EmbeddedSonarAnalyzer.props
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16749
> Update embedded CFamily analyzer to v6.21.0.32709

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
> Don't start EslintBridgeServer when VS is shutting down

- src/Infrastructure.VS.UnitTests/ActiveDocumentTrackerTests.cs
- src/Infrastructure.VS/DocumentEvents/ActiveDocumentTracker.cs
> Raise ActiveDocumentChanged event when transitioning from toolwindow to document

- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
> Remove noisy debug log in EslintBridgeProcess

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
- src/IssueViz.UnitTests/Editor/LineHashCalculatorTests.cs
- src/IssueViz/Editor/LineHashCalculator.cs
> Fix LF line hash calculations

- src/Core.UnitTests/RuleHelpLinkProviderTests.cs
- src/Core/RuleHelpLinkProvider.cs
- src/Core/SonarArtefactKeys.cs
> Fix hotspot help link in the Editor

- src/EmbeddedSonarAnalyzer.props
> Embed SonarJS 8.1.0

- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration/Helpers/Constants.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Catch exceptions on UIThread in ErrorListInfoBarController

- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration/LocalServices/ErrorListInfoBarController.cs
> Guard additional UI thread paths in ErrorListInfoBarController

- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotFactoryTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshotFactory.cs
- src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
> Don't show empty lines in the Error List when issues are non-navigable

- src/Infrastructure.VS.UnitTests/FolderWorkspaceServiceTests.cs
- src/Infrastructure.VS/FolderWorkspaceService.cs
- src/TypeScript.UnitTests/TsConfig/TsConfigsLocatorTests.cs
- src/TypeScript/TsConfig/TsConfigsLocator.cs
> Add FolderWorkspaceService

- src/Core/CFamily/IRequest.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/Request.cs
* changed CLangAnalyzer to use the new interface
* fixed up tests
Prep for #2194
> Introduced IRequest interface for CFamily subprocess requests

- src/Core/CFamily/SubProcessFilePaths.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/PreCompiledHeaders/PreCompiledHeadersEventListener.cs
* extracted path calculations to a separate class
* moved standalone execution method from CFamilyHelper to CLangAnalyzer
> Minor cleanup of CFamily helper code

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Embed CFamily analyzer 6.23.0.34138

- src/Core/CFamily/IRequest.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix.UnitTests/CFamily/RequestTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/Request.cs
* moved reproducer creation to CLangAnalyzer
* removed downcast from CLangAnalyzer
Prep for #2194
> Changed IRequest to include WriteX methods

- src/Core/CFamily/IRequest.cs
- src/Core/CFamily/RequestContext.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CFamily_CLangAnalyzer_IntegrationTests.cs
- src/Integration.Vsix.UnitTests/CFamily/RequestTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/Request.cs
* fix-up to CFamilyHelper / Request is hacky and needs more work
> Extracted RequestContext from IRequest

- src/CFamily/CMake/CompilationConfigProvider.cs
- src/Core.UnitTests/CFamily/CFamilySharedTests.cs
- src/Core/CFamily/CFamilyShared.cs
- src/Integration.Vsix.UnitTests/CFamily/CMake/CompilationDatabaseRequestFactoryTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequestFactory.cs
> Added CompilationDatabaseRequestFactory

- src/Integration.Vsix.UnitTests/CFamily/FileConfigProviderTests.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/FileConfigProvider.cs
> Extract code from CFamilyHelper into FileConfigProvider

- src/CFamily.UnitTests/Rules/RulesConfigProtocolFormatterTests.cs
- src/CFamily/Analysis/RulesConfigProtocolFormatter.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequest.cs
> Add RulesConfigProtocolFormatter

- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
> Fix PCH verbose output log

- src/CFamily.UnitTests/CMake/CompilationConfigProviderTests.cs
- src/CFamily/CMake/CompilationConfigProvider.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
- src/Core/CFamily/CFamilyShared.cs
- src/Integration.Vsix.UnitTests/CFamily/CMake/CompilationDatabaseRequestFactoryTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CMake/CompilationDatabaseRequestTests.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequest.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequestFactory.cs
> Support CMake header files analysis

- src/Integration.UnitTests/LocalServices/BuildPropertyTestProjectIndicatorTests.cs
- src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs
- src/Integration/LocalServices/ProjectSystemFilter.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/LocalServices/TestProjectIndicators/BuildPropertyTestProjectIndicator.cs
> Support running TestProjectIndicators on Open as Folder projects

- src/Infrastructure.VS.UnitTests/FolderWorkspaceServiceTests.cs
- src/Infrastructure.VS/FolderWorkspaceService.cs
- src/Integration.UnitTests/Binding/BindingControllerTests.cs
- src/Integration/Binding/BindingController.cs
> Enable Bind command on Open as Folder projects

- src/CFamily.UnitTests/SystemAbstractions/ProcessWrapperTests.cs
Tweaked test in an attempt to reduce the flakiness.
Added test logging to help diagnose failures.
> Added logging to flaky test

- src/Integration.Vsix.UnitTests/CFamily/CMake/CompilationDatabaseRequestTests.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequest.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequestFactory.cs
* the factory is responsible for getting the values to pass
> Pass env vars to CompilationDatabaseRequest from factory

- src/CFamily.UnitTests/CMake/VsDevCmdEnvironmentVarsProviderTests.cs
- src/CFamily/CMake/VsDevCmdEnvironmentVarsProvider.cs
- src/Core.UnitTests/Core.UnitTests.csproj
- src/Core.UnitTests/SystemAbstractions/CurrentProcessWrapperTests.cs
- src/Core.UnitTests/SystemAbstractions/ProcessWrapperTests.cs
- src/Core/SystemAbstractions/ICurrentProcess.cs
- src/Core/SystemAbstractions/IProcess.cs
- src/Integration.Vsix.UnitTests/Helpers/IDEWindowServiceTests.cs
- src/Integration.Vsix/Helpers/IDEWindowService.cs
No code changes: just file moves, namespace changes, and scope changes (moved classes and interfaces made public so they are accessible from the CFamily project).
> Move/rename IProcess and tests

- src/CFamily.UnitTests/CMake/CompilationConfigProviderTests.cs
- src/CFamily/CMake/CompilationConfigProvider.cs
- src/Core.UnitTests/CFamily/CFamilySharedTests.cs
- src/Core/CFamily/CFamilyShared.cs
> Support analyzing additional header extensions

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
> Fix CMake suppressions

- src/Integration.Vsix.UnitTests/CFamily/CMake/CompilationDatabaseRequestTests.cs
- src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequest.cs
> Pass HeaderFileLanguage to the subprocess

- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
Cleaned up the tests prior to making some changes to CLangAnalyzer.
No product code changes.
My overall plan for the next few PRs:
* clean up the CLangAnalyzer tests (this PR);
* change IRequestFactory.TryGet to be asynchronous, which will mean changing the CLangAnalyzer and its tests;
* add the new CMake environment settings provider, which needs to be async.
> Tidied up CLangAnalyzerTests

- src/CFamily.UnitTests/CMake/CompilationConfigProviderTests.cs
- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily/CMake/CompilationConfigProvider.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
> Move compilation database file existence check

- src/Integration.UnitTests/Telemetry/TelemetryClientTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/Payload/CFamilyProjectTypes.cs
- src/Integration/Telemetry/Payload/TelemetryPayload.cs
- src/Integration/Telemetry/TelemetryData.cs
- src/Integration/Telemetry/TelemetryHelper.cs
- src/Integration/Telemetry/TelemetryManager.cs
> Add CFamilyProjectTypes to telemetry payload

- src/CFamily.UnitTests/CFamilyProjectTypeIndicatorTests.cs
- src/CFamily/CFamilyProjectTypeIndicator.cs
- src/Core/CFamily/ICFamilyProjectTypeIndicator.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration/ProjectToLanguageMapper.cs
> Extract CMake project type indication logic

- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
> CLangAnalyzer: moved request-creation to background thread

- src/CFamily.UnitTests/CMake/VsDevCmdEnvironmentVarsProviderTests.cs
- src/CFamily/CMake/VsDevCmdEnvironmentVarsProvider.cs
> Increase timeout for fetching environment variables

- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
> Reduce verbosity of invalid CMake settings message

- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
> Handle missing buildRoot in CMakeSettings

- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/TestInfrastructure/Extensions/FileSystemExtensions.cs
> Added extension methods for IFileSystem mocks

- src/CFamily.UnitTests/CMake/CMakeSettingsProviderTests.cs
- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily/CMake/CMakeSettingsProvider.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
> Extract code to CMakeSettingsProvider

- src/CFamily.UnitTests/CMake/CMakeSettingsProviderTests.cs
- src/CFamily/CMake/CMakeSettingsProvider.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
> Search for CMakeSettings.json in all directories

- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily.UnitTests/CMake/MacroEvaluationServiceTests.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/MacroEvaluationService.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
> Added skeleton IMacroEvaluationService

- src/CFamily.UnitTests/CMake/MacroEvaluationServiceTests.cs
- src/CFamily.UnitTests/CMake/MacroEvaluatorTests.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/MacroEvaluationService.cs
- src/CFamily/CMake/MacroEvaluator.cs
- src/CFamily/CMake/Resources.Designer.cs
- src/CFamily/CMake/Resources.resx
> Added macro detection and processing

- src/CFamily.UnitTests/CMake/MacroEvaluatorTests.cs
- src/CFamily/CMake/MacroEvaluator.cs
- src/Core.UnitTests/EnvironmentVariableProviderTests.cs
- src/Core/EnvironmentVariableProvider.cs
> Evaluate env variables macros

- src/CFamily.UnitTests/CMake/CMakeSettingsProviderTests.cs
- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily.UnitTests/CMake/MacroEvaluationServiceTests.cs
- src/CFamily/CMake/CMakeSettings.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/MacroEvaluationService.cs
> Pass evaluation context + Parse the generator from CMakeSettings

- src/CFamily.UnitTests/CMake/CompilationDatabaseLocatorTests.cs
- src/CFamily.UnitTests/CMake/MacroEvaluationServiceTests.cs
- src/CFamily.UnitTests/CMake/MacroEvaluatorTests.cs
- src/CFamily/CMake/CompilationDatabaseLocator.cs
- src/CFamily/CMake/EvaluationContext.cs
- src/CFamily/CMake/MacroEvaluationService.cs
- src/CFamily/CMake/MacroEvaluator.cs
> Support additional simple macros

- src/CFamily.UnitTests/CMake/MacroEvaluatorTests.cs
- src/CFamily/CMake/MacroEvaluator.cs
> Support workspaceHash and projectHash

- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/MessageHandlerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/NoOpMessageHandlerTests.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/MessageHandler.cs
Refactoring `CLangAnalyzer` to improve testability
> Extracted message handling code to separate class

- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/MessageHandlerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/NoOpMessageHandlerTests.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
- src/Integration.Vsix/CFamily/CFamilyStrings.resx
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/MessageHandler.cs
> Handle CMake internal messages

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelper_CaptureTests.cs
- src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
- src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
- src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs
> Support the new "/std:c++20" flag

- src/EmbeddedVsix/EmbeddedVsix.csproj
> Improve performance of local builds

- src/EmbeddedVsix/EmbeddedVsix.csproj
> Remove duplicate property

- src/Integration.Vsix/Integration.Vsix.csproj
> Fix pipeline assembly locking

- src/Integration/Helpers/KnownUIContextsWrapper.cs
> Fix KnownUIContextsWrapper pass-through

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
Release notes: https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16944
> Update embedded CFamily analyzer to v6.27.0.38122

- src/Integration.Vsix.UnitTests/CFamily/VcxProject/FileConfigTests.cs
- src/Integration.Vsix/CFamily/VcxProject/FileConfig.cs
> Add support for platform toolset v143 (VS2022)

- src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
> Update extension description

- src/Core.UnitTests/Binding/CompositeBindingConfigProviderTests.cs
- src/Core.UnitTests/CFamily/CFamilyBindingConfigTests.cs
- src/Core/Binding/CompositeBindingConfigProvider.cs
- src/Core/CFamily/CFamilySonarWayRulesConfigProvider.cs
- src/Integration.UnitTests/NewConnectedMode/NoOpNuGetBindingOperationTests.cs
- src/Integration.Vsix.UnitTests/Settings/SonarLintSettingsTests.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/Integration/MefServices/MefSonarQubeService.cs
- src/IssueViz.Security.UnitTests/Hotspots/Models/HotspotRuleTests.cs
- src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
> Fix some SC warnings

- src/Core/CFamily/EffectiveRulesConfigCalculator.cs
> Change RulesConfigCache dictionary to ConcurrentDictionary

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Taint package load - handle exceptions when server is unavailable

- src/Integration.Vsix.UnitTests/CFamily/CFamilyHelper_CaptureTests.cs
- src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
> `platformName` should be compared in a case insensitive way

- src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
> Update VSIX marketplace description

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueConverterFactoryTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
- src/Integration.Vsix/CFamily/CLangAnalyzer.cs
- src/Integration.Vsix/CFamily/MessageHandler.cs
- src/Integration/ETW/CodeMarkers.cs
> Make CFamily converter stateful

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamily_CallAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CLangAnalyzerTestFile_OneIssue_HasSecondaryLocations_response.json
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CLangAnalyzerTestFile_OneIssue_response.json
- src/Integration.Vsix.UnitTests/CFamily/IntegrationTests/CLangAnalyzerTestFile_TwoIssues_response.json
- src/Integration.Vsix.UnitTests/CFamily/MessageHandlerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/NoOpMessageHandlerTests.cs
- src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Analyzer.cs
- src/Integration.Vsix/CFamily/PortedFromJava/Protocol.cs
Release notes
6.28 - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=17012
6.29 - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=17062
> Update embedded CFamily analyzer to v6.29.0.41127

- src/Core/Analysis/AnalysisIssue.cs
- src/Core/Analysis/IAnalysisIssue.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProvider.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
- src/TestInfrastructure/DummyAnalysisIssue.cs
- src/TestInfrastructure/NoOpThreadHandler.cs
> Add quick fix suggested action

- src/Core/Analysis/IAnalysisIssue.cs
- src/Core/Analysis/IQuickFix.cs
- src/Core/Analysis/QuickFix.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
- src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
- src/IssueViz/Editor/IIssueSpanCalculator.cs
- src/IssueViz/Models/AnalysisIssueVisualization.cs
- src/IssueViz/Models/AnalysisIssueVisualizationConverter.cs
- src/IssueViz/Models/QuickFixVisualization.cs
> Calculate QuickFixes span

- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
> Fix quick-fix's column offset

- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
> 2857 Removed question marks from VS 2019 description

- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
> 2863 Added "SonarLint" prefix to quick fix display

- src/Core/Telemetry/IQuickFixesTelemetryManager.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/Payload/RulesUsage.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProvider.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
Fixes [#2841](https://github.com/SonarSource/sonarlint-visualstudio/issues/2841)
> Add QuickFixes to telemetry payload

- src/Core/Telemetry/IQuickFixesTelemetryManager.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/Payload/RulesUsage.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/IQuickFixesTelemetryManager.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProvider.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
> Call IQuickFixTelemetryManager

- src/Core/Telemetry/IQuickFixesTelemetryManager.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_CreatePayload.cs
- src/Integration.UnitTests/Telemetry/TelemetryHelper_Serialize.cs
- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration/Telemetry/Payload/RulesUsage.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProviderTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/IQuickFixesTelemetryManager.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProvider.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
Prep for https://github.com/SonarSource/sonarlint-visualstudio/pull/2866
> Use test helper methods to avoid repetition

- src/Integration/Telemetry/TelemetryManager.cs
> Fix multithreading issue in TelemetryManager

- src/Core/Suppressions/ISuppressedIssuesFileStorage.cs
Prep for [#2889](https://github.com/SonarSource/sonarlint-visualstudio/issues/2889)
> Add ISuppressedIssuesFileStorage initial interface

- src/Core/Suppressions/ISonarQubeIssuesProvider.cs
- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/Integration/Suppression/SuppressedIssuesProvider.cs
Part of [#2889](https://github.com/SonarSource/sonarlint-visualstudio/issues/2889)
Prep for https://github.com/SonarSource/sonarlint-visualstudio/pull/2894
> Add GetAllSuppressedIssues method

- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SonarDiagnosticSuppressorTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/Container.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SonarDiagnosticSuppressor.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionChecker.cs
> Write the Diagnostic Suppressor 

- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionCheckerTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/TestHelper.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/Container.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionChecker.cs
> Implement suppression checker

- src/Core/Suppressions/ISonarQubeIssuesProvider.cs
- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/Integration/Suppression/SuppressedIssuesProvider.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/SuppressedIssuesFileSynchronizerTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/SuppressedIssuesFileSynchronizer.cs
> Made GetAllSuppressedIssues method async

- src/Core/IThreadHandling.cs
- src/Infrastructure.VS/ThreadHandling.cs
- src/TestInfrastructure/NoOpThreadHandler.cs
Prep for [#2932](https://github.com/SonarSource/sonarlint-visualstudio/issues/2932)
> Add RunAsync method to ThreadHandling

- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SonarDiagnosticSuppressorTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SonarDiagnosticSuppressor.cs
Fixes [#2937](https://github.com/SonarSource/sonarlint-visualstudio/issues/2937)
> Ensure container is initialized only in Connected Mode

- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/IssueConverterTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/RoslynSettingsFileStorageTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionCheckerTests.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/TestHelper.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/RoslynSettings.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionChecker.cs
> Store only required issue fields required for suppression matching

- src/Core/ETW/CodeMarkers.cs
> Fix duplicate ETW ids

- src/Core/ETW/CodeMarkers.cs
> Fix ETW ArrayTypeMismatch exception

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
Cherry-picked changes from #2874
> Update embedded CFamily analyzer from 6.29.0.41127 to 6.31.0.44497

- src/Core/Analysis/AnalysisIssue.cs
- src/Core/Analysis/IAnalysisIssue.cs
- src/Core/Analysis/IQuickFix.cs
- src/Core/Analysis/QuickFix.cs
- src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
- src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
- src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
- src/IssueViz/Models/AnalysisIssueVisualizationConverter.cs
Prep for [#2971](https://github.com/SonarSource/sonarlint-visualstudio/issues/2971)
> Change IEdit to have ITextRange

- src/Core.UnitTests/Helpers/PathHelperTests.cs
- src/Core/CFamily/SubProcessFilePaths.cs
- src/Core/Helpers/PathHelper.cs
- src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileInfo.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
> Notify EslintBridge that the caller is SonarLint 

- src/Core.UnitTests/Analysis/AnalysisIssueTests.cs
- src/Core/Analysis/IAnalysisIssue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
- src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/AccumulatingIssueConsumerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
- src/Integration.Vsix/SonarLintTagger/AccumulatingIssueConsumer.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
- src/IssueViz.UnitTests/Editor/IssueSpanCalculatorTests.cs
- src/IssueViz/Editor/IIssueSpanCalculator.cs
- src/IssueViz/Models/AnalysisIssueVisualization.cs
- src/IssueViz/Models/AnalysisIssueVisualizationConverter.cs
- src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
- src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
> [TypeScript] File-level are not displayed in the Error List

- src/EmbeddedSonarAnalyzer.props
- src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript.UnitTests/Rules/ActiveRulesCalculatorTests.cs
- src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
- src/TypeScript/EslintBridgeClient/Contract/AnalysisResponse.cs
- src/TypeScript/EslintBridgeClient/Contract/InitLinterRequest.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
- src/TypeScript/EslintBridgeClient/Resources.Designer.cs
- src/TypeScript/EslintBridgeClient/Resources.resx
- src/TypeScript/EslintBridgeClient/TypeScriptEslintBridgeClient.cs
- src/TypeScript/Rules/ActiveRulesCalculator.cs
> Update embedded JS/TS analyzer to 8.9.0.17411 

- src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryPayloadCreatorTests.cs
- src/Integration.UnitTests/Telemetry/TelemetrySerializerTests.cs
- src/Integration/Telemetry/TelemetryClient.cs
- src/Integration/Telemetry/TelemetryManager.cs
- src/Integration/Telemetry/TelemetryPayloadCreator.cs
- src/Integration/Telemetry/TelemetrySerializer.cs
> Change TelemetryHelper to non static class

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
- src/TypeScript/EslintBridgeClient/Contract/AnalysisRequest.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
>  Send FileType when analysing

- src/EmbeddedSonarAnalyzer.props
Fixes [#3013](https://github.com/SonarSource/sonarlint-visualstudio/issues/3013)
> Update JSTS to 8.6.0.16913

- src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
Fixes #3021, caused by https://github.com/SonarSource/sonarlint-visualstudio/pull/2973
> Fix xaml binding in Hotspots view model

- src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
Fixes #3015, caused by https://github.com/SonarSource/sonarlint-visualstudio/pull/2973
> Fix xaml binding in Taint Vulnerabilities view model

- src/Core/Analysis/IAnalyzableFileIndicator.cs
- src/Integration.UnitTests/Exclusions/AnalyzableFileIndicatorTests.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalyzerControllerTests.cs
- src/Integration.Vsix/Analysis/AnalyzerController.cs
- src/Integration/Exclusions/AnalyzableFileIndicator.cs
Part of [#3045](https://github.com/SonarSource/sonarlint-visualstudio/issues/3045)
> Add outer shell to exclude files from analysis

- src/Core/Analysis/IExclusionSettingsFileStorage.cs
- src/Integration.UnitTests/Exclusions/AnalyzableFileIndicatorTests.cs
- src/Integration/Exclusions/AnalyzableFileIndicator.cs
- src/Integration/Exclusions/ExclusionSettingsFileStorage.cs
Fixes [#3061](https://github.com/SonarSource/sonarlint-visualstudio/issues/3061)
Code coverage is low due to an empty class that would be implemented in a separate task.
> Add inclusions/exclusions logic

- src/Integration.UnitTests/Exclusions/ExclusionSettingsFileStorageTests.cs
- src/Integration/Exclusions/ExclusionSettingsFileStorage.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3057
> Save exclusions to disk

- src/Core/Analysis/IExclusionSettingsStorage.cs
- src/Integration.UnitTests/Exclusions/ExclusionSettingsStorageTests.cs
- src/Integration/Exclusions/ExclusionSettingsStorage.cs
Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/3069
> Add bool SettingsExist

- src/Integration.UnitTests/LocalServices/BindingCheckerTests.cs
- src/Integration/LocalServices/IBindingChecker.cs
- src/Integration/LocalServices/IUnboundSolutionChecker.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
Part of [#3069](https://github.com/SonarSource/sonarlint-visualstudio/issues/3069)
> Use IUnboundSolutionChecker in BindingChecker

- src/Integration.UnitTests/LocalServices/UnboundSolutionCheckerTests.cs
- src/Integration/LocalServices/IUnboundSolutionChecker.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
Fixes [#3069](https://github.com/SonarSource/sonarlint-visualstudio/issues/3069)
> Implement UnboundSolutionChecker

- src/Core.UnitTests/GlobPatternMatcherTests.cs
- src/Core/GlobPatternMatcher.cs
- src/Integration.UnitTests/Exclusions/AnalyzableFileIndicatorTests.cs
- src/Integration.UnitTests/Exclusions/ExclusionSettingsStorageTests.cs
- src/Integration/Exclusions/AnalyzableFileIndicator.cs
- src/Integration/Exclusions/ExclusionSettingsStorage.cs
> Add debug logs for server exclusions

- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Update binding out-of-date message

- src/Core.UnitTests/Binding/NonRoslynBindingConfigFileTests.cs
- src/Core.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
- src/Core/Binding/NonRoslynBindingConfigFile.cs
- src/Core/Binding/NonRoslynBindingConfigProvider.cs
- src/Integration/Binding/BindingController.cs
Prep for [#3105](https://github.com/SonarSource/sonarlint-visualstudio/issues/3105)
> Rename CFamily binding config to generic non-roslyn

- src/Core/JsTs/IJsTsProjectTypeIndicator.cs
- src/Core/Language.cs
- src/Core/SonarArtefactKeys.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/Connection/MinimumSupportedSonarQubePluginTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/Connection/MinimumSupportedSonarQubePlugin.cs
- src/Integration/ProjectToLanguageMapper.cs
- src/TypeScript/JsTsProjectTypeIndicator.cs
Fixes [#3105](https://github.com/SonarSource/sonarlint-visualstudio/issues/3105)
It might help to look at each commit separately; the changes done in each are only to fix a specific part of the binding.
> Fetch JS/TS QP from the server and save to disk

- src/CFamily.UnitTests/Rules/CFamilyRuleConfigProviderTests.cs
- src/CFamily/Rules/CFamilyRulesConfigProvider.cs
Cleanup following #[3109](https://github.com/SonarSource/sonarlint-visualstudio/issues/3109)
> Reuse IRuleSettingsProvider in CFamilyRuleConfigProvider

- src/Integration.UnitTests/Binding/BindingControllerTests.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/LocalServices/UnboundProjectFinderTests.cs
- src/Integration/Binding/BindingController.cs
- src/Integration/Binding/BindingProcessImpl.cs
- src/Integration/Binding/BindingWorkflow.cs
- src/Integration/Binding/IBindingProcess.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/LocalServices/UnboundProjectFinder.cs
- src/Integration/ProjectToLanguageMapper.cs
Fixes [#3113](https://github.com/SonarSource/sonarlint-visualstudio/issues/3113)
> Support connected mode for folders

- src/Core/RuleHelpLinkProvider.cs
- src/Core/SonarArtefactKeys.cs
> Fix js/ts taint help links

- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration/Connection/ConnectionWorkflow.cs
- src/Integration/Resources/Strings.Designer.cs
- src/Integration/Resources/Strings.resx
> Update list of supported languages in binding message

- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
- src/IssueViz/Resources.Designer.cs
- src/IssueViz/Resources.resx
> Guard against quick fix gold bar

- src/Core/IFolderWorkspaceInitializedEvent.cs
- src/Core/IFolderWorkspaceMonitor.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionTracker.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssuesBindingMonitorTests.cs
- src/IssueViz.Security/Taint/TaintIssuesBindingMonitor.cs
Fixes [#3133](https://github.com/SonarSource/sonarlint-visualstudio/issues/3133)
> Support Taint vulnerabilities in folder workspaces

- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration/Binding/SolutionBindingOperation.cs
- src/Integration/LocalServices/ProjectSystemHelper.cs
- src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs
> Handle project types without project-level binder

- src/Core/IThreadHandling.cs
- src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs
- src/Infrastructure.VS/ThreadHandling.cs
- src/TestInfrastructure/NoOpThreadHandler.cs
> Added RunOnBackgroundThread to IThreadHandling

- src/Integration/MefServices/MefSonarQubeService.cs
Fixes [#696](https://github.com/SonarSource/sonarlint-visualstudio/issues/696)
> Update submodule to override InvokeUncheckedRequestAsync

- src/Integration/MefServices/MefSonarQubeService.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
Fixes [#3152](https://github.com/SonarSource/sonarlint-visualstudio/issues/3152)
> Re-use the same ServerInfo

- src/Integration.UnitTests/MefServices/MefSonarQubeServiceTests.cs
- src/Integration/MefServices/MefSonarQubeService.cs
> Ensure web calls are done on a background thread

- src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
- src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
- src/Integration.Vsix/Analysis/AnalysisStrings.resx
Fixes [#3157](https://github.com/SonarSource/sonarlint-visualstudio/issues/3157)
> Ignore user settings change when in connected mode

- src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs
- src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs
> Run ActiveSolutionTracker_ActiveSolutionChanged on the background thread

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
> Embed CFamily analyzer 6.36.0.52033

- src/Core/InfoBar/IInfoBar.cs
- src/Core/InfoBar/IInfoBarManager.cs
- src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs
- src/Integration.Vsix/InfoBar/InfoBarManager.cs
- src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBar.cs
- src/TestInfrastructure/Framework/ConfigurableInfoBarManager.cs
- src/TestInfrastructure/Framework/ConfigurableVsInfoBarUIElement.cs
Fixes [#3189](https://github.com/SonarSource/sonarlint-visualstudio/issues/3189)
> Support multiple buttons in the infobar

- src/Core/Notifications/IDisabledNotificationsStorage.cs
- src/Core/Notifications/INotificationService.cs
- src/Core/Notifications/Notification.cs
- src/Core/Notifications/NotificationAction.cs
> Rename file + namespaces

- src/Core.UnitTests/Notifications/NotificationServiceTests.cs
- src/Core/CoreStrings.Designer.cs
- src/Core/CoreStrings.resx
- src/Core/Notifications/INotificationService.cs
- src/Core/SonarLintImageMoniker.cs
Fixes [#3194](https://github.com/SonarSource/sonarlint-visualstudio/issues/3194).
Supporting "do not show again" is a sizable chunk so I've created a new task for it and will do it in a separate PR.
> Implement NotificationService

- src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeHttpWrapperTests.cs
- src/TypeScript/EslintBridgeClient/EslintBridgeHttpWrapper.cs
> Add GetAsync method to EslintBridgeHttpWrapper

- src/Core.UnitTests/Notifications/NotificationServiceTests.cs
- src/Core/Notifications/INotificationService.cs
Fixes [#3205](https://github.com/SonarSource/sonarlint-visualstudio/issues/3205)
> Don't re-display same notification

- src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
- src/TypeScript.UnitTests/Notifications/UnsupportedNodeVersionNotificationServiceTests.cs
- src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs
> Call Node notification service if compatible version not found

- src/TypeScript.UnitTests/Rules/RuleDefns_CheckDetailedProperties.json
- src/TypeScript.UnitTests/Rules/RulesProviderFactoryTests.cs
- src/TypeScript/Rules/RuleDefinition.cs
> Fix JS scope metadata deserialization

- src/Core.UnitTests/Notifications/DisabledNotificationsStorageTests.cs
- src/Core/Notifications/IDisabledNotificationsStorage.cs
> Disabled notifications file is not created when folder does not exist 

- src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
- src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs
> Update the minimum required NodeJS version 

- src/Core.UnitTests/Notifications/DoNotShowAgainNotificationActionTests.cs
- src/Core.UnitTests/Notifications/NotificationActionTests.cs
- src/Core.UnitTests/Notifications/NotificationServiceTests.cs
- src/Core/Notifications/DoNotShowAgainNotificationAction.cs
- src/Core/Notifications/INotificationService.cs
- src/Core/Notifications/NotificationAction.cs
- src/TypeScript/Notifications/IUnsupportedNodeVersionNotificationService.cs
> Gold bar isn't removed after clicking don't show this again

- src/Core.UnitTests/Notifications/DisabledNotificationsStorageTests.cs
- src/Core/Notifications/DisabledNotifications.cs
- src/Core/Notifications/IDisabledNotificationsStorage.cs
> Change notification storage file format to be more general

- src/Integration.Vsix.UnitTests/Analysis/SingleFileMonitorTests.cs
> Ignore flaky test - RealFile_MultipleOperations_NoDuplicates

- src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
- src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
> Handle exceptions in quick fix source 

- .sonarlint/SonarLint.VisualStudio.Integration.slconfig
- .sonarlint/sonar.settings.json
- .sonarlint/sonarlint-visualstudioCSharp.ruleset
- .sonarlint/sonarlint-visualstudio_js_settings.json
- .sonarlint/sonarlint-visualstudio_ts_settings.json
Update the binding config.
No code changes.
> Updated .sonarlint config

- src/IssueViz.Security.UnitTests/OpenInIDE/Http/OwinPipelineProcessorTests.cs
- src/IssueViz.UnitTests/Editor/IssueSpanCalculatorTests.cs
- src/IssueViz.UnitTests/Editor/LocationTagging/IssueLocationStoreAggregatorTests.cs
- src/IssueViz.UnitTests/Selection/IssueSelectionServiceTests.cs
- src/IssueViz/Editor/LocationTagging/IssueLocationStoreAggregator.cs
- src/TestInfrastructure/Helpers/Exceptions.cs
- src/TestInfrastructure/Helpers/MefTestHelpers.cs
- src/TypeScript.UnitTests/NodeJSLocator/NodeVersionInfoProviderTests.cs
- was not correctly checking for required exports
Fixes #2467
> Fix MefTestHelper

- src/IssueViz.Security.UnitTests/OpenInIDE/Http/OwinPipelineProcessorTests.cs
- src/IssueViz.UnitTests/Editor/LocationTagging/IssueLocationStoreAggregatorTests.cs
- src/TestInfrastructure/Helpers/MefTestHelpers.cs
Simplified the two 'ImportMany' MEF tests
> Tidied up MEF tests

- src/Core.UnitTests/CSharpVB/SerializerTests.cs
- src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
- src/Integration.UnitTests/Binding/CSharpVbBindingConfigTests.cs
- src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
> Change serialization tests to pass for x64 .NET runtime

- src/Integration.Vsix.UnitTests/Analysis/IssueConsumerFactoryTests.cs
- src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
- src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs
- src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Refactoring: added IIssueConsumerFactory

- src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
- src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
- src/Integration.Vsix/Resources/Strings.Designer.cs
- src/Integration.Vsix/Resources/Strings.resx
- src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
> Execute GetGuidOfProject on UI thread

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
Fixes [#3262](https://github.com/SonarSource/sonarlint-visualstudio/issues/3262)
Tested by verifying a rule in the release notes https://sonarsource.atlassian.net/browse/CPP-2925?jql=project%20%3D%2010166%20AND%20fixVersion%20%3D%2013801%20ORDER%20BY%20priority%20DESC%2C%20key%20ASC
> Update embedded CFamily analyzer to 6.37.0.60132

- src/EmbeddedSonarAnalyzer.props
- src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
- src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs
- src/TypeScript/NodeJSLocator/Resources.Designer.cs
- src/TypeScript/NodeJSLocator/Resources.resx
- src/TypeScript/Notifications/IUnsupportedNodeVersionNotificationService.cs
Fixes [#3274](https://github.com/SonarSource/sonarlint-visualstudio/issues/3274)
> Update embedded SonarJS to 9.8.0.19239

- pipeline/azure-pipelines.yml
WhiteSource was renamed to Mend, we're changing the secret names (currently, both exists)
> Rename WHITESOURCE_APIKEY to MEND_APIKEY

- pipeline/azure-pipelines.yml
- pipeline/scripts/sbom.ps1
> Fix SBOM generation in pipeline

- pipeline/azure-pipelines.yml
> Change pipline feed to use new "ExternalTools" feed

- README.MD
WIP for this ticket to correctly capitalize Connected Mode.
https://sonarsource.atlassian.net/browse/DOC-96
> DOC-96, and minor stylization hardening

- src/EmbeddedSonarAnalyzer.props
> Update embedded JavaScript analyzer to 9.9.0.19492 

- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
> Update VSIX manifest to reference SonarAnalyzer.CFG

- src/Integration.UnitTests/Binding/JsTsProjectTypeIndicatorTests.cs
- src/Integration/Binding/BindingStrings.Designer.cs
- src/Integration/Binding/BindingStrings.resx
- src/Integration/Binding/JsTsProjectTypeIndicator.cs
> Add try-catch in JsTsProjectTypeIndicator

- src/IssueViz.UnitTests/Editor/TaggableBufferIndicatorTests.cs
- src/IssueViz/Editor/TaggableBufferIndicator.cs
Fixes [#3301](https://github.com/SonarSource/sonarlint-visualstudio/issues/3301)
> Exclude analysis on temp files

- src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
- src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
> Update VSIX manifest to reference Roslyn.Suppressions dependencies as an analyzers

- src/EmbeddedSonarAnalyzer.props
> Update embedded JavaScript analyzer to 9.11.0.20161

- src/Integration.Vsix.UnitTests/Analysis/SingleFileMonitorTests.cs
- src/Integration.Vsix/Analysis/SingleFileMonitor.cs
Fixes #3236
Replaced flaky test with ones that make more sense.
> Replace flaky test.

- src/Infrastructure.VS.UnitTests/FolderWorkspaceServiceTests.cs
- src/Infrastructure.VS.UnitTests/WorkspaceServiceTests.cs
- src/Infrastructure.VS/FolderWorkspaceService.cs
- src/Infrastructure.VS/Resources.Designer.cs
- src/Infrastructure.VS/Resources.resx
- src/Infrastructure.VS/WorkspaceService.cs
> Implement IWorkspaceService 

- src/CFamily.UnitTests/Analysis/CLangAnalyzerTests.cs
- src/CFamily/Analysis/CLangAnalyzer.cs
- src/CloudSecrets.UnitTests/SecretsAnalyzerTests.cs
- src/CloudSecrets/SecretsAnalyzer.cs
- src/Core/Analysis/IAnalysisStatusNotifierFactory.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierFactoryTests.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierTests.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifierFactory.cs
- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
Prep for [#3111](https://github.com/SonarSource/sonarlint-visualstudio/issues/3111)
> Make AnalysisStatusNotifier stateful

- src/CFamily.UnitTests/Analysis/CLangAnalyzerTests.cs
- src/CFamily/Analysis/CLangAnalyzer.cs
- src/CloudSecrets.UnitTests/SecretsAnalyzerTests.cs
- src/CloudSecrets/SecretsAnalyzer.cs
- src/Core/Analysis/IAnalysisStatusNotifierFactory.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierFactoryTests.cs
- src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierTests.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
- src/Integration.Vsix/Analysis/AnalysisStatusNotifierFactory.cs
- src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
- src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
- src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
- src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3111
> Include analyzer name in the output window

- src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
- src/Integration.Vsix/SonarLint.vsct
> New Top Menu for SonarLint under Extensions Menu

- src/Integration.Vsix/Commands/ConnectedModeMenu/ConnectedModeMenu.vsct
- src/Integration.Vsix/SonarLint.vsct
Fixes [#3372](https://github.com/SonarSource/sonarlint-visualstudio/issues/3372)
> Add Connected Mode menu

- src/Integration.Vsix/SonarLint.vsct
- src/IssueViz.Security/Commands/IssueVizSecurityPackage.vsct
Fixes [#3363](https://github.com/SonarSource/sonarlint-visualstudio/issues/3363)
> Move taint and hotspots into SonarLint -> Connected Mode menu

- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- no product changes
Prep for #3398
> Add CreateTestSubject method to SonarQubeIssuesProviderTests

- MarketPlaceFiles/VS2019/overview-2019.md
- MarketPlaceFiles/VS2022/overview-2022.md
Fixes [#3395](https://github.com/SonarSource/sonarlint-visualstudio/issues/3395)
> Update marketplace link

- src/Integration.Vsix/Commands/ConnectedModeMenu/ConnectedModeMenu.vsct
- src/Integration.Vsix/Commands/HelpMenu/HelpMenu.vsct
> Cosmetic changes to menus

- src/IssueViz/Commands/IssueVizPackage.vsct
> Place IssueViz command under SonarLint menu

- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
Changes to a single test file.
> Cleanup TaintIssuesSynchronizerTests

- src/Integration.Vsix/Commands/HelpMenu/HelpMenu.vsct
> Add groups to help menu for dividers.

- src/Integration.Vsix/Commands/ConnectedModeMenu/ConnectedModeMenu.vsct
Fixes [#3424](https://github.com/SonarSource/sonarlint-visualstudio/issues/3424)
> Improve UX of Bind command

- src/IssueViz/Editor/QuickActions/SelectIssueVisualizationAction.cs
> Capitalize Show Issue Viz action

- src/Integration.Vsix/Commands/HelpMenu/HelpMenu.vsct
> Change label of Report a Problem menu item

- src/Integration.UnitTests/Binding/BindingControllerTests.cs
- src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
- src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
- src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
- src/Integration.UnitTests/Connection/ConnectControllerTests.cs
- src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
- src/Integration.UnitTests/Helpers/SonarLintOutputTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
- src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
- src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
- src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
- src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleSetConflictsControllerTests.cs
- src/Integration.UnitTests/ProfileConflicts/RuleSetInspectorTests.cs
- src/Integration.UnitTests/Progress/ProgressNotificationListenerTests.cs
- src/Integration/MefServices/VsSessionHost.cs
- src/Integration/ProfileConflicts/RuleSetConflictsController.cs
- src/TestInfrastructure/Framework/ConfigurableHost.cs
Prep for [#3430](https://github.com/SonarSource/sonarlint-visualstudio/issues/3430)
> Replace direct references to SonarLintOutputLogger

- src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/3430
> Fix logging label in the Options page

- src/Core.UnitTests/EnvironmentSettingsTests.cs
- src/Core/EnvironmentSettings.cs
- src/Core/IEnvironmentSettings.cs
> Remove env var `SONARLINT_INTERNAL_LOG_DEBUG`

- src/IssueViz/Editor/QuickActions/DeselectIssueVisualizationAction.cs
> Capitalize Hide Issue Viz action

- src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
- src/ConnectedMode/ServerBranchProvider.cs
- src/Core/IServerBranchProvider.cs
- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Add cancellation token to IServerBranchProvider

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3381
> Update embedded CFamily analyzer to 6.40.0.60596

- src/ConnectedMode.UnitTests/BranchMatcherTests.cs
- src/ConnectedMode/BranchMatcher.cs
> Make IBranchMatcher MEF-exportable

- src/EmbeddedSonarAnalyzer.props
> Upgrade js analyzer to 9.12.0.20319

- src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
- src/ConnectedMode/Resources.Designer.cs
- src/ConnectedMode/Resources.resx
- src/ConnectedMode/ServerBranchProvider.cs
> Implement ServerBranchProvider

- src/ConnectedMode.UnitTests/BranchMatcherTests.cs
- src/ConnectedMode/BranchMatcher.cs
> Add cancellation token to IBranchMatcher

- pipeline/azure-pipelines.yml
> Fix yaml to reference ref/heads/master

- nuget.config
> Add CycloneDX to trusted signers

- src/SonarLint.Test.props
- src/TestProjects.ruleset
> Disable VSTHRD rules on test projects

- src/ConnectedMode.UnitTests/BranchMatcherTests.cs
- src/ConnectedMode.UnitTests/LibGit2SharpWrappers/BranchWrapper.cs
- src/ConnectedMode.UnitTests/LibGit2SharpWrappers/CommitLogWrapper.cs
- src/ConnectedMode.UnitTests/LibGit2SharpWrappers/CommitLogWrapperWithEnumerationCount.cs
- src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
- src/ConnectedMode/BranchMatcher.cs
- src/ConnectedMode/ServerBranchProvider.cs
> Optimise branch mapper 

- src/Core/IGitEvents.cs
> Added IGitChanges event

- src/Core/Binding/IActiveSolutionBoundTracker.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
- src/TestInfrastructure/Framework/ConfigurableActiveSolutionBoundTracker.cs
> Add PreSolutionBindingChanged to IActiveSolutionBoundTracker

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
>  Track repo events in ActiveSolutionBoundTracker

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
> Raise PreSolutionBindingEventUpdated event when repo changes

- src/ConnectedMode.UnitTests/BoundSolutionGitMonitorTests.cs
- src/ConnectedMode/BoundSolutionGitMonitor.cs
- src/Core.UnitTests/GitEventsMonitorTests.cs
- src/Core/Binding/IBoundSolutionGitMonitor.cs
- src/Core/GitEventsMonitor.cs
- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
- src/Integration/MefServices/ActiveSolutionBoundTracker.cs
> Add bound solution git monitor 

- src/ConnectedMode/BranchMatcher.cs
- src/Core/ETW/CodeMarkers.cs
> Add ETW tracing to branch mapper component 

- src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
- src/ConnectedMode/StatefulServerBranchProvider.cs
- src/Core/IServerBranchProvider.cs
- src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
- src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
- src/Integration/Suppression/SonarQubeIssuesProvider.cs
- src/Integration/Suppression/SuppressedIssuesProvider.cs
- src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
- src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
> Add Stateful IServerBranchMapper

- src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
> Add "Refresh" test

- src/ConnectedMode.UnitTests/BranchMatcherTests.cs
- src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
- src/ConnectedMode/BranchMatcher.cs
- src/ConnectedMode/Resources.Designer.cs
- src/ConnectedMode/Resources.resx
- src/ConnectedMode/ServerBranchProvider.cs
- src/ConnectedMode/StatefulServerBranchProvider.cs
> Add logging to branch matching

- src/ConnectedMode.UnitTests/BoundSolutionGitMonitorTests.cs
- src/ConnectedMode/BoundSolutionGitMonitor.cs
- src/ConnectedMode/Resources.Designer.cs
- src/ConnectedMode/Resources.resx
- src/Core.UnitTests/GitEventsMonitorTests.cs
> Add logging to git repo monitor

- src/Integration.UnitTests/Helpers/SonarLintOutputTests.cs
- src/Integration/Helpers/SonarLintOutputLogger.cs
> Log the thread id in verbose mode

- src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
- src/ConnectedMode/StatefulServerBranchProvider.cs
> Call branch mapper on the background thread

- src/EmbeddedSonarAnalyzer.props
- src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs
> Update embedded CFamily analyzer to 6.41.0.60884

- src/Core/IToolWindowService.cs
- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/ToolWIndowService.cs
fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3560
> Add a method GetToolWindow in ToolWindowService.

- .gitignore
- SonarLint.VisualStudio.Integration.sln
- build/ProcessJarFiles/CommonProperties.props
- build/ProcessJarFiles/JarProcessing.targets
- pipeline/azure-pipelines.yml
- src/Rules.UnitTests/EmbeddedResourceTests.cs
- src/Rules/Rules.csproj
> Embed rule descriptions as resources in Rules.csproj

- build/tools/ExtractRuleDescFromJson/RuleDescExtractor.cs
- src/Rules.UnitTests/EmbeddedResourceTests.cs
> Add test that rule desc resources are XML

- src/Core/IToolWindowService.cs
- src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
- src/Integration/Helpers/ToolWIndowService.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3560
> Change method signature of getToolWindow in ToolWindowService.

- src/Education/Commands/RuleDescriptionToolWindow.cs
> Make RuleDescriptionToolWindow of type IRuleDescriptionToolWindow

- src/Core/IErrorListHelper.cs
- src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
- src/Infrastructure.VS/ErrorListHelper.cs
- src/Infrastructure.VS/IErrorListHelper.cs
- src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
- src/Integration.Vsix/Analysis/DisableRuleCommand.cs
fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3597
> Add class "ErrorListHelper" and move errorList related logic from DisableRulesCommand

- src/Education/XamlGenerator/IRuleHelpXamlBuilder.cs
- src/Education/XamlGenerator/StyleResourceNames.cs
> Modify xaml generator to use styles

- src/Core.UnitTests/LanguageTests.cs
- src/Core/Language.cs
Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3600
> Add GetLanguageFromRepositoryKey to Languages.cs

- src/Education/XamlGenerator/IRuleHelpXamlBuilder.cs
- src/Education/XamlGenerator/StyleResourceNames.cs
- alter whitespace handling
- add table cell style
> Tweak the XAML generator

- src/Education/Commands/RuleDescriptionToolWindow.cs
- src/Education/Commands/RuleDescriptionUserControl.xaml
- src/Education/Resources.Designer.cs
- src/Education/Resources.resx
- add boilerplate text for the empty tool window
Part of #3601
> Add theming for standard rule help styles

- src/Education/EducationPackage.cs
> Temporarily disable initialization of command interceptor

- src/Education/Commands/RuleDescriptionUserControl.xaml
- src/Education/XamlGenerator/IRuleHelpXamlBuilder.cs
- src/Education/XamlGenerator/StyleResourceNames.cs
> Add title and text subtitle

- src/Education/Commands/EducationPackage.vsct
- src/Education/Resources.Designer.cs
- src/Education/Resources.resx
> Change help command text and window caption

- src/Education.UnitTests/Commands/RuleHelpWindowCommandTests.cs
- src/Education.UnitTests/Commands/ShowRuleHelpFromErrorListTests.cs
- src/Education.UnitTests/EducationTests.cs
- src/Education.UnitTests/ErrorList/SonarErrorListEventProcessorTests.cs
- src/Education/Commands/EducationPackage.vsct
- src/Education/Commands/RuleHelpToolWindow.cs
- src/Education/Commands/RuleHelpUserControl.xaml
- src/Education/Commands/RuleHelpUserControl.xaml.cs
- src/Education/Commands/RuleHelpWindowCommand.cs
- src/Education/Commands/ShowRuleHelpFromErrorList.cs
- src/Education/Education.csproj
- src/Education/EducationPackage.cs
- src/Education/ErrorList/SonarErrorListEventProcessor.cs
- src/Education/IEducation.cs
- src/Education/Resources.Designer.cs
- src/Education/Resources.resx
... from "rule description"
No code changes.
Part of #3629
> Rename education types to "rule help"
