appveyor.yml

Use correct syntax for command prompt environment variables %NAME% rather than MSBuild style $(NAME)

Fix use of environment variables

---

src/Integration.UnitTests/Binding/BindCommandTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectCommandTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.UnitTests/State/TransferableVisualStateTests.cs
src/Integration.UnitTests/TeamExplorer/ConnectSectionControllerTests.cs
src/Integration.UnitTests/TeamExplorer/ConnectSectionTests.cs
src/Integration.UnitTests/TeamExplorer/TestableConnectSectionController.cs
src/Integration/Binding/BindCommand.cs
src/Integration/Connection/ConnectCommand.cs
src/Integration/Integration.csproj
src/Integration/State/TransferableVisualState.cs
src/Integration/TeamExplorer/ConnectSectionController.cs
src/Integration/TeamExplorer/ConnectSectionView.xaml
src/Integration/TeamExplorer/ConnectSectionViewModel.cs

The visual state needs to be transferable between TE sections navigation since the view and vm are disposed each time.
I've also simplified the tests, the API and removed the bound-projects (plural) concept and replaced it with a single HasBoundProject property which will work with WPF as long as the state API will be used to set/clear the bound project.
Misc: quite a few of the changes are because I resolved tech-debt issue coming from the analyzers in the modified files that I've touched.
I'll highlight the important changes

[SVS-24] Extract the transferable state into a separate cls

---

src/Integration.UnitTests/Binding/BindCommandTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration/Binding/BindCommand.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingWorkflowExecutor.cs
src/Integration/Binding/SolutionRuleSetWriter.cs
src/Integration/Constants.cs
src/Integration/IProjectSystemHelper.cs
src/Integration/Integration.csproj
src/Integration/ProjectSystemHelper.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/VsShellUtils.cs
src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs
src/TestInfrastructure/Helpers/RoslynExportProfileHelper.cs
src/TestInfrastructure/TestInfrastructure.csproj
src/TestInfrastructure/VsObjectModelMocks/SolutionMock.Solution2.cs
src/TestInfrastructure/VsObjectModelMocks/SolutionMock.cs

Added an extra step in the BindingWorkflow to unpack the additional files (if any) that are downloaded with the quality profile export XML. Additional files are unpacked under the SonarQube folder, alongside the solution level rule set file.
Also renamed the IBindingWorkflow interface to IBindingWorkflowExecutor in order to better reflect what it actually does (similar to the IConnectionWorkflowExec..). With the previous name, it was strange to have BindCommand implement IBindingWorkflow, but BindingWorkflow NOT implement IBindingWorkflow.

[SVS-5] Additional files for parametrized SonarQube rules are retrieved from the SonarQube quality profile

---

src/Integration.UnitTests/ProjectSystemHelperTests.cs
src/Integration/ProjectSystemHelper.cs

Globally filtering out VB.NET projects as a supported managed project.

[SVS-20] Filter out VB.NET projects globally

---

.gitignore
src/Integration.UnitTests/Binding/BindCommandTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectCommandTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/TeamExplorer/ConnectSectionControllerTests.cs
src/Integration.UnitTests/TeamExplorer/ConnectSectionTests.cs
src/Integration.UnitTests/TeamExplorer/TestableConnectSectionController.cs
src/Integration/Constants.cs
src/Integration/IWebBrowser.cs
src/Integration/Integration.csproj
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/TeamExplorer/CommonStyles.xaml
src/Integration/TeamExplorer/ConnectSectionController.cs
src/Integration/TeamExplorer/ConnectSectionView.xaml
src/Integration/TeamExplorer/ConnectSectionViewModel.cs
src/Integration/WebBrowser.cs
src/TestInfrastructure/Framework/ConfigurableWebBrowser.cs
src/TestInfrastructure/TestInfrastructure.csproj

Invitation to connect/use SonarQube is shown on the Team Explorer SonarQube page > Connections section when there is no active server connection.
The card provides "Connect..." and "More info..." links.
Connect executes the connect command. More info executes a new command to
navigate to any URL using new IWebBrowser, passing the URL as a parameter.
Currently looks like this:
With "More info..." taking you to http://sonarqube.org

[SVS-29] Add SonarQube invitation when not connected

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.UnitTests/ProjectSystemHelperTests.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Constants.cs
src/Integration/IProjectSystemHelper.cs
src/Integration/Integration.csproj
src/Integration/ProjectSystemHelper.cs
src/Integration/VsShellUtils.cs
src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs
src/TestInfrastructure/TestInfrastructure.csproj
src/TestInfrastructure/VsObjectModelMocks/ProjectItemsMock.cs
src/TestInfrastructure/VsObjectModelMocks/PropertiesMock.cs

@duncanpMS pointed out two issues, corrected both with these changes.
Issue 1: `AdditionalFiles` not `AdditionalFile` => renamed.
Issue 2: Files are not shown in Solution Explorer immediately => use EnvDTE object model rather than MSBuild.

[SVS-5] Fix issues with adding Additional Files

---

src/Integration.UnitTests/Binding/ProjectRuleSetWriterTests.cs
src/Integration.UnitTests/PathHelperTests.cs
src/Integration/Binding/ProjectRuleSetWriter.cs

For solutions which already had setup shared project-level rule sets, we were updating the rule set file once per project (with the same include).
This was causing unnecessary disk writes. As a result the IDE/Roslyn was reloading (with a lock for some reason) this file just as we are about to write to it again (for the next project).
Now keeping track of which existing rule sets we've already updated and skipping the update & write when we try with the same file again. This is OK since a new `ProjectRuleSetWriter` is created for each `BindingWorkflow` (which is per bind operation).

[SVS-38] Alleviate file locking issues by reducing number of rule set writes

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/ProjectRuleSetWriterTests.cs
src/Integration.UnitTests/PathHelperTests.cs
src/Integration/Binding/ProjectRuleSetWriter.cs
src/Integration/PathHelper.cs
src/TestInfrastructure/Helpers/TestRuleSetHelper.cs

Corrected an issue whereby when updating a project level rule set's
includes, the removal of old 'SonarQube' rule sets wasn't happening.
In fact it was (in some cases) removing other rule set includes NOT under
the SonarQube folder.
This was because the relative path resolution of the rule set include was
being done against the wrong base path. Also there was no check for
whether or not the computed path actually existed.
This issue manifested itself when binding with the Roslyn project.

[SVS-39] Fix issue around duplicate Includes in rule set files

---

src/Integration.UnitTests/Binding/BindCommandTests.cs
src/Integration/Binding/BindCommand.cs
src/Integration/VsShellUtils.cs

Disabled the bind command until the UI context SolutionExistsAndIsFullyLoaded is also activated.

[SVS-47] Bind command is disabled until sln is fully loaded

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/Service/ISonarQubeServiceWrapper.cs
src/Integration/Service/SonarQubeServiceWrapper.cs
src/Integration/TeamExplorer/NotificationIds.cs
src/TestInfrastructure/Framework/ConfigurableProgressStepExecutionEvents.cs
src/TestInfrastructure/Framework/ConfigurableSonarQubeServiceWrapper.cs

Instead of checking as a step in the `BindingWorkflow`, now do the check as part of the `ConnectionStep` of the `ConnectionWorkflow`.
In the event that the server does not have the correct plugin version, a Team Explorer notification is shown and the workflow is aborted.

[SVS-43] Check for server plugin at connection step

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/ProjectSystemFilterTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.UnitTests/LanguageTests.cs
src/Integration.UnitTests/ProjectSystemHelperTests.cs
src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IProjectSystemFilter.cs
src/Integration/Binding/ProjectSystemFilter.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/Constants.cs
src/Integration/IProjectSystemHelper.cs
src/Integration/Integration.csproj
src/Integration/Language.cs
src/Integration/ProjectSystemHelper.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/Service/DataModel/ServerProperty.cs
src/Integration/Service/ISonarQubeServiceWrapper.cs
src/Integration/Service/SonarQubeServiceWrapper.cs
src/TestInfrastructure/Framework/ConfigurableProjectSystemFilter.cs
src/TestInfrastructure/Framework/ConfigurableServiceProvider.cs
src/TestInfrastructure/Framework/ConfigurableSonarQubeServiceWrapper.cs
src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs
src/TestInfrastructure/TestInfrastructure.csproj
src/TestInfrastructure/VsObjectModelMocks/ProjectMock.cs

SonarQubeTestProject and SonarQubeExclude MSBuild properties are now detected and respected on bind. Also the test project regex (from the server) is taken into account when detecting a test project.

[SVS-58] Test project detection and project exclusion

---

src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/Service/ISonarQubeServiceWrapper.cs
src/Integration/Service/SonarQubeServiceWrapper.cs
src/Integration/State/StateManager.cs
src/Integration/TeamExplorer/ISectionController.cs
src/Integration/TeamExplorer/SectionController.cs
src/Integration/TeamExplorer/ServerViewModel.cs
src/TestInfrastructure/Framework/ConfigurableSectionController.cs
src/TestInfrastructure/Framework/ConfigurableSonarQubeServiceWrapper.cs

- Added a "Browse" command to the server node in the Team Explorer to open the user's preferred web browser at the server's URL.
- Added a "View in SonarQube" command to the project nodes (under a server) to also open the user's browser at the project dashboard.

[SVS-13] Add Browse/View on web commands to server & project nodes

---

src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.UnitTests/Service/ConnectionInformationTests.cs
src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
src/Integration.UnitTests/UriExtensionsTests.cs
src/Integration/Integration.csproj
src/Integration/Service/DataModel/ConnectionInformation.cs
src/Integration/Service/SonarQubeServiceWrapper.cs
src/Integration/UriExtensions.cs

When the request Uri was being constructed, the presence of the leading slash on the API URI paths forced the path to be relative to the root of the base address (the hostname).
Strengthened against inconsistencies with leading & trailing slashes when combining Uri parts.

[SVS-78] Fix issue with request URL construction

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.UnitTests/Persistence/SolutionBindingSerializerTests.cs
src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
src/Integration.UnitTests/SonarAnalyzer/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/VsSessionHostTests.cs
src/Integration.Vsix.UnitTests/Telemetry/BoundSolutionAnalyzerTests.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/Integration.csproj
src/Integration/Persistence/ISolutionBindingSerializer.cs
src/Integration/Persistence/SolutionBindingSerializer.cs
src/Integration/ProfileConflicts/ConflictsManager.cs
src/Integration/SonarAnalyzer/ActiveSolutionBoundTracker.cs
src/Integration/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableSolutionBindingSerializer.cs
src/TestInfrastructure/TestInfrastructure.csproj

Rename SolutionBinding to SolutionBindingSerializer (consistent with another functionally similar class), also less ambiguous.
All the changes are obvious except for one - which I'll comment inline. 
NOTE : Please look at the specific commit (6e6....) since this builds on top of an already existing PR (the first commit). Once the 1st PR is reviewed and we can check it in I'll commit and rebase this one,

[Technical] rename SolutionBinding

---

src/Integration.Vsix.UnitTests/SonarAnalyzer/SonarAnalyzerDeactivationManagerForBoundTests.cs
src/Integration.Vsix/SonarAnalyzerDeactivationManager.cs
src/Integration.Vsix/SonarLintIntegrationPackage.cs

SonarAnalyzerDeactivationManager  disposed a MEF imported service by implementing IDisposable interface and as a result the test implemented it as well (presumable in order to avoid suppressing a false positive which would be a more appropriate in this case). 
The thing is that MEF IDisposable components are managed and disposed by MEF, so we should not need all of that, hence this PR.

[Technical] Remove non-required IDisposable objects from VSIX

---

src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
src/Integration.UnitTests/SonarAnalyzer/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/VsSessionHostTests.cs
src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs
src/Integration.Vsix.UnitTests/SonarAnalyzer/SonarAnalyzerDeactivationManagerForBoundTests.cs
src/Integration.Vsix/InfoBar/InfoBarManager.cs
src/Integration.Vsix/SonarAnalyzerDeactivationManager.cs
src/Integration.Vsix/Telemetry/GeneratedCode/SqmCommandFacade.cs
src/Integration.Vsix/Telemetry/GeneratedCode/SqmOleCommandTarget.cs
src/Integration.Vsix/Telemetry/GeneratedCode/SqmVsCommands.vsct
src/Integration.Vsix/Telemetry/SonarLintSqmData.ttinclude
src/Integration.Vsix/Telemetry/TelemetryLogger.cs
src/Integration/Integration.csproj
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/LocalServices/IErrorListInfoBarController.cs
src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
src/Integration/LocalServices/SolutionBindingInformationProvider.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/IActiveSolutionBoundTracker.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/TelemetryEvent.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionBoundTracker.cs
src/TestInfrastructure/Framework/ConfigurableErrorListInfoBarController.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs
src/TestInfrastructure/Framework/ConfigurableVsWindowFrame.cs
src/TestInfrastructure/TestInfrastructure.csproj

ErrorListInfoBarController is complex enough to be reviewed by itself. So i split the PR into two parts - this part focuses on integration and the next PR will focus just on ErrorListInfoBarController which is responsible to call the various services and show the info bar when needed.
1. Added a stub for ErrorListInfoBarController 
2. Integrated it into the extension (the methods don't do anything at this point)
3. Added tests
4. Modified and tested other bits of the existing code which I'll be using in the non-stub version of ErrorListInfoBarController.

[SVS-9] Add an ErrorListInfoBarController stub

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

The output is less detailed as proposed in SVS-81, but has enough information to understand which project were excluded/not supported etc.

[SVS-81] Provide information which projects excluded from binding

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/SanityTests.cs
src/Integration.UnitTests/Service/SonarQubeServiceWrapperTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/Service/ISonarQubeServiceWrapper.cs
src/Integration/Service/SonarQubeServiceWrapper.cs
src/Integration/State/IStateManager.cs
src/Integration/State/StateManager.cs
src/Integration/TeamExplorer/ProjectViewModel.cs
src/Integration/TeamExplorer/SectionController.cs
src/TestInfrastructure/Framework/ConfigurableConnectionWorkflow.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs
src/TestInfrastructure/Framework/ConfigurableSolutionBindingInformationProvider.cs
src/TestInfrastructure/Framework/ConfigurableSonarQubeServiceWrapper.cs
src/TestInfrastructure/Framework/ConfigurableStateManager.cs

Before proceeding with the SQ condition of SVS-9, I'm cleaning up the service since the state that it holds needs to be kept at the state manager level.
Please review c501d31 only (this PR builds on an already pending PR).
The state manager holds the state and disposes of connection information when disconnected.

[Techincal] [SVS-9] SonarQubeServiceWrapper is stateless and we can clearly know when the service call failed

---

src/Integration/TeamExplorer/CommonStyles.xaml
src/SonarQube/SolutionBinding.sqconfig
src/SonarQube/sonarlint-visualstudioCSharp.ruleset

Use a custom control template for the tree view on the SonarQube team explorer page, which omits the `ScrollViewer` present in the default one.
This allows the mouse scroll wheel events to be first handled by the TE, rather than our control.
I also updated the binding, as prompted, because the quality profile had changed on the SQ server.

[SVS-21] Allow to scroll in the SonarQube projects lists when binding

---

src/Integration.Vsix/Commands/PackageCommands.vsct

NB: I'm not using the exact wording/brackets in the [ticket](https://jira.sonarsource.com/browse/SVS-102)
> "SonarLint (connected mode)"
because this does not align with the phrasing/style of the rest of the VS menus.
> "SonarLint Connected Mode"
is much more appealing and consistent.

[SVS-102] SonarLint -> SonarLint Connected Mode

---

src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/Integration.Vsix/Suppression/DelegateInjector.cs
src/Integration.Vsix/Suppression/LiveIssue.cs
src/Integration.Vsix/Suppression/LiveIssueFactory.cs
src/Integration.Vsix/Suppression/SuppressionManager.cs
src/Integration/Suppression/ChecksumCalculator.cs
src/Integration/Suppression/IServerIssuesProvider.cs
src/Integration/Suppression/ServerIssue.cs
src/Integration/Suppression/ServerIssuesProvider.cs

Added skeleton classes as a starting point for the end-to-end suppressions experience.
This commit is a first attempt at breaking the whole problem into a series of smaller pieces that can be tackled individually. All of the classes have TODOs in them and we'll probably want to split/move some of the code around.
I was struggling to understand what the logical split between the _Integration_ and the _Integration.VSIX_ is supposed to be. I've put classes that need to access the SQ server in the _Integration_ project since that is the only place the server connection information is available, and I've put the code that uses Roslyn in the _Integration.VSIX_ project since that already references Roslyn and the other project doesn't.  I did that simply because that required fewest changes for …

Added skeleton classes for suppressions handling

---

src/Integration.Vsix.UnitTests/Helpers/FileUtilitiesTests.cs
src/Integration.Vsix/Helpers/FileUtilities.cs
src/Integration.Vsix/Suppression/LiveIssue.cs
src/Integration.Vsix/Suppression/LiveIssueFactory.cs
src/Integration.Vsix/Suppression/SuppressionManager.cs
src/Integration/Suppression/SonarQubeIssuesProvider.cs
src/SonarQube.Client/Models/SonarQubeIssue.cs

1/ The _LiveIssue_ file path should be the relative path from the MSBuild project file
2/ Comparison of module keys and file paths should be case-insensitive
3/ The function calculating the suppression was called _ShouldIssueBeSuppressed,_ but the suppression property is _ShouldIssueBeReported_. The function was returning the wrong logical result.

Fixes to suppression calculation and matching

---

src/Integration.UnitTests/Notifications/SonarQubeNotificationServiceTests.cs
src/Integration/Notifications/SonarQubeNotificationService.cs

Two tests are failing following the fix for #330
It's a test setup issue: previously, the tests didn't called _StartAsync_ as it didn't use to be necessary as the cancellation source was created when the class was constructed.

Fix notification tests

---

src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs

That's a funny one. The test fails on the build machine, but on mine it's fine.
Reported problem is:
[vs2015] Failed   Ctor_WhenInstallationDateIsDateTimeMin_SetsCurrentDateAndSave
Expected a date and time before <2017-10-11 12:07:42.470>, but found <2017-10-11 12:07:42.470>.
This is likely caused by DateTime accuracy. It is as accurate as OS timer, which on Windows defaults to ~15ms. So it is quite possible that calling DateTime.Now in short intervals gives the same answer.

fix failing test

---

src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
src/Integration.Vsix/Suppression/SuppressionManager.cs
src/Integration/Suppression/SonarQubeIssuesProvider.cs

Previously, the issue provider was tracking solution events to work out when it needed to fetch issues from the server. However, this wasn't necessary as the suppression manager was also tracking the solution events and creates a new issue provider whenever the bound solution changes.
I've removed the solution tracking code from the issue provider and deleted the unnecessary tests.

Removed solution tracking from the issues provider

---

src/Integration.Vsix/source.extension.vsixmanifest

Fixes #407 
Note: VS doesn't complain about a missing icon during the build, but if you install the VSIX locally and look in the Extension Manager you'll see that VS uses a generic icon if it can't find the one specified in the manifest file.

Fixed path to icon in VS2015

---

src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix.UnitTests/Suppression/SuppressionHandlerTests.cs
src/Integration.Vsix.UnitTests_2017/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix/Suppression/ILiveIssueFactory.cs
src/Integration.Vsix/Suppression/LiveIssue.cs
src/Integration.Vsix/Suppression/LiveIssueFactory.cs
src/Integration.Vsix/Suppression/SuppressionHandler.cs
src/Integration.Vsix/Suppression/SuppressionManager.cs

I made some minor changes to the product code to make it more testable - I moved the suppression matching code into a separate class and added an interface for the live issue factory.

Added unit tests for suppression matching

---

src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration/Connection/ConnectionWorkflow.cs

Cannot update bindings when SonarC# 6.7 is installed on SonarQube

---

src/Integration.Vsix.UnitTests/Settings/OtherOptionsDialogPageTests.cs
src/Integration.Vsix.UnitTests/SonarLintDaemonTests.cs
src/Integration.Vsix.UnitTests/SonarLintTracker/TaggerProviderTests.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs
src/Integration.Vsix/Settings/OtherOptionsDialogPage.cs
src/Integration.Vsix/SonarLintDaemon/CFamily.cs
src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonInstaller.xaml.cs
src/Integration.Vsix/SonarLintDaemon/SonarLintDaemonSplashscreen.xaml.cs
src/Integration.Vsix/SonarLintDaemonPackage.cs
src/Integration.Vsix/SonarLintTagger/IssueTagger.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration/Helpers/SonarLintOutput.cs

* removed uses of the static _ServiceProvider.GlobalProvider_ (it should always be possible to get hold of a specific service provider, and it makes testing simpler)
* changed variables typed as _SVSServiceProvider_ (it's a marker interface - should always use _IServiceProvider_)
* removed _GetMefService_ calls from MEF components (if a component is created using MEF then it should import any MEF components it needs; it should not query for them using the service provider)

Removed a couple of anti-patterns

---

src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
src/Integration.UnitTests/LocalServices/SolutionBindingInformationProviderTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.Vsix/BoundSolutionAnalyzer.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingWorkflow.cs
src/Integration/Binding/ProjectBindingOperation.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/LocalServices/SolutionBindingInformationProvider.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/BindingConfiguration.cs
src/Integration/NewConnectedMode/IConfigurationProvider.cs
src/Integration/NewConnectedMode/LegacyConfigurationProviderAdapter.cs
src/Integration/ProfileConflicts/ConflictsManager.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

... instead of having multiple separate methods. This is required for the upcoming changes to the command handling as the command methods that implement _ICommand_ can only accept a single parameter.
* added comments/TODOs to identify required legacy modes changes
* added _IBindingWorkflow_ interface so we can inject different binding behaviours later
Relates to #508

Modified IConfigurationProvider to return a config object

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/NewConnectedMode/BindingConfigurationTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationProviderTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationSerializerTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingSerializerTests.cs
src/Integration/Helpers/IO/FileWrapper.cs
src/Integration/Helpers/IO/IFile.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/ConfigFileUtilities.cs
src/Integration/NewConnectedMode/ConfigurationProvider.cs
src/Integration/NewConnectedMode/ConfigurationSerializer.cs
src/Integration/Persistence/SolutionBindingSerializer.cs

With this change, the _IConfigurationProvider_ will correctly detect whether it is in standalone, legacy or new connected mode.
There isn't any way to configure a project to be in "new" connected mode yet except by manually setting it up i.e. writing the expected file to disk in the correct location.
Related to #508

Added reader for new config mode

---

src/Integration.Vsix/source.extension.vsixmanifest

This reverts commit 7ecfc8fd29206a5d2a9f8d523de1aaa0d0d061e3.

Revert "Drop support for VS2015 earlier to Update 3 (#425)" - Postponed

---

Jenkinsfile

if the string returned from grep is `<MainVersion>1.2.3.4.5</MainVersion>`, first `cut` will return everything after `>`, e.g. `1.2.3.4.5</MainVersion>` and the second will return everything before `<`, e.g. `1.2.3.4.5`

Fixing the version number extraction

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
src/Integration/TeamExplorer/ConnectSectionViewModel.cs
src/Integration/TeamExplorer/ISectionController.cs
src/Integration/TeamExplorer/SectionController.cs
src/TestInfrastructure/Framework/ConfigurableSectionController.cs

Minor refactoring - changed commands that take an argument from _ICommand_ to use _ICommand[T]_.
_ICommand[T]_ inherits from _ICommand_ so it is still possible to use the overload defined in _ICommand_ to pass in a parameter of the wrong type. It's still an improvement as at least we get an overload in IntelliSense that shows the expected argument type.

Added type parameters for parameterised commands

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingWorkflowExecutor.cs

More straightforward refactoring of the existing legacy binding code - changing the binding workflow interfaces to use _BindCommandArgs_ rather than passing in individual parameters.

Minor refactor of legacy binding code

---

src/Integration.UnitTests/NewConnectedMode/ConfigurationProviderTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationSerializerTests.cs
src/Integration.UnitTests/NewConnectedMode/UnbindCommandTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingSerializerTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration.UnitTests/TeamExplorer/SectionControllerTests.cs
src/Integration/NewConnectedMode/ConfigurationProvider.cs
src/Integration/NewConnectedMode/ConfigurationSerializer.cs
src/Integration/NewConnectedMode/IConfigurationProvider.cs
src/Integration/NewConnectedMode/UnbindCommand.cs
src/Integration/Persistence/FileBindingSerializer.cs
src/Integration/Persistence/ISolutionBindingSerializer.cs
src/Integration/Persistence/SolutionBindingSerializer.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/State/StateManager.cs
src/Integration/TeamExplorer/ISectionController.cs
src/Integration/TeamExplorer/ProjectViewModel.cs
src/Integration/TeamExplorer/SectionController.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs
src/TestInfrastructure/Framework/ConfigurableSectionController.cs
src/TestInfrastructure/Framework/ConfigurableSolutionBindingSerializer.cs

* added new _delete_ methods to _IConfigurationProvider_ and _ISolutionBoundSerializer_
* added a new server-level UI _Unbind_ command (i.e. appears on the SQ server context menu, not on the project-level menu). The new command only works for connected mode. It's visible but disabled in other modes.
* added tests

Added unbind command for new connected mode

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/Persistence/ISolutionBindingSerializer.cs

Simplified the legacy serialization slightly by removing _ISolutionBindingSerializer_ as a local service.
It is now only used by the _ConfigurationProvider_.
Relates to #554

Minor refactoring to remove ISolutionBindingSerializer service

---

src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/LocalServices/ISolutionBindingInformationProvider.cs
src/Integration/LocalServices/SolutionBindingInformationProvider.cs
src/Integration/MefServices/VsSessionHost.cs

- only used by the ErrorListInfoBarController so it doesn't need to be a service
Miscellaneous refactoring. Not required for the change to binding serialization, but it's a small step that removes some unnecessary complexity.

Refactor: removed ISolutionBindingInformationProvider as a local service

---

src/Integration/Notifications/VisualStudioStatusBarHelper.cs

The _RemoveIcon_ method already contains defensive code so it won't fail if the icon is not parented.

Fixed #560 - setting WPF parent twice

---

src/Integration.UnitTests/ProfileConflicts/RuleSetConflictsControllerTests.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/ProfileConflicts/IConflictsManager.cs
src/Integration/ProfileConflicts/RuleSetConflictsController.cs

The ConflictsManager was only used by the RulesSetConflictsController.
All of the remaining local services are consumed by multiple other classes
the interfaces that just exist to help with testing are no longer exposed as "local services"

Refactor: removed IConflictsManager as a local service

---

src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/Integration/MefServices/ActiveSolutionTrackerEventArgs.cs
src/Integration/MefServices/IActiveSolutionTracker.cs
src/Integration/MefServices/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs

Added a boolean event arg to indicate there is an open solution or not.
This change will be required by the changes to save the binding data in the .suo file (we'll be storing the binding state in memory so we'll need to know when a solution is closed to reset it. Currently we're relying on deleting files on disk which gives us a stateful way to accurately detect which mode a solution is in).

Added isSolutionOpen argument to solution tracking event arg

---

src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/SonarLintDaemonPackage.cs
src/Integration/Helpers/IServiceProviderExtensions.cs

- Enabled background load
- Moved autoload to ShellInitialized event
- Removed need to use EnvDTE events
- Added a GetMefServiceAsync method
- Moved WPF to UI thread outside package init

Converted to AsyncPackage

---

src/Integration.UnitTests/Rules/QualityProfileProviderCachingDecoratorTests.cs

Excluded _SynchOnTimerElapsed_WhenNotConnected_NoErrors_ - passes locally, but not on CIX

[WIP] Excluded failing test

---

src/Integration.UnitTests/Rules/QualityProfileProviderCachingDecoratorTests.cs
src/Integration/Rules/QualityProfileProviderCachingDecorator.cs

The approach being used by the tests to wait for the initial fetch to complete was unreliable leading to intermittent test failures.

Fix ignored tests

---

src/Integration.UnitTests/NewConnectedMode/ConfigurationProviderTests.cs
src/Integration.UnitTests/NewConnectedMode/InMemoryConfigurationProviderTests.cs
src/Integration/NewConnectedMode/ConfigurationProvider.cs

Previously the in-memory config would not be updated in legacy mode so it would think it was still in standalone mode.
This lead to misleading messages in the SonarLint output window.

Changed in-memory config provider to record legacy mode

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
src/Integration.UnitTests/Binding/NuGetHelperTests.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/INuGetBindingOperation.cs
src/Integration/Binding/NuGetBindingOperation.cs
src/Integration/Binding/NuGetHelper.cs
src/TestInfrastructure/Framework/TestLogger.cs

I suggest starting with the _BindingWorkflow.cs_ file. I extracted code from that into a new _NuGetBindingOperation_ file, and then moved the tests into a new file too.
I'll call out all of the changed code.

Refactored binding workflow to extract NuGet code

---

src/Integration.UnitTests/Rules/SonarQubeQualityProfileProviderTests.cs
src/SonarQube.Client.Tests/Api/SonarQubeService_GetQualityProfileAsync.cs
src/SonarQube.Client/Api/SonarQubeService.cs
src/SonarQube.Client/Models/SonarQubeLanguage.cs

The service method is called in three places - workflow, golden bar and quality profile provider. All methods are generally testable, but apart from checking that the exception message is logged, there is nothing else to do...
Fix #662

Show more meaningful message when SonarC# is not installed on SonarQube

---

src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/SonarLintNotificationsPackage.cs
src/Integration/Notifications/SonarQubeNotificationService.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

Resolved #679 
I followed the pattern Mads used for the [SonarLintDaemonPackage](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/Integration.Vsix/SonarLintDaemonPackage.cs#L49) and the MSDN guidance [here](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-extension-performance).
I've manually tested with VS2015 and VS2017 and the notification package no longer appears in the _Visual Studio Performance_ entries in the activity log.
However, the telemetry package does, so that's next.

Changed notifications package to be asynchronous

---

src/Integration.UnitTests/LocalServices/ProjectSystemFilterTests.cs
src/Integration/LocalServices/ProjectSystemFilter.cs

There is a separate issue with regard to test projects not being correctly recognized.
I've created #785 to track that bug, and I'm investigating another test project issue.

Fixed #760: shared projects should be excluded from binding

---

src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs

Fix #778 
Fix #779 (with the change it just works)
I changed the way we compute the FilePath of SonarQubeIssue. It used to be substring of `component` or `subProject`, now we lookup the corresponding component in the response and take the file path from there.
```
{
"issues": [
{
"component": "component1",
...
}
],
"components": [
{
"key": "component1",
"qualifier": "FIL",
"path": "the actual path of the file where the issue is raised",
...
}
]
}
```

Suppressions in shared/linked files do not work in SQ7.4

---

src/SonarQube.Client.Tests/Api/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/Api/SonarQubeService_GetSuppressedIssuesAsync.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/Requests/IGetIssuesRequest.cs
src/SonarQube.Client/Api/Requests/V5_10/GetIssuesRequest.cs
src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequest.cs
src/SonarQube.Client/Api/Requests/V7_20/GetIssuesRequestWrapper.cs
src/SonarQube.Client/Api/SonarQubeService.cs

Fix #776
In general I am not sure if this change brings large benefit, because we will start doing three times more requests for each sync.
Two commits, a bit related:
- Moving the suppressed issues filtering from the service to the request - this is request-specific, so there is no need to filter already filtered data and potentially put pressure on the memory and CPU when copying large collections.
- Request suppressed issues by type.

[DO NOT SQUASH]  Request suppressed issues by type

---

src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration/Integration.csproj
src/TestInfrastructure/TestInfrastructure.csproj

* using $(DevEnvDir) works locally for VS2015. However, the VSIX built by the cix slave selects v12 TeamFoundation dlls, not v14 dlls.

Revert build property changes to VS2015 projects

---

src/Integration.Vsix/SonarLintNotificationsPackage.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/WPF/RelayCommandBase.cs

Fixed #835 
The refactoring of the Team Explorer plugins to a separate assembly changed the order of initialisation of components, which led to some of the UI-related components being created on background threads in some circumstances (i.e. timing related)

Fix #835: initialisation should be on the UI thread

---

src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs

* this try-catch just prevents #818 from crashing VS. The underlying issue is tracked by #850.
Relates to #818 
Relates to #850

Added daemon exception handling

---

src/Integration.Vsix/Manifests/VS2015/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest

...otherwise we can't publish a new marketplace offering for VS2019

Updating publisher in vsix to match publisher login name

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/TestInfrastructure/Framework/TestLogger.cs

* ruleset binding should not add project-level rulesets if the generated ruleset is already referenced

Fixed #859

---

src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Manifests/VS2015_v3Manifest/source.extension.vsixmanifest
src/SonarLint.VSSpecificAssemblies.props

... which allows the VS2015 vsix to be built using VS2017 or VS2019

Added v3 format version of the manifest for VS2015

---

src/Integration.Vsix.UnitTests/SonarLintDaemon/CFamilyTest.cs
src/Integration.Vsix/SonarLintDaemon/CFamily.cs

The previous implementation was always adding `/Yu` or `/Yu <name of header.h>` while in fact there is another property to check. Also there should be no space between the argument and the file name (checked in VS UI, and also this is what is expected by the [MsvcDriver](https://github.com/SonarSource/sonar-cpp/blob/f2f07b7c78f9b766942427117550f7a4cbb9c9c0/sonar-cfamily-plugin/src/main/java/com/sonar/cpp/analyzer/MsvcDriver.java#L171)).

Fix generation of /Yc /Yu compiler arguments

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
src/Integration.Vsix.UnitTests/CFamily/ProtocolTest.cs
src/Integration.Vsix/CFamily/Protocol.cs

New PR limited to the protocol. This time I have implemented the (hopefully) correct encoding for numbers, and a good enough implementation for strings (we could fix NUL and supplementary characters if needed, assuming it is properly handled on C++ side).

Implement protocol to talk to the CFamily analyzer (#928)

---

src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/InternalsVisibleTo.cs
src/Integration.Vsix/SonarLintDaemon/IAnalyzerController.cs
src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

Fixed up existing unit tests
Note: C++ analysis no longer requires additional language support to be enabled
I'm trying to break the refactorings into small pieces so they can still be reviewed. I'm not worrying at the moment about the code coverage; there's no point in additional unit tests to cover code that is still changing.

Introduced IAnalyzerController to break direct dependency on ISonarLintDaemon

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
src/Integration.Vsix.UnitTests/CFamily/RulesLoaderTest.cs
src/Integration.Vsix.UnitTests/CFamily/RulesMetadataCacheTest.cs
src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix.UnitTests/packages.config
src/Integration.Vsix/CFamily/CFamilyHelper.cs
src/Integration.Vsix/CFamily/RulesLoader.cs

... rather than using hard-coded values.
Fixes #969
Two commits: the first removes duplicate severity/type enums (one from the proto buf, the other defined in the SLVS).

Set default issue severity and type

---

src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/packages.config

* build tested in VS2017, VS2019 and VS2019 Prview (v16.3.0 Preview 1).
The build had started failing in v16.3.0 Preview 1 and adding this ref fixed it (although I'm not sure how it was working before in other vrsions of VS without this reference...)

Added ref to Microsoft.VSSDK.BuildTools NuGet package

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
src/Integration.Vsix.UnitTests/CFamily/RulesMetadataCacheTest.cs
src/Integration.Vsix/CFamily/CFamilyHelper.cs
src/Integration.Vsix/CFamily/CLangAnalyzer.cs
src/Integration.Vsix/CFamily/RulesLoader.cs
src/Integration.Vsix/CFamily/RulesMetadataCache.cs

Not all C-Family rules apply to all C-Family languages (C, C++, ObjC). SLVS detects whether the code being analysed is C or C++, but previously it passed the same rules configuration to `subprocess.exe` regardless.
This change means that the configuration passed to `subprocess.exe` is now language-specific.

Changed C-family rules config to be language-specific

---

src/Integration.Vsix/SonarLintDaemon/DaemonCommands.vsct

Register the command in a custom group on IDM_VS_CTXT_ERRORLIST
Adding our command to a group provided by another core VS package is not reliable - our command won't appear if the other VS package hasn't loaded at the point we register.

Fix disable rule command VSCT

---

build/ChangeVersion.proj
build/Version.props
src/Integration.Vsix/Integration.Vsix.csproj

Previously this was done separately in PowerShell in the build pipline.
However, the version properties are available during the build so we can create a VSIX with the expected name here - no need to rename later.

Modify build to include version in VSIX name

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyHelperTest.cs
src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
src/Integration.Vsix/CFamily/FileConfig.cs
src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs

Apply CPP-2305 to SonarLint: Properly predefine language version macros

---

SonarLint.VisualStudio.Integration.sln
src/Core.UnitTests/Core.UnitTests.csproj
src/Core/Core.csproj
src/Core/SonarLanguageKeys.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration.Vsix/CFamily/RulesMetadataCache.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration/Integration.csproj
src/Integration/Telemetry/TelemetryManager.cs

* moved SonarLanguageKeys constants class to the new assembly
* manually verified that the VSIX contains the new assembly
* manually verified that the new assembly has the expected assembly properties
First steps to separate out the code that depends on VS from the code that doesn't.
Created a new assembly to hold the non-VS code. The intention is to gradually move the non-VS code out of `SonarLint.VisualStudio.Integration.dll` and `SonarLint.VisualStudio.Integration.Vsixdll` as a step towards cleaning up and simplifying the architecture.

Added Core project and unit test project

---

src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
src/Integration.Vsix/Commands/ProjectExcludePropertyToggleCommand.cs
src/Integration.Vsix/Commands/ProjectSonarLintMenuCommand.cs
src/Integration.Vsix/Commands/ProjectTestPropertySetCommand.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/NuGetBindingOperation.cs
src/Integration/Binding/ProjectBindingOperation.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/Language.cs
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/LocalServices/ProjectSystemFilter.cs
src/Integration/LocalServices/ProjectSystemHelper.cs
src/Integration/LocalServices/SolutionBindingInformationProvider.cs
src/Integration/ProfileConflicts/ConflictsManager.cs
src/Integration/Service/DataModel/MinimumSupportedServerPlugin.cs

* removes the dependency on EnvDTE.Project so Language can be moved to the Core assembly

Removed redundant Language.ForProject method

---

src/Core/IRulesConfigurationProvider.cs
src/Integration.UnitTests/Binding/DotNetRulesConfigurationFileTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration/Binding/DotNetRuleConfigurationFile.cs
src/Integration/Binding/DotNetRuleConfigurationProvider.cs
src/Integration/Binding/IRuleConfigurationFileWithRuleSet.cs
src/Integration/Binding/ProjectBindingOperation.Writer.cs
src/Integration/Binding/SolutionBindingOperation.cs

No longer uses `IRuleSetSerializer` for solution-level rules config files i.e. no longer dependent on the `RuleSet` class.
Now calls `IRulesConfigurationFileWithRuleset.Save` instead.

Changed solution binding solution-level save to be generic

---

src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

Minor improvement to plugin detection output message - now includes the installed version number as well as the minimum required version.

Cleaned up IsSonarQubePluginSupported code and tests

---

src/Core.UnitTests/CFamily/CFamilyRulesConfigurationProviderTests.cs
src/Core.UnitTests/Helpers/LanguageHelperTests.cs
src/Core.UnitTests/LanguageTests.cs
src/Core/Language.cs
src/Integration.UnitTests/Binding/DotNetRulesConfigurationProviderTests.cs
src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs

Previously the extension was always ".ruleset". This is no longer appropriate for all languages (i.e. we don't use rulesets for connected mode C++ configuration).

Modified sln-level rule config naming to be type-specific

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/ProjectBindingOperation.WriterTests.cs
src/Integration.UnitTests/Binding/ProjectBindingOperationTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/ConfigFileInformation.cs
src/Integration/Binding/ISolutionBindingConfigFileStore.cs
src/Integration/Binding/ISolutionBindingOperation.cs
src/Integration/Binding/ProjectBindingOperation.Writer.cs
src/Integration/Binding/ProjectBindingOperation.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/TestInfrastructure/Framework/ConfigurableSolutionRuleStore.cs

* no product changes - renaming only.
* not all project types are configured using RuleSets to so the use of "RuleSet" in some method names is no longer appropriate. Changed to be more general e.g. "ConfigFile"

Changed "RuleSet" in name where no longer appropriate

---

src/Core.UnitTests/CFamily/DynamicCFamilyRulesConfigTests.cs
src/Core/CFamily/CFamilyShared.cs
src/Core/CFamily/DynamicCFamilyRulesConfig.cs
src/Integration.Vsix/SonarLintDaemon/DisableRuleCommand.cs
src/Integration/CFamily/CFamilyRulesConfigProvider.cs
src/TestInfrastructure/CFamily/DummyCFamilyRulesConfig.cs

* moved all of the CFamily-related classes that can be moved without additional refactoring out of Integration.csproj and into Core
* moved related tests
* the only remaining class CFamilyRulesConfigProvider still references internal interfaces and so would require more work to move

Moved CFamily classes out of Integration.csproj to Core where possible

---

src/Core.UnitTests/CFamily/CFamilyBindingConfigProviderTests.cs
src/Core/CFamily/CFamilyBindingConfigProvider.cs
src/Core/UserSettings.cs

* optimisation to avoid creating hundreds of empty dictionaries.
Note:
* there are already unit tests to check that serialization/deserialization handles null correctly.
* the sonarqube client library GetRulesAsync request is still creating hundreds of empty dictionaries

Set connected mode rule settings Parameters to null if no params

---

src/Integration.Vsix.UnitTests/SonarLintTagger/CancellableJobRunnerTests.cs
src/Integration.Vsix/SonarLintTagger/CancellableJobRunner.cs

The CancelAfterFirstOperation test fails intermittently because of timing issue.
It's not a product issues and it isn't worth the cost of refactoring the product code to make the test 100% reliable, so I've added a 200ms pause to see if that improves reliability sufficiently.
Relates to #1238

Added pause to CancellableJobRunner test to reduce flakiness

---

src/Integration.Vsix.UnitTests/Analysis/SingleFileMonitorTests.cs
src/Integration.Vsix/Analysis/SingleFileMonitor.cs

Fixed SingleFileMonitor dispose error
Fixes #1248
Increase timeout to reduce test flakiness
Relates to #1238

Fixed SingleFileMonitor dispose error

---

src/Integration.UnitTests/LocalServices/CredentialStoreTests.cs
src/Integration/LocalServices/CredentialStore.cs

Fixes #768
This change only handles storing the token so it can't be seen in clear in the Windows Credential Manager.
It doesn't address the token being visible in the SL connection dialogue - that's covered by #1229

Securely save token in the credentials store

---

src/Integration.Vsix.UnitTests/Delegates/SonarAnalyzerConnectedWorkflowTests.cs
src/Integration.Vsix.UnitTests/Delegates/SonarAnalyzerLegacyConnectedWorkflowTests.cs
src/Integration.Vsix.UnitTests/Suppression/RoslynLiveIssueFactoryTests.cs
src/Integration.Vsix.UnitTests/Suppression/RoslynSuppressionHandlerTests.cs
src/Integration.Vsix/Delegates/SonarAnalyzerConnectedWorkflow.cs
src/Integration.Vsix/Delegates/SonarAnalyzerLegacyConnectedWorkflow.cs
src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
src/Integration.Vsix/Suppression/IRoslynLiveIssueFactory.cs
src/Integration.Vsix/Suppression/IRoslynSuppressionHandler.cs
src/Integration.Vsix/Suppression/LiveIssue.cs
src/Integration.Vsix/Suppression/RoslynLiveIssueFactory.cs
src/Integration.Vsix/Suppression/RoslynSuppressionHandler.cs

There are two commits; I suggest looking at them separately.
* the first just contains file renames (prefixing Roslyn-specific classes with `Roslyn`), and minor test code cleanup. There are no product code changes.
* the second removes the Roslyn-specific `Diagnostic` property from `LiveIssue` as only the rule identifier is required. I'm aiming to reuse the `LiveIssue` class for other languages.

Renamed Roslyn-specific classes

---

src/Core/IIssuesFilter.cs
src/Core/ISonarQubeIssuesProvider.cs
src/Integration.UnitTests/Suppression/IssuesFilterTests.cs
src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
src/Integration.Vsix.UnitTests/Delegates/SonarAnalyzerManagerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix.UnitTests/Suppression/RoslynSuppressionHandlerTests.cs
src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/Integration.Vsix/Suppression/RoslynSuppressionHandler.cs
src/Integration/Suppression/IssuesFilter.cs
src/Integration/Suppression/SonarQubeIssuesProvider.cs
src/Integration/Suppression/SuppressedIssuesProvider.cs

This PR contains almost no actual code changes. Instead, I've moved some of the files to other folders/projects:
* `IIssuesFilter` and `ISonarQubeIssuesProvider` don't depend on VS so I've moved them to the `Core` project. I haven't moved the implementation classes.
* Moved the `IssuesFilter` class to the `Suppressions` folder since that seems a better location than under the tagger folder. I moved the corresponding test classes.
* added the `IFilterableIssue` interface. There are currently multiple data classes that describe issues: the Protobuf one used by the daemon; the Protobuf one use to talk to the CFamily process; and the `LiveIssue` used when suppressing Roslyn issues. I'm not trying to standardise these at the moment.

Move some interfaces to Core

---

src/Core/Suppressions/IFilterableIssue.cs
src/Core/Suppressions/IIssuesFilter.cs
src/Core/Suppressions/ISonarQubeIssuesProvider.cs
src/Core/Suppressions/ISuppressedIssueMatcher.cs
src/Core/Suppressions/ISuppressedIssuesMonitor.cs
src/Integration.UnitTests/Suppression/IssuesFilterTests.cs
src/Integration.UnitTests/Suppression/SuppressedIssueMatcherTests.cs
src/Integration.UnitTests/Suppression/SuppressedIssuesProviderTests.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix.UnitTests/Delegates/SonarAnalyzerManagerTests.cs
src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonIssueAdapterTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix.UnitTests/Suppression/RoslynSuppressionHandlerTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration.Vsix/Delegates/SonarAnalyzerManager.cs
src/Integration.Vsix/SonarLintDaemon/DaemonIssueAdapter.cs
src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/Integration.Vsix/SonarLintTagger/IssueToFilterableIssueConverter.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/Integration.Vsix/Suppression/LiveIssue.cs
src/Integration.Vsix/Suppression/RoslynSuppressionHandler.cs
src/Integration/Suppression/IssuesFilter.cs
src/Integration/Suppression/SonarQubeIssuesProvider.cs
src/Integration/Suppression/SuppressedIssueMatcher.cs
src/Integration/Suppression/SuppressedIssuesProvider.cs

* no code changes
* move the suppression interfaces that don't depend on VS to Core
* moved interfaces are now in the namespace "SonarLint.VisualStudio.Core.Suppression"
* fixed up namespace references

Moved suppression interfaces to Core

---

src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix.UnitTests/CFamily/CFamilyReproducerCommandTests.cs
src/Integration.Vsix.UnitTests/Framework/DummyMenuCommandService.cs
src/Integration.Vsix.UnitTests/Helpers/ActiveDocumentLocatorTests.cs
src/Integration.Vsix/Analysis/CFamilyReproducerCommand.cs
src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
src/Integration.Vsix/CFamily/CFamilyStrings.Designer.cs
src/Integration.Vsix/CFamily/CFamilyStrings.resx
src/Integration.Vsix/Helpers/ActiveDocumentLocator.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/SonarLintDaemon/DaemonCommands.vsct
src/Integration.Vsix/SonarLintDaemonPackage.cs

Relates to #1295.
Adds the menu command. The command is only enabled if document that can be analysed by the CFamily analyser is active.
TODO: trigger the reproducer.

Add CFamily reproducer command

---

src/Core/CFamily/CFamilyAnalyzerOptions.cs
src/Core/IAnalzyerOptions.cs
src/Integration.Vsix/CFamily/CFamilyAnalyzerOptions.cs

Move `IAnalyzerOptions` to Core so they are accessible to `IAnalysisRequester`
Relates to #1295

Moved analyzer options to Core

---

build/Signing.targets

The symantec server is been replaced following the takeover by digicert.
https://knowledge.digicert.com/alerts/migration-of-legacy-verisign-and-symantec-time-stamping-services.html

Changed the timestamp server used

---

src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
src/Core.UnitTests/CSharpVB/SerializerTests.cs
src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Core/CSharpVB/NuGetPackageInfoGenerator.cs
src/Core/CSharpVB/RoslynPluginRuleKeyExtensions.cs
src/Core/CSharpVB/RuleAction.cs
src/Core/CSharpVB/RuleSet.cs
src/Core/CSharpVB/RuleSetGenerator.cs
src/Core/CSharpVB/Serializer.cs
src/Core/CSharpVB/SonarLintConfigGenerator.cs
src/Core/CSharpVB/SonarLintConfiguration.cs

Relates to #1129 
Moved previously reviewed classes from the web client branch.
* no code changes
* changed copyright notices
* added classes to `Core` in the namespace `SonarLint.VisualStudio.Core.CSharpVB`.
Core already has a namespace called `SonarLint.VisualStudio.Core.CFamily`, so I went with `SonarLint.VisualStudio.Core.CSharpVB` for the sub-folder containing the  C#/VB-specific classes.
I'm trying to find an alternative to using `Roslyn` for code that doesn't actually use/reference any of the Roslyn assemblies. `DotNet` is an alternative, but it isn't strictly accurate either so I though I'd try `CSharpVB` to see how it feels.

Added RoslynProfileExporter replacement classes to Core

---

src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Core/CSharpVB/SonarLintConfigGenerator.cs

Sort the contents of the SonarLint.xml file.
Also, only include ruleset that have parameters. Most rules don't have parameters, so the file contains hundreds of entries like the following, which isn't useful:
```
<Rule>
<Key>S101</Key>
</Rule>
<Rule>
<Key>S102</Key>
</Rule>
...
```

Sort rules and params in SonarLintConfiguration

---

src/Core.UnitTests/CSharpVB/NuGetPackageInfoTests.cs
src/Core/CSharpVB/NuGetPackageInfo.cs
src/Core/CSharpVB/NuGetPackageInfoGenerator.cs
src/Integration.UnitTests/Binding/DotNetBindingConfigProviderTests.cs
src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
src/Integration.UnitTests/NewConnectedMode/NoOpNuGetBindingOperationTests.cs
src/Integration/Binding/DotNetBindingConfigProvider.cs
src/Integration/Binding/NuGetBindingOperation.cs
src/Integration/NewConnectedMode/NoOpNuGetBindingOperation.cs

A small refactoring to remove one of the dependencies on the data class returned by the call to the soon-to-be-obsolete `GetRoslynExportProfileAsync` method.
I've changed the data types used in the interface from `RoslynProfileExportResponse` to `IEnumerable<NuGetPackageInfo>` and fixed up the tests.
There's a one-line temporary hack in the binding code to translate from the old to the new data type.

Removed INuGetBindingOperation dependency on RoslynExportProfile

---

src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
src/Core/CSharpVB/NuGetPackageInfoGenerator.cs
src/Core/CSharpVB/RoslynPluginRuleKeyExtensions.cs
src/Core/CSharpVB/RuleSetGenerator.cs

There are two small commits. It might be easier to look at them separate in the GitHub web UI.
The first just changes an existing test to be data-driven.
The second fixes the bug in the NuGet generator.

Updated NuGet info generator to exclude taint-analysis packages

---

src/Core.UnitTests/Binding/SolutionBindingFilePathGeneratorTests.cs
src/Core/Binding/ISolutionBindingFilePathGenerator.cs
src/Core/Binding/SolutionBindingFilePathGenerator.cs
src/Integration.UnitTests/Binding/ProjectBindingOperationTests.cs
src/Integration.UnitTests/LocalServices/SolutionRuleSetsInformationProviderTests.cs
src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs

ISolutionBindingFilePathGenerator contains the logic from SolutionRuleSetsInformationProvider.GenerateSolutionRuleSetPath. Extracted as-is and added a few tests.
Please note the base: let me know if I should merge this to my base branch instead.

Extract solution file path generation to another class

---

src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
src/Core.UnitTests/EnvironmentSettingsTests.cs
src/Core/CSharpVB/RuleSetGenerator.cs
src/Core/EnvironmentSettings.cs
src/Core/IEnvironmentSettings.cs

Adding the interface improves testability and makes the 'TreatBlockerSeverityAsError` check re-usable (it will also need to be called by the CFamily code).

Added IEnvironmentSettings to abstract access to environment variables

---

src/Core.UnitTests/Binding/CompositeBindingConfigProviderTests.cs
src/Core.UnitTests/CFamily/CFamilyBindingConfigProviderTests.cs
src/Core/Binding/CompositeBindingConfigProvider.cs
src/Core/Binding/IBindingConfigProvider.cs
src/Core/CFamily/CFamilyBindingConfigProvider.cs
src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationProviderTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/CSharpVBBindingConfigProvider.cs
src/Integration/Binding/ISolutionBindingOperation.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/NewConnectedMode/ConfigurationProvider.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

I found a nasty bug during QA: I used the existing binding information in order to fetch the configurations, which caused a bug when there was no existing binding information (first time bind).
Hence I had to move the code that calculates the new binding configuration, and use that new configuration.

Fix bug of first time binding

---

src/EmbeddedSonarAnalyzer.props

Fixes #1400
I checked that my manual repro of the bug that was blocking the analyzer update no longer repros.
The DotNet team now have an automated test to check the analyzers run on the minimum supported .NET version to catch similar problems in the future.

Embed SonarC# 8.7 and SonarVB 8.7

---

src/Integration.UnitTests/Binding/CSharpVBBindingOperation.WriterTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
src/Integration/Binding/CSharpVBBindingOperation.Writer.cs
src/Integration/Binding/CSharpVBBindingOperation.cs

Fixes #817
I think we can only point to the Solution's ruleset when the user has no ruleset at all.
If there is a ruleset, we might not be able to amend it -- for example, if it's a pre-defined MS ruleset (under C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Team Tools\Static Analysis Tools\Rule Sets).
I think that if there is any ruleset in the project, we should continue with the previous behavior: create a new ruleset that references our ruleset + the project's. It also solves the problem if the ruleset is some global ruleset that is shared across multiple solutions.

Don't generate project-level ruleset when project has no rulesets

---

src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
src/Integration.UnitTests/Binding/CSharpVBProjectBinderTests.cs
src/Integration.UnitTests/Binding/RuleSetReferenceCheckerTests.cs
src/Integration/Binding/CSharpVBBindingOperation.cs
src/Integration/Binding/CSharpVBProjectBinder.cs
src/Integration/Binding/IRuleSetReferenceChecker.cs
src/Integration/Binding/RuleSetReferenceChecker.cs

We only need the file path, not an actual ruleset object.

Removed VS RuleSet param from IRuleSetReferenceChecker interface

---

src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
src/Integration/Binding/CSharpVBBindingOperation.cs

Bug fix: don't set non-conditional ruleset when existing ruleset already references the generated ruleset

---

src/Integration.Vsix.UnitTests/Analysis/AnalyzerControllerTests.cs
src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs
src/Integration.Vsix.UnitTests/SonarLintDaemon/DaemonAnalyzerTests.cs
src/Integration.Vsix.UnitTests/SonarLintDaemon/Helpers/DummySonarLintDaemon.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/Analysis/AnalyzerController.cs
src/Integration.Vsix/Analysis/IAnalyzerController.cs
src/Integration.Vsix/CFamily/CLangAnalyzer.cs
src/Integration.Vsix/SonarLintDaemon/DaemonAnalyzer.cs
src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

The `ProjectItem` parameter is only required by the CLangAnalyzer, and shouldn't be on the analyzer interface. I've refactored the `CLangAnalyzer` to fetch the `ProjectItem` instead.
The changes to all of the other files are just to remove the redundant `ProjectItem` parameter.

Removed VS types from IAnalyzer interface

---

src/Integration.Vsix.UnitTests/SonarLintTagger/IssueTaggerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/IIssueTracker.cs
src/Integration.Vsix/SonarLintTagger/IssueTagger.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

* moved the responsibility for managing the taggers to the tracker
* removed dependency between the tagger and the tracker (dependency still exists the other way)
* added some tests for the tagger

Simplified IIssueTracker and IssueTagger

---

src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/IIssueTracker.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

* moved responsibility for registering with the error list from the TaggerProvider to the TextBufferIssueTracker
* removed unnecessary members from `IIssueTracker`

Refactoring to TextBufferIssueTracker

---

src/Integration.Vsix.UnitTests/SonarLintTagger/AccumulatingIssueConsumerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/AccumulatingIssueConsumer.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

Relates to #1471
Fixes #1487
* separate issue consumer into separate class
* translate spans from the analysis snapshot to the current snapshot
* minor refactoring of buffer handling code
* added unit test for buffer handling code
TODO: change the CLangAnalyzer to actually stream the issues...

Refactor issue consumer to separate class

---

src/Integration.Vsix/Integration.Vsix.csproj

I'm in two minds about whether auto-updating the baseline during development defeats the point of having the AsmRef checking. On balance I think it's ok since we should notice that the baseline has been updated and decide whether or not to commit the changes.

Automatically update the asmref baseline when building in the IDE

---

src/Integration.Vsix.UnitTests/SonarLintTagger/IssueTaggerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/IssueTagger.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

The TextBufferIssueTracker is now only responsible for triggering analysis (when the doc is opened, saved, or analysis requested because the user settings have changed).
TODO: more cleanup

Removed tagging functionality from TextBufferIssueTracker

---

src/Core/WPF/AggregatorValueConverter.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/IssueToIssueMarkerConverterTests.cs
src/Integration.Vsix/SonarLintTagger/IssueToIssueMarkerConverter.cs
src/IssueViz.UnitTests/Editor/IssueSpanCalculatorTests.cs
src/IssueViz.UnitTests/Editor/LocationNavigatorTests.cs
src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
src/IssueViz.UnitTests/IssueVisualizationControl/SpanToNavigabilityConverterTests.cs
src/IssueViz.UnitTests/Models/AnalysisIssueLocationVisualizationExtensionsTests.cs
src/IssueViz.UnitTests/Models/AnalysisIssueLocationVisualizationTests.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz.UnitTests/Selection/IssueFlowStepNavigatorTests.cs
src/IssueViz/Editor/IIssueSpanCalculator.cs
src/IssueViz/Editor/LocationNavigator.cs
src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
src/IssueViz/IssueVisualizationControl/SpanToNavigabilityConverter.cs
src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs
src/IssueViz/Models/AnalysisIssueLocationVisualization.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs
src/IssueViz/Selection/IssueFlowStepNavigator.cs

The main changes are in 
1. `IAnalysisIssueLocationVisualization` - removing IsNavigable property and adding extension methods that rely on Span.
2. `LocationNavigator` - now uses the existing `IAnalysisIssueLocationVisualization.Span`, and is responsible to update it if it's null.
The rest of the files were changed as a result.

Change IsNavigable to rely on SnapshotSpan

---

src/IssueViz.UnitTests/Editor/TaggableBufferIndicatorTests.cs
src/IssueViz/Editor/TaggableBufferIndicator.cs

When opening a quick info window, an exception is thrown from the ErrorTaggerProvider since the buffer doesn't have an associated text document.

Fix tagger exception when buffer has no document

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyHelper_CaptureTests.cs
src/Integration.Vsix.UnitTests/CFamily/MsvcDriverTest.cs
src/Integration.Vsix/CFamily/CFamilyHelper_Capture.cs
src/Integration.Vsix/CFamily/PortedFromJava/MsvcDriver.cs

MSVC Driver: add support for "/arch:AVX512" compiler option

---

src/Integration.Vsix/Integration.Vsix.csproj

The baseline files should now only be updated in local builds if there has been a change.
Fixes #1789

[Infra] Updated AsmRef package and tweaked targets file

---

src/IssueViz.Security.UnitTests/HotspotsList/HotspotTableEntryTests.cs
src/IssueViz.Security/HotspotsList/TableDataSource/HotspotTableEntry.cs

Cosmetics: I've noticed in the docs that there is a base class that I can inherit from, instead of the interface, so all the empty methods can be removed.

Use WpfTableEntryBase instead of IWpfTableEntry

---

src/IssueViz.Security.UnitTests/Models/HotspotRuleTests.cs
src/IssueViz.Security.UnitTests/Models/HotspotTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE/Api/HotspotToIssueVisualizationConverterTests.cs
src/IssueViz.Security/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Models/IHotspot.cs
src/IssueViz.Security/Models/IHotspotRule.cs
src/IssueViz.Security/OpenInIDE/Api/IHotspotToIssueVisualizationConverter.cs

Added data fields for rule help
The web API returns additional information such as the "help" fields that we currently don't handle but will need later.
This commit changes the SLVS data structure to more closely match the data structure returned by the API i.e. a separate interface to contain the rule metadata.

Separated rule metadata from IHotspot

---

src/Core/Binding/IActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/IssueViz.Security/IssueVizSecurityPackage.cs
src/IssueViz.Security/Taint/TaintResources.Designer.cs
src/IssueViz.Security/Taint/TaintResources.resx
src/IssueViz.Security/Taint/TaintSyncPackage.cs

* avoids reentrant calls on UI thread causing VS to lock up
Relates to #2059

Initialize taint sync monitor in a separate package

---

src/Core/IToolWindowService.cs
src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs

Relates to #2059
Modifies the taint synchronizer to ensure the taint tool window has been created so the tool window caption can be set correctly.

Ensure taint tool window is initialized

---

src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
src/IssueViz.Security/Taint/TaintResources.Designer.cs
src/IssueViz.Security/Taint/TaintResources.resx

Fixes #2179
Example of new output:

Taint issues: output user-friendly message for unsupported SQ version

---

.gitignore
build/DownloadCFamilyPlugin/Common.cs
build/DownloadCFamilyPlugin/DownloadAndExtract.cs
build/DownloadCFamilyPlugin/DownloadCFamilyPlugin.csproj

No product code changes, just build-time internal tooling.
Part of #2246

Tooling: extract common code from download plugin task

---

build/DownloadCFamilyPlugin/DownloadAndExtractSonarJS.cs
build/DownloadCFamilyPlugin/DownloadCFamilyPlugin.csproj
build/DownloadCFamilyPlugin/DownloadCFamilyPlugin.sln

Part of #2246
First part: add a new target and tasks to download the required files from the SonarJS plugin.

Internal tooling: add targets to download and extract SonarJS plugin

---

src/EmbeddedSonarAnalyzer.props
src/EmbeddedVsix.UnitTests/TypeScriptRuleDefinitions_SanityChecks.cs
src/EmbeddedVsix/EmbeddedVsix.csproj

* unreleased, but the metadata file now contains JS rule definitions
Fixes #2282

Updated SonarJS jar to internal version 7.4.0.15161

---

build/ChangeVersion.proj
src/EmbeddedVsix/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2015/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2015_v3Manifest/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest

* the embedded VSIX version number is set to be the same as the main VSIX
* the main VSIX manifests are changed to reference an specific embeded VSIX version
Manually tested: auto-upgrade correctly updates both embedded and main VSIXes, and removes the old versions.

Update change version script to handle embedded VSIX

---

src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs
src/TypeScript/EslintBridgeClient/Resources.Designer.cs
src/TypeScript/EslintBridgeClient/Resources.resx

Changing LogDebug to Writeline, so we could see the termination logs in non-debug mode.

Change EslintBridgeProcess log verbosity

---

src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
src/TypeScript.UnitTests/Rules/RulesProviderTests.cs
src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
src/TypeScript/Rules/RulesProviders.cs

* it was only used by the issue converter, which had already fetched the appropriate rule definition

Drop redundant GetSonarRuleKey method

---

src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

Fixes #2193
Seems that there is no concept of Current Project in the Error List for CMake projects.
For example, compiler errors are showed for all projects in the "solution" even when Current Project filter is selected:
Hence, if we just return Guid.Empty for CMake projects, we will get the default VS's behavior.

Set projectGuid to empty if there is no project file

---

src/TypeScript.UnitTests/TsConfig/TsConfigProviderTests.cs

Minor nuisance fix: there is a debug.assert in the code that these tests are failing on.
https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/TypeScript/TsConfig/TsConfigProvider.cs#L94

Fix debug.assert failures

---

src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeProcessTests.cs
src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs

Don't show verbose log output when node was not located

---

src/Integration.Vsix.UnitTests/CFamily/CLangAnalyzerTests.cs

Mea culpa - I didn't run all of the tests in debug after fixing the assertion to use `PathHelper`. Two of the tests failed in debug due to invalid paths, but of course this wasn't picked up by the CI.

Fix debug test failures

---

src/Core/CFamily/IRequest.cs
src/Integration.Vsix/CFamily/CMake/CompilationDatabaseRequest.cs
src/Integration.Vsix/CFamily/ProcessRunner.cs
src/Integration.Vsix/CFamily/ProcessRunnerArguments.cs
src/Integration.Vsix/CFamily/Request.cs

There's no need for the settings to be writable, and the new VS environment variable provider returns 'IReadOnlyDictionary<>`, so I've switched to make everything read-only.

Changed Request.EnvironmentVariables to IReadOnlyDictionary<>

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Release notes:
* `6.22` - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16806
* `6.23` - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16855
* `6.24` - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16866
* `6.25` - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16938
* `6.26` - https://jira.sonarsource.com/secure/ReleaseNote.jspa?projectId=10090&version=16932

Update embedded CFamily analyzer to v6.26.0.36731

---

src/EmbeddedVsix/EmbeddedVsix.csproj
src/EmbeddedVsix/Manifests/PreVS2022/source.extension.vsixmanifest
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest

* use v16 for VS2017 and VS2019
* use v17 for VS2022
Enables building and debugging both VS2019 and VS2022.
NB Do not have SLVS open in both IDEs simultaneously - the package refs will get messed up.
To be on the safe side:
* close all IDEs
* open the appropriate dev command prompt (VS2019 or VS2022)
* msbuild /t:restore,rebuild
* then open and build/debug in the corresponding IDE

Conditionally select SDK build tools

---

src/Integration.Vsix/Manifests/VS2017/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

No idea why it happened or why simply removing and readding the `>` fixed it...
Before:
After:

Remove ?? from VSIX description

---

src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceTests.cs
src/IssueViz/Editor/QuickActions/IssueLocationActionsSource.cs

2694 Added existence of secondary location control for selected primary items

Fix2694: don't show "hide issue visualisation" menu for issues without secondary locations

---

build/DownloadSonarPlugin/Common.cs
build/DownloadSonarPlugin/DownloadAndExtractCFamily.cs
build/DownloadSonarPlugin/DownloadAndExtractSonarJS.cs

This is a change to a build-time helper project - no changes to product code.
Parts of the CFamily and JS/TS plugins are embedded in the VSIX we ship. At build time, we download and unpack the required plugins if they are not already on the machine.
Previously, the plugins were always cached under %LOCALAPPDATA%. However, a recent security change by the IT Ops teams meant they had to recreate my user account on my local dev machine. One effect of this is that the name of my local app data folder is now much longer, which is causing SLVS builds to fail on my machine because the paths created when unzipping the plugins are now too long.
The default behaviour hasn't changed. However, there is now a local environment variable that can be set to change the root download folder if necessary.

Fix build-time plugin download error caused by long paths

---

src/Integration.UnitTests/Exclusions/ExclusionSettingsFileStorageTests.cs
src/Integration/Exclusions/ExclusionSettingsFileStorage.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

Part of [#3057](https://github.com/SonarSource/sonarlint-visualstudio/issues/3057)
Example json file (`sonar.settings.json`):
```
{
"Exclusions" : [],
"GlobalExclusions" : [],
"Inclusions" : ["**/*"]
}
```
User messages:

Read exclusions from disk

---

src/Integration.UnitTests/LocalServices/BindingCheckerTests.cs
src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
src/Integration.UnitTests/LocalServices/UnboundSolutionCheckerTests.cs
src/Integration/LocalServices/ErrorListInfoBarController.cs
src/Integration/LocalServices/IBindingChecker.cs
src/Integration/LocalServices/IUnboundSolutionChecker.cs
src/Integration/MefServices/VsSessionHost.cs

Fixes [#3083](https://github.com/SonarSource/sonarlint-visualstudio/issues/3083)
Perhaps worth reviewing in separate commits: first commit changes the call to async, and second commit pulls exclusions from the server and compares.

Show goldbar if server exclusions are different

---

src/Core.UnitTests/RuleSettingsProviderTests.cs
src/Core/CoreStrings.Designer.cs
src/Core/CoreStrings.resx
src/Core/IRuleSettingsProvider.cs
src/Core/RulesSettingsSerializer.cs
src/EmbeddedVsix.UnitTests/TypeScriptRuleDefinitions_SanityChecks.cs
src/Integration.Vsix.UnitTests/Analysis/RuleSettingsProviderFactoryTests.cs
src/Integration.Vsix/Analysis/RuleSettingsProviderFactory.cs
src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Rules/ActiveRulesCalculatorTests.cs
src/TypeScript.UnitTests/Rules/RulesProviderFactoryTests.cs
src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
src/TypeScript/Analyzer/TypeScriptAnalyzer.cs
src/TypeScript/Rules/ActiveRulesCalculator.cs
src/TypeScript/Rules/RulesProviderFactory.cs

Fixes [#3109](https://github.com/SonarSource/sonarlint-visualstudio/issues/3109)
Might help to review the commits separately. First commit is the infrastructure, copy-pasted from CFamily code. Second PR is using it.
Once this PR is merged, I will apply the changes to CFamily code to re-use the code.

Apply JS/TS connected mode settings

---

src/Infrastructure.VS/LanguageDetection/SonarLanguageRecognizer.cs

Rita suggested this change after the merge of the branch. With using of GetContentTypeForExtension the result will not be different for each language anymore so no need to run the method multiple times.

moved result of GetContentTypeForExtension to a variable

---

src/Core/ETW/CodeMarkers.cs
src/Core/IThreadHandling.cs
src/Infrastructure.VS.UnitTests/ThreadHandlingTests.cs
src/Infrastructure.VS/ThreadHandling.cs
src/TestInfrastructure/NoOpThreadHandler.cs

* accepting a Func<T> doesn't fit nicely with using the method from MefSonarQubeService, which already has a task
* changing the argument to  Task<T> falls foul of VSTHRD003
https://github.com/Microsoft/vs-threading/blob/main/doc/analyzers/VSTHRD003.md

Changing method signature of RunOnBackgroundThread

---

src/TypeScript.UnitTests/Notifications/UnsupportedNodeVersionNotificationServiceTests.cs
src/TypeScript/Notifications/IUnsupportedNodeVersionNotificationService.cs

A placeholder for the new page exist, but without any content: https://github.com/SonarSource/sonarlint-visualstudio/wiki/Supported-NodeJS-versions

Changed NodeJS notification help to a specific wiki page

---

pipeline/azure-pipelines.yml

Update NuGet version used in the pipeline
Related to [CVE-2022-41032](https://github.com/NuGet/NuGet.Client/security/advisories/GHSA-g3q9-xf95-8hp5)

Update NuGet version used in pipeline

---

src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript/Analyzer/JavaScriptAnalyzer.cs

This PR is almost the same as https://github.com/SonarSource/sonarlint-visualstudio/pull/3313
seperated them as I already put the CLang one in a different pr aswell so this made most sense to me

Remove TaskScheduler.Default from JavaScriptAnalyzer and update tests

---

src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
src/IssueViz.Security/OpenInIDE/Api/OpenInIDEFailureInfoBar.cs

Fixes part of https://github.com/SonarSource/sonarlint-visualstudio/issues/3145

Remove direct calls to RunOnUIThread.cs in OpenInIDEFailureInfoBar.cs

---

src/Directory.Build.props
src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/vs-threading.MainThreadAssertingMethods.txt

Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3169
The only method that is available to be recognized is ThrowIfNotOnUIThread as our method signature for RunOnUIThread differs from the original implementation.

Working configuration for VSTHRD Analyzer to recognize ThrowIfNotOnUIThread in the IThreadHandling class.

---

src/Integration.UnitTests/Suppression/SonarQubeIssuesProviderTests.cs
src/Integration/Suppression/SonarQubeIssuesProvider.cs
src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs

Fix up calling code (by passing `null` for the `branch` parameter)
Fixes #3396

Update web client to get branch-aware APIs

---

Directory.Build.props
THIRD-PARTY-NOTICES
src/CFamily.UnitTests/packages.lock.json
src/ConnectedMode.UnitTests/ConnectedMode.UnitTests.csproj
src/ConnectedMode.UnitTests/packages.lock.json
src/ConnectedMode/ConnectedMode.csproj
src/Integration.Vsix.UnitTests/packages.lock.json
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/packages.lock.json

TODO
- the VSIX contains the native binaries for Linux and OSX, which we don't need.
- the VS2019 and VS2022 probably only need one copy of the Windows native binaries i.e. either x86 or x64
Part of #3431

Add LibGit binaries to VSIX

---

src/ConnectedMode.UnitTests/ServerSentEvents/ServerSentEventSessionManagerTests.cs
src/ConnectedMode/ServerSentEvents/ServerSentEventSessionManager.cs

@georgii-borovinskikh-sonarsource I went over the design with @duncanp-sonar and we came up with a solution that we think is simpler and addresses a couple of problems:
* It allows the whole "session" to be disposed, whenever the binding changes, without the risk of concurrency problems
* It makes explicit usage of the cancellation token which makes it simpler to understand how the session is disposed and canceled.
Please take a look and LMK what you think.

Change EventPump into a transient instance

---

src/Education/Commands/RuleHelpUserControl.xaml

part of https://github.com/SonarSource/sonarlint-visualstudio/issues/3615
Before:
After:

Fix alignment of icons

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingOperationTests.cs
src/Integration.UnitTests/Binding/NuGetBindingOperationTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/LocalServices/ErrorListInfoBarController.QualityProfileBackgroundProcessorTests.cs
src/Integration.UnitTests/LocalServices/ErrorListInfoBarControllerTests.cs
src/Integration.UnitTests/ProfileConflicts/ConflictsManagerTests.cs
src/Integration.UnitTests/ProjectToLanguageMapperTests.cs
src/Integration/ProjectToLanguageMapper.cs

fixes part 4 of https://github.com/SonarSource/sonarlint-visualstudio/issues/3673
When connecting to SonarCloud / SonarQube >= v9.9 secrets settings get downloaded.
When the slconfig secrets time stamp is out of date a gold bar asks to update it.
When updating it the slconfig gets correctly updated.

Add check for secrets in ProjectToLanguageMapper

---

src/ConnectedMode.UnitTests/BranchMatcherTests.cs
src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
src/ConnectedMode/BranchMatcher.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/ServerBranchProvider.cs
src/Core/IServerBranchProvider.cs

Fixes [#3697](https://github.com/SonarSource/sonarlint-visualstudio/issues/3697)
I've reverted my previous commit that handled headless branches. This new commit should handle both cases (no git repo + headless).

Return default Main branch when there is no git repo or no git head

---

src/ConnectedMode.UnitTests/Suppressions/SuppressedIssueMatcherTests.cs
src/Core/Suppressions/IFilterableIssue.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs

- no longer used. It was used by the old Roslyn suppressions code, but that was removed March 2022.
Fixes #3888

Remove ProjectGuid field from IFilterableIssue

---

src/Education.UnitTests/SimpleRuleHelpXamlBuilderTests.cs
src/Education.UnitTests/XamlGeneratorHelperTests.cs
src/Education/Education.cs
src/Education/XamlGenerator/SimpleRuleHelpXamlBuilder.cs
src/Education/XamlGenerator/XamlGeneratorHelper.cs

It is going to be reused by Simple and Rich layout generators.
NOTE: no new code, just moved the bits to a separate class

Extract xaml header and closer generation to a separate class

---

src/Rules.UnitTests/RuleInfoTests.cs
src/Rules.UnitTests/ServerRuleMetadataProviderTests.cs
src/Rules/IRuleInfo.cs
src/Rules/ServerRuleMetadataProvider.cs

Handle null collections when processing server rule info
Last part of the fix for #3973

Handle null collections when parsing server rule info

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingProcess.cs

- most of the implement was removed in a previous commit. This removes the entry points that called the now-removed code.
Part of #4120

Remove NuGet steps from binding process

---

src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/LocalServices/ProjectSystemHelperTests.cs
src/Integration/LocalServices/IProjectSystemHelper.cs
src/Integration/LocalServices/ProjectSystemHelper.cs
src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs

- no longer called. With the new binding model, we don't need to check which projects contain supported languages since 1) we won't make changes to individual project files, and 2) we download QPs for all supported languages if a project does not have any supported languages.
Part of #4120

(2) Remove IProjectSystemHelper.GetFilteredSolutionProjects

---

src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx

- changed to a section on the migration page rather than a separate page.

Change Tfvc migration help URL

---

src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsStoreTests.cs
src/IssueViz.Security/IssueViz.Security.csproj
src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsControl.xaml
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsControl.xaml.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsStore.cs

Part of #4559
- reverts changes in https://github.com/SonarSource/sonarlint-visualstudio/commit/997d521b9a3688c25cae2976b3f8ada40408dc86
- renamed duplicated classes with `OpenInIDE` e.g. `OpenInIDEHotspotsToolWindow`

Reinstate OpenInIDE hotspot store and supporting types

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotTests.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/LocalHotspot.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

* LocalHotspot now has Priority
* LocalHotspotsStore uses PriorityProvider to create LocalHotspot
* HotspotViewModel uses Priority from LocalHotspot
* HotspotsControl displays the new Priority of HotspotViewModel
Implements #4532

Add data binding for priority column

---

src/ConnectedMode.UnitTests/Binding/BindingProcessImplTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileDownloaderTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileUpdaterTests.cs
src/ConnectedMode/Binding/BindingProcessImpl.cs
src/ConnectedMode/Binding/BindingStrings.Designer.cs
src/ConnectedMode/Binding/BindingStrings.resx
src/ConnectedMode/QualityProfiles/QualityProfileDownloader.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs

Implements #4705
* QualityProfileDownloader returns false when no QPs updated, true if at least one
* QualityProfileDownloader throws InvalidOperationException if binding config not found
* QualityProfileUpdater only raises the event if QualityProfileDownloader returns true
* QualityProfileUpdater handles InvalidOperationException from QualityProfileDownloader
* BindingProcessImpl handles InvalidOperationException from QualityProfileDownloader

Make QualityProfileDownloader return if there were changes

---

src/Education.UnitTests/XamlGenerator/CustomTextMarkupParserTests.cs
src/Education.UnitTests/XamlGenerator/RichRuleHelpXamlBuilderTests.cs
src/Education.UnitTests/XamlGenerator/RuleHelpXamlBuilderTests.cs
src/Education.UnitTests/XamlGenerator/RuleHelpXamlTranslatorTests.cs
src/Education.UnitTests/XamlGenerator/SimpleRuleHelpXamlBuilderTests.cs
src/Education.UnitTests/XamlGenerator/StaticXamlStorageTests.cs
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education.UnitTests/XamlGenerator/XamlWriterFactoryTests.cs

Fixed up namespaces
No product or test code changes

[CAYC] Move XAML generator tests to match product folder structure

---

src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
src/IssueViz.UnitTests/Helpers/AnalysisSeverityToVsSeverityConverterTests.cs
src/IssueViz/Helpers/IAnalysisSeverityToVsSeverityConverter.cs

Add CCT severity to Vs Severity mapping

---

src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs

* Convert from Sonar Qube Client models to SLVS SoftwareQualitySeverity
* Select the highest Severity to be displayed
Implements #4834

Add mapping from SonarQube CCT to SLVS CCT severity for Taint issues

---

src/Integration.UnitTests/Notifications/NotificationIndicatorViewModelTests.cs
src/Integration/Notifications/NotificationIndicatorViewModel.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3213

Remove use of obsolete ThreadHelper.Generic.Invoke

---

src/Integration.Vsix.UnitTests/Commands/ProjectExcludePropertyToggleCommandTests.cs

fixes part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4770

Use mock of IProjectPropertyManager rather than an actual instance in ProjectExcludePropertyToggleCommandTests

---

src/Core/ISolutionInfoProvider.cs
src/Infrastructure.VS.UnitTests/FolderWorkspaceServiceTests.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/FolderWorkspaceService.cs
src/Infrastructure.VS/SolutionInfoProvider.cs

Remove calls to GetService from Importing Constructor.
part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4842

Add IsFolderWorkerSpace wrapper to ISolutionInfoProvider

---

src/CloudSecrets.UnitTests/SecretsAnalyzerTests.cs
src/CloudSecrets/SecretsAnalyzer.cs

Make secretsAnalyzer ctor free threaded

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs

- reverts part of commit 51533477; use previous API call for SonarCloud
Fixes #4848

Fix SonarCloud Connected Mode behaviour

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionManagerTests.cs
src/ConnectedMode/ConnectedModePackage.cs
src/ConnectedMode/ServerSentEvents/SSESessionManager.cs

Make SSESessionManager ctor free threaded

---

.editorconfig

CS7035 expects the build number to fit in 16 bits, our build numbers are bigger
https://github.com/dotnet/roslyn/issues/17024#issuecomment-1669503201

Ignore CS7035

---

src/Integration.TeamExplorer.UnitTests/SonarQubeNavigationItemTests.cs
src/Integration.TeamExplorer/SonarQubeNavigationItem.cs

Add tests to check if SonarQubeNavigationItem is free-threaded

---

src/Education.UnitTests/XamlGenerator/RuleXamlBuilderSmokeTest.cs
src/Rules.UnitTests/HtmlXmlCompatibilityHelperTests.cs
src/Rules/HtmlXmlCompatibilityHelper.cs

EnsureHtmlIsXml column cleaner regexp mistakenly matches too much

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode.UnitTests/Shared/SharedBindingConfigModelTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/Education.UnitTests/XamlGenerator/RuleXamlBuilderSmokeTest.cs
src/Education.UnitTests/XamlGenerator/SimpleRuleHelpXamlBuilderTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/Notifications/VisualStudioStatusBarHelper.cs
src/Rules.UnitTests/HtmlXmlCompatibilityHelperTests.cs
src/Rules/HtmlXmlCompatibilityHelper.cs
src/SonarQube.Client.Tests/SonarQubeService_GetProjectDashboardUrl.cs
src/SonarQube.Client/SonarQubeService.cs

Hardening Sprint November 2023

---

src/ConnectedMode.UnitTests/Suppressions/ClientSuppressionSynchronizerTests.cs
src/ConnectedMode.UnitTests/Synchronization/SuppressedIssueMatcherTests.cs
src/ConnectedMode/Suppressions/ClientSuppressionSynchronizer.cs
src/ConnectedMode/Synchronization/SuppressedIssueMatcher.cs
src/Integration.Vsix.UnitTests/Analysis/IssueConsumerFactoryTests.cs
src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs

Convert SuppressedIssueMatcher to IssueMatcher, return SonarQubeIssue instead of boolean

---

src/ConnectedMode.UnitTests/Suppressions/ClientSuppressionSynchronizerTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressedIssueMatcherTests.cs
src/ConnectedMode/Suppressions/ClientSuppressionSynchronizer.cs
src/ConnectedMode/Suppressions/SuppressedIssueMatcher.cs
src/Integration.Vsix.UnitTests/Analysis/IssueConsumerFactoryTests.cs
src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs

Not needed anymore, we went in a different direction with issue fetching for muting

Revert "Convert SuppressedIssueMatcher to IssueMatcher, return SonarQubeIssue instead of boolean"

---

src/ConnectedMode.UnitTests/ProjectRootCalculatorTests.cs
src/ConnectedMode/ProjectRootCalculator.cs
src/ConnectedMode/StatefulServerBranchProvider.cs
src/Core.UnitTests/Helpers/PathHelperTests.cs
src/Core/Helpers/PathHelper.cs

Add ProjectRootCalculator, cleanup PathHelper

---

src/ConnectedMode.UnitTests/ProjectRootCalculatorTests.cs
src/ConnectedMode/ProjectRootCalculator.cs

Change ProjectRootCalculator to use IActiveSolutionBoundTracker

---

src/ConnectedMode.UnitTests/Transition/MuteIssuesServiceTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/Transition/MuteIssuesService.cs
src/Core/Transition/IMuteIssuesService.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

Add IMuteIssuesService

---

src/Core.UnitTests/Configuration/ConnectedModeFeaturesConfigurationTests.cs
src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs
src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs

Make SonarCloud use won't fix

---

src/SLCore.UnitTests/Listener/BranchListenerTests.cs
src/SLCore/Listener/BranchListener.cs

Add ProjectBranchListener

---

src/EmbeddedSonarAnalyzer.props
src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs

Update embedded JS/TS analyzer 10.11.0.25043

---

src/SLCore.UnitTests/Listener/ConnectionConfigurationListenerTests.cs
src/SLCore.UnitTests/Listener/ProgressListenerTests.cs
src/SLCore/Listener/ConnectionConfigurationListener.cs
src/SLCore/Listener/ProgressListener.cs

Implement ConnectionConfigurationListener

---

src/SLCore.UnitTests/Protocol/EitherJsonConverterTests.cs
src/SLCore/Protocol/Either.cs
src/SLCore/Protocol/EitherJsonConverter.cs

Add Either helper class & serialization

---

src/Education.UnitTests/Layout/Logical/ContextualRuleDescriptionTabTests.cs
src/Education.UnitTests/Layout/Logical/NonContextualRuleDescriptionTabTests.cs
src/Education.UnitTests/Layout/Logical/RuleSplitDescriptionTests.cs
src/Education/Education.csproj
src/Education/Layout/Logical/ContextualRuleDescriptionTab.cs
src/Education/Layout/Logical/IRuleDescriptionTab.cs
src/Education/Layout/Logical/IVisualNodeProducer.cs
src/Education/Layout/Logical/NonContextualRuleDescriptionTab.cs
src/Education/Layout/Visual/Tabs/TabItem.cs

Add IVisualNodeProducer.ProduceVisualNode implementations

---

src/SLCore.UnitTests/Common/Helpers/ConnectionIdHelperTests.cs
src/SLCore/Common/Helpers/ConnectionIdHelper.cs

Add GetConnectionIdFromUri Method to ConnectionIdHelper

---

src/Infrastructure.VS.UnitTests/AsyncLockFactoryTests.cs
src/Infrastructure.VS.UnitTests/AsyncLockTests.cs
src/Infrastructure.VS/AsyncLock.cs

Add IAsyncLock implementation

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/Service/Project/IBindingSLCoreService.cs
src/SLCore/Service/Project/IConfigurationScopeSLCoreService.cs
src/SLCore/Service/Project/Params/DidAddConfigurationScopesParams.cs
src/SLCore/Service/Project/Params/DidRemoveConfigurationScopeParams.cs
src/SLCore/Service/Project/Params/DidUpdateBindingParams.cs
src/SLCore/State/ActiveConfigScopeTracker.cs

Update config scope when binding changes

---

src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/Models/FeatureFlagsDto.cs
src/SLCore/Service/Telemetry/ITelemetrySLCoreService.cs

Change SLCoreInstanceHandle & SLCoreConstantsProvider to disable telemetry as part of initialization

---

src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs

Make SLConstantsProvider use VS instance name as the client name

---

src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

Fixes a problem introduced by https://github.com/SonarSource/sonarlint-visualstudio/commit/a5c28455c4191a55c2958f6bf75b7505c2521265

Change vs22/vsixmanifest version to 8.0

---

src/SonarLint.Test.props

Add common test usings to SonarLint.Test.props

---

src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix/Analysis/DisableRuleCommand.cs

Fixes #5072
Wiki changes required:
* Add CSS to the table on `Define C, C++, JS, TS or secrets detection rules for local analysis` section
https://docs.sonarsource.com/sonarlint/visual-studio/using-sonarlint/rules/
On a standalone project with CSS files.
Before this PR:
After this PR:

Disable rule command does not have CSS in the supported languages list

---

src/Directory.Build.props
src/SonarLint.Product.props
src/SonarLint.Test.props

Fixes #5426
Based on:
https://github.com/SonarSource/sonarlint-visualstudio/pull/5432#discussion_r1603237273

 Move common, test and product, global usings to Directory.Build.props

---

src/Education/Rule/SLCoreRuleMetaDataProvider.cs
src/SLCore.UnitTests/Common/Helpers/ModelConversionExtensionsTests.cs
src/SLCore/Common/Helpers/ModelConversionExtensions.cs

Fixes missed bits from https://github.com/SonarSource/sonarlint-visualstudio/pull/5482

CaYC: SLCoreRuleMetaDataProvider & ModelExtensions

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Updated docs with the procedure followed to upgrade the CFamily analyzer:
https://xtranet-sonarsource.atlassian.net/wiki/spaces/DevEx/pages/3399614534/Upgrade+analyzers

SLVS-1290 Upgrade CFamily analyzer to 6.57.0.73017

---

pipeline/azure-pipelines.yml

This PR is
1. Publishing the artifacts to repox
> https://repox.jfrog.io/ui/repos/tree/General/sonarsource-public-qa/org/sonarsource/sonarlint/visualstudio
> the `sonarlint-visualstudio` has been replaced by `sonarlint-visualstudio-2022`. However, there is no such dir on repox at the moment as all the artifacts have been promoted to the `sonarsource-public-builds`.
2. Publishing the build info
> https://repox.jfrog.io/ui/builds/sonarlint-visualstudio-2022/97475/1724053604929/published?buildRepo=artifactory-build-info
> There are no dependencies reported on the build-info yet. Dependencies will be added when we migrate to Cirrus CI
3. Promoting the artifact on repox builds when tests pass
> https://repox.jfrog.io/ui/repos/tree/General/sonarsource-public-builds/org/sonarsource/sonarlint/visu …

SLVS-1356 Publish artifacts on repox instead of azure

---

src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/ConnectedMode.UnitTests/UI/Credentials/CredentialsViewModelTests.cs
src/ConnectedMode.UnitTests/UI/OrganizationSelection/OrganizationSelectionViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ProgressReporterViewModelTests.cs
src/ConnectedMode/SlCoreConnectionAdapter.cs
src/ConnectedMode/UI/Credentials/CredentialsViewModel.cs
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionViewModel.cs
src/ConnectedMode/UI/ProgressReporterViewModel.cs

[SLVS-1418](https://sonarsource.atlassian.net/browse/SLVS-1418)
This PR targets the 
[SLVS-1418]: https://sonarsource.atlassian.net/browse/SLVS-1418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1418 Extract progress duplication in view models

---

src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/ConnectedMode.UnitTests/UI/Credentials/CredentialsViewModelTests.cs
src/ConnectedMode.UnitTests/UI/OrganizationSelection/OrganizationSelectionViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ProgressReporterViewModelTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/SlCoreConnectionAdapter.cs
src/ConnectedMode/UI/Credentials/CredentialsViewModel.cs
src/ConnectedMode/UI/Credentials/ICredentialsModel.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionDialog.xaml
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionDialog.xaml.cs
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionViewModel.cs
src/ConnectedMode/UI/ProgressReporterViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-1394](https://sonarsource.atlassian.net/browse/SLVS-1394)
This PR updates the ISlCoreConnectionAdapter to load the organizations for SonarCloud when creating a new connection.
Showing it in the UI will be a different PR
[SLVS-1394]: https://sonarsource.atlassian.net/browse/SLVS-1394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1394 Load organizations

---

.cirrus.yaml

BUILD-6082: Implement sbom generation

BUILD-6082: Implement sbom generation

---

src/Core/Binding/IActiveSolutionBoundTracker.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-1406](https://sonarsource.atlassian.net/browse/SLVS-1406)
[SLVS-1406]: https://sonarsource.atlassian.net/browse/SLVS-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1406 Add binding changed trigger to ActiveSolutionBoundTracker

---

src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/Core/Binding/IServerConnectionsRepository.cs

[SLVS-1382](https://sonarsource.atlassian.net/browse/SLVS-1382)
This PR is based on the [binding dialog PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5649), because the ServerConnectionsRepositoryAdapter was needed to map the model used for the repository to the UI model.
[SLVS-1382]: https://sonarsource.atlassian.net/browse/SLVS-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1382 Manage Connections Dialog: User should be able to view the list of connections

---

src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ConnectedModeServicesTests.cs
src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode.UnitTests/UI/ProgressReporterViewModelTests.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/UI/ConnectedModeServices.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/ProgressReporterViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/Core/Binding/IServerConnectionsRepository.cs

[SLVS-1376](https://sonarsource.atlassian.net/browse/SLVS-1376)
To test this feature in the UI, you have to adapt the DummyServerConnectionsRepository.GetAll to return some connections instead of throwing
[SLVS-1376]: https://sonarsource.atlassian.net/browse/SLVS-1376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1376 Binding Dialog: list connections

---

.cirrus.yaml

[BUILD-6161](https://sonarsource.atlassian.net/browse/BUILD-6161)
- add `sonar.cs.vscoveragexml.reportsPaths` parameter to have coverage analysis
- add `sonar.scanner.scanAll=false` parameter to get rid of the warning message
- convert coverage report to xml
[BUILD-6161]: https://sonarsource.atlassian.net/browse/BUILD-6161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6161 Add coverage parameter for SonarCloud scan

---

src/ConnectedMode.UnitTests/Persistence/ServerConnectionModelMapperTest.cs
src/ConnectedMode/Persistence/ServerConnectionJsonModel.cs
src/ConnectedMode/Persistence/ServerConnectionModelMapper.cs
src/Core/Binding/ServerConnection.cs

[SLVS-1431](https://sonarsource.atlassian.net/browse/SLVS-1431)
[SLVS-1431]: https://sonarsource.atlassian.net/browse/SLVS-1431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1431 Add server connection json model and mapper

---

src/SLCore.UnitTests/Common/Models/FileUriTests.cs
src/SLCore/Common/Models/FileUri.cs

[SLVS-1436](https://sonarsource.atlassian.net/browse/SLVS-1436)
[SLVS-1436]: https://sonarsource.atlassian.net/browse/SLVS-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1436 Escape rfc 3986 reserved chars in file names.

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1423](https://sonarsource.atlassian.net/browse/SLVS-1423)
This build fails, because the artifact for the SonarText 2.15.0.3845 was not published to the expected binaries location. But once we [change](https://github.com/SonarSource/sonarlint-visualstudio/pull/5674) the download logic to take the analyzer from repox, it should pass.
[SLVS-1423]: https://sonarsource.atlassian.net/browse/SLVS-1423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1423 Update embedded SonarText analyzer to 2.15.0.3845

---

src/SLCore.Listeners.UnitTests/HttpConfigurationListenerTests.cs
src/SLCore.Listeners.UnitTests/Implementation/Http/CertificateChainValidatorTests.cs
src/SLCore.Listeners.UnitTests/Implementation/Http/CertificateDtoConverterTests.cs
src/SLCore.Listeners.UnitTests/Implementation/Http/HttpConfigurationListenerTests.cs
src/SLCore.Listeners/Implementation/Http/HttpConfigurationListener.cs
src/SLCore.Listeners/Implementation/Http/ICertificateChainValidator.cs
src/SLCore.Listeners/Implementation/Http/ICertificateDtoConverter.cs
src/SLCore.Listeners/Implementation/HttpConfigurationListener.cs
src/SLCore/Listener/Http/CheckServerTrustedParams.cs
src/SLCore/Listener/Http/CheckServerTrustedResponse.cs
src/SLCore/Listener/Http/IHttpConfigurationListener.cs
src/SLCore/Listener/Http/Model/X509CertificateDto.cs
src/SLCore/Listener/Http/SelectProxiesResponse.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx

[SLVS-1369](https://sonarsource.atlassian.net/browse/SLVS-1369)
[SLVS-1369]: https://sonarsource.atlassian.net/browse/SLVS-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1369 Add checkServerTrusted rpc method implementation

---

src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml

The problem seemed to be that the binding was not updating the value of the view model property, so when the OK button was pressed in the Options page, the previous value was overwritten

SLVS-1442 Fix JRE not persisted

---

src/ConnectedMode.UnitTests/Persistence/ServerConnectionsRepositoryTests.cs
src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/Persistence/ServerConnectionsRepository.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/Core/Binding/IServerConnectionsRepository.cs

[SLVS-1399](https://sonarsource.atlassian.net/browse/SLVS-1399)
This PR targets this [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5661), because it depends on it for the implementation.
The server connections could be tested with the UI: if the file exists, the connections are shown in the manage binding dialog and manage connections dialog. Adding a connection with the UI is not implemented yet.
Example of a valid json:
{
"serverConnections": [
{
"id": "https://sonarcloud.io/organizations/myOrg",
"setting": {
"IsSmartNotificationsEnabled": false
},
"organizationKey": "mya",
"serverUri": null
}
]
}
[SLVS-1399]: https://sonarsource.atlassian.net/browse/SLVS-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1399 Implement IServerConnectionRepository

---

src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-1393](https://sonarsource.atlassian.net/browse/SLVS-1393)
Prevent deleting the connection when there are bindings that use that connection will be done in a separate PR, because it depends on the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5685) (to get the list of bindings that contain the ConnectionId info). And that PR is still work in progress
[SLVS-1393]: https://sonarsource.atlassian.net/browse/SLVS-1393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1393 Delete Connection Dialog: User should be able to delete a connectionGt/delete connection

---

src/ConnectedMode.UnitTests/Migration/BindingToConnectionMigrationTests.cs
src/ConnectedMode/Migration/BindingToConnectionMigration.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx
src/ConnectedMode/Persistence/ServerConnectionsRepository.cs
src/Core/Binding/IServerConnectionsRepository.cs
src/Integration.Vsix/SonarLintDaemonPackage.cs

Implemented the migration and called it in the SonarLintDaemonPackage at the very beginning, because it should be performed as early as possible. This package is also called if solutions or folders are opened, or even none of them, which is desirable.
When the migration is performed for the first time, if you open a solution super fast, it might not actually be bound. But if you re-open the solution, then everything works as expected. 
I did not find a workaround for this issue (even triggering the binding manually did not help, I guess because it was too early). But I don't think I should invest too much effort into this, as it will only happen once: when the migration is performed, after the first update.

SLVS-1400 Add migration mechanism to separate connections from bindings

---

src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
src/Integration.TeamExplorer/SectionController.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs
src/Integration/MefServices/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs

[SLVS-1457](https://sonarsource.atlassian.net/browse/SLVS-1457)
It should have been easy: just instantiate the ManageBindingDialog in the SharedBindingSuggestionService and pass it to the goldbar. But it was a mess, because once you start adding the reference to IConnectedModeBindingServices you have a circular reference that crashes the app at runtime (the circular reference was VsSessionHost ->  SharedBindingSuggestionService -> UnintrusiveBindingController -> ActiveSolutionBoundTracker -> VsSessionHost)
So I had to restructure the logic to break the circular refernce.
[SLVS-1457]: https://sonarsource.atlassian.net/browse/SLVS-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1457 Open ManageBindingDialog from SharedBindingGoldBar

---

src/ConnectedMode/UI/Credentials/CredentialsDialog.xaml

[SLVS-1466](https://sonarsource.atlassian.net/browse/SLVS-1466)
[SLVS-1466]: https://sonarsource.atlassian.net/browse/SLVS-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1466 Add back warning for the deprecated credentials

---

.sonarlint/SonarLint.VisualStudio.Integration.json
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-1370](https://sonarsource.atlassian.net/browse/SLVS-1370)
- rename "use shared binding" to "use shared configuration"
- rename "export" to "share configuration"
- remove tooltip that doesn't make sense anymore, because we only show the button when the shared binding configuration is present
- Change "Learn more about connected mode here" to "Learn more about Connected Mode"
[SLVS-1370]: https://sonarsource.atlassian.net/browse/SLVS-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1370 Incorporate UX feedback

---

src/ConnectedMode.UnitTests/Migration/BindingToConnectionMigrationTests.cs
src/ConnectedMode/Migration/BindingToConnectionMigration.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx

[SLVS-1477](https://sonarsource.atlassian.net/browse/SLVS-1477)
[SLVS-1477]: https://sonarsource.atlassian.net/browse/SLVS-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1477 Add more logs to new migration

---

src/ConnectedMode.UnitTests/Persistence/ServerConnectionsRepositoryTests.cs
src/ConnectedMode/Persistence/ServerConnectionsRepository.cs
src/Core/Binding/IServerConnectionsRepository.cs
src/SLCore.UnitTests/State/AliveConnectionTrackerTests.cs
src/SLCore/State/AliveConnectionTracker.cs

[SLVS-1473](https://sonarsource.atlassian.net/browse/SLVS-1473)
Update ActiveConnectionTracker to listen to events from ServerConnectionRepository instead of ISolutionBindingRepository.
The connections are saved in a dedicated file and are no longer calculated from binding. Therefore, we need to listen to the repository.
Update the ServerConnectionRepository to raise events when a connection is added/deleted/updated and when the credentials are changed.
This PR is only really testable in conjunction with the [this PR ](https://github.com/SonarSource/sonarlint-visualstudio/pull/5718)
[SLVS-1473]: https://sonarsource.atlassian.net/browse/SLVS-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1473 Refactor AliveConnectionTracker

---

src/SLCore.Listeners.UnitTests/Implementation/Analysis/AnalysisListenerTests.cs
src/SLCore.Listeners/Implementation/Analysis/AnalysisListener.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseIssuesParamsTests.cs
src/SLCore/Listener/Analysis/IAnalysisListener.cs
src/SLCore/Listener/Analysis/RaiseFindingParams.cs

[SLVS-1503](https://sonarsource.atlassian.net/browse/SLVS-1503)
[SLVS-1503]: https://sonarsource.atlassian.net/browse/SLVS-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1503 Address breaking change from SlCore 10.7

---

src/Integration.Vsix/SonarLintIntegrationPackage.cs
src/Integration.Vsix/SonarLintNotificationsPackage.cs

[SLVS-1489](https://sonarsource.atlassian.net/browse/SLVS-1489)
Moved the call to ISharedBindingSuggestionService to SonarLintNotificationsPackage and made sure that the package is also initialized when opening a folder and a workspace.
[SLVS-1489]: https://sonarsource.atlassian.net/browse/SLVS-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1489 Use Shared Binding Config infobar not shown unless Manage Binding dialog is clicked

---

src/Infrastructure.VS.UnitTests/Infrastructure.VS.UnitTests.csproj
src/Infrastructure.VS.UnitTests/Roslyn/EmbeddedRoslynAnalyzerProviderTests.cs
src/Infrastructure.VS.UnitTests/packages.lock.json
src/Infrastructure.VS/Resources.Designer.cs
src/Infrastructure.VS/Resources.resx
src/Infrastructure.VS/Roslyn/EmbeddedRoslynAnalyzerProvider.cs
src/Infrastructure.VS/Roslyn/IEmbeddedRoslynAnalyzerProvider.cs
src/Infrastructure.VS/Roslyn/IEmbeddedRoslynAnalyzersLocator.cs
src/Integration.Vsix.UnitTests/EmbeddedAnalyzers/EmbeddedRoslynAnalyzersLocatorTests.cs
src/Integration.Vsix/EmbeddedAnalyzers/EmbeddedRoslynAnalyzersLocator.cs

This targets the [SLVS-1514 PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5755), because the location to the embedded analyzers changed in that PR, so the provider should look in the updated location.

SLVS-1517 Implement IEmbeddedAnalyzerProvider

---

src/Infrastructure.VS.UnitTests/Infrastructure.VS.UnitTests.csproj
src/Infrastructure.VS.UnitTests/Roslyn/AnalyzerAssemblyLoaderFactoryTests.cs
src/Infrastructure.VS.UnitTests/packages.lock.json
src/Infrastructure.VS/Roslyn/AnalyzerAssemblyLoaderFactory.cs

[SLVS-1529](https://sonarsource.atlassian.net/browse/SLVS-1529)
This PR targets the [implementation of the AnalyzerAssemblyLoader,](https://github.com/SonarSource/sonarlint-visualstudio/pull/5764) because it depends on it
[SLVS-1529]: https://sonarsource.atlassian.net/browse/SLVS-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1529 Cache analyzerAssemblyLoader

---

src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-1537](https://sonarsource.atlassian.net/browse/SLVS-1537)
[SLVS-1537]: https://sonarsource.atlassian.net/browse/SLVS-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1537 Add ISolutionRoslynAnalyzerManager integration to ActiveSolutionBoundTracker

---

src/Integration.Vsix/Integration.Vsix.csproj

Fix exception when connecting to SQ by making sure that the Google.Protobuf.dll is also part of the root folder inside vsix, which is needed by SonarQube.Client
[SLVS-1550](https://sonarsource.atlassian.net/browse/SLVS-1550)
[SLVS-1550]: https://sonarsource.atlassian.net/browse/SLVS-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1550 Fix exception when connecting to SQ

---

src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs

[SLVS-1554](https://sonarsource.atlassian.net/browse/SLVS-1554)
Part of SLVS-1183
[SLVS-1554]: https://sonarsource.atlassian.net/browse/SLVS-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1554 CaYC Replace Moq with NSubstitute

---

src/ConnectedMode.UnitTests/Binding/Suggestion/SuggestSharedBindingGoldBarTests.cs
src/ConnectedMode/Binding/Suggestion/SuggestSharedBindingGoldBar.cs
src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs
src/Core/Notifications/Notification.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs
src/SLCore.UnitTests/NodeJS/Notifications/UnsupportedNodeVersionNotificationServiceTests.cs
src/SLCore.UnitTests/Notification/SloopRestartFailedNotificationServiceTests.cs
src/SLCore/NodeJS/Notifications/IUnsupportedNodeVersionNotificationService.cs
src/SLCore/Notification/ISloopRestartFailedNotificationService.cs

[SLVS-1561](https://sonarsource.atlassian.net/browse/SLVS-1561)
Part of SLVS-1183
Expectations:
1. When closing a solution notifications should be closed
> Except for the ones that are session-scoped (NodeJS version, Sloop restart)
[SLVS-1561]: https://sonarsource.atlassian.net/browse/SLVS-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1561 Close notifications when solution is closed

---

src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration/Binding/BindingSuggestionHandler.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs

[SLVS-1183](https://sonarsource.atlassian.net/browse/SLVS-1183)
Expectations:
1. On a project with shared binding which is still in Standalone mode, after binding the notification should close
2. On a project which is still in Standalone mode and an Open in IDE request came, after binding the notification to connect should close
[SLVS-1183]: https://sonarsource.atlassian.net/browse/SLVS-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1183 SLVS goldbars are not reset on solution/binding change

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs

[SLVS-1562](https://sonarsource.atlassian.net/browse/SLVS-1562)
CaYC: refactor ActiveConfigScopeTrackerTests to use Nsubstitute and extract commin initialization logic inside TestInitialize
Part of SLVS-1497
[SLVS-1562]: https://sonarsource.atlassian.net/browse/SLVS-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1562 Refactor ActiveConfigScopeTrackerTests to use Nsubstitute

---

src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-1565](https://sonarsource.atlassian.net/browse/SLVS-1565)
Part of SLVS-1385
Expectations:
1. You should be able to see the edit connection button on the connections list
2. You should be able to update the credentials of any connection
> You can test that after updating the credentials when having an unbound project, the "Select Project" loads correctly
Note: Re-triggering the connection is **not** part of this task
[SLVS-1565]: https://sonarsource.atlassian.net/browse/SLVS-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1565 User should be able to update the credentials

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/State/ActiveConfigScopeTracker.cs

[SLVS-1563](https://sonarsource.atlassian.net/browse/SLVS-1563)
This is a draft, because it targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5782), which is needed for the tests. It can still be reviewed. 
[SLVS-1563]: https://sonarsource.atlassian.net/browse/SLVS-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1563 Raise CurrentConfigurationScopeChanged when configuration scope changed

---

src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-1385](https://sonarsource.atlassian.net/browse/SLVS-1385)
Expectations:
* A connection should be re-triggered when the user edits the credentials
* If any error occurs, show an error message at the bottom of the dialog
To test:
1. Bind a solution with a token
2. Close the solution
3. Revoke the token
4. Open the solution again (expect that the binding is broken)
5. Update with a new token (expect that the solution is bound and you are able to view for example taints)
[SLVS-1385]: https://sonarsource.atlassian.net/browse/SLVS-1385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1385 Manage Connections Dialog: User should be able to edit credentials

---

src/SLCore.Listeners.UnitTests/Implementation/TaintVulnerabilityListenerTests.cs
src/SLCore.Listeners/Implementation/TaintVulnerabilityListener.cs
src/SLCore.UnitTests/Common/Models/TaintVulnerabilityDtoTests.cs
src/SLCore.UnitTests/Listener/Taint/DidChangeTaintVulnerabilitiesParamsTests.cs
src/SLCore.UnitTests/Service/Taint/ListAllTaintsParamsTests.cs
src/SLCore.UnitTests/Service/Taint/ListAllTaintsResponseTests.cs
src/SLCore/Common/Models/TaintVulnerabilityDto.cs
src/SLCore/Common/Models/TextRangeWithHashDto.cs
src/SLCore/Listener/Taint/DidChangeTaintVulnerabilitiesParams.cs
src/SLCore/Listener/Taint/ITaintVulnerabilityListener.cs
src/SLCore/Service/Taint/ListAllTaintsParams.cs
src/SLCore/Service/Taint/ListAllTaintsResponse.cs
src/SLCore/Service/Taint/TaintVulnerabilityTrackingSLCoreService.cs

[SLVS-1590](https://sonarsource.atlassian.net/browse/SLVS-1590)
[SLVS-1590]: https://sonarsource.atlassian.net/browse/SLVS-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1590 Add SLCore rpc contracts for taint issues

---

src/Integration.Vsix.UnitTests/Settings/SonarLintSettingsTests.cs
src/Integration.Vsix/Settings/SonarLintSettings.cs

When exiting Visual Studio we often get an Exception because SLCore is sending log messages for shutdown, but the log level settings have already been disposed and the COM object has been detached from VS.

SLVS-1627 Graceful shutdown: Prevent exception when calling detached COM object

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionManagerTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionManager.cs

[SLVS-1629](https://sonarsource.atlassian.net/browse/SLVS-1629)
SSESessionManager does not support SonarCloud connections and currently throws an Exception when project is connected to SonarCloud.
[SLVS-1629]: https://sonarsource.atlassian.net/browse/SLVS-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1629 Prevent SSESessionManager creating session for SonarCloud

---

src/Education/Rule/IRuleInfoConverter.cs
src/SLCore.UnitTests/Common/Helpers/ModelConversionExtensionsTests.cs
src/SLCore/Common/Helpers/ModelConversionExtensions.cs

[SLVS-1623](https://sonarsource.atlassian.net/browse/SLVS-1623)
The other enums RuleIssueType, RuleIssueSeverity can not be moved, because they are specific to the Education assembly 
[SLVS-1623]: https://sonarsource.atlassian.net/browse/SLVS-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1623 Move CleanCodeAttribute enum conversion from IRuleInfoConverter

---

src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/Resources/Pencil.xaml

[SLVS-1618](https://sonarsource.atlassian.net/browse/SLVS-1618)
[SLVS-1618]: https://sonarsource.atlassian.net/browse/SLVS-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1618 Change the edit credentials icon to be usable in dark mode as well

---

SonarLint.VisualStudio.Integration.sln.DotSettings
src/ConnectedMode.UnitTests/UI/ProgressReporterViewModelTests.cs
src/Education.UnitTests/EducationTests.cs
src/Education.UnitTests/ErrorList/SonarErrorListEventProcessorProviderTests.cs
src/Education.UnitTests/ErrorList/SonarErrorListEventProcessorTests.cs
src/Education.UnitTests/Rule/SLCoreRuleMetaDataProviderTests.cs
src/Education/Education.cs
src/Education/ErrorList/SonarErrorListEventProcessor.cs
src/Education/ErrorList/SonarErrorListEventProcessorProvider.cs
src/Education/Rule/SLCoreRuleMetaDataProvider.cs
src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs

[SLVS-1625](https://sonarsource.atlassian.net/browse/SLVS-1625)
As part of CaYC, replace Moq with Nsubstitute in the touched test classes of [this PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5830) and clean up the test classes
Also reformat code and execute Resharper’s code cleanup both in the test classes and in the classes under test
[SLVS-1625]: https://sonarsource.atlassian.net/browse/SLVS-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1625 CaYC: Replace Moq with Nsubstitute

---

src/IssueViz.Security.UnitTests/Taint/TaintStoreTests.cs
src/IssueViz.Security/Taint/TaintStore.cs

[SLVS-1647](https://sonarsource.atlassian.net/browse/SLVS-1647)
[SLVS-1647]: https://sonarsource.atlassian.net/browse/SLVS-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1647 On taint update with changed id, fallback to match by server key

---

src/Integration.UnitTests/LocalServices/SolutionWorkspaceServiceTests.cs
src/Integration/LocalServices/SolutionWorkspaceService.cs

[SLVS-1652](https://sonarsource.atlassian.net/browse/SLVS-1652)
[SLVS-1652]: https://sonarsource.atlassian.net/browse/SLVS-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1652 Add try/catch in SolutionWorkspaceService VsHierarchy enumeration

---

.cirrus.yaml
.cirrus/sonarqube-cloud-analysis.sh

[SLVS-1662](https://sonarsource.atlassian.net/browse/SLVS-1662)
[SLVS-1662]: https://sonarsource.atlassian.net/browse/SLVS-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1662 Run sonarcloud analysis for long lived branches and PRs

---

.cirrus/sonarqube-cloud-analysis.sh

[SLVS-1662](https://sonarsource.atlassian.net/browse/SLVS-1662)
[SLVS-1662]: https://sonarsource.atlassian.net/browse/SLVS-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1662 Fix unknown variable on long lived branches

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

[SLVS-1648](https://sonarsource.atlassian.net/browse/SLVS-1648)
[SLVS-1648]: https://sonarsource.atlassian.net/browse/SLVS-1648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1648 Update Sonar CFamily to 6.61.0.77816

---

src/CFamily.UnitTests/Subprocess/MessageHandlerTests.cs
src/CFamily/Subprocess/MessageHandler.cs
src/Core.UnitTests/Analysis/AnalysisServiceTests.cs
src/Core/Analysis/AnalysisService.cs
src/Core/Analysis/IIssueConsumer.cs
src/Integration.Vsix.UnitTests/Analysis/IssueConsumerFactoryTests.cs
src/Integration.Vsix.UnitTests/ReferencesTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/IssueConsumerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/VsAwareAnalysisServiceTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
src/Integration.Vsix/SonarLintTagger/IssueConsumer.cs
src/Integration.Vsix/SonarLintTagger/VsAwareAnalysisService.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/RaisedFindingProcessorTests.cs
src/SLCore.Listeners/Implementation/Analysis/RaisedFindingProcessor.cs

[SLVS-1679](https://sonarsource.atlassian.net/browse/SLVS-1679)
[SLVS-1679]: https://sonarsource.atlassian.net/browse/SLVS-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1679 Enable issue streaming for SLCore analysis

---

src/CFamily.UnitTests/CompilationDatabase/AggregatingCompilationDatabaseProviderTests.cs
src/CFamily.UnitTests/CompilationDatabase/ExternalCompilationDatabaseHandleTests.cs
src/CFamily/CompilationDatabase/ExternalCompilationDatabaseHandle.cs
src/CFamily/IVCXCompilationDatabaseProvider.cs
src/Core/CFamily/IAggregatingCompilationDatabaseProvider.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/TemporaryCompilationDatabaseHandleTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/VCXCompilationDatabaseProviderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/VCXCompilationDatabaseStorageTests.cs
src/Integration.Vsix/CFamily/VcxProject/IVCXCompilationDatabaseStorage.cs
src/Integration.Vsix/CFamily/VcxProject/TemporaryCompilationDatabaseHandle.cs
src/Integration.Vsix/CFamily/VcxProject/VCXCompilationDatabaseProvider.cs
src/SLCore.UnitTests/Analysis/SLCoreAnalyzerTests.cs
src/SLCore/Analysis/SLCoreAnalyzer.cs

[SLVS-1678](https://sonarsource.atlassian.net/browse/SLVS-1678)
[SLVS-1678]: https://sonarsource.atlassian.net/browse/SLVS-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1678 Use unique generated compilation database names

---

src/Integration.Vsix.UnitTests/CFamily/CmdBuilderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/FileConfigTests.cs
src/Integration.Vsix/CFamily/VcxProject/CmdBuilder.cs
src/Integration.Vsix/CFamily/VcxProject/FileConfig.cs
src/Integration.Vsix/CFamily/VcxProject/IFileConfig.cs

[SLVS-1668](https://sonarsource.atlassian.net/browse/SLVS-1668)
Part of SLVS-1637
See the linked ticket for details about the problems we identified. This PR introduces the following changes:
- To communicate the header file language, I am adding the relevant switches to the generated command in the header case as well. This helps analyze C headers as such when they are located inside C VCX projects.
- Since `HeaderFileLanguage` is no longer needed, I am removing it from `FileConfig`.
[SLVS-1668]: https://sonarsource.atlassian.net/browse/SLVS-1668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1668 Include header file language in the VCX command

---

src/ConnectedMode.UnitTests/BoundSolutionUpdateHandlerTests.cs
src/ConnectedMode/BoundSolutionUpdateHandler.cs

[SLVS-1688](https://sonarsource.atlassian.net/browse/SLVS-1688)
[SLVS-1688]: https://sonarsource.atlassian.net/browse/SLVS-1688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1688 Update Quality Profiles on solution open

---

src/SLCore.UnitTests/Analysis/SLCoreAnalyzerTests.cs
src/SLCore/Analysis/SLCoreAnalyzer.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx

[SLVS-1669](https://sonarsource.atlassian.net/browse/SLVS-1669)
[SLVS-1669]: https://sonarsource.atlassian.net/browse/SLVS-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1669 Handle the case of C/C++ files outside the projects

---

src/CFamily.UnitTests/Subprocess/MessageHandlerTests.cs
src/CFamily/Subprocess/MessageHandler.cs
src/Core.UnitTests/Analysis/AnalysisServiceTests.cs
src/Core.UnitTests/Analysis/HotspotsPublisherTests.cs
src/Core.UnitTests/Analysis/IssuePublisherTests.cs
src/Core/Analysis/AnalysisService.cs
src/Core/Analysis/HotspotPublisher.cs
src/Core/Analysis/IAnalysisService.cs
src/Core/Analysis/IFindingsPublisher.cs
src/Core/Analysis/IssuePublisher.cs
src/Integration.Vsix.UnitTests/Analysis/IssueConsumerFactoryTests.cs
src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/IssueConsumerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/VsAwareAnalysisServiceTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs
src/Integration.Vsix/SonarLintTagger/IssueConsumer.cs
src/Integration.Vsix/SonarLintTagger/VsAwareAnalysisService.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/AnalysisListenerTests.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/RaisedFindingProcessorTests.cs
src/SLCore.Listeners/Implementation/Analysis/AnalysisListener.cs
src/SLCore.Listeners/Implementation/Analysis/RaisedFindingProcessor.cs

[SLVS-1693](https://sonarsource.atlassian.net/browse/SLVS-1693)
[SLVS-1693]: https://sonarsource.atlassian.net/browse/SLVS-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1693 Fix: issues set to empty after hotspots event

---

src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs

[SLVS-1712](https://sonarsource.atlassian.net/browse/SLVS-1712)
Fix QG caused by "parameter being captured into the state of the enclosing type and its value is also used to initialize a field"
[SLVS-1712]: https://sonarsource.atlassian.net/browse/SLVS-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1712 Fix QG caused by "parameter being captured into the state of the enclosing type and its value is also used to initialize a field"

---

src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs

[SLVS-1718](https://sonarsource.atlassian.net/browse/SLVS-1718)
[SLVS-1718]: https://sonarsource.atlassian.net/browse/SLVS-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1718 Fix UI not updated after deleting connection

---

src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs

[SLVS-1721](https://sonarsource.atlassian.net/browse/SLVS-1721)
[SLVS-1721]: https://sonarsource.atlassian.net/browse/SLVS-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1721 Fix "Use shared configuration" button not shown after unbind

---

src/EmbeddedSonarAnalyzer.props
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/Models/JsTsRequirementsDto.cs

[SLVS-1692](https://sonarsource.atlassian.net/browse/SLVS-1692)
[SLVS-1692]: https://sonarsource.atlassian.net/browse/SLVS-1692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1692 Update SlCore to 10.12.0.79820

---

src/Core/Analysis/CFamilyAnalyzerOptions.cs
src/Integration.Vsix.UnitTests/CFamily/CFamilyReproducerCommandTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/FileConfigProviderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/VCXCompilationDatabaseProviderTests.cs
src/Integration.Vsix/CFamily/CFamilyReproducerCommand.cs
src/Integration.Vsix/CFamily/VcxProject/FileConfigProvider.cs
src/Integration.Vsix/CFamily/VcxProject/VCXCompilationDatabaseProvider.cs
src/SLCore.UnitTests/Analysis/SLCoreAnalyzerTests.cs
src/SLCore/Analysis/SLCoreAnalyzer.cs

[SLVS-1697](https://sonarsource.atlassian.net/browse/SLVS-1697)
[SLVS-1697]: https://sonarsource.atlassian.net/browse/SLVS-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1697 Integrate Reproducer command with SLCore analysis

---

src/ConnectedMode.UnitTests/Binding/BindingProcessFactoryTests.cs
src/ConnectedMode.UnitTests/Binding/BindingProcessImplTests.cs
src/ConnectedMode/Binding/BindingProcessImpl.cs
src/ConnectedMode/Binding/IBindingProcessFactory.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

[SLVS-1739](https://sonarsource.atlassian.net/browse/SLVS-1739)
Part of SLVS-1167
[SLVS-1739]: https://sonarsource.atlassian.net/browse/SLVS-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1739 Fix QualityGate issues

---

src/ConnectedMode.UnitTests/Persistence/CredentialsExtensionMethodsTests.cs
src/ConnectedMode.UnitTests/Persistence/SolutionBindingCredentialsLoaderTests.cs
src/ConnectedMode.UnitTests/Persistence/TokenAuthCredentialsTests.cs
src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/ConnectedMode/Persistence/ICredentialsExtensionMethods.cs
src/ConnectedMode/Persistence/SolutionBindingCredentialsLoader.cs
src/ConnectedMode/Persistence/TokenAuthCredentials.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/SlCoreConnectionAdapter.cs
src/Integration/MefServices/MefSonarQubeService.cs
src/SonarQube.Client.Tests/Helpers/AuthenticationHeaderFactoryTests.cs
src/SonarQube.Client/Helpers/AuthenticationHeaderFactory.cs
src/SonarQube.Client/Models/IConnectionCredentials.cs
src/SonarQube.Client/SonarQubeService.cs

[SLVS-1732](https://sonarsource.atlassian.net/browse/SLVS-1732)
[SLVS-1732]: https://sonarsource.atlassian.net/browse/SLVS-1732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1732 Fix SSF-694

---

src/ConnectedMode/UI/ConnectionInfoComponent.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml

[SLVS-1651](https://sonarsource.atlassian.net/browse/SLVS-1651)
[SLVS-1651]: https://sonarsource.atlassian.net/browse/SLVS-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1651 Manage Binding window minor UI fixes

---

build/DownloadDependencies/JarProcessing.targets
src/EmbeddedSonarAnalyzer.props
src/Roslyn.Suppressions/Roslyn.Suppressions/SupportedSuppressionBuilder.g.cs

[SLVS-1720](https://sonarsource.atlassian.net/browse/SLVS-1720)
[SLVS-1720]: https://sonarsource.atlassian.net/browse/SLVS-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1720 Upgrade sonar-dotnet & sonar-dotnet-enterprise to 10.4.0.108396

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingControllerTests.cs
src/ConnectedMode/Binding/IUnintrusiveBindingController.cs
src/Core/Binding/IActiveSolutionBoundTracker.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-1532](https://sonarsource.atlassian.net/browse/SLVS-1532)
[SLVS-1532]: https://sonarsource.atlassian.net/browse/SLVS-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1532 Remove unreachable BindingUpdated code from ActiveSolutionBoundTracker

---

src/ConnectedMode.UnitTests/UI/ConnectedModeServicesTests.cs
src/ConnectedMode/UI/ConnectedModeServices.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/ConnectedMode/UI/ServerSelection/ServerSelectionDialog.xaml
src/ConnectedMode/UI/ServerSelection/ServerSelectionDialog.xaml.cs
src/Core/Telemetry/ITelemetryManager.cs
src/Core/Telemetry/TelemetryLinks.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration/Telemetry/TelemetryManager.cs

[SLVS-1729](https://sonarsource.atlassian.net/browse/SLVS-1729)
[SLVS-1729]: https://sonarsource.atlassian.net/browse/SLVS-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1729 Promote SQC free plan inside the IDE extensions

---

src/ConnectedMode.UnitTests/Binding/GlobalConfigGeneratorTests.cs
src/ConnectedMode/Binding/GlobalConfigGenerator.cs

[SLVS-1641](https://sonarsource.atlassian.net/browse/SLVS-1641)
[SLVS-1641]: https://sonarsource.atlassian.net/browse/SLVS-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1641 Add support of MQR mode to GlobalConfigGenerator

---

SonarLint.VisualStudio.Integration.sln.DotSettings

Fix run Rersharper's code cleanup on save not working in VS by adding file mask to R# options.
Maybe the reviewer can try to see if it works for him as well.

SLVS-1761 Fix run Resharper code cleanup on save not working

---

src/Integration.Vsix.UnitTests/CFamily/CFamilyTestUtility.cs
src/Integration.Vsix.UnitTests/CFamily/CmdBuilderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/CompileAsValueConverterTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/FileConfigTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/LanguageFlagsProviderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/LanguageStandardConverterTests.cs
src/Integration.Vsix/CFamily/VcxProject/CmdBuilder.cs
src/Integration.Vsix/CFamily/VcxProject/CompileAsValueConverter.cs
src/Integration.Vsix/CFamily/VcxProject/FileConfig.cs
src/Integration.Vsix/CFamily/VcxProject/LanguageFlagsProvider.cs
src/Integration.Vsix/CFamily/VcxProject/LanguageStandardConverter.cs

* Only set one language standard for the file
* Always set either `/TC` or `/TP` flag for the file (`/TC` for C and `/TP` for CPP)
* Assume the file is C if `CompileAsC `or if not `CompileAsCpp` and `vcFile.ContentType` is `CCode`
* Assume the file is CPP otherwise
Note: it's entirely possible to have a file with `CompileAsCpp` and `CCode`, `CompileAsC` and `CppCode`, `Default` and `CppHeader` or any other combination of these values by manually setting the overrides in vcxproj. For consistency, `CompileAs` is chosen as the primary indicator for the language, `vcFile.ContentType` is only used if `CompileAs` is not set to `CompileAsCpp`

SLVS-1717 Fix C++ Language standard recognition when a C language standard is also specified

---

src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/packages.lock.json

[SLVS-1774](https://sonarsource.atlassian.net/browse/SLVS-1774)
Downgrade Microsoft.VSSDK.BuildTools nuget package to prevent runtime error that causes services from Integration.Vsix not to be loaded
[SLVS-1774]: https://sonarsource.atlassian.net/browse/SLVS-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1774 Downgrade Microsoft.VSSDK.BuildTools nuget package to 17.5

---

build/CopyDependencies/CopyDependencies.targets
build/DownloadDependencies/CommonProperties.props
build/DownloadDependencies/JarProcessing.targets
src/ConnectedMode/Binding/NonRoslynDummyBindingConfigProvider.cs
src/Core.UnitTests/LanguageTests.cs
src/Core/Language.cs
src/Core/SonarArtefactKeys.cs
src/Core/Telemetry/ITelemetryManager.cs
src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix.UnitTests/SLCore/SLCoreEmbeddedPluginJarLocatorTests.cs
src/Integration.Vsix/Analysis/DisableRuleCommand.cs
src/Integration.Vsix/Analysis/MuteIssueCommand.cs
src/Integration.Vsix/SLCore/SLCoreEmbeddedPluginJarLocator.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/Integration/Telemetry/TelemetryManager.cs
src/SLCore.IntegrationTests/DependencyLocator.cs
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs
src/SLCore/Common/Helpers/LanguageExtensions.cs
src/SonarQube.Client.Tests/Requests/Api/V9_4/GetSonarLintEventStreamTests.cs
src/SonarQube.Client.Tests/SonarQubeService_CreateServerSentEventsSession.cs
src/SonarQube.Client/Models/SonarQubeLanguage.cs

[SLVS-1769](https://sonarsource.atlassian.net/browse/SLVS-1769)
[SLVS-1769]: https://sonarsource.atlassian.net/browse/SLVS-1769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1769 Enable HTML analysis

---

src/IssueViz.UnitTests/FixSuggestion/DiffView/DiffViewServiceTests.cs
src/IssueViz.UnitTests/FixSuggestion/FixSuggestionHandlerTests.cs
src/IssueViz/FixSuggestion/DiffView/ChangeModel.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewService.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewToolWindowPane.cs
src/IssueViz/FixSuggestion/DiffView/FixSuggestionDetails.cs
src/IssueViz/FixSuggestion/FixSuggestionHandler.cs

[SLVS-1745](https://sonarsource.atlassian.net/browse/SLVS-1745)
[SLVS-1745]: https://sonarsource.atlassian.net/browse/SLVS-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1745 Show diff view window for each fix suggestion

---

src/Integration.Vsix/Commands/PackageCommands.vsct

[SLVS-1765](https://sonarsource.atlassian.net/browse/SLVS-1765)
[SLVS-1765]: https://sonarsource.atlassian.net/browse/SLVS-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1765 Rename "Connected Mode" project context menu

---

src/Core/Telemetry/ITelemetryManager.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration/Telemetry/TelemetryManager.cs
src/IssueViz.UnitTests/FixSuggestion/FixSuggestionHandlerTests.cs
src/IssueViz/FixSuggestion/FixSuggestionHandler.cs
src/SLCore.UnitTests/Service/Telemetry/FixSuggestionResolvedParamsTests.cs
src/SLCore/Service/Telemetry/FixSuggestionResolvedParams.cs
src/SLCore/Service/Telemetry/ITelemetrySLCoreService.cs
src/SLCore/Service/Telemetry/Models/FixSuggestionStatus.cs

[SLVS-1771](https://sonarsource.atlassian.net/browse/SLVS-1771)
[SLVS-1771]: https://sonarsource.atlassian.net/browse/SLVS-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1771 Support fix suggestion telemetry

---

src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/Configuration/ISLCoreConstantsProvider.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs
src/SLCore/Service/Lifecycle/Models/ClientConstantInfoDto.cs

[SLVS-1764](https://sonarsource.atlassian.net/browse/SLVS-1764)
Additionally the DTO (ClientConstantsDto) was renamed to match the one in SLCore (ClientConstantInfoDto)
[SLVS-1764]: https://sonarsource.atlassian.net/browse/SLVS-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1764 Stop using ClientConstantInfoDto SLCORE deprecated APIs

---

src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/EmbeddedSonarAnalyzer.props
src/SLCore.IntegrationTests/InitializationTests.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Connection/GetAllProjectsParamsTests.cs
src/SLCore.UnitTests/Service/Connection/GetProjectNamesByKeyParamsTests.cs
src/SLCore.UnitTests/Service/Connection/ListUserOrganizationsParamsTests.cs
src/SLCore.UnitTests/Service/Connection/Models/SonarCloudConnectionConfigurationDtoTests.cs
src/SLCore.UnitTests/Service/Connection/Models/TransientSonarCloudConnectionDtoTests.cs
src/SLCore.UnitTests/Service/Connection/ValidateConnectionParamsTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore.UnitTests/State/AliveConnectionTrackerTests.cs
src/SLCore.UnitTests/State/ServerConnectionsProviderTests.cs
src/SLCore/Service/Connection/ListUserOrganizationsParams.cs
src/SLCore/Service/Connection/Models/ServerConnectionConfigurationDtoBase.cs
src/SLCore/Service/Connection/Models/SonarCloudConnectionConfigurationDto.cs
src/SLCore/Service/Connection/Models/SonarCloudRegion.cs
src/SLCore/Service/Connection/Models/SonarQubeConnectionConfigurationDto.cs
src/SLCore/State/ServerConnectionsProvider.cs

[SLVS-1818](https://sonarsource.atlassian.net/browse/SLVS-1818)
[SLVS-1818]: https://sonarsource.atlassian.net/browse/SLVS-1818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1818 Upgrade SLCore to 10.14.0.80189 and adapt RPC changes for SQC multi-region

---

src/ConnectedMode.UnitTests/Binding/NonRoslynDummyBindingConfigProviderTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/OutOfDateQualityProfileFinderTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileDownloaderTests.cs
src/ConnectedMode/QualityProfiles/OutOfDateQualityProfileFinder.cs
src/ConnectedMode/QualityProfiles/QualityProfileDownloader.cs
src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Core.UnitTests/LanguageProviderTests.cs
src/Core.UnitTests/LanguageTests.cs
src/Core/ILanguageProvider.cs
src/Core/Language.cs
src/Core/LanguageConverter.cs
src/Core/RuleHelpLinkProvider.cs
src/SLCore.Listeners/Implementation/Analysis/RaisedFindingProcessor.cs

[SLVS-1826](https://sonarsource.atlassian.net/browse/SLVS-1826)
Introduce LanguageProvider service to increase testability 
This includes some feedback from [previous PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5987) that has been split
[SLVS-1826]: https://sonarsource.atlassian.net/browse/SLVS-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1826 Introduce LanguageProvider

---

src/Integration.Vsix/SonarLint.vsct

[SLVS-1777](https://sonarsource.atlassian.net/browse/SLVS-1777)
[SLVS-1777]: https://sonarsource.atlassian.net/browse/SLVS-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1777 Allow SonarQube for VS to be shown in the top-level menu

---

src/SLCore.UnitTests/Service/Connection/Models/SonarCloudRegionExtensionsTests.cs
src/SLCore.UnitTests/State/ServerConnectionsProviderTests.cs
src/SLCore/Service/Connection/Models/SonarCloudRegionExtensions.cs
src/SLCore/State/ServerConnectionsProvider.cs

[SLVS-1835](https://sonarsource.atlassian.net/browse/SLVS-1835)
Adapt ServerConnectionsProvider to ensure that the ServerConnectionConfigurationDtoBase models have the region set.
[SLVS-1835]: https://sonarsource.atlassian.net/browse/SLVS-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1835 Adapt ServerConnectionsProvider to ensure region is set

---

src/Core.UnitTests/Analysis/HotspotsPublisherTests.cs
src/Core.UnitTests/Analysis/IssuePublisherTests.cs
src/Core/Analysis/HotspotPublisher.cs
src/Core/Analysis/IFindingsPublisher.cs
src/Core/Analysis/IssuePublisher.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/RaisedFindingProcessorTests.cs
src/SLCore.Listeners/Implementation/Analysis/RaisedFindingProcessor.cs

[SLVS-1752](https://sonarsource.atlassian.net/browse/SLVS-1752)
When an issue is muted on the server, SlCore raises the RaiseFinding event for which the AnalysisId is NULL.
We have to stop ignoring such issues that are raised (they should be suppressed instead: not part of this PR)
[SLVS-1752]: https://sonarsource.atlassian.net/browse/SLVS-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1752 Stop ignoring issues that are raised by SlCore when AnalysisId is null

---

src/ConnectedMode.UnitTests/Transition/MuteIssuesServiceTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/Transition/MuteIssueException.cs
src/ConnectedMode/Transition/MuteIssuesService.cs
src/Core/Transition/IMuteIssuesService.cs
src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
src/Integration.Vsix/Analysis/AnalysisStrings.resx
src/Integration.Vsix/Analysis/MuteIssueCommand.cs

[SLVS-1753](https://sonarsource.atlassian.net/browse/SLVS-1753)
[SLVS-1753]: https://sonarsource.atlassian.net/browse/SLVS-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1753 SLVS-1754 Send mute issue request to SlCore

---

src/Integration/Transition/MuteWindowDialog.xaml
src/Integration/Transition/MuteWindowDialog.xaml.cs

[SLVS-1863](https://sonarsource.atlassian.net/browse/SLVS-1863)
This is caused by the fact that the radio button consumes the click event and it is not bubbled back to the parent event (ListBox.SelectedItem), which does not trigger the update of the ViewModel.SelectedStatusViewModel, to which the IsEnabled property is bound.
[SLVS-1863]: https://sonarsource.atlassian.net/browse/SLVS-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1863 Fix the button “Mark issue as” does not become enabled if you click directly on the RadioButton.

---

src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs
src/Integration.UnitTests/Transition/MuteIssuesWindowServiceTests.cs
src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs
src/Integration.Vsix/Settings/OpenSettingsFileWpfCommand.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/Integration/Transition/MuteIssuesWindowService.cs

[SLVS-1876](https://sonarsource.atlassian.net/browse/SLVS-1876)
Part of SLVS-1708
[SLVS-1876]: https://sonarsource.atlassian.net/browse/SLVS-1876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1876 Mute Issue cleanup unused fields

---

src/SLCore.UnitTests/Listener/Analysis/RaiseFindingToAnalysisIssueConverterTests.cs
src/SLCore/Listener/Analysis/RaiseFindingToAnalysisIssueConverter.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx

[SLVS-1875](https://sonarsource.atlassian.net/browse/SLVS-1875)
The RaiseFindingToAnalysisIssueConverter.CreateAnalysisIssue crashes due to a null reference exception (the TextRangeDto is null [here](https://github.com/SonarSource/sonarlint-visualstudio/blob/c01c118a3ea0d2a53d500fb7aadcab96add98747/src/SLCore/Listener/Analysis/RaiseFindingToAnalysisIssueConverter.cs#L84)), so the RaisedFindingProcessor.PublishFindings  doesn’t publish any issue. The TextRangeDto is null because it's a file level issue.
Added null check and  try/catch inside RaiseFindingToAnalysisIssueConverter.CreateAnalysisIssue so that, if an issue can’t be converted, it doesn’t prevent all the other issues to be published
[SLVS-1875]: https://sonarsource.atlassian.net/browse/SLVS-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

SLVS-1875 JS analysis not working when S1451 is enabled

---

src/SLCore.UnitTests/State/AliveConnectionTrackerTests.cs
src/SLCore/State/AliveConnectionTracker.cs

[SLVS-1787](https://sonarsource.atlassian.net/browse/SLVS-1787)
Calling DidChangeCredentials from inside AliveConnectionTracker.RefreshConnectionList is not needed anymore, since we have a separate event now for when the credentials are changed, which takes care of passing this info to SlCore
[SLVS-1787]: https://sonarsource.atlassian.net/browse/SLVS-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1787 Remove DidChangeCredentials from AliveConnectionTracker.RefreshConnectionList

---

src/SLCore.Listeners.UnitTests/Implementation/ConnectedModeSuggestionListenerTests.cs
src/SLCore.Listeners/Implementation/ConnectedModeSuggestionListener.cs
src/SLCore.UnitTests/Listener/Binding/AssistBindingParamsTests.cs
src/SLCore.UnitTests/Listener/Binding/AssistBindingResponseTests.cs
src/SLCore/Listener/Binding/AssistBindingParams.cs
src/SLCore/Listener/Binding/AssistBindingResponse.cs

[SLVS-1790](https://sonarsource.atlassian.net/browse/SLVS-1790)
[SLVS-1790]: https://sonarsource.atlassian.net/browse/SLVS-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1790 Add `assistBinding` method & related models to IConnectedModeSuggestionListener

---

src/SLCore.Listeners.UnitTests/Implementation/BrowserListenerTests.cs
src/SLCore.Listeners/Implementation/BrowserListener.cs
src/SLCore.UnitTests/Listener/Visualization/OpenUrlInBrowserParamsTests.cs
src/SLCore.UnitTests/Service/Connection/Models/HelpGenerateUserTokenParamsTests.cs
src/SLCore.UnitTests/Service/Connection/Models/HelpGenerateUserTokenResponseTests.cs
src/SLCore/Listener/Visualization/IBrowserListener.cs
src/SLCore/Listener/Visualization/Models/OpenUrlInBrowserParams.cs
src/SLCore/Service/Connection/IConnectionConfigurationSLCoreService.cs
src/SLCore/Service/Connection/Models/HelpGenerateUserTokenParams.cs
src/SLCore/Service/Connection/Models/HelpGenerateUserTokenResponse.cs

Add the RPCs method helpGenerateUserToken and OpenUrlInBrowser, needed for generating a token
[SLVS-1884](https://sonarsource.atlassian.net/browse/SLVS-1884)
[SLVS-1884]: https://sonarsource.atlassian.net/browse/SLVS-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1884 Add RPC method helpGenerateUserToken

---

src/Core.UnitTests/LanguageTests.cs
src/SonarQube.Client.Tests/SonarQubeService_GetQualityProfileAsync.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRoslynExportProfileAsync.cs
src/SonarQube.Client/Api/V9_4/GetSonarLintEventStream.cs
src/SonarQube.Client/Models/SonarQubeLanguage.cs
src/SonarQube.Client/SonarQubeService.cs

[SLVS-1914](https://sonarsource.atlassian.net/browse/SLVS-1914)
`SonarQubeLanguage` should not have a list of all known languages and instead should use the `LanguageProvider`
This targets the branch in which the dependcies between `SonarQube.Client` and `Core` has been swapped
[SLVS-1914]: https://sonarsource.atlassian.net/browse/SLVS-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1914 Remove multiple source of truth for language

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1922](https://sonarsource.atlassian.net/browse/SLVS-1922)
Fix mute Roslyn language issues with comment on SonarQube Cloud fails by updating the SlCore version to the one that includes a fix for this problem.
[SLVS-1922]: https://sonarsource.atlassian.net/browse/SLVS-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1922 Fix mute Roslyn language issues with comment on SQC

---

src/IssueViz.Security.UnitTests/OpenInIdeHotspots/HotspotDetailsDtoToHotspotConverterTests.cs
src/IssueViz.Security/OpenInIdeHotspots/HotspotDetailsDtoToHotspotConverter.cs

[SLVS-1886](https://sonarsource.atlassian.net/browse/SLVS-1886)
The `HotspotDetailsDto.codeSnippet` is nullable and should be treated accordingly.
[SLVS-1886]: https://sonarsource.atlassian.net/browse/SLVS-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1886 Fix "open in ide" button does not work for hotspot when codeSnippet is null.

---

src/ConnectedMode.UnitTests/Binding/Suggestion/SuggestSharedBindingGoldBarTests.cs
src/ConnectedMode.UnitTests/Shared/SharedBindingConfigModelTests.cs
src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode/Binding/Suggestion/SuggestSharedBindingGoldBar.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/ConnectedMode/UI/BindingResult.cs
src/ConnectedMode/UI/ConnectedModeUIManager.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/IssueViz.UnitTests/Editor/Common/CommonTaggerProviderTestsBase.cs

When using the shared binding and the server connection could not be found in the `connections.json`, a message box is shown that informs the user that he has to add it manually (this was a temporary workaround) 
Instead of the message box, the trust connection dialog should be shown
[SLVS-1464](https://sonarsource.atlassian.net/browse/SLVS-1464)
[SLVS-1464]: https://sonarsource.atlassian.net/browse/SLVS-1464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1464 Show trust connection dialog on use shared binding configuration without pre-existing connection 

---

src/ConnectedMode.UnitTests/Binding/Suggestion/UpdateTokenNotificationTests.cs
src/ConnectedMode.UnitTests/UI/ConnectedModeUIManagerTests.cs
src/ConnectedMode/Binding/BindingStrings.Designer.cs
src/ConnectedMode/Binding/BindingStrings.resx
src/ConnectedMode/Binding/Suggestion/IUpdateTokenNotification.cs
src/ConnectedMode/UI/ConnectedModeUIManager.cs
src/SLCore.Listeners.UnitTests/ConnectionConfigurationListenerTests.cs
src/SLCore.Listeners/Implementation/ConnectionConfigurationListener.cs
src/SLCore/Listener/Connection/IConnectionConfigurationListener.cs
src/SLCore/Listener/Connection/InvalidTokenParams.cs

[SLVS-1908](https://sonarsource.atlassian.net/browse/SLVS-1908)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6111) in which the EditCredentialsDialog was introduced, because it depends on it.
[SLVS-1908]: https://sonarsource.atlassian.net/browse/SLVS-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1908 Show warning when token becomes invalid

---

src/Education.UnitTests/XamlGenerator/RuleHelpXamlTranslatorTests.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs

[SLVS-1776](https://sonarsource.atlassian.net/browse/SLVS-1776)
Fix rule description not shown when compliant and non-compliant code snippets are in different tabs, like web:S6811
The fix consists in making sure that the code snippet (compliant/non-compliant) is shown in the tab even without a diff (the behavior seems to be the same on the server side)
[SLVS-1776]: https://sonarsource.atlassian.net/browse/SLVS-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1776 Fix rule description not shown when compliant and non-compliant code snippets are in different tabs

---

src/SLCore.Listeners/Implementation/ConnectedModeSuggestionListener.cs
src/SLCore.UnitTests/Listener/Binding/AssistCreatingConnectionParamsTests.cs
src/SLCore.UnitTests/Listener/Binding/SonarCloudConnectionParamsTests.cs
src/SLCore/Listener/Binding/SonarCloudConnectionParams.cs

[SLVS-1985](https://sonarsource.atlassian.net/browse/SLVS-1985)
Fix RPC parameter name mismatch makes assist connection fail for SQC, US region.
[SLVS-1985]: https://sonarsource.atlassian.net/browse/SLVS-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1985 Fix RPC parameter name mismatch

---

src/SLCore.IntegrationTests/SimpleAnalysisTests.cs

[SLVS-2003](https://sonarsource.atlassian.net/browse/SLVS-2003)
Part of SLVS-1990
[SLVS-2003]: https://sonarsource.atlassian.net/browse/SLVS-2003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2003 Fail integration tests when MSVC is improperly configured instead of silently failing later

---

src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core/Helpers/CommaSeparatedStringArrayConverter.cs

[SLVS-2016](https://sonarsource.atlassian.net/browse/SLVS-2016)
The file exclusions do not work when provided to SlCore, if the pattern contains spaces at the end or beginning. So we should improve our converter to trim the list items, for a better user experience.
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6140) in which integration with SlCore was done for better testability for the reviewer.
[SLVS-2016]: https://sonarsource.atlassian.net/browse/SLVS-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2016 Improve the CommaSeparatedStringArrayConverter to trim the list items.

---

src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs

[SLVS-2028](https://sonarsource.atlassian.net/browse/SLVS-2028)
Part of 1960
[SLVS-2028]: https://sonarsource.atlassian.net/browse/SLVS-2028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2028 Re-generate standalone roslyn configs on startup

---

src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/Configuration/ISLCoreConstantsProvider.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs
src/SLCore/Service/Lifecycle/Models/BackendCapability.cs

[SLVS-2021](https://sonarsource.atlassian.net/browse/SLVS-2021)
[SLVS-2021]: https://sonarsource.atlassian.net/browse/SLVS-2021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2021 Update to SLCore 10.20 release and fix breaking change caused by FeatureFlagsDto being dropped.

---

src/Core.UnitTests/UserRuleSettings/UserSettingsProviderTests.cs
src/Core/Helpers/CommaSeparatedStringArrayConverter.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/IUserSettingsProvider.cs
src/Core/UserRuleSettings/UserSettingsProvider.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogPage.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs
src/SLCore.Listeners.UnitTests/Implementation/GetFileExclusionsListenerTests.cs

[SLVS-2068](https://sonarsource.atlassian.net/browse/SLVS-2068)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6157) in which the UI for file exclusions was added.
[SLVS-2068]: https://sonarsource.atlassian.net/browse/SLVS-2068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2068 Show exclusions stored in settings.json into the UI and save them on disk on OK

---

src/ConnectedMode.UnitTests/Binding/SonarQubeRoslynRuleStatusTests.cs
src/ConnectedMode/Binding/SonarQubeRuleStatus.cs
src/Integration/CSharpVB/GlobalConfigGenerator.cs

After refactoring done in this [commit](https://github.com/SonarSource/sonarlint-visualstudio/commit/2929fab489126c6d6fbd41998f4178ecbd57da53#diff-254a46be7d88f94dac16d260e591af3f15d5ef294b16cae324b11e9ef250621bL63), the following code from the `GlobalConfigGenerator` has been removed and never replaced in a different place:
`var severityText = rule.IsActive ? GetActionText(GetVsSeverity(rule)) : inactiveRuleActionText;`
[SLVS-2074](https://sonarsource.atlassian.net/browse/SLVS-2074)
[SLVS-2074]: https://sonarsource.atlassian.net/browse/SLVS-2074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2074 Fix inactive rules are no longer disabled on connected mode

---

src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Integration.Vsix/Settings/FileExclusions/AddExclusionDialog.xaml

[SLVS-2076](https://sonarsource.atlassian.net/browse/SLVS-2076)
- The "AddExclusionDialog" changes background color on dark mode. The Options page does not change its color, so we should keep it consistent
- Fix exception when normalizing paths and path contains invalid characters
[SLVS-2076]: https://sonarsource.atlassian.net/browse/SLVS-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2076 File exclusion improvements

---

src/Core/UserRuleSettings/IUserSettingsProvider.cs
src/Core/UserRuleSettings/IUserSettingsStorage.cs
src/Integration.UnitTests/UserSettingsConfiguration/GlobalSettingsStorageTest.cs
src/Integration.UnitTests/UserSettingsConfiguration/SolutionSettingsStorageTest.cs
src/Integration.UnitTests/UserSettingsConfiguration/UserSettingsProviderTests.cs
src/Integration.Vsix.UnitTests/Settings/OpenSettingsFileWpfCommandTests.cs
src/Integration.Vsix.UnitTests/Settings/SolutionSettings/AnalysisPropertiesViewModelTests.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs
src/Integration.Vsix/Settings/OpenSettingsFileWpfCommand.cs
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesViewModel.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml.cs
src/Integration/UserSettingsConfiguration/GlobalSettingsStorage.cs
src/Integration/UserSettingsConfiguration/SolutionSettingsStorage.cs
src/Integration/UserSettingsConfiguration/UserSettingsProvider.cs

[SLVS-2114](https://sonarsource.atlassian.net/browse/SLVS-2114)
Introduced classes for storing the global and solution settings and move logic from the UserSettingsProvider into corresponding classes.
[SLVS-2114]: https://sonarsource.atlassian.net/browse/SLVS-2114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2114 Introduced classes for storing the global and solution settings

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/release.yaml

[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-8073 Migrate public repositories workflows to large runners

---

src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore/ISLCoreInstanceHandle.cs

[SLVS-2144](https://sonarsource.atlassian.net/browse/SLVS-2144)
Fix issues can not be muted in some cases the first time a solution is opened by making sure that the `ActiveSolutionBoundTracker` is initialized before updating the configuration scope for the current solution.
[SLVS-2144]: https://sonarsource.atlassian.net/browse/SLVS-2144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2144 Fix issues can not be muted in some cases the first time a solution is opened

---

src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/TestInfrastructure/NSubstituteHelpers.cs

[SLVS-1996](https://sonarsource.atlassian.net/browse/SLVS-1996)
[SLVS-1996]: https://sonarsource.atlassian.net/browse/SLVS-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1996 Add extension method as a workaround to avoid await warning CS4014 for NSubstitute assertions

---

src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSourceProvider.cs

[SLVS-2347](https://sonarsource.atlassian.net/browse/SLVS-2347)
The application of the QuickFix was based on an older Snapshot, which resulted to be falsely detected as not applicable when there were changes on the current document.
[SLVS-2347]: https://sonarsource.atlassian.net/browse/SLVS-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2347 Quick fix cannot be reapplied after same issue re-appearance

---

src/Core.UnitTests/SourceFileTests.cs
src/Core/DocumentEvents.cs
src/Core/SourceFile.cs
src/Integration.Vsix.UnitTests/Analysis/DocumentEventsHandlerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/SLCore.UnitTests/Common/Helpers/ClientFileDtoFactoryTests.cs

Revert "SLVS-2326 Don't send file content for flushed files to SLCore (https://github.com/SonarSource/sonarlint-visualstudio/pull/6298)"
This reverts commit https://github.com/SonarSource/sonarlint-visualstudio/commit/53053c118e6de17beda6c93a6023eef03b01ce5b.
Revert "SLVS-2348 Fix: stop assuming encoding when it is not known (https://github.com/SonarSource/sonarlint-visualstudio/pull/6310)"
This reverts commit https://github.com/SonarSource/sonarlint-visualstudio/commit/27cf058c13732e95fdc4de44ce1e210030f5ee91.
[SLVS-2354](https://sonarsource.atlassian.net/browse/SLVS-2354)
Part of SLVS-2314
[SLVS-2354]: https://sonarsource.atlassian.net/browse/SLVS-2354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2354 Send file content to SLCore

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/ViewModels/ChangeHotspotStatusViewModelTest.cs
src/IssueViz.Security.UnitTests/ReviewStatus/ChangeStatusViewModelTest.cs
src/IssueViz.Security.UnitTests/ReviewStatus/StatusViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/ChangeHotspotStatusViewModel.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz.Security/ReviewStatus/ChangeStatusViewModel.cs
src/IssueViz.Security/ReviewStatus/ChangeStatusWindow.xaml
src/IssueViz.Security/ReviewStatus/ChangeStatusWindow.xaml.cs
src/IssueViz.Security/ReviewStatus/IChangeStatusViewModel.cs
src/IssueViz.Security/ReviewStatus/IStatusViewModel.cs
src/IssueViz.Security/ReviewStatus/StatusViewModel.cs

[SLVS-2395](https://sonarsource.atlassian.net/browse/SLVS-2395)
Extend the `ChangeStatusWindow` to allow showing a comment and to make the comment mandatory depending on configured statuses.
This targets the https://github.com/SonarSource/sonarlint-visualstudio/pull/6328 in which the `ChangeStatusWindow` has been added.
[SLVS-2395]: https://sonarsource.atlassian.net/browse/SLVS-2395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2395 Extend the ChangeStatusWindow to allow showing a comment 

---

src/Core/Analysis/IAnalysisIssue.cs
src/IssueViz.Security.UnitTests/DependencyRisks/ChangeDependencyRiskStatusViewModelTest.cs
src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRiskViewModelTest.cs
src/IssueViz.Security/DependencyRisks/ChangeDependencyRiskStatusViewModel.cs
src/IssueViz.Security/DependencyRisks/DependencyRiskViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz.Security/SharedUI/SharedResources.xaml

[SLVS-2375](https://sonarsource.atlassian.net/browse/SLVS-2375)
Add Change Status menu item command and show the `ChangeStatusWindow` on click. Make sure comment field is shown and that it is mandatory for `Accepted` and `Safe` statuses.
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6330) in which the `ChangeStatusWindow` has been adapted to show comment and make it mandatory for some statuses.
**DO NOT MERGE** this PR until the target PR is merged into the feature branch
[SLVS-2375]: https://sonarsource.atlassian.net/browse/SLVS-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2375 Add Change Status menu item command

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

[SLVS-2397](https://sonarsource.atlassian.net/browse/SLVS-2397)
The behavior is not easy to reproduce, but it can happen when there is a race condition between the context menu being shown and the row in the DataGrid being selected. If the first action happens first, then the exception is thrown and the UI crashes.
[SLVS-2397]: https://sonarsource.atlassian.net/browse/SLVS-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2397 Fix exception thrown when trying to review hotspot when no hotspot is selected

---

src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalysisConfigurationProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalysisProfilesProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalyzerProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/SonarLintXmlProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/RoslynProjectCompilationProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/RoslynAnalyzerServer.UnitTests.csproj
src/RoslynAnalyzerServer.UnitTests/packages.lock.json
src/RoslynAnalyzerServer/Analysis/Configuration/IRoslynAnalysisProfilesProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/IRoslynAnalyzerLoader.cs
src/RoslynAnalyzerServer/Analysis/Configuration/IRoslynAnalyzerProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalysisConfigurationProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalysisProfilesProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalyzerLoader.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalyzerProvider.cs
src/RoslynAnalyzerServer/Analysis/RoslynAnalysisConfiguration.cs
src/RoslynAnalyzerServer/Resources.Designer.cs
src/RoslynAnalyzerServer/Resources.resx

[SLVS-2495](https://sonarsource.atlassian.net/browse/SLVS-2495)
Part of SLVS-2406
[SLVS-2495]: https://sonarsource.atlassian.net/browse/SLVS-2495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2495 Load CodeFixProvider-s from analyzer assemblies

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/EmbeddedAnalyzers/EmbeddedDotnetAnalyzersLocatorTests.cs
src/Integration.Vsix/EmbeddedAnalyzers/EmbeddedDotnetAnalyzersLocator.cs
src/RoslynAnalyzerServer.IntegrationTests/Http/Helper/HttpServerStarter.cs
src/RoslynAnalyzerServer.IntegrationTests/Http/RoslynAnalysisHttpServerTest.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalysisConfigurationProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalyzerProviderTests.cs
src/RoslynAnalyzerServer.UnitTests/RoslynAnalysisServiceTests.cs
src/RoslynAnalyzerServer/Analysis/Configuration/IEmbeddedRoslynAnalyzersLocator.cs
src/RoslynAnalyzerServer/Analysis/Configuration/IRoslynAnalysisConfigurationProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/IRoslynAnalyzerProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalysisConfigurationProvider.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalyzerProvider.cs
src/RoslynAnalyzerServer/Http/Models/AnalyzerInfoDto.cs
src/RoslynAnalyzerServer/Http/RoslynAnalysisHttpServer.cs
src/RoslynAnalyzerServer/IRoslynAnalysisService.cs
src/RoslynAnalyzerServer/RoslynAnalysisService.cs

[SLVS-2500](https://sonarsource.atlassian.net/browse/SLVS-2500)
[SLVS-2500]: https://sonarsource.atlassian.net/browse/SLVS-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2500 Respect NET repackaging

---

src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaskExecutorWithDebounceFactoryTest.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaskExecutorWithDebounceTest.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TaskExecutorWithDebounce.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

[SLVS-2430](https://sonarsource.atlassian.net/browse/SLVS-2430)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6401) in which `DocumentUpdated` event was introduced
[SLVS-2430]: https://sonarsource.atlassian.net/browse/SLVS-2430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2430 Trigger analysis on pressed key with debounce

---

src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRiskImpactSeverityToImageSourceConverterTest.cs
src/IssueViz.Security.UnitTests/ReportView/EnumToImageSourceConverterTest.cs
src/IssueViz.Security/DependencyRisks/DependencyRiskImpactSeverityToImageSourceConverter.cs
src/IssueViz.Security/ReportView/EnumToImageSourceConverter.cs
src/IssueViz.Security/ReportView/IResourceFinder.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml

[SLVS-2570](https://sonarsource.atlassian.net/browse/SLVS-2570)
Part of 
[SLVS-2517](https://sonarsource.atlassian.net/browse/SLVS-2517)
[SLVS-2517]: https://sonarsource.atlassian.net/browse/SLVS-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2570]: https://sonarsource.atlassian.net/browse/SLVS-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2570 Adapt converter to be able to search for any DarawingImage

---

src/IssueViz.Security.UnitTests/ReportView/Hotspots/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/ReportView/Hotspots/HotspotViewModel.cs
src/IssueViz.Security/ReportView/IIssueViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs

[SLVS-2521](https://sonarsource.atlassian.net/browse/SLVS-2521)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6421) in which the double click event has been added to the `TreeViewItem`
[SLVS-2521]: https://sonarsource.atlassian.net/browse/SLVS-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2521 Implement navigation to the hotspot location

---

src/IssueViz.Security.UnitTests/ReportView/Hotspots/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/ReportView/Hotspots/HotspotsReportViewModelTest.cs
src/IssueViz.Security/ReportView/Hotspots/HotspotViewModel.cs
src/IssueViz.Security/ReportView/Hotspots/HotspotsReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

[SLVS-2522](https://sonarsource.atlassian.net/browse/SLVS-2522)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6423) in which the `ReportViewModel` was refactored to prevent crowding it with lots of logic.
The logic is mostly a copy-paste from `HotspotsControlViewModel` and its tests. Nothing new should have been added, just minor UI changes were done.
[SLVS-2522]: https://sonarsource.atlassian.net/browse/SLVS-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2522 Add context menu for hotspot

---

src/Core/Telemetry/ITelemetryManager.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration/Telemetry/TelemetryManager.cs
src/IssueViz.Security.UnitTests/ReportView/Hotspots/HotspotsReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/ReportView/Hotspots/HotspotsReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/SLCore/Service/Telemetry/ITelemetrySLCoreService.cs

[SLVS-2523](https://sonarsource.atlassian.net/browse/SLVS-2523)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6424) in which show in browser command has been implemented, because telemetry is also added for it 
[SLVS-2523]: https://sonarsource.atlassian.net/browse/SLVS-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2523 Implement telemetry for interacting with hotspots
