src/Education.UnitTests/EducationTests.cs
src/Education/IEducation.cs
src/Education/Resources.Designer.cs
src/Education/Resources.resx

Handle unknown rules in IEducation.ShowRuleHelp

---

src/Education.UnitTests/EducationTests.cs
src/Education/IEducation.cs

Lazily fetch the tool window on the UI thread

---

src/Education/Commands/RuleHelpUserControl.xaml

Tweak document settings to improve appearance and readability

---

src/Education/Commands/RuleHelpUserControl.xaml

Make the images slightly less blurry.

---

src/Core/IEducation.cs
src/Education/Education.cs
src/Education/ErrorList/SonarErrorListEventProcessor.cs
src/Education/ErrorList/SonarErrorListEventProcessorProvider.cs
src/IssueViz.UnitTests/Helpers/ShowInBrowserServiceTests.cs
src/IssueViz.UnitTests/IssueVisualizationControl/ViewModelCommands/NavigateToRuleDescriptionCommandTests.cs
src/IssueViz/Helpers/ShowInBrowserService.cs
src/IssueViz/IssueVisualizationControl/ViewModels/Commands/NavigateToRuleDescriptionCommand.cs

Change tooltip help navigation to use IEducation

---

src/Education/Resources.Designer.cs
src/Education/Resources.resx
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz/Resources.Designer.cs
src/IssueViz/Resources.resx

... from "SonarLint"
Fixes #3656

Change tool window caption prefix to Sonar

---

src/Core.UnitTests/LanguageTests.cs
src/Core/Language.cs
src/Core/SonarArtefactKeys.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingProcessImpl.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3663

Add secrets to languages

---

src/Core/SonarArtefactKeys.cs
src/Integration.UnitTests/Connection/MinimumSupportedSonarQubePluginTests.cs
src/Integration/Connection/MinimumSupportedSonarQubePlugin.cs

Part 1 & 2 of https://github.com/SonarSource/sonarlint-visualstudio/issues/3673

Add Secrets to MinimumSupportedSonarQubePlugin.

---

src/Integration/Binding/BindingController.cs

part 3 of https://github.com/SonarSource/sonarlint-visualstudio/issues/3673

Add secrets to bindingController.cs

---

src/CloudSecrets.UnitTests/SecretsAnalyzerTests.cs
src/CloudSecrets/SecretsAnalyzer.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3688

Use quality profile

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionManagerTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionManager.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs

Initialize SSESession if already in connected mode when loaded

---

src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs

Prep for [#3678](https://github.com/SonarSource/sonarlint-visualstudio/issues/3678)

Always set analysis info when in connected mode

---

src/IssueViz.Security.UnitTests/Taint/TaintStoreTests.cs
src/IssueViz.Security/Taint/TaintStore.cs

Fixes [#3678](https://github.com/SonarSource/sonarlint-visualstudio/issues/3678)

Add methods Add/Remove to ITaintStore

---

src/ConnectedMode.UnitTests/BranchMatcherTests.cs
src/ConnectedMode/BranchMatcher.cs
src/Core/IServerBranchProvider.cs

Return Main branch name for headless branches

---

src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix/Analysis/DisableRuleCommand.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3691

Update disable rule command for secrets

---

src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs

Fixes [#3683](https://github.com/SonarSource/sonarlint-visualstudio/issues/3683)

Fix the displayed taint branch name

---

src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTagTooltipProviderTests.cs
src/IssueViz.UnitTests/Editor/ErrorTagging/SonarErrorTagUnitTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagTooltipProvider.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagger.cs
src/IssueViz/Editor/ErrorTagging/SonarErrorTag.cs

Add IErrorTag implementation that lazily-creates tooltips

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Update embedded CFamily analyzer to 6.42.0.61084

---

src/Integration.UnitTests/Helpers/AbsoluteFilePathLocatorTests.cs
src/Integration/Helpers/AbsoluteFilePathLocator.cs

Part of [#3705](https://github.com/SonarSource/sonarlint-visualstudio/issues/3705)

Fix AbsoluteFilePathLocator to handle forward slashes

---

build/ProcessJarFiles/CommonProperties.props
src/CloudSecrets/CloudSecrets.csproj
src/EmbeddedSonarAnalyzer.props

Modify rule preprocessor to handle secrets jar

---

src/IssueViz.Security.UnitTests/Taint/ServerSentEvents/TaintServerEventsListenerTests.cs
src/IssueViz.Security/Taint/ServerSentEvents/TaintServerEventsListener.cs

Fixes [#3715](https://github.com/SonarSource/sonarlint-visualstudio/issues/3715)

Handle exceptions in receiving taint events

---

src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTagTooltipProviderTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagTooltipProvider.cs

Fix styling of tooltip hyperlinks

---

src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTagTooltipProviderTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagTooltipProvider.cs

Change tooltip command handling to use NavigateUri event

---

src/IssueViz/Editor/IIssueSpanCalculator.cs

Calculate span hash for the given range

---

src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs

Update Taint window caption whenever the list changes

---

src/EmbeddedSonarAnalyzer.props
src/EmbeddedVsix.UnitTests/TypeScriptRuleDefinitions_SanityChecks.cs

Update embedded JS/TS analyzer to 10.0.1.20755 

---

src/Education/Commands/RuleHelpUserControl.xaml
src/Education/Education.csproj
src/Education/UI/Readme.txt
src/Education/UI/SeverityImages.xaml
src/Education/UI/TypeImages.xaml
src/Education/XamlGenerator/RuleHelpXamlBuilder.cs
src/Education/XamlGenerator/SubTitleImageInfo.cs

Fix svg images

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration/Binding/BindingProcessImpl.cs

Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/3680

fix BindingProcessingImplTests a little bit

---

src/Core/Suppressions/IIssuesFilter.cs
src/Integration.UnitTests/Suppression/IssuesFilterTests.cs
src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs
src/Integration/Suppression/IssuesFilter.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3778

Change code so that suppressed issues will no longer be thrown away-

---

src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTaggerTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagger.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3782

Change errorTagger to filter suppressed issues-

---

build/tools/ExtractRuleDescFromJson/RuleDescExtractor.cs
src/Rules.UnitTests/RuleHelpTests.cs
src/Rules/IRuleInfo.cs

 Add new fields to IRuleInfo

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionFactoryTests.cs
src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionFactory.cs
src/ConnectedMode/Suppressions/IIssueServerEventSourcePublisher.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3788

Add issueEventSourcePublisher

---

src/ConnectedMode/Suppressions/IIssueServerEventSource.cs
src/ConnectedMode/Suppressions/IssueServerEventChannel.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3793

Add eventsource and eventchannel

---

src/ConnectedMode.UnitTests/Suppressions/IssueServerEventsListenerTests.cs
src/ConnectedMode/Suppressions/IssueServerEventsListener.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3795

Add IssueServerEventsListener

---

src/Education.UnitTests/EducationTests.cs
src/Education.UnitTests/RuleHelpXamlBuilderTests.cs
src/Education.UnitTests/RuleHelpXamlTranslatorTests.cs
src/Education/Education.cs
src/Education/XamlGenerator/RuleHelpXamlBuilder.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs
src/Education/XamlGenerator/SimpleRuleHelpXamlBuilder.cs
src/Education/XamlGenerator/XamlOutputElementInfo.cs
src/Education/XamlGenerator/XmlWriterExtensions.cs

Seperate xaml translation and layout generation 

---

src/ConnectedMode/Suppressions/IServerIssuesStore.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs

Prep for #3831, #3832, #3883 and #3884

Add interfaces for server issue store and updater

---

src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3821

Unhook AnalysisConfigMonitor from suppression updates.

---

src/Rules.UnitTests/RuleHelpTests.cs
src/Rules/IRuleInfo.cs

Make context singular in IRuleInfo 

---

src/ConnectedMode.UnitTests/ServerQueryInfoProviderTests.cs
src/ConnectedMode/ServerQueryInfoProvider.cs

Add helper class to simplify making branch-aware web calls

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/ConnectedMode/Suppressions/IServerIssuesStore.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs
src/SonarQube.Client/Models/SonarQubeIssue.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3832

Implement ServerIssueStoreWriter

---

src/Core.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
src/SonarQube.Client/Api/V5_50/GetRulesRequest.cs
src/SonarQube.Client/Models/SonarQubeContext.cs
src/SonarQube.Client/Models/SonarQubeDescriptionSection.cs
src/SonarQube.Client/Models/SonarQubeRule.cs

Add rich rule description fields to SQ Client 

---

src/ConnectedMode.UnitTests/BoundSolutionUpdateHandlerTests.cs
src/ConnectedMode/BoundSolutionUpdateHandler.cs
src/ConnectedMode/Suppressions/ServerSuppressionsChangedHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3846

Add BoundSolutionUpdateHandler

---

src/ConnectedMode.UnitTests/Suppressions/TimedUpdateHandlerTests.cs
src/ConnectedMode/Suppressions/TimedUpdateHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3845

Add timedUpdateHandler

---

src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3875

Remove ISonarQubeIssueProvider from RoslynSettingsSynchronizer

---

src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/TestHelper.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3868

Change RoslynSettingsFileSynchronizer to only save suppressed issues

---

src/ConnectedMode/ConnectedModePackage.cs

Trigger a suppressions update when the package loads

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/ServerSentEvents/Issue/IssueServerEventsListener.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs
src/SonarQube.Client.Tests/Models/ServerSentEvents/ClientContract/IssueChangedServerEventTests.cs
src/SonarQube.Client/Models/ServerSentEvents/ClientContract/IIssueChangedServerEvent.cs

Add suppression logging to event listener and store UpdateIssue

---

src/ConnectedMode.UnitTests/Suppressions/ClientSuppressionSynchronizerTests.cs
src/ConnectedMode/Suppressions/ClientSuppressionSynchronizer.cs
src/ConnectedMode/Suppressions/IClientSuppressionSynchronizer.cs
src/ConnectedMode/Suppressions/IssuesFilter.cs

Add file changed event to client suppressions synchronizer

---

src/Core.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/SonarQube.Client.Tests/SonarQubeService_ExtensionMethods.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRuleByKeyAsync.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
src/SonarQube.Client/Api/V5_50/GetRulesRequest.cs
src/SonarQube.Client/Models/SonarQubeRule.cs

Add name and tags to SQ Client 

---

src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
src/IssueViz.Security/IssuesStore/AggregatingIssueLocationStoreAdapter.cs
src/IssueViz.UnitTests/Editor/LocationTagging/IssueLocationStoreAggregatorTests.cs
src/IssueViz/Editor/LocationTagging/IIssueLocationStore.cs
src/IssueViz/Editor/LocationTagging/IssueLocationStoreAggregator.cs

- fixed up existing implementations
- added tests
Fixes #3898 and #3900

Add IIssueLocationStore.RefreshOnBufferChanged

---

build/tools/ExtractRuleDescFromJson/RuleDescExtractor.cs
src/Education.UnitTests/Layout/Logical/RuleInfoTranslatorTests.cs
src/Education.UnitTests/XamlGeneratorHelperTests.cs
src/Rules.UnitTests/RuleHelpTests.cs
src/Rules/IRuleInfo.cs
src/Rules/ServerRuleMetadataProvider.cs

Add htmlnote to IRuleInfo 

---

src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs
src/SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestTests.cs
src/SonarQube.Client.Tests/Requests/Api/V7_20/GetIssuesRequestWrapperTests.cs
src/SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs
src/SonarQube.Client/Api/IGetIssuesRequest.cs
src/SonarQube.Client/Api/V5_10/GetIssuesRequest.cs
src/SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
src/SonarQube.Client/Api/V7_20/GetIssuesRequestWrapper.cs
src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/SonarQubeService.cs

Pass issue keys to api/issues/search

---

src/Core.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/Core.UnitTests/CSharpVB/NuGetPackageInfoGeneratorTests.cs
src/Core.UnitTests/CSharpVB/RoslynPluginRuleKeyExtensionsTests.cs
src/Core.UnitTests/CSharpVB/RuleSetGeneratorTests.cs
src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/Rules.UnitTests/RuleExtensionTests.cs
src/Rules.UnitTests/ServerRuleMetadataProviderTests.cs
src/Rules/ServerRuleMetadataProvider.cs
src/SonarQube.Client.Tests/SonarQubeService_ExtensionMethods.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRuleByKeyAsync.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
src/SonarQube.Client/Api/V5_50/GetRulesRequest.cs
src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/Models/SonarQubeRule.cs
src/SonarQube.Client/SonarQubeService.cs

Add htmlNote to SQ Client 

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs

Handle adding existing issues to the store

---

src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSource_IssueLocationStoreTests.cs
src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs

Raise single file changed event

---

src/ConnectedMode.UnitTests/ServerSentEvents/Issue/IssueServerEventsListenerTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/ServerSentEvents/Issue/IssueServerEventsListener.cs
src/ConnectedMode/Suppressions/IServerIssuesStore.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs

Fixes [#3919](https://github.com/SonarSource/sonarlint-visualstudio/issues/3919)

Fetch missing suppressions coming from SSE

---

src/ConnectedMode.UnitTests/Suppressions/LocalSuppressionsChangedHandlerTests.cs
src/ConnectedMode.UnitTests/Suppressions/ServerSuppressionsChangedHandlerTests.cs
src/ConnectedMode/ConnectedModePackage.cs
src/ConnectedMode/Suppressions/LocalSuppressionsChangedHandler.cs

Trigger UI update when locally-suppressed issues change

---

src/ConnectedMode.UnitTests/ServerSentEvents/Issue/IssueServerEventsListenerTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/ServerSentEvents/Issue/IssueServerEventsListener.cs

Fixes [#3895](https://github.com/SonarSource/sonarlint-visualstudio/issues/3895)

Add branch-awareness to IssueServerEventsListener

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/Suppressions/IServerIssuesStore.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs

Update issues in batch

---

src/ConnectedMode.UnitTests/ServerSentEvents/Issue/IssueServerEventsListenerTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/ServerSentEvents/Issue/IssueServerEventsListener.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs
src/IssueViz.Security/IssuesStore/AggregatingIssueLocationStoreAdapter.cs
src/SonarQube.Client.Tests/SonarQubeService_GetSuppressedIssuesAsync.cs

No product code changes.
Four test assertions changed (using code fixes)
See https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&branch=branch-issues2&id=sonarlint-visualstudio

Fix new code smells in branch-issues2

---

src/EmbeddedSonarAnalyzer.props

Update embedded CFamily analyzer to 6.43.0.61486

---

src/Education.UnitTests/EducationTests.cs
src/Education/Education.cs

Tie EducationService to wrapper 

---

src/Rules.UnitTests/HtmlXmlCompatibilityHelperTests.cs
src/Rules/HtmlXmlCompatibilityHelper.cs

Null html Note causing ServerMetadataProvider to fail

---

src/ConnectedMode.UnitTests/Suppressions/ClientSuppressionSynchronizerTests.cs
src/ConnectedMode.UnitTests/Suppressions/IssuesFilterTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressedIssueMatcherTests.cs
src/ConnectedMode/Suppressions/ClientSuppressionSynchronizer.cs
src/ConnectedMode/Suppressions/IssuesFilter.cs
src/ConnectedMode/Suppressions/ServerSuppressionsChangedHandler.cs
src/ConnectedMode/Suppressions/SuppressedIssueMatcher.cs
src/Core/Suppressions/IFilterableIssue.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration.Vsix/Analysis/IssueConsumerFactory_IssueHandler.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3783

Rename namespace from suppression to suppressions in core.

---

src/Roslyn.Suppressions/Roslyn.Suppressions/SupportedSuppressionBuilder.tt
src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressorCodeGen.targets
src/Roslyn.Suppressions/Roslyn.Suppressions/packages.lock.json

Regenerate T4 template on build

---

src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
src/IssueViz/IssueVisualizationControl/ViewModels/Commands/NavigateToRuleDescriptionCommand.cs

Taint should trigger education service 

---

src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs

Fixes [#3942](https://github.com/SonarSource/sonarlint-visualstudio/issues/3942)

Refresh taint list when suppressions change

---

src/Integration.UnitTests/Exclusions/ExclusionSettingsStorageTests.cs
src/Integration/Exclusions/ExclusionSettingsStorage.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/RoslynSettingsFileStorageTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs

Format json when serializing

---

src/ConnectedMode.UnitTests/ServerSentEvents/Issue/IssueServerEventsListenerTests.cs
src/ConnectedMode/ServerSentEvents/Issue/IssueServerEventsListener.cs
src/IssueViz.Security.UnitTests/Taint/ServerSentEvents/TaintServerEventsListenerTests.cs
src/IssueViz.Security/Taint/ServerSentEvents/TaintServerEventsListener.cs

Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3946

Handle dispose exception when closing VS

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionFactoryTests.cs
src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionManagerTests.cs
src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionFactory.cs
src/ConnectedMode/ServerSentEvents/SSESessionManager.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/3718

Restart SSESession when failure occurs

---

src/ConnectedMode/Suppressions/SuppressedIssueMatcher.cs
src/Core.UnitTests/Helpers/PathHelperTests.cs
src/Core/Helpers/PathHelper.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/SuppressionCheckerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionChecker.cs

- renamed to IsServerFileMatch
Prep for #3997

Move IsFileMatch to PathHelper

---

src/Core.UnitTests/LanguageTests.cs
src/Core/Language.cs
src/Rules/RuleMetaDataProvider.cs

Add secrets to repo key mapping

---

src/Rules/ServerRuleMetadataProvider.cs
src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_GetRulesAsync.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/IGetRulesRequest.cs
src/SonarQube.Client/Api/V5_50/GetRulesRequest.cs
src/SonarQube.Client/Api/V9_5/GetRulesWithDescriptionSectionsRequest.cs
src/SonarQube.Client/Api/V9_6/GetRulesWithEducationPrinciplesRequest.cs

Support DescriptionSections and EducationPrinciples in SQ Client with versioning

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
src/SonarQube.Client/Api/V8_6/GetTaintVulnerabilitiesRequest.cs
src/SonarQube.Client/Api/V9_6/GetIssuesWithContextRequest.cs
src/SonarQube.Client/Api/V9_6/GetTaintVulnerabilitiesWithContextRequest.cs
src/SonarQube.Client/Models/SonarQubeIssue.cs

Get ContextKey from SQ Client 

---

src/Core.UnitTests/CSharpVB/SonarLintConfigGeneratorTests.cs
src/Core/CSharpVB/ISonarLintConfigGenerator.cs
src/Core/CSharpVB/SonarLintConfigGenerator.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/Integration.UnitTests/Exclusions/AnalyzableFileIndicatorTests.cs
src/Integration/Binding/CSharpVBBindingConfigProvider.cs
src/SonarQube.Client.Tests/Models/ServerExclusionsTests.cs
src/SonarQube.Client.Tests/Requests/Api/V7_20/GetExclusionsRequestTests.cs
src/SonarQube.Client/Models/ServerExclusions.cs

Fixes [#3093](https://github.com/SonarSource/sonarlint-visualstudio/issues/3093)

Write server inclusions/exclusions to SonarLint.xml

---

build/tools/ExtractRuleDescFromJson/ExtractRuleDescFromJson.csproj
src/CFamily/CMake/MacroEvaluationService.cs
src/Core/GlobPatternMatcher.cs
src/Core/RegexConstants.cs
src/Integration.Vsix/CFamily/VcxProject/CmdBuilder.cs
src/Integration/Connection/BasicAuthenticationCredentialsValidator.cs
src/Integration/LocalServices/TestProjectIndicators/ProjectNameTestProjectIndicator.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressionExecutionContext.cs
src/Rules/HtmlXmlCompatibilityHelper.cs
src/SonarQube.Client/Api/V6_30/GetPluginsRequest.cs
src/SonarQube.Client/ChecksumCalculator.cs
src/TypeScript/EslintBridgeClient/EslintBridgeProcess.cs

Add timeouts to regular expressions

---

src/Core/Analysis/AnalysisIssue.cs
src/Core/Analysis/IAnalysisIssue.cs
src/IssueViz.Security.UnitTests/Hotspots/Models/HotspotTests.cs
src/IssueViz.Security.UnitTests/Taint/Models/TaintIssueTests.cs
src/IssueViz.Security/Hotspots/Models/IHotspot.cs
src/IssueViz.Security/Taint/Models/ITaintIssue.cs
src/TestInfrastructure/DummyAnalysisIssue.cs

Add ContextKey to AnalysisIssueBase 

---

src/Education/Commands/RuleHelpToolWindow.cs
src/Education/Commands/RuleHelpUserControl.xaml.cs
src/Education/EducationPackage.cs
src/Education/Resources.Designer.cs
src/Education/Resources.resx

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4043

Handle relative URIs in Rule descriptions.

---

src/Education/XamlGenerator/CustomTextMarkupParser.cs

Add timeout to RegEx

---

src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
src/IssueViz.UnitTests/IssueVisualizationControl/ViewModelCommands/NavigateToRuleDescriptionCommandTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagTooltipProvider.cs
src/IssueViz/IssueVisualizationControl/ViewModels/Commands/NavigateToRuleDescriptionCommand.cs

When you click the ruleID from tooltip it crashes

---

src/IssueViz.UnitTests/IssueVisualizationControl/IssueVisualizationViewModelTests.cs
src/IssueViz/IssueVisualizationControl/IssueVisualizationControl.xaml
src/IssueViz/IssueVisualizationControl/ViewModels/IssueVisualizationViewModel.cs

Add context key to issue visualization screen links

---

src/IssueViz.Security.UnitTests/Taint/TaintStoreTests.cs
src/IssueViz.Security/Taint/TaintStore.cs

Trigger taint issues changed unconditionally

---

src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeHttpHelperTests.cs
src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs
src/TypeScript/EslintBridgeClient/EslintBridgeHttpHelper.cs
src/TypeScript/EslintBridgeClient/TypeScriptEslintBridgeClient.cs

Extract methods from EslintBridgeClient 

---

src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
src/TypeScript/EslintBridgeClient/Contract/CssAnalysisRequest.cs
src/TypeScript/EslintBridgeClient/Contract/InitLinterRequest.cs
src/TypeScript/EslintBridgeClient/Contract/JsTsAnalysisRequest.cs
src/TypeScript/EslintBridgeClient/Contract/Rule.cs
src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs

Create CSS Analysis Request 

---

src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs
src/TypeScript.UnitTests/EslintBridgeClient/EslintBridgeClientTests.cs
src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs
src/TypeScript/EslintBridgeClient/Contract/CssAnalysisResponse.cs
src/TypeScript/EslintBridgeClient/Contract/Issue.cs
src/TypeScript/EslintBridgeClient/Contract/JsTsAnalysisResponse.cs
src/TypeScript/EslintBridgeClient/EslintBridgeClient.cs

Create CSS analysis Response 

---

build/ProcessJarFiles/CommonProperties.props

Embed CSS rule descriptions 

---

src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
src/TypeScript/Analyzer/AnalyzerBase.cs
src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
src/TypeScript/Analyzer/TypeScriptAnalyzer.cs

Refactor js and ts EslintBridgeAnalyzers, extract common logic 

---

src/TypeScript.UnitTests/Rules/ActiveRulesCalculatorTests.cs
src/TypeScript/Rules/ActiveRulesCalculator.cs
src/TypeScript/Rules/RuleDefinition.cs

Support stylelintKey in RuleDefinitions 

---

src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs

CSS analysis fails with System.InvalidOperationException 

---

src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/EslintBridgeIssueConverterTests.cs
src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs
src/TypeScript/Analyzer/EslintBridgeAnalyzerFactory.cs
src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs
src/TypeScript/Analyzer/Resources.Designer.cs
src/TypeScript/Analyzer/Resources.resx

Invalid CSS causes an exception in output 

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration/Binding/RuleSetReferenceChecker.cs
src/Integration/LocalServices/IRuleSetSerializer.cs
src/Integration/LocalServices/ISolutionRuleSetsInformationProvider.cs
src/Integration/LocalServices/RuleSetSerializer.cs
src/Integration/LocalServices/SolutionRuleSetsInformationProvider.cs
src/Integration/MefServices/VsSessionHost.cs

- remove unused services and tidy up tests
Part  of #4120

(1) Cleanup binding code

---

src/SonarQube.Client.Tests/Requests/Api/V9_4/GetSonarLintEventStreamTests.cs
src/SonarQube.Client.Tests/SonarQubeService_CreateServerSentEventsSession.cs
src/SonarQube.Client/Models/SonarQubeLanguage.cs

Add css to SonarQubeLanguage.AllLanguages 

---

src/Integration/Binding/BindingController.cs

Add css to NonRoslynBindingConfigProvider inside of BindingController

---

src/Infrastructure.VS.UnitTests/LanguageDetection/SonarLanguageRecognizerTests.cs
src/Infrastructure.VS/LanguageDetection/SonarLanguageRecognizer.cs

Enable CSS analysis for Vue only 

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/NewConnectedMode/ObsoleteConfigurationProviderTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingDataReaderTests.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/ObsoleteConfigurationProvider.cs
src/Integration/Persistence/ISolutionBindingDataReader.cs

Simplify SolutionBindingDataReader construction

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/NewConnectedMode/ObsoleteConfigurationProviderTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingDataReaderTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingDataWriterTests.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/ObsoleteConfigurationProvider.cs
src/Integration/Persistence/ISolutionBindingDataReader.cs
src/Integration/Persistence/ISolutionBindingDataWriter.cs

- class is not quite MEF-exportable, but it's close

Simplify SolutionBindingDataWriter construction

---

src/CFamily/CMake/MacroEvaluator.cs
src/Core.UnitTests/EnvironmentVariableProviderExtensionsTests.cs
src/Core.UnitTests/EnvironmentVariableProviderTests.cs
src/Core.UnitTests/Notifications/DisabledNotificationsStorageTests.cs
src/Core/EnvironmentVariableProvider.cs
src/Core/Notifications/IDisabledNotificationsStorage.cs
src/Integration.UnitTests/Telemetry/TelemetryDataRepositoryTests.cs
src/Integration.Vsix/Analysis/UserSettingsProvider.cs
src/Integration/Telemetry/TelemetryDataRepository.cs

- addIEnvironmentVariableProvider.GetFolderPath
- refactored existing code
Prep for #4170

Add extension method to get standard SLVS user folder

---

src/Core/IThreadHandling.cs
src/Infrastructure.VS/ThreadHandling.cs
src/TestInfrastructure/NoOpThreadHandler.cs

Add RunOnUIThreadSync method to IThreadHandling

---

src/Integration.UnitTests/NewConnectedMode/ObsoleteConfigurationProviderTests.cs
src/Integration/NewConnectedMode/ObsoleteConfigurationProvider.cs

Fix duplicate IConfigurationProvider export

---

src/Integration.UnitTests/UnintrusiveBinding/UnintrusiveBindingPathProviderTests.cs
src/Integration/UnintrusiveBinding/UnintrusiveBindingPathProvider.cs

(1) Add UnintrusiveBindingPathProvider

---

src/Integration.UnitTests/UnintrusiveBinding/UnintrusiveBindingPathProviderTests.cs
src/Integration.UnitTests/UnintrusiveBinding/UnintrusiveConfigurationProviderTests.cs
src/Integration/UnintrusiveBinding/UnintrusiveBindingPathProvider.cs
src/Integration/UnintrusiveBinding/UnintrusiveConfigurationProvider.cs

(2) Implement IConfigurationProvider

---

src/ConnectedMode.UnitTests/Binding/ImportBeforeInstallTriggerTests.cs
src/ConnectedMode/Binding/ImportBeforeFileGenerator.cs
src/ConnectedMode/Binding/ImportBeforeInstallTrigger.cs
src/ConnectedMode/ConnectedModePackage.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4189

Add triggers to update on SolutionBindingChanged/Update

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationPersisterTests.cs
src/Integration.UnitTests/UnintrusiveBinding/UnintrusiveBindingPathProviderTests.cs
src/Integration.UnitTests/UnintrusiveBinding/UnintrusiveConfigurationProviderTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/UnintrusiveBinding/UnintrusiveBindingPathProvider.cs
src/Integration/UnintrusiveBinding/UnintrusiveConfigurationProvider.cs

(3) Persist CM config in the new location

---

src/Education.UnitTests/RuleHelpXamlTranslatorTests.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs

Add support for span to RuleHelpXamlTranslator 

---

src/ConnectedMode.UnitTests/Binding/GlobalConfigGeneratorTests.cs
src/ConnectedMode/Binding/GlobalConfigGenerator.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4205

Change global level to 1999999999

---

src/Integration/Binding/CSharpVBBindingConfigProvider.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4206

Rename GetSolutionRuleSetFilePath method to GetSolutionGlobalConfigFilePath

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/VsSessionHost.cs

Cleanup VSSessionHost

---

src/ConnectedMode/Embedded/SonarLintTargets.xml

Fix _SLVSRootFolder HashCode

---

src/ConnectedMode/Embedded/SonarLintTargets.xml
src/Core/Binding/BindingConfiguration.cs
src/Core/Language.cs
src/Integration.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/Integration.UnitTests/NewConnectedMode/BindingConfigurationTests.cs

Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4203 and https://github.com/SonarSource/sonarlint-visualstudio/issues/4188

Store the globalconfig and SonarLint.xml without projectKey

---

src/SonarQube.Client.Tests/Requests/Api/V9_7/SearchHotspotRequestTests.cs
src/SonarQube.Client/Api/Common/ApiExtensions.cs
src/SonarQube.Client/Api/Common/ServerComponent.cs
src/SonarQube.Client/Api/Common/ServerIssueTextRange.cs
src/SonarQube.Client/Api/ISearcHotspotRequest.cs
src/SonarQube.Client/Api/ISearchHotspotRequest.cs
src/SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
src/SonarQube.Client/Api/V9_7/SearcHotspotRequest.cs
src/SonarQube.Client/Models/SonarQubeHotspotSearch.cs

Get hotspots from server in SQ Client

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingProcess.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

- new binding method does not change any files in the solution
Part of #4120

Simplify IBindingProcess - drop solution-save code

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_SearchHotspotsAsync.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/SonarQubeService.cs

Create hotspots endpoint in SQ Client

---

src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs

- no product changes
Part of #4120

(1) Remove redundant setup from SolutionBindingOperationTests

---

src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4269

Change INotificationService to not be a singleton.

---

pipeline/azure-pipelines.yml

Fix CI test failures caused by MSTest v17.6

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration/Binding/BindingProcessImpl.cs

(1) Download QPs for all known languages

---

src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

(3) Handle missing server plugins

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationPersisterTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

Part of #4120
Removed code relating to saving in different Connected Mode formats - we'll only save in the new format.

Cleanup - save only in new format

---

src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingProcessImplTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration.UnitTests/NewConnectedMode/ConfigurationPersisterTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingDataWriterTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/SolutionBindingOperation.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs
src/Integration/Persistence/ISolutionBindingDataWriter.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

- new connected mode doesn't save files in a source-controlled location
Part of #4120

(2) Drop usage of ISourceControlledFileSystem

---

src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4286

Add RemoveNotification method to INotificationService

---

src/IssueViz.Security.UnitTests/Hotspots/ServerHotspotStoreTests.cs
src/IssueViz.Security/Hotspots/ServerHotspotStore.cs

Add ServerHotspotStore

---

src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Binding/SolutionBindingOperationTests.cs
src/Integration/Binding/BindingProcessImpl.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Binding/IBindingProcess.cs
src/Integration/Binding/ISolutionBindingOperation.cs
src/Integration/Binding/SolutionBindingOperation.cs

Rename SBO.Prepare -> SaveRuleConfiguration

---

build/ProcessJarFiles/JarProcessing.targets
src/Education.UnitTests/SimpleRuleHelpXamlBuilderTests.cs
src/Rules.UnitTests/LocalRuleMetadataProviderTests.cs

Get local rule descriptions for Hotspots

---

src/Integration.UnitTests/NewConnectedMode/ConfigurationPersisterTests.cs
src/Integration.UnitTests/Persistence/SolutionBindingDataWriterTests.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs
src/Integration/Persistence/ISolutionBindingDataWriter.cs

Make IConfigurationPersister MEF-exportable

---

src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/NewConnectedMode/IConfigurationPersister.cs

Remove IConfigurationPersister as an ILocalService

---

src/CFamily.UnitTests/packages.lock.json
src/CloudSecrets.UnitTests/packages.lock.json
src/ConnectedMode.UnitTests/packages.lock.json
src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/packages.lock.json
src/Core.UnitTests/packages.lock.json
src/Education.UnitTests/packages.lock.json
src/EmbeddedVsix.UnitTests/packages.lock.json
src/Infrastructure.VS.UnitTests/packages.lock.json
src/Integration.TeamExplorer.UnitTests/packages.lock.json
src/Integration.TeamExplorer/Integration.TeamExplorer.csproj
src/Integration.TeamExplorer/packages.lock.json
src/Integration.UnitTests/packages.lock.json
src/Integration.Vsix.UnitTests/packages.lock.json
src/Integration.Vsix/packages.lock.json
src/Integration/packages.lock.json
src/IssueViz.Security.UnitTests/packages.lock.json
src/IssueViz.Security/packages.lock.json
src/IssueViz.UnitTests/packages.lock.json
src/Progress.UnitTests/packages.lock.json
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/packages.lock.json
src/Roslyn.Suppressions/Roslyn.Suppressions/packages.lock.json
src/Rules.UnitTests/packages.lock.json
src/TestInfrastructure/packages.lock.json
src/TypeScript.UnitTests/packages.lock.json

- prep for moving credential classes
- added project ref TeamExplorer -> ConnectedMode
Part of #4320

Add Alm ref to ConnectedMode

---

src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/LocalServices/CredentialStore.cs
src/Integration/LocalServices/ICredentialStoreService.cs
src/Integration/MefServices/VsSessionHost.cs

- can now only be created using MEF
- prep for moving the implementation from Integration to ConnectedMode
Part of #4320

Change ICredentialStoreService to not be an ILocalService

---

src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs

Ignore flaky test UpdateAll_CallInProgress_CallIsCancelled

---

src/Core/IMefFactory.cs
src/Integration.UnitTests/Helpers/MefFactoryTests.cs
src/Integration/Helpers/MefFactory.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4341

Add MefFactory

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode.UnitTests/Migration/FileProviderTests.cs
src/ConnectedMode.UnitTests/Migration/LegacySettingsTests.cs
src/ConnectedMode.UnitTests/Migration/MSBuildFileCleanerTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/IConnectedModeMigration.cs
src/ConnectedMode/Migration/MSBuildFileCleaner.cs
src/ConnectedMode/Migration/MSBuildFileProvider.cs

Update skeleton interfaces

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode.UnitTests/Migration/VsAwareFileSystemTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/Interfaces.cs
src/ConnectedMode/Migration/MSBuildFileCleaner.cs
src/ConnectedMode/Migration/VsAwareFileSystem.cs

(1) Add VS-aware file system abstraction for migration

---

src/ConnectedMode.UnitTests/Migration/Wizard/MigrationWizardControllerTests.cs
src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4355

Implement IConnectedModeMigration in MigrationWizard and add simple ui

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationCheckerTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationPromptTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/IMigrationPrompt.cs
src/ConnectedMode/Migration/Interfaces.cs
src/ConnectedMode/Migration/MigrationChecker.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

(3) Pass old binding information to the migration process

---

src/ConnectedMode.UnitTests/Migration/FileProviderTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/MSBuildFileProvider.cs
src/TestInfrastructure/Framework/TestLogger.cs

(2) Implement basic file provider

---

src/ConnectedMode.UnitTests/ConnectedMode.UnitTests.csproj
src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_my_project_key_Cleaned.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_my_project_key_Input.xml
src/ConnectedMode.UnitTests/Migration/MSBuildFileCleanerTests.cs
src/ConnectedMode.UnitTests/Migration/XmlDocumentHelperTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/Interfaces.cs
src/ConnectedMode/Migration/MSBuildFileCleaner.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx
src/ConnectedMode/Migration/XmlDocumentHelper.cs

Clean up additional files references

---

src/ConnectedMode.UnitTests/Migration/XmlFileCleanerTests.cs
src/ConnectedMode.UnitTests/Migration/XmlFileProviderTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/XmlFileCleaner.ElementAndAttributeTailMatcher.cs
src/ConnectedMode/Migration/XmlFileCleaner.ElementAndValueTailMatcher.cs
src/ConnectedMode/Migration/XmlFileCleaner.cs
src/ConnectedMode/Migration/XmlFileProvider.cs

- no code changes, just file renames

Rename file cleaner and provider types

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4396

Connect to SonarQubeService in ConnectedModeMigration

---

src/ConnectedMode.UnitTests/Migration/MigrationCheckerTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationPromptTests.cs
src/ConnectedMode/Migration/IMigrationPrompt.cs
src/ConnectedMode/Migration/MigrationChecker.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4365

Change Migration prompt to show if user has both old and new style connected mode.

---

src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

i.e. removed fixed sizes
Fixese #4407

Change wizard XAML to size to content

---

src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs

Move file provider types to new folder

---

src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/RoslynProjectProvider.cs

- if there are no projects then there is nothing to clean
Part of #4386

Get list of project to check from RoslynProjectProvider

---

src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Move start button to first page of wizard

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs
src/Core/IThreadHandling.cs
src/Infrastructure.VS/ThreadHandling.cs
src/TestInfrastructure/NoOpThreadHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4369

Add Threadhandling in wizard and connectedmodemigration

---

src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProvider.FileFinderTests.cs
src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.FileFinder.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/MigrationExtensions.cs

Move file finding to separate class

---

src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Update wizard: add cancellation, timer and fix bug

---

src/ConnectedMode/Migration/ConnectedModeMigration.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4421

Update progress messages

---

src/Core/IThreadHandling.cs
src/Infrastructure.VS/ThreadHandling.cs
src/TestInfrastructure/NoOpThreadHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4415

Add an actually synchronous method to IThreadHandling

---

src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs

Search in project dirs (non-recursive)

---

src/ConnectedMode.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/Core.UnitTests/Helpers/WebServiceHelperTests.cs
src/Core/Helpers/WebServiceHelper.cs

Don't suppress TaskCanceled exceptions

---

src/ConnectedMode.UnitTests/Migration/Wizard/MigrationWizardControllerTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Handle help hyperlink in wizard

---

src/ConnectedMode.UnitTests/ConnectedMode.UnitTests.csproj
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_XprojectkeyY_NoneItemGroup_Cleaned.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_XprojectkeyY_NoneItemGroup_Input.xml
src/ConnectedMode.UnitTests/Migration/XmlFileCleanerTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/XmlFileCleaner.cs

Remove None ItemGroup that references the generated ruleset

---

src/ConnectedMode.UnitTests/ConnectedMode.UnitTests.csproj
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_XprojectkeyY_NoneItemGroup_Cleaned.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/AdditionalFiles_my_project_key_Cleaned.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/RulesetProp-project_key_aaa_Cleaned.vbproj
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/Ruleset_IncludedTopLevel-project-key_Cleaned.ruleset.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/Ruleset_IncludedTopLevel-project-key_Input.ruleset.xml
src/ConnectedMode.UnitTests/Migration/FileCleanerTestCases/Ruleset_XX-project-key_Cleaned.ruleset.xml
src/ConnectedMode.UnitTests/Migration/XmlFileCleanerTests.cs
src/ConnectedMode/Migration/XmlFileCleaner.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4426

Improve cleanup of xml elements

---

src/ConnectedMode/Install/SonarLintTargets.xml

Fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4439

Clean up SonarLintTargets.xml

---

src/ConnectedMode/Install/SonarLintTargets.xml
src/Core/Language.cs

Rename generated globalconfig files to include sonarlint in the name

---

src/ConnectedMode.UnitTests/Migration/MigrationPromptTests.cs
src/ConnectedMode.UnitTests/Migration/Wizard/MigrationWizardControllerTests.cs
src/ConnectedMode/Migration/IMigrationPrompt.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Show output window when migration fails

---

src/ConnectedMode.UnitTests/Migration/VsAwareFileSystemTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx
src/ConnectedMode/Migration/VsAwareFileSystem.cs

Add SCC operations to VsAwareFileSystem

---

src/ConnectedMode.UnitTests/Migration/Wizard/MigrationWizardControllerTests.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Show Tfvc info in wizard conditionally

---

src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest

fixes part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4173

Increase minimum vs version in manifest

---

src/ConnectedMode/Install/SonarLintTargets.xml

Don't show generated SonarLint.xml in the Solution Explorer

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingPathProviderTests.cs
src/ConnectedMode/Binding/UnintrusiveBindingPathProvider.cs
src/ConnectedMode/Install/SonarLintTargets.xml

Remove hash from settings folder name

---

src/ConnectedMode.UnitTests/Binding/CSharpVBBindingConfigProviderTests.cs
src/ConnectedMode.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingPathProviderTests.cs
src/Progress.TestFramework/ConfigurableServiceProvider.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs

Fix test code smells

---

src/Roslyn.Suppressions/Roslyn.Suppressions/SupportedSuppressionBuilder.g.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/SupportedSuppressionBuilder.tt

Fix supported suppressions T4

---

src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Theme the migration wizard

---

MarketPlaceFiles/VS2019/overview-2019.md
MarketPlaceFiles/VS2022/overview-2022.md
src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

Update marketplace pages

---

src/ConnectedMode.UnitTests/ConnectedMode.UnitTests.csproj
src/ConnectedMode.UnitTests/packages.lock.json

- fixes merge issue (builds ok locally but not on CI)

Add ref to ALM binary to tests

---

src/ConnectedMode/Migration/MigrationStrings.Designer.cs
src/ConnectedMode/Migration/MigrationStrings.resx

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4488

Update migration gold bar message

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs

Trigger update of suppressions post-migration

---

src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

- also exclude the thin controller that creates it

Exclude wizard XAML component from code coverage

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotMatcherTests.cs
src/IssueViz.Security/Hotspots/HotspotMatcher.cs

Implement HotspotMatcher (#4492)

---

src/Core/DocumentEvents.cs
src/Infrastructure.VS/DocumentEvents/DocumentEvents.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

Add IDocumentEvents interface and implementation

---

src/ConnectedMode/ConnectedModePackage.cs

Add call to update server hotspots on ConnectedModePackage initialization

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs

- refactor existing tests. No product changes.

Add MefTestHelper for multiple exports

---

src/IssueViz.Security.UnitTests/Hotspots/DocumentClosedHandlerTests.cs
src/IssueViz.Security/Hotspots/DocumentClosedHandler.cs

Trigger local hotspot store cleanup when a file is closed

---

src/ConnectedMode/ConnectedModePackage.cs
src/ConnectedMode/Hotspots/IHotspotDocumentClosedHandler.cs
src/IssueViz.Security.UnitTests/Hotspots/DocumentClosedHandlerTests.cs
src/IssueViz.Security/Hotspots/DocumentClosedHandler.cs

Create doc closed handler in ConnectedMode package initialization

---

src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
src/Integration.Vsix/Analysis/AnalysisStrings.resx

Raise config changed when solution binding changes

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotReviewPriorityProviderTests.cs
src/IssueViz.Security/Hotspots/HotspotReviewPriorityProvider.cs

Add HotspotReviewPriorityProvider

---

src/ConnectedMode.UnitTests/Hotspots/ServerHotspotStoreTests.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotMatcherTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE/Api/HotspotToIssueVisualizationConverterTests.cs
src/SonarQube.Client/Api/V8_6/GetHotspotRequest.cs
src/SonarQube.Client/Models/SonarQubeHotspot.cs
src/SonarQube.Client/Models/SonarQubeHotspotSearch.cs

Add Resolution to SonarQubeHotspot

---

src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs

Disable "Remove" hotspot view context menu command

---

src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs

Remove Category column from the local hotpot list

---

src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDERequestHandlerTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsStoreTests.cs
src/IssueViz.Security/Commands/Constants.cs
src/IssueViz.Security/Commands/IssueVizSecurityPackage.vsct
src/IssueViz.Security/IssueViz.Security.csproj
src/IssueViz.Security/IssueVizSecurityPackage.cs
src/IssueViz.Security/OpenInIDE/Api/OpenInIDERequestHandler.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsControl.xaml
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsControl.xaml.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsStore.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

The individual commits have already been reviewed.

Merge dp/openInIDE changes to branch-hotspots2

---

src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

Show only unreviewed hotspots

---

src/Education/XamlGenerator/DiffTranslator.cs

Add IDiffTranslator

---

src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsControl.xaml
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs

Add rule description hyperlink to OpenInIDE Hotspots window

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs

Add rule description hyperlink to Hotspots window

---

src/ConnectedMode/ConnectedModePackage.cs
src/ConnectedMode/Hotspots/IHotspotSolutionClosedHandler.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotSolutionClosedHandlerTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security/Hotspots/HotspotSolutionClosedHandler.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

Add clearing of LocalHotspotsStore on solution close

---

src/ConnectedMode.UnitTests/Helpers/CancellableActionRunnerTests.cs
src/Education.UnitTests/Layout/Logical/RuleInfoTranslatorTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsStoreTests.cs
src/SonarQube.Client.Tests/SonarQubeService_SearchHotspotsAsync.cs
src/TypeScript.UnitTests/Rules/ActiveRulesCalculatorTests.cs

CAYC - tests

---

src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

Remove todos

---

src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs

Fix comparisons in LocalHotspotStoreTests

---

src/Education.UnitTests/SimpleRuleHelpXamlBuilderTests.cs
src/EmbeddedSonarAnalyzer.props

Update SonarJS to version 10.3.2.22047

---

src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStore.ServerHotspotComparerTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

Make local hotspot matching deterministic

---

src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs

Add test for local hotspot matching

---

src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs

Fix flaky hotspot test

---

pipeline/azure-pipelines.yml

[Pipeline] Add variable to disable Mend analysis

---

pipeline/custom/mend-only-azure-piplines.yml

[Pipeline] Add pipeline that only runs Mend analysis

---

src/Education/Commands/RuleHelpUserControl.xaml
src/Education/XamlGenerator/StyleResourceNames.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4621

Add new style resources for diff highlighting.

---

tools/CleanRebuild.cmd

Add CleanRebuild.cmd script that cleans and rebuilds the project

---

src/Education/Commands/RuleHelpUserControl.xaml

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4630

Update style resource for diffs

---

src/SonarQube.Client.Tests/Models/ServerSentEvents/SSEStreamReaderTests.cs
src/SonarQube.Client/Models/ServerSentEvents/ClientContract/IQualityProfileEvent.cs
src/SonarQube.Client/Models/ServerSentEvents/SSEStreamReader.cs

Add IQualityProfileEvent interface and an empty implementation
Add RuleSetEvent to SSEStreamReader
Implements #4633

Add IQualityProfileEvent

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionFactoryTests.cs
src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionFactory.cs

Add IQualityProfileServerEventSourcePublisher integration to SSESession

---

src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileUpdaterTests.cs
src/ConnectedMode/QualityProfiles/IQualityProfileUpdater.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs

Add IQualityProfileUpdater definition

---

src/ConnectedMode.UnitTests/Suppressions/TimedUpdateHandlerTests.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs
src/ConnectedMode/Suppressions/TimedUpdateHandler.cs

Add QualityProfileUpdater to TimedUpdateHandler

---

src/ConnectedMode.UnitTests/ServerSentEvents/SSESessionFactoryTests.cs
src/ConnectedMode/ServerSentEvents/SSESessionFactory.cs

Fix SSESessionFactory Dispose

---

src/Education/Commands/RuleHelpUserControl.xaml
src/Education/XamlGenerator/StyleResourceNames.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4656

Add sub style

---

src/Education.UnitTests/XamlGenerator/DiffTranslatorTests.cs
src/Education/Commands/RuleHelpUserControl.xaml
src/Education/XamlGenerator/DiffTranslator.cs
src/Education/XamlGenerator/StyleResourceNames.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4658

Implement more detailed highlighting

---

src/Education.UnitTests/XamlGenerator/DiffTranslatorTests.cs
src/Education/XamlGenerator/DiffTranslator.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4672

Deal with null or empty strings in DiffTranslator

---

src/Education.UnitTests/XamlGenerator/DiffTranslatorTests.cs
src/Education/XamlGenerator/DiffTranslator.cs

fix https://github.com/SonarSource/sonarlint-visualstudio/issues/4665

Fix line text being omitted if line has 0 subpieces

---

src/ConnectedMode.UnitTests/Binding/BindingProcessImplTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileDownloaderTests.cs
src/ConnectedMode/Binding/BindingProcessImpl.cs
src/ConnectedMode/Binding/IBindingProcessFactory.cs
src/ConnectedMode/QualityProfiles/QualityProfileDownloader.cs

Extract QP downloader code from BindingProcessImpl

---

src/ConnectedMode.UnitTests/Migration/UnintrusiveBindingControllerTests.cs
src/ConnectedMode/Binding/BindingProcessImpl.cs
src/ConnectedMode/Binding/IBindingProcess.cs
src/ConnectedMode/Migration/IUnintrusiveBindingController.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration/Binding/BindingWorkflow.cs

Remove redundant IBindingProcess.SaveRuleConfiguration

---

src/Education.UnitTests/RuleHelpXamlTranslatorTests.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs

"&lt;" and "&gt;" is replaced by "<" and ">" 

---

src/Education.UnitTests/SimpleRuleHelpXamlBuilderTests.cs

Create_CheckAllEmbedded fails after merge

---

src/ConnectedMode.UnitTests/Binding/BindingProcessFactoryTests.cs
src/ConnectedMode.UnitTests/Binding/CompositeBindingConfigProviderTests.cs
src/ConnectedMode.UnitTests/Binding/NonRoslynBindingConfigProviderTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileDownloaderTests.cs
src/ConnectedMode/Binding/CompositeBindingConfigProvider.cs
src/ConnectedMode/Binding/IBindingProcessFactory.cs
src/ConnectedMode/Binding/NonRoslynBindingConfigProvider.cs
src/ConnectedMode/Binding/SolutionBindingOperation.cs
src/ConnectedMode/QualityProfiles/QualityProfileDownloader.cs

(1) Modify QualityProfileDownloader to be MEF-creatable

---

src/SonarQube.Client.Tests/SonarQubeService_GetAllQualityProfilesAsync.cs
src/SonarQube.Client.Tests/SonarQubeService_GetQualityProfileAsync.cs
src/SonarQube.Client/Api/V5_20/GetQualityProfilesRequest.cs
src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/SonarQubeService.cs

Add GetAllQualityProfilesAsync to SonarQubeService

---

src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileUpdaterTests.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs
src/ConnectedMode/Suppressions/TimedUpdateHandler.cs

Cancel previous QP update jobs when triggering a new one

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingPathProviderTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationPromptTests.cs
src/ConnectedMode.UnitTests/Migration/VsAwareFileSystemTests.cs
src/ConnectedMode/Binding/UnintrusiveBindingPathProvider.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/IMigrationPrompt.cs
src/ConnectedMode/Migration/MigrationSettingsProvider.cs
src/ConnectedMode/Migration/VsAwareFileSystem.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs
src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/IThreadHandling.cs
src/Core/Notifications/INotificationService.cs
src/Education/Education.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/SolutionInfoProvider.cs
src/Infrastructure.VS/ThreadHandling.cs
src/Integration.UnitTests/Helpers/MefFactoryTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxRequestFactoryTests.cs
src/Integration.Vsix/CFamily/VcxProject/VcxRequestFactory.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/Integration/Helpers/MefFactory.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHostpotStoreMonitorTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE/Api/OpenInIDEFailureInfoBarTests.cs
src/IssueViz.Security/Hotspots/LocalHotspotStoreMonitor.cs
src/IssueViz.Security/OpenInIDE/Api/OpenInIDEFailureInfoBar.cs
src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixActionsSource.cs
src/TestInfrastructure/NoOpThreadHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4180

Change RunOnUIThread to RunOnUIThreadAsync

---

src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileUpdaterTests.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs
src/Core/Analysis/INotifyQualityProfilesChanged.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
src/Integration.Vsix/Analysis/AnalysisStrings.resx

Trigger re-analysis of open docs when QPs are updated

---

src/ConnectedMode.UnitTests/QualityProfiles/OutOfDateQualityProfileFinderTests.cs
src/ConnectedMode/QualityProfiles/OutOfDateQualityProfileFinder.cs

Add OutOfDateQualityProfileFinder

---

src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4526

Use RunOnBackgroundThread in SuppressionIssueStoreUpdate instead of SwitchToBackgroundThread.

---

src/Education.UnitTests/RuleHelpXamlTranslatorTests.cs
src/Education.UnitTests/SimpleRuleHelpXamlBuilderTests.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs

Support <sup> tag in xaml translator

---

src/EmbeddedSonarAnalyzer.props

Update embedded JS/TS analyzer to 10.4.0.22160

---

src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileDownloaderTests.cs
src/ConnectedMode/Binding/BindingStrings.Designer.cs
src/ConnectedMode/Binding/BindingStrings.resx
src/ConnectedMode/QualityProfiles/OutOfDateQualityProfileFinder.cs
src/ConnectedMode/QualityProfiles/QualityProfileDownloader.cs

Make QualityProfileDownloader download only outdated Quality Profiles

---

MarketPlaceFiles/VS2019/overview-2019.md
MarketPlaceFiles/VS2022/overview-2022.md

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4712

Change links to documentation on marketplace.

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_SearchHotspotsAsync.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/V10_2/SearchHotspotRequest.cs
src/SonarQube.Client/Api/V9_7/SearcHotspotRequest.cs

Handle API changes in SQ 10.2

---

THIRD-PARTY-NOTICES

Add third-party license for DiffPlex

---

src/Rules/CleanCodeTaxonomy.cs

Add new Clean Code Taxonomy models

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingControllerTests.cs
src/ConnectedMode/Binding/IUnintrusiveBindingController.cs

Move binding code out of Migration folder

---

src/ConnectedMode.UnitTests/Migration/MigrationPromptTests.cs
src/ConnectedMode/Migration/IMigrationPrompt.cs
src/Core/ISolutionInfoProvider.cs
src/Core/Notifications/INotificationService.cs

Refactor MigrationPrompt to use ISolutionInfoProvider

---

src/Core/ISolutionInfoProvider.cs
src/Core/IThreadHandling.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/SolutionInfoProvider.cs

Add sync method to ISolutionInfoProvider

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveBindingPathProviderTests.cs
src/ConnectedMode.UnitTests/Migration/ObsoleteConfigurationProviderTests.cs
src/ConnectedMode.UnitTests/Migration/ObsoleteConnectedModeSolutionBindingPathProviderTests.cs
src/ConnectedMode.UnitTests/Persistence/LegacySolutionBindingPathProviderTests.cs
src/ConnectedMode/Binding/UnintrusiveBindingPathProvider.cs
src/ConnectedMode/Migration/ObsoleteConfigurationProvider.cs
src/ConnectedMode/Migration/ObsoleteConnectedModeSolutionBindingPathProvider.cs
src/ConnectedMode/Persistence/LegacySolutionBindingPathProvider.cs

... instead of calling IVsSolution directly
Part of #4481

Refactor binding path providers to use ISolutionInfoProvider

---

build/tools/ExtractRuleDescFromJson/ExtractRuleDescFromJson.csproj
build/tools/ExtractRuleDescFromJson/RuleDescExtractor.cs
src/Education.UnitTests/Layout/Logical/RuleInfoTranslatorTests.cs
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Rules.UnitTests/RuleHelpTests.cs
src/Rules.UnitTests/RuleInfoTests.cs
src/Rules.UnitTests/RuleMetaDataProviderTests.cs
src/Rules/IRuleInfo.cs
src/Rules/ServerRuleMetadataProvider.cs

Add new CCT models CCCat, CCAtt, (SwQual, SwQualSeverity)[] to IRuleInfo

---

src/Education.UnitTests/XamlGenerator/SimpleRuleHelpXamlBuilderTests.cs
src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Update embedded CFamily analyzer to 6.48.0.62520

---

src/ConnectedMode.UnitTests/Persistence/LegacySolutionBindingPathProviderTests.cs
src/ConnectedMode/Persistence/LegacySolutionBindingPathProvider.cs
src/Core/ISolutionInfoProvider.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/SolutionInfoProvider.cs

Add "GetSolutionDirectory" methods to ISolutionInfoProvider

---

src/ConnectedMode.UnitTests/Migration/FileProviders/XmlFileProviderTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationSettingsProviderTests.cs
src/ConnectedMode.UnitTests/Persistence/LegacySolutionBindingPathProviderTests.cs
src/ConnectedMode/Migration/FileProviders/XmlFileProvider.cs
src/ConnectedMode/Migration/MigrationSettingsProvider.cs
src/ConnectedMode/Persistence/LegacySolutionBindingPathProvider.cs
src/Core/ISolutionInfoProvider.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/SolutionInfoProvider.cs

- XmlFileProvider and MigrationSettingsProvider
Part of #4481

Change components to use ISolutionInfoProvider

---

tools/CleanRebuild.cmd

... so it doesn't matter which directory it is run from

[Infra] Tweak cleanup script

---

build/ProcessJarFiles/CommonProperties.props

Update the sonarlint-rule-extractor-cli jar in repo

---

src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/State/StateManager.cs
src/Integration/State/TransferableVisualState.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs

Remove IHost.UIDispatcher

---

src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/VsSessionHost.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/State/StateManager.cs
src/Integration/State/TransferableVisualState.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs

[CAYC] Don't download server settings in ConnectionWorkflow

---

build/tools/ExtractRuleDescFromJson/PluginRule.cs
build/tools/ExtractRuleDescFromJson/RuleDescExtractor.cs

Update ExtractRuleDescFromJson project

---

src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
src/Integration.TeamExplorer/SectionController.cs
src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Binding/BindingWorkflowTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/Binding/BindingController.cs
src/Integration/Binding/BindingWorkflow.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs

Change IHost to not implement IServiceProvider

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/OpenInIDE_Hotspots/HotspotsList/OpenInIdeHotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.Caption.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/ViewModels/OpenInIDEHotspotsControlViewModel.cs
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs

Remove ThreadHelper from view models

---

src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/Controls/RuleHelpUserControl.xaml
src/Education/XamlGenerator/StyleResourceNames.cs
src/Education/XamlGenerator/SubTitleImageInfo.cs
src/Education/XamlGenerator/XamlGeneratorHelper.cs

Render new Clean Code Taxonomy in Rule Description

---

src/Education.UnitTests/XamlGenerator/SimpleRuleHelpXamlBuilderTests.cs
src/EmbeddedSonarAnalyzer.props

Update SonarJS to 10.5.1.22382

---

build/tools/ExtractRuleDescFromJson/ExtractRuleDescFromJson.csproj
build/tools/ExtractRuleDescFromJson/PluginRule.cs
src/Core/Analysis/CleanCodeTaxonomy.cs
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/XamlGenerator/SubTitleImageInfo.cs
src/Education/XamlGenerator/XamlGeneratorHelper.cs
src/Rules.UnitTests/RuleHelpTests.cs
src/Rules.UnitTests/RuleInfoTests.cs
src/Rules/IRuleInfo.cs

Move CCT to Core.Analysis

---

src/CloudSecrets/SecretsToAnalysisIssueConverter.cs
src/Core/Analysis/AnalysisIssue.cs
src/Core/Analysis/IAnalysisIssue.cs
src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
src/TestInfrastructure/DummyAnalysisIssue.cs
src/TypeScript/Analyzer/EslintBridgeIssueConverter.cs

Add CCT Severity to IAnalysisIssue

---

src/ConnectedMode.UnitTests/Suppressions/TimedUpdateHandlerTests.cs
src/ConnectedMode/Suppressions/TimedUpdateHandler.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4690

Add ActiveSolutionBoundTracker to TimedUpdateHandler

---

src/Core/ISolutionInfoProvider.cs
src/Infrastructure.VS.UnitTests/SolutionInfoProviderTests.cs
src/Infrastructure.VS/SolutionInfoProvider.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/LocalServices/ProjectSystemHelperTests.cs
src/Integration.Vsix/SonarLintTelemetryPackage.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/LocalServices/IProjectSystemHelper.cs
src/Integration/LocalServices/ProjectSystemHelper.cs
src/TestInfrastructure/Framework/ConfigurableVsProjectSystemHelper.cs

fixes https://github.com/SonarSource/sonarlint-visualstudio/issues/4760

Add IsSolutionFullyOpen to ISolutionInfoProvider.

---

src/Rules.UnitTests/RuleMetaDataProviderTests.cs
src/Rules/RuleMetaDataProvider.cs

Make RuleMetaDataProvider always disable CCT for Hotspots

---

src/Core/Analysis/CleanCodeTaxonomy.cs
src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueConverterFactoryTests.cs
src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs

Convert CCT impacts to CCT Severity in CFamilyIssueToAnalysisIssueConverter

---

src/EmbeddedSonarAnalyzer.props

Update Sonar Secrets metadata to 2.3.0.1632

---

src/Integration.Vsix.UnitTests/Commands/ProjectSonarLintMenuCommandTests.cs

fixes part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4770

Use mock of IProjectPropertyManager rather than an actual instance in ProjectSonarLintMenuCommandTests

---

src/IssueViz.Security.UnitTests/Taint/Models/TaintIssueTests.cs
src/IssueViz.Security/Taint/Models/ITaintIssue.cs
src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs

Add CCT severity to ITaintIssue

---

src/IssueViz.Security.UnitTests/Taint/TaintList/TaintViewModelTests.cs
src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssueViewModel.cs

Add SoftwareQualitySeverity support to TaintIssuesControl

---

src/Integration.Vsix.UnitTests/Analysis/SingleFileMonitorTests.cs
src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix.UnitTests/packages.lock.json
src/SonarLint.Test.props

- reenable disabled test
Fixes #3548, may fix #4827

Remove reference to MS.VS.Sdk.TestFramework

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_GetTaintVulnerabilitiesRequest.cs
src/SonarQube.Client/Api/Common/ServerImpact.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/V10_2/GetIssuesWithCCTRequest.cs
src/SonarQube.Client/Api/V10_2/GetTaintVulnerabilitiesWithCCTRequest.cs
src/SonarQube.Client/Api/V7_20/GetIssuesRequest.cs
src/SonarQube.Client/Helpers/ServerImpactHelper.cs
src/SonarQube.Client/Models/SonarQubeImpact.cs
src/SonarQube.Client/Models/SonarQubeIssue.cs

Add CCT Severity to SonarQubeIssue (GetTaintVulnerabilitiesAsync) for 10.2

---

src/Integration.Vsix.UnitTests/Commands/ProjectTestPropertySetCommandTests.cs

part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4770

Use mock of IProjectPropertyManager rather than an actual instance in ProjectTestPropertySetCommandTests

---

src/Rules.UnitTests/RuleExtensionTests.cs
src/Rules.UnitTests/ServerRuleMetadataProviderTests.cs
src/Rules/RuleExtensions.cs
src/Rules/ServerRuleMetadataProvider.cs

* Maps from SonarQubeRule to IRuleInfo
Implements #4818

Add CCT mapping to ServerRuleMetadataProvider

---

src/Integration/Telemetry/TelemetryPayloadCreator.cs

part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4842

Make ImportingConstructor free-threaded in TelemetryPayloadCreator.cs

---

src/Infrastructure.VS/DEBUG_ONLY_VsCookbookThreadingChecker.cs

[Infra] Add helper method to check if UI thread is required

---

src/Integration.Vsix.UnitTests/Analysis/UserSettingsProviderTests.cs
src/Integration.Vsix/Analysis/UserSettingsProvider.cs

Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4842

Fix UserSettingsProvider constructor to be free threaded

---

src/ConnectedMode.UnitTests/Install/ImportBeforeInstallTriggerTests.cs
src/ConnectedMode/ConnectedModePackage.cs
src/ConnectedMode/Install/ImportBeforeInstallTrigger.cs

Make ImportingConstructor in ImportBeforeInstallTrigger free threaded

---

src/TypeScript.UnitTests/NodeJSLocator/NodeLocationsProviderTests.cs
src/TypeScript/NodeJSLocator/NodeLocationsProvider.cs

Make ctor in NodeLocationsProvider free threaded.

---

src/Infrastructure.VS.UnitTests/ActiveDocumentLocatorTests.cs
src/Infrastructure.VS/ActiveDocumentLocator.cs

Make ctor in ActiveDocumentLocator free-threaded

---

src/Integration.UnitTests/Helpers/AbsoluteFilePathLocatorTests.cs
src/Integration/Helpers/AbsoluteFilePathLocator.cs

Make ctor in AbsoluteFilePathLocator free-threaded

---

src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
src/SonarQube.Client.Tests/Models/ServerSentEvents/SSEStreamReaderTests.cs
src/SonarQube.Client.Tests/Models/ServerSentEvents/TaintVulnerabilityRaisedServerEventTests.cs
src/SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintIssue.cs
src/SonarQube.Client/Models/ServerSentEvents/ClientContract/ITaintServerEvent.cs

Add Clean Code Taxonomy support to SSE for Taint

---

src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/Resources.Designer.cs
src/Education/Resources.resx
src/Education/XamlGenerator/StaticHtmlSnippets.Designer.cs
src/Education/XamlGenerator/XamlGeneratorHelper.cs

Add CCT Link To Rule Description

---

src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/Resources.Designer.cs
src/Education/Resources.resx
src/Education/XamlGenerator/XamlGeneratorHelper.cs

Add ToolTips to CCA + SQ in rule descriptions

---

src/Integration.UnitTests/Helpers/ToolWindowServiceTests.cs
src/Integration/Helpers/ToolWindowService.cs

Make ctor in ToolWindowService free-threaded

---

src/IssueViz.UnitTests/Editor/QuickActions/IssueLocationActionsSourceProviderTests.cs
src/IssueViz/Editor/QuickActions/IssueLocationActionsSourceProvider.cs

Make IssueLocationActionsSourceProvider ctor free threaded

---

src/Integration.Vsix.UnitTests/InfoBar/InfoBarManagerTests.cs

Add tests to check if InfoBarManager is free threaded

---

src/Integration.Vsix.UnitTests/CFamily/VcxRequestFactoryTests.cs
src/Integration.Vsix/CFamily/VcxProject/VcxRequestFactory.cs

Make ctor in VcxrequestFactory free threaded

---

src/TypeScript.UnitTests/Analyzer/CssAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
src/TypeScript/Analyzer/AnalyzerBase.cs

Make analyzerbase ctor free threaded.

---

src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs

Make ctor in errorListHelper free threaded

---

src/Integration.Vsix.UnitTests/Helpers/StatusBarNotifierTests.cs
src/Integration.Vsix/Helpers/IStatusBarNotifier.cs

Make ctor in StatusBarNotifier free threaded.

---

src/Integration.TeamExplorer.UnitTests/SonarQubeNavigationItemTests.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs

[Infra] Fix MefTestHelper to not fail on exceptions in Dispose

---

src/IssueViz.Security.UnitTests/OpenInIDE/Api/StatusRequestHandlerTests.cs
src/IssueViz.Security/OpenInIDE/Api/StatusRequestHandler.cs

Make ctor of StatusRequestHandler free threaded

---

src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs

Make TaintIssuesSynchronizer ctor free threaded

---

SonarLint.VisualStudio.Integration.sln
src/Directory.Build.props
src/vs-threading.MainThreadAssertingMethods.txt
src/vs-threading.MainThreadSwitchingMethods.txt

[Infra] add configuration for VSSDK thread analyzers

---

src/EmbeddedVsix/EmbeddedVsix.csproj
src/EmbeddedVsix/packages.lock.json
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/packages.lock.json

Update SDK build tools version to v7.7

---

src/Infrastructure.VS.UnitTests/VsVersionProviderTests.cs
src/Infrastructure.VS/VsVersion/VsVersionProvider.cs

Make VsVersionProvider ctor free threaded

---

src/EmbeddedSonarAnalyzer.props

Update Sonar Js to 10.6.0.22520

---

src/ConnectedMode/Shared/SharedBindingConfigModel.cs

Add shared binding Config model

---

src/ConnectedMode/Shared/ISharedBindingConfigProvider.cs

Add ISharedBindingConfigProvider

---

src/Core.UnitTests/SharedFolderProviderTests.cs
src/Core/SharedFolderProvider.cs

Add ISharedFolderProvider

---

src/ConnectedMode/Shared/ISharedBindingConfigProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/IHost.cs
src/Integration/MefServices/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs

Add shared binding and credentials support to VsSessionHost

---

src/Integration.TeamExplorer.UnitTests/SectionControllerTests.cs
src/Integration.TeamExplorer/ConnectSectionView.xaml
src/Integration.TeamExplorer/ConnectSectionViewModel.cs
src/Integration.TeamExplorer/SectionController.cs
src/Integration.UnitTests/Binding/AutoBindTriggerTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/Connection/ConnectionWorkflowTests.cs
src/Integration.UnitTests/State/StateManagerTests.cs
src/Integration/Binding/AutoBindTrigger.cs
src/Integration/BindingAbortedException.cs
src/Integration/Connection/ConnectConfiguration.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/Connection/ConnectionWorkflow.cs
src/Integration/State/StateManager.cs
src/Integration/State/TransferableVisualState.cs
src/Integration/TeamExplorer/IConnectSectionViewModel.cs
src/Integration/TeamExplorer/ISectionController.cs
src/TestInfrastructure/Framework/ConfigurableConnectSectionViewModel.cs
src/TestInfrastructure/Framework/ConfigurableHost.cs
src/TestInfrastructure/Framework/ConfigurableSectionController.cs

Enable auto-binding with shared settings and already stored credentials

---

src/Integration.UnitTests/Binding/AutoBindTriggerTests.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/Binding/AutoBindTrigger.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/Connection/IConnectionWorkflowExecutor.cs
src/Integration/MefServices/VsSessionHost.cs

Do not use host.BoundProjectKey manually + AutoBindTrigger refactoring

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode.UnitTests/Shared/SharedBindingConfigModelTests.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs

Implement SharedBindingConfigFileProvider

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigProviderTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/Shared/ISharedBindingConfigProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigProvider.cs

Implement ISharedBindingConfigProvider

---

src/Core.UnitTests/SharedFolderProviderTests.cs
src/Core/SharedFolderProvider.cs

Exclude User folder from SharedFolderProvider

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs

Create .sonarlint folder on Save

---

src/Core/MessageBox.cs

Add a MessageBox Wrapper

---

src/Integration.UnitTests/MefServices/ConnectedModeWindowEventBasedSchedulerTests.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration/MefServices/ConnectedModeWindowEventBasedScheduler.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs

* Add SharedBindingSuggestionService that contains binding suggestion logic
* Add ConnectedModeWindowEventBasedScheduler that contains logic for delayed execution of action items based on CM window loading event
Implements #4964

Add Shared Binding suggestion service

---

src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix.UnitTests/Commands/PackageCommandManagerTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/ConnectedModeMenu.vsct
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs
src/Integration.Vsix/Commands/PackageCommandManager.cs
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/SonarLintIntegrationPackage.cs

Add Save Shared Config Command to the Sonarlint Menu

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigModelTests.cs
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/VsSessionHost.cs
src/TestInfrastructure/Framework/ConfigurableStateManager.cs

Add binding suggestion invocation to VsHost after solution opens

---

src/ConnectedMode.UnitTests/Binding/Suggestion/SuggestSharedBindingGoldBarTests.cs
src/ConnectedMode/Binding/Suggestion/SuggestSharedBindingGoldBar.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs
src/Integration/MefServices/VsSessionHost.cs

Close SuggestSharedBindingGoldBar when closing Solution

---

src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Add SharedConfig Checkbox to Migration Wizard

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs

Add json formatting for shared binding saving

---

src/ConnectedMode.UnitTests/Binding/Suggestion/SuggestSharedBindingGoldBarTests.cs
src/ConnectedMode/Binding/Suggestion/SuggestSharedBindingGoldBar.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardController.cs
src/Core/DocumentationLinks.cs
src/Integration.TeamExplorer/ConnectSectionView.xaml
src/Integration/Helpers/Constants.cs

Update Connected Mode documentation links

---

src/ConnectedMode.UnitTests/Migration/ConnectedModeMigrationTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Migration/Interfaces.cs
src/ConnectedMode/Migration/Wizard/MigrationWizardWindow.xaml.cs

Add shared config save to the migration

---

.github/workflows/RequestReview.yml

Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4955

GitHub workflow: Add RequestReview

---

.github/workflows/StartProgress.yml

Part of https://github.com/SonarSource/sonarlint-visualstudio/issues/4955

GitHub workflow: Add StartProgress

---

.github/workflows/SubmitReview.yml

GitHub workflow: Add SubmitReview

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigProviderTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Shared/ISharedBindingConfigProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigProvider.cs
src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx

Add path to saved message in menu

---

src/SonarQube.Client.Tests/SonarQubeService_GetProjectDashboardUrl.cs
src/SonarQube.Client/SonarQubeService.cs

"View in SonarQube" returns a 404

---

src/Integration/Notifications/VisualStudioStatusBarHelper.cs

Add support for newer version of vs to VisualStudioStatusBarHelper

---

src/Education.UnitTests/XamlGenerator/RuleXamlBuilderSmokeTest.cs
src/Education.UnitTests/XamlGenerator/SimpleRuleHelpXamlBuilderTests.cs

Add rule description xaml builder smoke test for rich rule descriptions

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode.UnitTests/Shared/SharedBindingConfigModelTests.cs
src/ConnectedMode/Migration/ConnectedModeMigration.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/Integration.UnitTests/Connection/ConnectControllerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs
src/Integration/Connection/ConnectionController.cs
src/Integration/MefServices/VsSessionHost.cs

Remove string uri from SharedBindingConfig

---

src/Core.UnitTests/GitEventsMonitorTests.cs
src/Core/GitEventsMonitor.cs

Fix the Threading Issue in GitEventsMonitor

---

src/SonarQube.Client/Models/IssueTransition.cs

Add model for issue transitions

---

src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/Models/SonarQubeIssueTransition.cs
src/SonarQube.Client/SonarQubeService.cs

Add transition method to ISonarQubeService, rename IssueTransition

---

src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/Models/SonarQubeIssueTransitionResult.cs
src/SonarQube.Client/SonarQubeService.cs

Add SonarQubeIssueTransitionResult

---

.github/ISSUE_TEMPLATE.md

Sections on the Community forum were changes

Update links in issue template

---

src/SonarQube.Client.Tests/Helpers/SonarQubeIssueTransitionExtensionsTests.cs
src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_TransitionIssueAsync.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/ICommentIssueRequest.cs
src/SonarQube.Client/Api/ITransitionIssueRequest.cs
src/SonarQube.Client/Api/V10_4/TransitionIssueRequestWithAccept.cs
src/SonarQube.Client/Api/V9_9/CommentIssueRequest.cs
src/SonarQube.Client/Api/V9_9/TransitionIssueRequestWithWontFix.cs
src/SonarQube.Client/Helpers/SonarQubeIssueTransitionExtensions.cs
src/SonarQube.Client/SonarQubeService.cs

Add TransitionIssue method to ISonarQubeService

---

src/Core.UnitTests/Configuration/ConnectedModeFeaturesConfigurationTests.cs
src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs

Add check for SQ version to fill the Combobox

---

src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx

Change Accept Text

---

src/SonarQube.Client/ISonarQubeService.cs
src/SonarQube.Client/SonarQubeService.cs

Add SearchFilesByName & GetIssuesForComponent methods to ISonarQubeService interface

---

src/SonarQube.Client.Tests/Helpers/ComponentKeyGeneratorTests.cs
src/SonarQube.Client.Tests/Helpers/FilePathNormalizerTests.cs
src/SonarQube.Client/Helpers/ComponentKeyGenerator.cs
src/SonarQube.Client/Helpers/FilePathNormalizer.cs

Add ComponentKeyGenerator, add FilePathNormalizer reverse conversion

---

src/ConnectedMode.UnitTests/ServerIssueFinderTests.cs
src/ConnectedMode/ServerIssueFinder.cs

Add IServerIssueFinder

---

src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs
src/Infrastructure.VS/IErrorListHelper.cs
src/Infrastructure.VS/SonarLintTableControlConstants.cs
src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
src/Integration.Vsix.UnitTests/ErrorList/SonarErrorListDataSourceTests.cs
src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
src/Integration.Vsix/ErrorList/SonarErrorListDataSource.cs
src/IssueViz.UnitTests/TableControls/VSTableEventProcessorTests.cs
src/IssueViz/TableControls/VSTableEventProcessorProvider.cs

Add ErrorListHelper.TryGetIssueFromSelectedRow + refactoring

---

src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client.Tests/SonarQubeService_SearchFilesByName.cs
src/SonarQube.Client/Api/Common/ApiExtensions.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs
src/SonarQube.Client/Api/ISearchFilesByNameRequest.cs
src/SonarQube.Client/Api/V9_9/SearchFilesByNameRequest.cs
src/SonarQube.Client/SonarQubeService.cs

Implement SearchFilesByName method to SonarQubeClient

---

src/SonarQube.Client.Tests/SonarQubeService_SearchFilesByName.cs
src/SonarQube.Client/Api/V9_9/SearchFilesByNameRequest.cs

Add file path normalization to SearchFilesByName request

---

src/Core/SonarArtefactKeys.cs
src/Core/Suppressions/FilterableRoslynIssue.cs
src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs
src/Infrastructure.VS/IErrorListHelper.cs
src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix.UnitTests/Analysis/RoslynIssueLineHashCalculatorTests.cs
src/Integration.Vsix/Analysis/MuteIssueCommand.cs
src/Integration.Vsix/Analysis/RoslynIssueLineHashCalculator.cs

Add support for C#+VB.NET server issue muting

---

src/Integration/Transition/MuteWindowDialog.xaml

Add Dark Mode to Mute Issue window

---

src/Integration/Transition/MuteWindowDialog.xaml
src/Integration/Transition/MuteWindowDialog.xaml.cs

Make radio button selected when clicked inside border

---

src/ConnectedMode.UnitTests/IssueMatcherTests.cs
src/ConnectedMode/IssueMatcher.cs
src/Core/Suppressions/FilterableRoslynIssue.cs
src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs

Add support for muting file-level C#&VB.NET issues

---

src/ConnectedMode.UnitTests/Transition/MuteIssuesServiceTests.cs
src/ConnectedMode/Transition/MuteIssuesService.cs
src/Core/Transition/IMuteIssuesWindowService.cs
src/Core/Transition/MuteIssuesWindowResponse.cs
src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix/Analysis/MuteIssueCommand.cs
src/Integration/Transition/MuteIssuesWindowService.cs

Fix MuteIssuesService should use ServerIssueStore.AddIssues instead of UpdateIssues

---

src/EmbeddedSonarAnalyzer.props

Update embedded JS/TS analyzer to 10.10.0.24774

---

src/SLCore/Core/ISLCoreListener.cs
src/SLCore/Core/ISLCoreService.cs

Create SLCore.Core Interfaces

---

src/SLCore/Core/ISLCoreJsonRpc.cs

Add ISLCoreJsonRpc wrapper interface for JsonRpc

---

src/Integration.Vsix/Manifests/VS2019/source.extension.vsixmanifest
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

Add SLCORE assemblies to vsix manifest

---

src/CFamily.UnitTests/packages.lock.json
src/Integration.Vsix.UnitTests/packages.lock.json
src/Integration.Vsix/packages.lock.json
src/SLCore.UnitTests/packages.lock.json
src/SLCore/SLCore.csproj
src/SLCore/packages.lock.json

https://github.com/microsoft/vs-streamjsonrpc & https://www.nuget.org/packages/StreamJsonRpc

Add StreamJsonRpc v2.5.46 package

---

src/SLCore.UnitTests/Core/SLCoreJsonRpcTests.cs
src/SLCore.UnitTests/Integration/SLCoreIntegrationSmokeTest.cs
src/SLCore.UnitTests/Listener/BranchListenerTests.cs
src/SLCore.UnitTests/Protocol/RpcMethodNameTransformerTests.cs
src/SLCore/Core/ISLCoreJsonRpc.cs
src/SLCore/Listener/BranchListener.cs
src/SLCore/Protocol/RpcMethodNameTransformer.cs
src/SLCore/Service/Lifecycle/ISLCoreLifecycleService.cs

Add Async suffix trimming from JsonRPC method names

---

src/Core.UnitTests/Configuration/ConnectedModeFeaturesConfigurationTests.cs
src/Core/Configuration/ConnectedModeFeaturesConfiguration.cs
src/SonarQube.Client.Tests/Requests/DefaultConfiguration_Configure.cs
src/SonarQube.Client/Api/DefaultConfiguration.cs

Support Accept in SonarCloud

---

src/SLCore.UnitTests/Listener/ProgressListenerTests.cs
src/SLCore/Listener/ProgressListener.cs

Fix ProgressListener Method Names

---

nuget.config
pipeline/azure-pipelines.yml

Add Repox Artifactory authentication credentials to the CI Pipeline

---

src/Education/Layout/Logical/IVisualNodeProducer.cs
src/Education/Layout/Logical/RuleSplitDescription.cs

Create IVisualNodeProducer & RuleSplitDescription models for new rule descriptions

---

Directory.Build.props
src/Education/Education.csproj
src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/SonarLint.Test.props

Use latest C# version

---

src/Education.UnitTests/Layout/Logical/RichRuleDescriptionTests.cs
src/Education.UnitTests/XamlGenerator/RichRuleHelpXamlBuilderTests.cs
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/Layout/Logical/RichRuleDescription.cs
src/Education/Layout/Logical/RichRuleDescriptionConverter.cs
src/Education/XamlGenerator/RichRuleHelpXamlBuilder.cs

Add new RichRuleDesc model support to RichRuleHelpXamlBuilder

---

src/Core/DocumentationLinks.cs
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/XamlGenerator/XamlGeneratorHelper.cs

Update Clean Code documentation page link

---

nuget.config

Add information about DiffPlex to nuget.config comments

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Update embedded CFamily analyzer to 6.53.0.67215

---

src/SLCore.Listeners.UnitTests/SLCore.Listeners.UnitTests.csproj
src/SLCore.Listeners.UnitTests/packages.lock.json

Fix StreamJsonRpc version in integration tests

---

build/DownloadDependencies/CommonProperties.props
build/DownloadDependencies/JarProcessing.targets
src/EmbeddedSonarAnalyzer.props

Download SLOOP Binaries

---

build/DownloadDependencies/CommonProperties.props
build/DownloadDependencies/JarProcessing.targets
pipeline/azure-pipelines.yml

Unzip SLOOP Binary

---

src/SLCore.UnitTests/Service/Rules/GetEffectiveRuleDetailsResponseTests.cs
src/SLCore/Service/Rules/GetEffectiveRuleDetailsResponse.cs
src/SLCore/Service/Rules/IRulesRpcService.cs
src/SLCore/Service/Rules/ListAllStandaloneRulesDefinitionsResponse.cs
src/SLCore/Service/Rules/Models/AbstractRuleDto.cs
src/SLCore/Service/Rules/Models/EffectiveRuleDetailsDto.cs
src/SLCore/Service/Rules/Models/RuleDefinitionDto.cs

Add ListAllStandaloneRulesDefinitions to IRulesRpcService

---

src/SLCore.UnitTests/State/AliveConnectionTrackerTests.cs
src/SLCore.UnitTests/State/ServerConnectionsProviderTests.cs
src/SLCore/State/AliveConnectionTracker.cs
src/SLCore/State/ServerConnectionsProvider.cs

Extract ServerConnectionsProvider from AliveConnectionTracker

---

src/SLCore.IntegrationTests/SLCoreTestProcessRunner.cs
src/SLCore.UnitTests/Core/Process/SLCoreProcessFactoryTests.cs
src/SLCore/Core/Process/ISLCoreLocator.cs
src/SLCore/Core/Process/ISLCoreProcess.cs
src/SLCore/Core/Process/ISLCoreProcessFactory.cs
src/SLCore/Core/Process/SLCoreLaunchParameters.cs
src/SLCore/Core/Process/SLCoreProcess.cs
src/SLCore/Core/Process/SLCoreProcessFactory.cs

Add SLCoreProcessFactory & related classes

---

.gitignore
build/CopyDependencies/CopyDependencies.targets
src/Integration.Vsix/Integration.Vsix.csproj

Package the SLOOP

---

src/SLCore.IntegrationTests/DependencyLocator.cs
src/SLCore.IntegrationTests/InitializationTests.cs
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs
src/SLCore.IntegrationTests/SLCoreTestProcessRunner.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreRpcFactoryTests.cs
src/SLCore/ISLCoreRpcFactory.cs
src/SLCore/SLCoreHandle.cs

Move ITs to use SLCoreHandle, fix bug with double StartListening call

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/State/ActiveConfigScopeTracker.cs

Fix removing already removed config scope

---

src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs
src/Core/Notifications/Notification.cs
src/SLCore/Notification/ISloopRestartFailedNotificationService.cs

Make notification show once per session only if it's dismissed

---

src/Integration.Vsix.UnitTests/CFamily/CmdBuilderTests.cs
src/Integration.Vsix/CFamily/VcxProject/CmdBuilder.cs

Trim paths loaded from VS in solution mode

---

src/ConnectedMode.UnitTests/BranchMatcherTests.cs
src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
src/ConnectedMode/BranchMatcher.cs
src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/SonarQube.Client.Tests/SonarQubeService_GetProjectBranchesAsync.cs
src/SonarQube.Client/Api/V6_60/GetProjectBranchesRequest.cs
src/SonarQube.Client/Models/SonarQubeProjectBranch.cs

Short lived branches ignored on branch matching

---

src/ConnectedMode.UnitTests/BranchMatcherTests.cs
src/ConnectedMode/BranchMatcher.cs

Prioritise "Main" when matching branches

---

src/EmbeddedSonarAnalyzer.props
src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs

Update embedded JS/TS analyzer to 10.13.0.25911

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

Update embedded CFamily analyzer to 6.54.0.69031

---

src/SLCore.UnitTests/Listener/Visualization/ShowIssueParamsTests.cs
src/SLCore/Common/Models/TextRangeDto.cs
src/SLCore/Listener/Visualization/IShowInIdeListener.cs
src/SLCore/Listener/Visualization/Models/FlowDto.cs
src/SLCore/Listener/Visualization/Models/IssueDetailDto.cs
src/SLCore/Listener/Visualization/Models/LocationDto.cs
src/SLCore/Listener/Visualization/Models/TextRangeWithHashDto.cs
src/SLCore/Listener/Visualization/ShowIssueParams.cs

Add IShowInIdeListener

---

src/SLCore.Listeners.UnitTests/Implementation/ClientInfoListenerTests.cs
src/SLCore.Listeners/Implementation/ClientInfoListener.cs
src/SLCore/Listener/ClientInfo/GetClientLiveInfoResponse.cs
src/SLCore/Listener/ClientInfo/IClientInfoListener.cs

Add listener for getClientLiveInfo

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/State/ActiveConfigScopeTracker.cs

Add RootPath property to ConfigurationScope

---

src/IssueViz.Security/OpenInIDE_Hotspots/HotspotsList/OpenInIDEHotspotsToolWindow.cs
src/IssueViz.Security/Taint/TaintList/TaintToolWindow.cs
src/IssueViz.UnitTests/OpenInIDE/OpenInIdeFailureInfoBarTests.cs
src/IssueViz.UnitTests/OpenInIDE/OpenIssueInIdeHandlerTests.cs
src/IssueViz/OpenInIDE/IssueListIds.cs
src/IssueViz/OpenInIDE/OpenIssueInIdeHandler.cs
src/IssueViz/OpenInIde/OpenInIdeFailureInfoBar.cs
src/IssueViz/OpenInIde/OpenInIdeResources.Designer.cs
src/IssueViz/OpenInIde/OpenInIdeResources.resx

Add OpenIssueInIdeHandler, add IssueListIds

---

src/IssueViz.UnitTests/OpenInIDE/IssueDetailDtoToAnalysisIssueConverterTests.cs
src/IssueViz/OpenInIde/IssueDetailDtoToAnalysisIssueConverter.cs

Fix import for IssueDetailDtoToAnalysisIssueConverter

---

src/Core/ISolutionWorkspaceService.cs
src/Integration.UnitTests/LocalServices/SolutionWorkspaceServiceTests.cs
src/Integration/LocalServices/SolutionWorkspaceService.cs

Implemented ISolutionWorkspaceService

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/State/ActiveConfigScopeTracker.cs

Implemented RootPath ConfigurationScope in ActiveConfigScopeTracker

---

src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs
src/SLCore/Service/Lifecycle/Models/LanguageSpecificRequirements.cs

Update Sloop to 10.1.0.77731 release

---

src/EmbeddedSonarAnalyzer.props

Update embedded CFamily analyzer to 6.55.0.70177

---

.editorconfig

Add forcing license header check to editorconfig

---

src/EmbeddedSonarAnalyzer.props
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs

Update embedded JS/TS analyzer to 10.14.0.26080

---

src/TypeScript.UnitTests/NodeJSLocator/CompatibleNodeLocatorTests.cs
src/TypeScript/NodeJSLocator/CompatibleNodeLocator.cs
src/TypeScript/NodeJSLocator/Resources.Designer.cs
src/TypeScript/NodeJSLocator/Resources.resx

Fix ERR_NoCompatibleVersion message

---

src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.Listeners.UnitTests/Logging/LoggerListenerTests.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/SLCoreInstanceHandlerTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs
src/SLCore/Service/Lifecycle/Models/LanguageSpecificRequirements.cs
src/TestInfrastructure/Framework/TestLogger.cs
src/TypeScript.UnitTests/Analyzer/EslintBridgeAnalyzerTests.cs

Make LogVerbose in TestLogger assertable

---

src/SLCore.Listeners.UnitTests/Implementation/ListFilesListenerTests.cs
src/SLCore.Listeners/Implementation/ListFilesListener.cs

Remove leading slashes in relative paths

---

src/EmbeddedSonarAnalyzer.props

Update Sloop to 10.2.0.77934

---

src/Integration.UnitTests/Transition/MuteIssuesWindowServiceTests.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/Integration/Transition/MuteIssuesWindowService.cs
src/Integration/Transition/MuteWindowDialog.xaml
src/Integration/Transition/MuteWindowDialog.xaml.cs

Add formatting help below Mute Issue window's comment box

---

src/Core/SystemAbstractions/Timer/TimerWrapper.cs
src/SonarLint.Product.props
src/SonarLint.Test.props
src/TestInfrastructure/VsObjectModelMocks/DTEMock.cs

Add common usings into props file for the entire project (production + test code)

---

src/SLCore.UnitTests/Core/RpcDebuggerTests.cs
src/SLCore/Core/IRpcDebugger.cs

Remove RPC debug logs from production build

---

MarketPlaceFiles/VS2019/overview-2019.md

Add Deprecation announcement to SLVS 2019 Marketplace

---

src/EmbeddedSonarAnalyzer.props

Update Sloop to 10.2.0.78029 release

---

src/SLCore.UnitTests/State/ActiveConfigScopeTrackerTests.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx
src/SLCore/State/ActiveConfigScopeTracker.cs

Maintain RootPath when updating the current config scope

---

src/ConnectedMode/Binding/Suggestion/IBindingSuggestionHandler.cs
src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs
src/Integration/Binding/BindingStrings.Designer.cs
src/Integration/Binding/BindingStrings.resx
src/Integration/Binding/BindingSuggestionHandler.cs
src/SLCore.Listeners.UnitTests/Implementation/ConnectedModeSuggestionListenerTests.cs
src/SLCore.Listeners/Implementation/ConnectedModeSuggestionListener.cs
src/SLCore/Listener/Binding/AssistCreatingConnectionParams.cs
src/SLCore/Listener/Binding/AssistCreatingConnectionResponse.cs
src/SLCore/Listener/Binding/IConnectedModeSuggestionListener.cs
src/SLCore/Listener/Binding/NoBindingSuggestionFoundParams.cs

Handle Open in IDE on standalone mode

---

src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs
src/Infrastructure.VS/ErrorListHelper.cs

Implement a workaround for roslyn issues broken rule descriptions since VS 17.10

---

src/SLCore.Listeners/Implementation/BranchListener.cs

https://github.com/SonarSource/sonarlint-visualstudio/issues/5401

Add link to BranchListener doc strings with info about proper implementation

---

src/Core/DocumentationLinks.cs
src/IssueViz.UnitTests/OpenInIDE/OpenInIdeFailureInfoBarTests.cs
src/IssueViz.UnitTests/OpenInIDE/OpenInIdeNotificationTests.cs
src/IssueViz/OpenInIde/OpenInIdeFailureInfoBar.cs
src/IssueViz/OpenInIde/OpenInIdeNotification.cs
src/IssueViz/OpenInIde/OpenInIdeResources.Designer.cs
src/IssueViz/OpenInIde/OpenInIdeResources.resx

Add documentation link to OpenInIdeFailureInfoBar

---

src/SLCore/Core/IJsonRpc.cs
src/SLCore/Core/Process/SLCoreProcess.cs
src/SLCore/Core/Process/SLCoreProcessFactory.cs
src/SLCore/Service/Connection/DidChangeCredentialsParams.cs
src/SLCore/Service/Connection/DidUpdateConnectionsParams.cs
src/SLCore/Service/Connection/IConnectionConfigurationSLCoreService.cs
src/SLCore/Service/Project/Models/BindingConfigurationDto.cs
src/SLCore/Service/Project/Models/ConfigurationScopeDto.cs
src/SLCore/Service/Project/Params/DidAddConfigurationScopesParams.cs
src/SLCore/Service/Project/Params/DidUpdateBindingParams.cs
src/SLCore/Service/Rules/ListAllStandaloneRulesDefinitionsResponse.cs
src/SLCore/Service/Rules/Models/EffectiveRuleParamDto.cs
src/SLCore/Service/Rules/Models/RuleContextualSectionDto.cs
src/SLCore/Service/Rules/Models/RuleContextualSectionWithDefaultContextKeyDto.cs
src/SLCore/Service/Rules/Models/RuleDefinitionDto.cs
src/SLCore/Service/Rules/Models/RuleMonolithicDescriptionDto.cs

Remove code coverage exclusions from SLCore assembly

---

src/Core/DocumentationLinks.cs
src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs
src/Integration/Binding/BindingStrings.Designer.cs
src/Integration/Binding/BindingStrings.resx
src/Integration/Binding/BindingSuggestionHandler.cs

Add documentation link to BindingSuggestionHandler goldbar

---

src/Core.UnitTests/Analysis/IssueConsumerStorageTests.cs
src/Core/Analysis/IssueConsumerStorage.cs

SLVS-1181 Implement IIssueConsumerStorage

---

src/SLCore.Listeners.UnitTests/AnalysisListenerTests.cs
src/SLCore.Listeners/Implementation/AnalysisListener.cs
src/SLCore.UnitTests/Common/Helpers/MillisecondUnixTimestampDateTimeOffsetConverterTests.cs
src/SLCore/Common/Helpers/MillisecondUnixTimestampDateTimeOffsetConverter.cs
src/SLCore/Common/Models/FileEditDto.cs
src/SLCore/Common/Models/HotspotStatus.cs
src/SLCore/Common/Models/ImpactDto.cs
src/SLCore/Common/Models/IssueFlowDto.cs
src/SLCore/Common/Models/IssueLocationDto.cs
src/SLCore/Common/Models/QuickFixDto.cs
src/SLCore/Common/Models/TextEditDto.cs
src/SLCore/Common/Models/VulnerabilityProbability.cs
src/SLCore/Listener/Analysis/IAnalysisListener.cs
src/SLCore/Listener/Analysis/Models/RaisedFindingDto.cs
src/SLCore/Listener/Analysis/Models/RaisedHotspotDto.cs
src/SLCore/Listener/Analysis/Models/RaisedIssueDto.cs
src/SLCore/Listener/Analysis/RaiseHotspotsParams.cs
src/SLCore/Listener/Analysis/RaiseIssuesParams.cs

Fixes [SLVS-1174](https://sonarsource.atlassian.net/browse/SLVS-1174)
[SLVS-1174]: https://sonarsource.atlassian.net/browse/SLVS-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1174 Handle SLCore analysis results events - Create listener interfaces

---

src/SLCore.UnitTests/Service/Analysis/AnalyzeFilesAndTrackParamsTests.cs
src/SLCore.UnitTests/Service/Analysis/AnalyzeFilesResponseTests.cs
src/SLCore/Service/Analysis/AnalyzeFilesAndTrackParams.cs
src/SLCore/Service/Analysis/AnalyzeFilesResponse.cs
src/SLCore/Service/Analysis/IAnalysisSLCoreService.cs
src/SLCore/Service/Analysis/Models/RawIssueDto.cs
src/SLCore/Service/Analysis/Models/RawIssueFlowDto.cs
src/SLCore/Service/Analysis/Models/RawIssueLocationDto.cs

Fixes [SLVS-1173](https://sonarsource.atlassian.net/browse/SLVS-1173)
[SLVS-1173]: https://sonarsource.atlassian.net/browse/SLVS-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1173 Handle SLCore analysis events - Create IAnalysisSLCoreService

---

src/Integration.Vsix.UnitTests/SLCore/RaiseIssueParamsToAnalysisIssueConverterTests.cs
src/Integration.Vsix/SLCore/RaiseIssueParamsToAnalysisIssueConverter.cs
src/SLCore.UnitTests/Common/Helpers/ModelExtensionsTests.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseIssueParamsToAnalysisIssueConverterTests.cs
src/SLCore/Common/Helpers/ModelExtensions.cs
src/SLCore/Listener/Analysis/IRaiseIssueParamsToAnalysisIssueConverter.cs
src/SLCore/Listener/Analysis/RaiseIssueParamsToAnalysisIssueConverter.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx

SLVS-1176 Create RaiseIssuesParams to IAnalysisIssue Converter

---

src/SLCore.UnitTests/Service/File/AnalyzeFilesResponseTests.cs
src/SLCore.UnitTests/Service/File/GetFilesStatusParamsTests.cs
src/SLCore.UnitTests/Service/File/GetFilesStatusResponseTests.cs
src/SLCore/Service/File/DidUpdateFileSystemParams.cs
src/SLCore/Service/File/GetFilesStatusParams.cs
src/SLCore/Service/File/GetFilesStatusResponse.cs
src/SLCore/Service/File/IFileRpcSLCoreService.cs
src/SLCore/Service/File/Models/FileStatusDto.cs

Fixes [SLVS-1197](https://sonarsource.atlassian.net/browse/SLVS-1197)
[SLVS-1197]: https://sonarsource.atlassian.net/browse/SLVS-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1197 - Create service for SLCore FileRpcService

---

src/CFamily/Analysis/CFamilyAnalyzerOptions.cs
src/Core/Analysis/IAnalyzerOptions.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/SLCore.UnitTests/Analysis/SLCoreAnalyzerTests.cs
src/SLCore/Analysis/SLCoreAnalyzer.cs

SLVS-1200 SLCoreAnalyzer should ask to fetch server issues only on open

---

src/SLCore.Listeners.UnitTests/Implementation/GetBaseDirListenerTests.cs
src/SLCore.Listeners/Implementation/GetBaseDirListener.cs
src/SLCore.UnitTests/Listener/Files/GetBaseDirParamsTests.cs
src/SLCore.UnitTests/Listener/Files/GetBaseDirResponseTests.cs
src/SLCore/Listener/Files/GetBaseDirParams.cs
src/SLCore/Listener/Files/GetBaseDirResponse.cs
src/SLCore/Listener/Files/IGetBaseDirListener.cs

SLVS-1205 Handle getBaseDir request with default value (null)

---

src/SLCore.Listeners.UnitTests/Implementation/AnalysisListenerTests.cs
src/SLCore.Listeners/Implementation/AnalysisListener.cs

SLVS-1206 Request analysis for open files when Sloop is ready

---

src/EmbeddedSonarAnalyzer.props
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs

SLVS-1217 Disable Sloop analysis for non-migrated languages

---

src/Core/Analysis/IAnalysisStatusNotifierFactory.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisStatusNotifierTests.cs
src/Integration.Vsix/Analysis/AnalysisStatusNotifier.cs
src/Integration.Vsix/Analysis/AnalysisStatusNotifierFactory.cs
src/Integration.Vsix/Analysis/AnalysisStrings.Designer.cs
src/Integration.Vsix/Analysis/AnalysisStrings.resx
src/SLCore.Listeners.UnitTests/Implementation/AnalysisListenerTests.cs
src/SLCore.Listeners/Implementation/AnalysisListener.cs
src/TypeScript.UnitTests/Analyzer/CssAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs

SLVS-1218 Improve `raiseIssues` handling and `analysisId` logging

---

src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/SLCore.IntegrationTests/FileAnalysisTests.cs
src/SLCore.UnitTests/Common/Helpers/LanguageExtensionsTests.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/Common/Helpers/LanguageExtensions.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs

SLVS-1240 Disable SLCore analysis for non-migrated languages' plugins

---

src/Core.UnitTests/SystemAbstractions/DefaultCurrentTimeProviderTests.cs
src/Core/SystemAbstractions/ICurrentTimeProvider.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration.UnitTests/Telemetry/TelemetryPayloadCreatorTests.cs
src/Integration/Telemetry/TelemetryManager.cs
src/Integration/Telemetry/TelemetryPayloadCreator.cs
src/SLCore.UnitTests/Analysis/SLCoreAnalyzerTests.cs
src/SLCore/Analysis/SLCoreAnalyzer.cs

Use the ICurrentTimeProvider and made the DefaultCurrentTimeProvider Mef-exportable

SLVS-1216 Use ICurrentTimeProvider in SLCoreAnalyzer

---

src/Integration/SLCore/SLCoreConstantsProvider.cs
src/Integration/Telemetry/IdeVersionInformation.cs

NO-JIRA Re-add IdeVersionInformation that was deleted by mistake

---

src/Integration/LocalServices/FileTracker.cs

Fix FileTracker is accessing ActiveConfigScopeTracker without null check

SLVS-1252 FileTracker is accessing ConfigScope without null check

---

CODE_OF_CONDUCT.md

SLVS-1277 Remove dotnet@ from code of conduct

---

src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/FileAnalysisTests.cs
src/SLCore.IntegrationTests/Resources/TwoIssues.js
src/SLCore.IntegrationTests/SLCore.IntegrationTests.csproj
src/TypeScript.UnitTests/Analyzer/CssAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/JavaScriptAnalyzerTests.cs
src/TypeScript.UnitTests/Analyzer/TypeScriptAnalyzerTests.cs
src/TypeScript/Analyzer/CssAnalyzer.cs
src/TypeScript/Analyzer/JavaScriptAnalyzer.cs
src/TypeScript/Analyzer/TypeScriptAnalyzer.cs

SLVS-1268 Enable JavaScript, TypeScript and CSS analysis in SLCore

---

pipeline/azure-pipelines.yml

BUILD-6083: Fix jira build name in repox

BUILD-6083: Fix buildinfo params in repox

---

.cirrus.yaml
.cirrus/publish-dogfood-site.sh

BUILD-6085: Dogfooding task

---

src/ConnectedMode.UnitTests/UI/OrganizationSelection/OrganizationSelectionViewModelTests.cs
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionDialog.xaml
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionDialog.xaml.cs
src/ConnectedMode/UI/OrganizationSelection/OrganizationSelectionViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

This PR targets the [load organizations PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5629) and shows the loaded in the UI

SLVS-1417 Show organizations list in the UI

---

.cirrus.yaml

[BUILD-6078](https://sonarsource.atlassian.net/browse/BUILD-6078)
[BUILD-6078]: https://sonarsource.atlassian.net/browse/BUILD-6078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6078 Sign artifacts

---

src/ConnectedMode.UnitTests/Migration/MigrationCheckerTests.cs
src/ConnectedMode/Migration/IObsoleteConfigurationProvider.cs
src/Core/Binding/LegacyBindingConfiguration.cs

[SLVS-1410](https://sonarsource.atlassian.net/browse/SLVS-1410)
Preparation for [SLVS-1411](https://sonarsource.atlassian.net/browse/SLVS-1411)
[SLVS-1410]: https://sonarsource.atlassian.net/browse/SLVS-1410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-1411]: https://sonarsource.atlassian.net/browse/SLVS-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1410 Split IObsoleteConfigurationProvider from IConfigurationProvider

---

src/ConnectedMode.UnitTests/Binding/UnintrusiveConfigurationProviderTests.cs
src/ConnectedMode.UnitTests/Migration/MigrationCheckerTests.cs
src/ConnectedMode.UnitTests/QualityProfiles/QualityProfileUpdaterTests.cs
src/ConnectedMode.UnitTests/ServerBranchProviderTests.cs
src/ConnectedMode.UnitTests/ServerQueryInfoProviderTests.cs
src/ConnectedMode/Binding/UnintrusiveConfigurationProvider.cs
src/ConnectedMode/QualityProfiles/QualityProfileUpdater.cs
src/ConnectedMode/ServerBranchProvider.cs
src/ConnectedMode/ServerQueryInfoProvider.cs
src/Core/Binding/BoundServerProject.cs
src/Core/Binding/IConfigurationProvider.cs
src/Integration.UnitTests/Binding/BindingControllerTests.cs
src/Integration.UnitTests/Exclusions/ExclusionSettingsStorageTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/VsSessionHostTests.cs
src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs
src/Integration/Exclusions/ExclusionSettingsStorage.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/VsSessionHost.cs
src/IssueViz.Security.UnitTests/Taint/TaintIssuesSynchronizerTests.cs
src/IssueViz.Security/Taint/TaintIssuesSynchronizer.cs
src/IssueViz.UnitTests/Helpers/ShowInBrowserServiceTests.cs
src/IssueViz/Helpers/ShowInBrowserService.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs

[SLVS-1411](https://sonarsource.atlassian.net/browse/SLVS-1411)
Part of 
[SLVS-1411]: https://sonarsource.atlassian.net/browse/SLVS-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1411 Use BoundServerProject model in IConfigurationProvider

---

src/ConnectedMode.UnitTests/Migration/ObsoleteConfigurationProviderTests.cs
src/ConnectedMode.UnitTests/Persistence/SolutionBindingRepositoryTests.cs
src/ConnectedMode/Migration/ObsoleteConfigurationProvider.cs
src/ConnectedMode/Persistence/SolutionBindingRepository.cs
src/Core/Binding/ISolutionBindingRepository.cs

[SLVS-1422](https://sonarsource.atlassian.net/browse/SLVS-1422)
[SLVS-1422]: https://sonarsource.atlassian.net/browse/SLVS-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1422 Split ISolutionBindingRepository and ILegacySolutionBindingRepository

---

.cirrus.yaml
pipeline/azure-pipelines.yml

BUILD-6080: Implement sonarcloud analysis

BUILD-6080: Implement sonarcloud analysis

---

.github/workflows/release.yaml
MarketPlaceFiles/VS2022Test/manifest-2022.json
MarketPlaceFiles/VS2022Test/overview-2022.md

BUILD-6086: Release pipeline to push to test project

BUILD-6086: Release pipeline to push to test project

---

.cirrus.yaml

[BUILD-6079](https://sonarsource.atlassian.net/browse/BUILD-6079)
[BUILD-6079]: https://sonarsource.atlassian.net/browse/BUILD-6079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6079 Deploy to repox

---

.cirrus.star
.cirrus.yaml
.cirrus/publish-dogfood-site.sh
build/DownloadDependencies/JarProcessing.targets
pipeline/azure-pipelines.yml
src/CFamily.UnitTests/Subprocess/ProcessRunnerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/CancellableJobRunnerTests.cs
src/SLCore.IntegrationTests/RuleConfigurationAnalysisTests.cs
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs
src/SLCore.IntegrationTests/SimpleAnalysisTests.cs

[BUILD-6068](https://sonarsource.atlassian.net/browse/BUILD-6068)
Part of 
[BUILD-6068]: https://sonarsource.atlassian.net/browse/BUILD-6068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6068 Migration to Cirrus CI

---

src/EmbeddedSonarAnalyzer.props
src/Integration.Vsix.UnitTests/CFamily/CFamilyEmbeddedSonarWayRulesTests.cs

[SLVS-1416](https://sonarsource.atlassian.net/browse/SLVS-1416)
[SLVS-1416]: https://sonarsource.atlassian.net/browse/SLVS-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1416 Upgrade CFamily analyzer to 6.58.0.74356

---

build/DownloadDependencies/CommonProperties.props

[SLVS-1438](https://sonarsource.atlassian.net/browse/SLVS-1438)
[SLVS-1438]: https://sonarsource.atlassian.net/browse/SLVS-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1438 Download analyzers from repox

---

src/Integration.Vsix.UnitTests/Settings/SonarLintSettingsTests.cs
src/Integration.Vsix/Settings/SonarLintSettings.cs

[SLVS-1440](https://sonarsource.atlassian.net/browse/SLVS-1440)
[SLVS-1440]: https://sonarsource.atlassian.net/browse/SLVS-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1440 Fix Options page crashes VS

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1441](https://sonarsource.atlassian.net/browse/SLVS-1441)
[SLVS-1441]: https://sonarsource.atlassian.net/browse/SLVS-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1441 Update SLCore to 10.5.0.78949

---

src/ConnectedMode.UnitTests/Persistence/BindingDtoConverterTests.cs
src/ConnectedMode.UnitTests/Persistence/BindingDtoSerializationTests.cs
src/ConnectedMode.UnitTests/Persistence/BoundSonarQubeProjectTests.cs
src/ConnectedMode/Persistence/BindingDto.cs
src/ConnectedMode/Persistence/BindingDtoConverter.cs

[SLVS-1446](https://sonarsource.atlassian.net/browse/SLVS-1446)
[SLVS-1446]: https://sonarsource.atlassian.net/browse/SLVS-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1446 Add BindingDto model & serialization

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml

[SLVS-1451](https://sonarsource.atlassian.net/browse/SLVS-1451)
Part of BUILD-6119
[SLVS-1451]: https://sonarsource.atlassian.net/browse/SLVS-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1451 Jira integration: Use repo vault token

---

.cirrus.yaml

[BUILD-6166](https://sonarsource.atlassian.net/browse/BUILD-6166)
Use sonarlint-visualstudio image and remove installation commands
[BUILD-6166]: https://sonarsource.atlassian.net/browse/BUILD-6166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6166 Use sonarlint-visualstudio image

---

src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/ProjectSelection/ProjectSelectionDialog.xaml

[SLVS-1452](https://sonarsource.atlassian.net/browse/SLVS-1452)
* ManageBinding: Unbind button
* ManageBinding: Export button
* ManageConnections: Edit button
* ManageConnections: Smart notifications checkbox
* ProjectSelection: Search field
[SLVS-1452]: https://sonarsource.atlassian.net/browse/SLVS-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1452 Hide features not supported initially

---

src/ConnectedMode/Persistence/ServerConnectionJsonModel.cs

[SLVS-1469](https://sonarsource.atlassian.net/browse/SLVS-1469)
[SLVS-1469]: https://sonarsource.atlassian.net/browse/SLVS-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1469 Fix typo in json model

---

src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/Resources/CheckImage.xaml
src/ConnectedMode/UI/Resources/TrashCanImage.xaml

[SLVS-1467](https://sonarsource.atlassian.net/browse/SLVS-1467)
Part of 
[SLVS-1467]: https://sonarsource.atlassian.net/browse/SLVS-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1467 Fix icons not visible on dark theme

---

src/CFamily.UnitTests/Subprocess/ProcessRunnerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/CancellableJobRunnerTests.cs
src/SLCore.IntegrationTests/RuleConfigurationAnalysisTests.cs
src/SLCore.IntegrationTests/RuleDescriptionConversionSmokeTest.cs
src/SLCore.IntegrationTests/SimpleAnalysisTests.cs

[SLVS-1428](https://sonarsource.atlassian.net/browse/SLVS-1428)
[SLVS-1428]: https://sonarsource.atlassian.net/browse/SLVS-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1428 Integration tests with flaky behavior on Cirrus-CI

---

.cirrus.yaml

[BUILD-6437](https://sonarsource.atlassian.net/browse/BUILD-6437)
[BUILD-6437]: https://sonarsource.atlassian.net/browse/BUILD-6437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-6437 fix dogfooding task

---

src/ConnectedMode/UI/DeleteConnection/PreventDeleteConnectionDialog.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ServerSelection/ServerSelectionDialog.xaml
src/Core/DocumentationLinks.cs

[SLVS-1471](https://sonarsource.atlassian.net/browse/SLVS-1471)
[SLVS-1471]: https://sonarsource.atlassian.net/browse/SLVS-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1471 Move URLs into constant

---

src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/Service/Lifecycle/Models/FeatureFlagsDto.cs

[SLVS-1485](https://sonarsource.atlassian.net/browse/SLVS-1485)
[SLVS-1485]: https://sonarsource.atlassian.net/browse/SLVS-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1485 Enable FixSuggestion feature flag

---

src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs

[SLVS-1506](https://sonarsource.atlassian.net/browse/SLVS-1506)
[SLVS-1506]: https://sonarsource.atlassian.net/browse/SLVS-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1506 Fix typo in CreteConnectionInfoFromSharedBinding

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1458](https://sonarsource.atlassian.net/browse/SLVS-1458)
[SLVS-1458]: https://sonarsource.atlassian.net/browse/SLVS-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1458 Update CFamily analyzer to 6.59.0.75237

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1468](https://sonarsource.atlassian.net/browse/SLVS-1468)
[SLVS-1468]: https://sonarsource.atlassian.net/browse/SLVS-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1468 Update SonarJS analyzer to 10.16.0.27621

---

src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ProjectSelection/ProjectSelectionViewModelTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/SlCoreConnectionAdapter.cs
src/ConnectedMode/UI/ProjectSelection/ProjectSelectionDialog.xaml
src/ConnectedMode/UI/ProjectSelection/ProjectSelectionViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-1387](https://sonarsource.atlassian.net/browse/SLVS-1387)
[SLVS-1387]: https://sonarsource.atlassian.net/browse/SLVS-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1387 Project Selection Dialog: User should be able to search for a project

---

src/Integration.Vsix/Integration.Vsix.csproj

[SLVS-1514](https://sonarsource.atlassian.net/browse/SLVS-1514)
[SLVS-1514]: https://sonarsource.atlassian.net/browse/SLVS-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1514 Put embedded sonar dotnet analyzers in a subfolder within vsix during build

---

src/ConnectedMode.UnitTests/Migration/MigrationCheckerTests.cs
src/Core/IActiveSolutionTracker.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs

[SLVS-1524](https://sonarsource.atlassian.net/browse/SLVS-1524)
Part of SLVS-1496
[SLVS-1524]: https://sonarsource.atlassian.net/browse/SLVS-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1524 Add Solution name tracking to ActiveSolutionTracker

---

src/Infrastructure.VS/Roslyn/AnalyzerAssemblyLoaderFactory.cs

[SLVS-1513](https://sonarsource.atlassian.net/browse/SLVS-1513)
[SLVS-1513]: https://sonarsource.atlassian.net/browse/SLVS-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1513 Implement IAnalyzerAssemblyLoader

---

src/Integration.Vsix.UnitTests/SLCore/SLCoreEmbeddedPluginJarLocatorTests.cs
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/SLCore/SLCoreEmbeddedPluginJarLocator.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore/Configuration/ISLCoreEmbeddedPluginJarLocator.cs
src/SLCore/ISLCoreInstanceHandle.cs

[SLVS-1541](https://sonarsource.atlassian.net/browse/SLVS-1541)
[SLVS-1541]: https://sonarsource.atlassian.net/browse/SLVS-1541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1541 Fix secrets analysis not working in connected mode for SQ 9.9.1

---

src/Integration.Vsix.UnitTests/SLCore/SLCoreEmbeddedPluginJarLocatorTests.cs

[SLVS-1546](https://sonarsource.atlassian.net/browse/SLVS-1546)
[SLVS-1546]: https://sonarsource.atlassian.net/browse/SLVS-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1546 Clean up SLCoreEmbeddedPluginJarLocatorTests

---

src/SLCore.UnitTests/Service/Analysis/ShouldUseEnterpriseCSharpAnalyzerParamsTests.cs
src/SLCore.UnitTests/Service/Analysis/ShouldUseEnterpriseCSharpAnalyzerResponseTests.cs
src/SLCore/Service/Analysis/IRoslynAnalyzerService.cs
src/SLCore/Service/Analysis/Models/ShouldUseEnterpriseCSharpAnalyzerParams.cs
src/SLCore/Service/Analysis/Models/ShouldUseEnterpriseCSharpAnalyzerResponse.cs

[SLVS-1543](https://sonarsource.atlassian.net/browse/SLVS-1543)
[SLVS-1543]: https://sonarsource.atlassian.net/browse/SLVS-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1543 Add shouldUseEnterpriseCSharpAnalyzer SlCore RPC method

---

src/Infrastructure.VS/Roslyn/AnalyzerAssemblyLoaderFactory.cs

[SLVS-1556](https://sonarsource.atlassian.net/browse/SLVS-1556)
[SLVS-1556]: https://sonarsource.atlassian.net/browse/SLVS-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1556 Fix analyzers not loaded

---

src/Infrastructure.VS.UnitTests/Roslyn/RoslynSolutionWrapperTests.cs
src/Infrastructure.VS.UnitTests/Roslyn/SolutionRoslynAnalyzerManagerTests.cs
src/Infrastructure.VS/Roslyn/IRoslynSolutionWrapper.cs
src/Infrastructure.VS/Roslyn/SolutionRoslynAnalyzerManager.cs

[SLVS-1557](https://sonarsource.atlassian.net/browse/SLVS-1557)
Side effect: fixes SonarDiagnosticSuppressor not being executed
[SLVS-1557]: https://sonarsource.atlassian.net/browse/SLVS-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1557 Fix analyzers being replaced rather than added

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1533](https://sonarsource.atlassian.net/browse/SLVS-1533)
[SLVS-1533]: https://sonarsource.atlassian.net/browse/SLVS-1533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1533 Update CFamily analyzer to 6.60.0.76379

---

src/Infrastructure.VS.UnitTests/Roslyn/ConnectedModeRoslynAnalyzerProviderTests.cs
src/Infrastructure.VS.UnitTests/Roslyn/SolutionRoslynAnalyzerManagerTests.cs
src/Infrastructure.VS/Roslyn/ConnectedModeRoslynAnalyzerProvider.cs
src/Infrastructure.VS/Roslyn/IConnectedModeRoslynAnalyzerProvider.cs
src/Infrastructure.VS/Roslyn/SolutionRoslynAnalyzerManager.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-1553](https://sonarsource.atlassian.net/browse/SLVS-1553)
Depends on[ this PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/5775), because both PRs incorporate changes of IConnectedModeRoslynAnalyzerProvider
[SLVS-1553]: https://sonarsource.atlassian.net/browse/SLVS-1553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1553 Update IConnectedModeRoslynAnalyzerProvider.GetOrNull method signature

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1572](https://sonarsource.atlassian.net/browse/SLVS-1572)
Part of SLVS-1497
[SLVS-1572]: https://sonarsource.atlassian.net/browse/SLVS-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1572 Change SLCore version to repackaging branch build

---

src/ConnectedMode.UnitTests/Binding/Suggestion/SuggestSharedBindingGoldBarTests.cs
src/ConnectedMode/Binding/Suggestion/SuggestSharedBindingGoldBar.cs
src/Core.UnitTests/Notifications/NotificationServiceTests.cs
src/Core/Notifications/INotificationService.cs
src/Core/Notifications/Notification.cs
src/EmbeddedSonarAnalyzer.props
src/Integration.UnitTests/Binding/BindingSuggestionHandlerTests.cs
src/Integration.UnitTests/MefServices/SharedBindingSuggestionServiceTests.cs
src/Integration/Binding/BindingSuggestionHandler.cs
src/Integration/MefServices/SharedBindingSuggestionService.cs
src/SLCore.UnitTests/NodeJS/Notifications/UnsupportedNodeVersionNotificationServiceTests.cs
src/SLCore.UnitTests/Notification/SloopRestartFailedNotificationServiceTests.cs
src/SLCore/NodeJS/Notifications/IUnsupportedNodeVersionNotificationService.cs
src/SLCore/Notification/ISloopRestartFailedNotificationService.cs

[SLVS-1534](https://sonarsource.atlassian.net/browse/SLVS-1534)
[SLVS-1534]: https://sonarsource.atlassian.net/browse/SLVS-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1534 [Visual Studio] Hardening 2024 Q4 #2

---

src/AssemblyInfo.Shared.cs
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

[SLVS-1574](https://sonarsource.atlassian.net/browse/SLVS-1574)
[SLVS-1574]: https://sonarsource.atlassian.net/browse/SLVS-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1574 Update product name in Assembly and manifest

---

src/ConnectedMode/Binding/FilePathAndContent.cs

[SLVS-1603](https://sonarsource.atlassian.net/browse/SLVS-1603)
[SLVS-1603]: https://sonarsource.atlassian.net/browse/SLVS-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1603 Fix S2955 Reliability issue on FilePathAndContent.cs

---

src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[MMF-4041](https://sonarsource.atlassian.net/browse/MMF-4041)
[MMF-4041]: https://sonarsource.atlassian.net/browse/MMF-4041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MMF-4041 [Visual Studio] Edit credentials within the new Connected Mode UI

---

src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs

[SLVS-1608](https://sonarsource.atlassian.net/browse/SLVS-1608)
[SLVS-1608]: https://sonarsource.atlassian.net/browse/SLVS-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1608 Fix Quality Gate caused by issue CS9124

---

THIRD-PARTY-NOTICES

[SLVS-1547](https://sonarsource.atlassian.net/browse/SLVS-1547)
[SLVS-1547]: https://sonarsource.atlassian.net/browse/SLVS-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1547 Add notice to LGPL license regarding C# analyzer

---

src/Integration.UnitTests/Notifications/NotificationIndicatorViewModelTests.cs
src/Integration.Vsix/SonarLintNotificationsPackage.cs
src/Integration/Notifications/INotificationIndicatorViewModel.cs
src/Integration/Notifications/NotificationIndicator.xaml
src/Integration/Notifications/NotificationIndicatorViewModel.cs

[SLVS-1607](https://sonarsource.atlassian.net/browse/SLVS-1607)
[SLVS-1607]: https://sonarsource.atlassian.net/browse/SLVS-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1607 Show SonarQube Server or SonarQube Cloud icon conditionally

---

src/SLCore.Listeners.UnitTests/Implementation/Analysis/RaisedFindingProcessorTests.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseFindingToAnalysisIssueConverterTests.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseIssuesParamsTests.cs
src/SLCore/Listener/Analysis/Models/RaisedFindingDto.cs
src/SLCore/Listener/Analysis/Models/RaisedHotspotDto.cs
src/SLCore/Listener/Analysis/Models/RaisedIssueDto.cs
src/SLCore/Listener/Analysis/RaiseFindingToAnalysisIssueConverter.cs

[SLVS-1589](https://sonarsource.atlassian.net/browse/SLVS-1589)
[SLVS-1589]: https://sonarsource.atlassian.net/browse/SLVS-1589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1589 Update RaisedFindingDto to support new MQR/Std mode with overrides from SLCore

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1606](https://sonarsource.atlassian.net/browse/SLVS-1606)
[SLVS-1606]: https://sonarsource.atlassian.net/browse/SLVS-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1606 Update SLCore to 10.9 release

---

MarketPlaceFiles/VS2022/overview-2022.md

[SLVS-1576](https://sonarsource.atlassian.net/browse/SLVS-1576)
[SLVS-1576]: https://sonarsource.atlassian.net/browse/SLVS-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1576 Update product name in marketplace

---

src/Integration.Vsix/SonarLint.vsct
src/Integration.Vsix/SonarLintIntegrationPackage.cs

[SLVS-1619](https://sonarsource.atlassian.net/browse/SLVS-1619)
[SLVS-1619]: https://sonarsource.atlassian.net/browse/SLVS-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1619 Rename missing rebranding references

---

src/Core/Analysis/AnalysisIssue.cs
src/Core/Analysis/CleanCodeTaxonomy.cs
src/Core/Analysis/IAnalysisIssue.cs
src/Education/Rule/SLCoreRuleMetaDataProvider.cs
src/Integration.Vsix.UnitTests/CFamily/CFamilyIssueToAnalysisIssueConverterTests.cs
src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
src/Integration.Vsix/CFamily/CFamilyIssueToAnalysisIssueConverter.cs
src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
src/IssueViz.UnitTests/Helpers/AnalysisSeverityToVsSeverityConverterTests.cs
src/IssueViz/Helpers/IAnalysisSeverityToVsSeverityConverter.cs
src/SLCore.UnitTests/Common/Helpers/ModelConversionExtensionsTests.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseFindingToAnalysisIssueConverterTests.cs
src/SLCore/Common/Helpers/ModelConversionExtensions.cs
src/SLCore/Listener/Analysis/RaiseFindingToAnalysisIssueConverter.cs
src/TestInfrastructure/DummyAnalysisIssue.cs

[SLVS-1614](https://sonarsource.atlassian.net/browse/SLVS-1614)
[SLVS-1614]: https://sonarsource.atlassian.net/browse/SLVS-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1614 Fix Category in the error list for MQR mode

---

src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
src/ConnectedMode/StatefulServerBranchProvider.cs
src/Core/IServerBranchProvider.cs
src/SLCore.Listeners.UnitTests/BranchListenerTests.cs
src/SLCore.Listeners/Implementation/BranchListener.cs
src/SLCore/Service/Branch/ISonarProjectBranchSlCoreService.cs

[SLVS-1602](https://sonarsource.atlassian.net/browse/SLVS-1602)
[SLVS-1602]: https://sonarsource.atlassian.net/browse/SLVS-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1602 Improve branch-awareness for SLCore integration

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1635](https://sonarsource.atlassian.net/browse/SLVS-1635)
[SLVS-1635]: https://sonarsource.atlassian.net/browse/SLVS-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1635 Update SLCore to 10.10.0.79572

---

src/Integration.Vsix/ErrorList/IssuesSnapshot.cs

[SLVS-1642](https://sonarsource.atlassian.net/browse/SLVS-1642)
Part of 
[SLVS-1642]: https://sonarsource.atlassian.net/browse/SLVS-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1642 QualityGate: Make IssuesSnapshot.ToString a static method

---

src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
src/Infrastructure.VS.UnitTests/ErrorListHelperTests.cs

[SLVS-1657](https://sonarsource.atlassian.net/browse/SLVS-1657)
Part of SLVS-1568
[SLVS-1657]: https://sonarsource.atlassian.net/browse/SLVS-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1657 Fix unit tests after rebase

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1655](https://sonarsource.atlassian.net/browse/SLVS-1655)
[SLVS-1655]: https://sonarsource.atlassian.net/browse/SLVS-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1655 Update Sonar Dotnet to 10.3.0.106239

---

MarketPlaceFiles/VS2022/overview-2022.md
THIRD-PARTY-NOTICES

[SLVS-1636](https://sonarsource.atlassian.net/browse/SLVS-1636)
[SLVS-1636]: https://sonarsource.atlassian.net/browse/SLVS-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1636 Update THIRD-PARTY-LICENSES.txt

---

src/Integration.Vsix.UnitTests/CFamily/VcxProject/FileConfigProviderTests.cs
src/Integration.Vsix/CFamily/VcxProject/FileConfigProvider.cs

[SLVS-1665](https://sonarsource.atlassian.net/browse/SLVS-1665)
Part of SLVS-1637
[SLVS-1665]: https://sonarsource.atlassian.net/browse/SLVS-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1665 Make FileConfigProvider mef-exporting

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1667](https://sonarsource.atlassian.net/browse/SLVS-1667)
[SLVS-1667]: https://sonarsource.atlassian.net/browse/SLVS-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1667 Update SonarJS to 10.18.0.28572

---

THIRD-PARTY-NOTICES

[SLVS-1676](https://sonarsource.atlassian.net/browse/SLVS-1676)
[SLVS-1676]: https://sonarsource.atlassian.net/browse/SLVS-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1676 Add `sonar-cfamily` to the enterprise plugin list in THIRD-PARTY-NOTICES

---

src/ConnectedMode/Persistence/SolutionBindingRepository.cs
src/Core/Binding/ISolutionBindingRepository.cs

[SLVS-1403](https://sonarsource.atlassian.net/browse/SLVS-1403)
[SLVS-1403]: https://sonarsource.atlassian.net/browse/SLVS-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1403 Add DeleteBinding method to ISolutionBindingRepository

---

src/ConnectedMode.UnitTests/Persistence/SolutionBindingFileLoaderTests.cs
src/ConnectedMode.UnitTests/Persistence/SolutionBindingRepositoryTests.cs
src/ConnectedMode/Persistence/ISolutionBindingFileLoader.cs
src/ConnectedMode/Persistence/PersistenceStrings.Designer.cs
src/ConnectedMode/Persistence/PersistenceStrings.resx
src/ConnectedMode/Persistence/SolutionBindingFileLoader.cs
src/ConnectedMode/Persistence/SolutionBindingRepository.cs
src/Core/Binding/ISolutionBindingRepository.cs

[SLVS-1404](https://sonarsource.atlassian.net/browse/SLVS-1404)
[SLVS-1404]: https://sonarsource.atlassian.net/browse/SLVS-1404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1404 Implement DeleteBinding method in SolutionBindingRepository

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1681](https://sonarsource.atlassian.net/browse/SLVS-1681)
[SLVS-1681]: https://sonarsource.atlassian.net/browse/SLVS-1681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1681 Update Sloop to 10.11.1.79701

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1684](https://sonarsource.atlassian.net/browse/SLVS-1684)
[SLVS-1684]: https://sonarsource.atlassian.net/browse/SLVS-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1684 Update SlCore to 10.11.2.79730

---

src/ConnectedMode.UnitTests/Suppressions/ServerIssuesStoreTests.cs
src/ConnectedMode.UnitTests/Suppressions/SuppressionIssueStoreUpdaterTests.cs
src/ConnectedMode/Suppressions/IServerIssuesStore.cs
src/ConnectedMode/Suppressions/ServerIssuesStore.cs
src/ConnectedMode/Suppressions/SuppressionIssueStoreUpdater.cs

[SLVS-1687](https://sonarsource.atlassian.net/browse/SLVS-1687)
[SLVS-1687]: https://sonarsource.atlassian.net/browse/SLVS-1687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1687 Reset suppressions from store on unbind

---

src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/RoslynSettingsFileStorageTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/Resources/Strings.Designer.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/Resources/Strings.resx
src/Roslyn.Suppressions/Roslyn.Suppressions/SettingsFile/RoslynSettingsFileStorage.cs

[SLVS-1680](https://sonarsource.atlassian.net/browse/SLVS-1680)
Part of 
[SLVS-1680]: https://sonarsource.atlassian.net/browse/SLVS-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1680 Remove Roslyn suppressions file on unbind

---

.cirrus/sonarqube-cloud-analysis.sh

[SLVS-1707](https://sonarsource.atlassian.net/browse/SLVS-1707)
[SLVS-1707]: https://sonarsource.atlassian.net/browse/SLVS-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1707 Update SonarQube Cloud analysis sh

---

src/Core.UnitTests/RuleSettingsSerializerTests.cs
src/Core/UserRuleSettings/RulesSettings.cs
src/SLCore.UnitTests/Service/Analysis/AnalyzeFilesResponseTests.cs
src/SLCore/Service/Analysis/Models/RawIssueDto.cs

[SLVS-1291](https://sonarsource.atlassian.net/browse/SLVS-1291)
[SLVS-1291]: https://sonarsource.atlassian.net/browse/SLVS-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1291 Remove IssueSeverity from RuleSettings

---

.cirrus/sonarqube-cloud-analysis.sh

[SLVS-1711](https://sonarsource.atlassian.net/browse/SLVS-1711)
[SLVS-1711]: https://sonarsource.atlassian.net/browse/SLVS-1711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1711 Fix branch analysis

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1682](https://sonarsource.atlassian.net/browse/SLVS-1682)
[SLVS-1682]: https://sonarsource.atlassian.net/browse/SLVS-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1682 Update SonarJS analyzer to 10.19.0.29100

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1730](https://sonarsource.atlassian.net/browse/SLVS-1730)
[SLVS-1730]: https://sonarsource.atlassian.net/browse/SLVS-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1730 Update SlCore to 10.12.1.79852

---

src/EmbeddedSonarAnalyzer.props
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/Models/JsTsRequirementsDto.cs

[SLVS-1713](https://sonarsource.atlassian.net/browse/SLVS-1713)
[SLVS-1713]: https://sonarsource.atlassian.net/browse/SLVS-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1713 [Visual Studio] Hardening 2024 Q4 #6

---

src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/packages.lock.json

[SLVS-1725](https://sonarsource.atlassian.net/browse/SLVS-1725)
[SLVS-1725]: https://sonarsource.atlassian.net/browse/SLVS-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1725 Update Microsoft.VSSDK.BuildTools nuget package

---

src/CFamily.UnitTests/packages.lock.json
src/CFamily/packages.lock.json
src/ConnectedMode.UnitTests/packages.lock.json
src/ConnectedMode/packages.lock.json
src/Core.UnitTests/packages.lock.json
src/Core/Core.csproj
src/Core/packages.lock.json
src/Education.UnitTests/packages.lock.json
src/Education/packages.lock.json
src/Infrastructure.VS.UnitTests/packages.lock.json
src/Infrastructure.VS/packages.lock.json
src/Integration.TeamExplorer.UnitTests/packages.lock.json
src/Integration.TeamExplorer/packages.lock.json
src/Integration.UnitTests/packages.lock.json
src/Integration.Vsix.UnitTests/packages.lock.json
src/Integration.Vsix/packages.lock.json
src/Integration/packages.lock.json
src/IssueViz.Security.UnitTests/packages.lock.json
src/IssueViz.Security/packages.lock.json
src/IssueViz.UnitTests/packages.lock.json
src/IssueViz/packages.lock.json
src/Progress.UnitTests/packages.lock.json
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/packages.lock.json
src/Roslyn.Suppressions/Roslyn.Suppressions/packages.lock.json
src/SLCore.IntegrationTests/packages.lock.json
src/SLCore.Listeners.UnitTests/packages.lock.json
src/SLCore.Listeners/packages.lock.json
src/SLCore.UnitTests/packages.lock.json
src/SLCore/packages.lock.json
src/TestInfrastructure/packages.lock.json

[SLVS-1733](https://sonarsource.atlassian.net/browse/SLVS-1733)
[SLVS-1733]: https://sonarsource.atlassian.net/browse/SLVS-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1733 Add System.Collections.Immutable reference to Core

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1727](https://sonarsource.atlassian.net/browse/SLVS-1727)
[SLVS-1727]: https://sonarsource.atlassian.net/browse/SLVS-1727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1727 Update CFamily analyzer to 6.62.0.78645

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1715](https://sonarsource.atlassian.net/browse/SLVS-1715)
[SLVS-1715]: https://sonarsource.atlassian.net/browse/SLVS-1715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1715 Update SonarText analyzer to 2.20.0.5038

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1755](https://sonarsource.atlassian.net/browse/SLVS-1755)
[SLVS-1755]: https://sonarsource.atlassian.net/browse/SLVS-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1755 Update SonarJS analyzer to 10.20.0.29356

---

src/Integration.UnitTests/LocalServices/SolutionWorkspaceServiceTests.cs
src/Integration/LocalServices/SolutionWorkspaceService.cs

[SLVS-1653](https://sonarsource.atlassian.net/browse/SLVS-1653)
[SLVS-1653]: https://sonarsource.atlassian.net/browse/SLVS-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1653 Use IVsUIServiceOperation in SolutionWorkspaceService

---

.cirrus.yaml
src/SLCore.IntegrationTests/FileAnalysisTestsRunner.cs
src/SLCore.IntegrationTests/Resources/CFamilyIssues.cpp
src/SLCore.IntegrationTests/SLCore.IntegrationTests.csproj
src/SLCore.IntegrationTests/SimpleAnalysisTests.cs

[SLVS-1660](https://sonarsource.atlassian.net/browse/SLVS-1660)
[SLVS-1660]: https://sonarsource.atlassian.net/browse/SLVS-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1660 Create integration tests for CFamily

---

src/ConnectedMode/UI/Credentials/CredentialsViewModel.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration/MefServices/ActiveSolutionTracker.cs

[SLVS-1762](https://sonarsource.atlassian.net/browse/SLVS-1762)
[SLVS-1762]: https://sonarsource.atlassian.net/browse/SLVS-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1762 Remove unused fields

---

src/Core/DocumentationLinks.cs

[SLVS-1760](https://sonarsource.atlassian.net/browse/SLVS-1760)
[SLVS-1760]: https://sonarsource.atlassian.net/browse/SLVS-1760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1760 Update link to "Advanced Configuration" documentation page

---

src/Education.UnitTests/XamlGenerator/RuleHelpXamlTranslatorTests.cs
src/Education/XamlGenerator/RuleHelpXamlTranslator.cs

[SLVS-1600](https://sonarsource.atlassian.net/browse/SLVS-1600)
[SLVS-1600]: https://sonarsource.atlassian.net/browse/SLVS-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1600 Fix rule description for S3516 not formatted correctly

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1768](https://sonarsource.atlassian.net/browse/SLVS-1768)
[SLVS-1768]: https://sonarsource.atlassian.net/browse/SLVS-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1768 Upgrade SlCore to 10.13.0.79996

---

src/IssueViz/FixSuggestion/DiffView/DiffViewToolPackage.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewToolWindowPane.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewWindow.xaml
src/IssueViz/FixSuggestion/DiffView/DiffViewWindow.xaml.cs
src/IssueViz/FixSuggestion/DiffView/FixSuggestionDetails.cs
src/IssueViz/IssueViz.csproj
src/IssueViz/Resources.Designer.cs
src/IssueViz/Resources.resx

[SLVS-1744](https://sonarsource.atlassian.net/browse/SLVS-1744)
Add a diff view window and the capability to show in it a fix suggestion
[SLVS-1744]: https://sonarsource.atlassian.net/browse/SLVS-1744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1744 Add a diff view window

---

src/SLCore.IntegrationTests/FileAnalysisTestsRunner.cs
src/SLCore.IntegrationTests/Resources/HtmlIssues.html
src/SLCore.IntegrationTests/RuleConfigurationAnalysisTests.cs
src/SLCore.IntegrationTests/SLCore.IntegrationTests.csproj
src/SLCore.IntegrationTests/SimpleAnalysisTests.cs

[SLVS-1778](https://sonarsource.atlassian.net/browse/SLVS-1778)
[SLVS-1778]: https://sonarsource.atlassian.net/browse/SLVS-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1778 Add integration tests for Html analysis

---

src/Core.UnitTests/Binding/ServerConnectionTests.cs
src/Core/Binding/ServerConnection.cs

[SLVS-1475](https://sonarsource.atlassian.net/browse/SLVS-1475)
[SLVS-1475]: https://sonarsource.atlassian.net/browse/SLVS-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1475 Drop ServerConnection CredentialsUri

---

src/ConnectedMode/Binding/NonRoslynDummyBindingConfigProvider.cs
src/Core.UnitTests/LanguageTests.cs
src/Core/Language.cs
src/Core/SonarArtefactKeys.cs
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix/Analysis/MuteIssueCommand.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/RaisedFindingProcessorTests.cs
src/SLCore.Listeners/Implementation/Analysis/RaisedFindingProcessor.cs
src/SLCore.UnitTests/Common/Helpers/LanguageExtensionsTests.cs
src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore/Common/Helpers/LanguageExtensions.cs
src/SLCore/Configuration/ISLCoreConstantsProvider.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SonarQube.Client.Tests/Requests/Api/V9_4/GetSonarLintEventStreamTests.cs
src/SonarQube.Client.Tests/SonarQubeService_CreateServerSentEventsSession.cs
src/SonarQube.Client/Models/SonarQubeLanguage.cs

[SLVS-1772](https://sonarsource.atlassian.net/browse/SLVS-1772)
[SLVS-1772]: https://sonarsource.atlassian.net/browse/SLVS-1772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1772 Enable T-SQL analysis in Connected Mode

---

src/Integration.Vsix.UnitTests/SLCore/SLCoreEmbeddedPluginJarLocatorTests.cs
src/Integration.Vsix/SLCore/SLCoreEmbeddedPluginJarLocator.cs

[SLVS-1782](https://sonarsource.atlassian.net/browse/SLVS-1782)
[SLVS-1782]: https://sonarsource.atlassian.net/browse/SLVS-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1782 Use embedded CFamily plugin in Connected Mode

---

src/SLCore.Listeners.UnitTests/Logging/LoggerListenerTests.cs
src/SLCore.Listeners/Implementation/LoggerListener.cs
src/SLCore/Listener/Logger/LogParams.cs

[SLVS-1796](https://sonarsource.atlassian.net/browse/SLVS-1796)
Part of SLVS-1766
[SLVS-1796]: https://sonarsource.atlassian.net/browse/SLVS-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1796 Handle nullable SLCore log message

---

src/IssueViz.UnitTests/Editor/TextViewEditorTests.cs
src/IssueViz.UnitTests/FixSuggestion/DiffView/ChangeViewModelTests.cs
src/IssueViz.UnitTests/FixSuggestion/DiffView/DiffViewServiceTests.cs
src/IssueViz.UnitTests/FixSuggestion/DiffView/DiffViewViewModelTests.cs
src/IssueViz.UnitTests/FixSuggestion/FixSuggestionHandlerTests.cs
src/IssueViz/Editor/TextViewEditor.cs
src/IssueViz/FixSuggestion/DiffView/ChangeViewModel.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewService.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewToolWindowPane.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewViewModel.cs
src/IssueViz/FixSuggestion/DiffView/DiffViewWindow.xaml
src/IssueViz/FixSuggestion/DiffView/DiffViewWindow.xaml.cs
src/IssueViz/FixSuggestion/FinalizedFixSuggestionChange.cs
src/IssueViz/FixSuggestion/FixSuggestionChange.cs
src/IssueViz/FixSuggestion/FixSuggestionHandler.cs
src/IssueViz/FixSuggestion/IFixSuggestionHandler.cs
src/SLCore.Listeners.UnitTests/Implementation/ShowFixSuggestionListenerTests.cs
src/SLCore.Listeners/Implementation/ShowFixSuggestionListener.cs

[SLVS-1797](https://sonarsource.atlassian.net/browse/SLVS-1797)
[SLVS-1797]: https://sonarsource.atlassian.net/browse/SLVS-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1797 Introduce FixSuggestionChange model & conversion from ChangeDto

---

src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/InProcess/RoslynSettingsFileSynchronizerTests.cs
src/Roslyn.Suppressions/Roslyn.Suppressions/InProcess/RoslynSettingsFileSynchronizer.cs

[SLVS-1822](https://sonarsource.atlassian.net/browse/SLVS-1822)
Part of SLVS-1766
[SLVS-1822]: https://sonarsource.atlassian.net/browse/SLVS-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1822 Skip Roslyn settings sync when no solution is open

---

src/Core.UnitTests/Logging/StringBuilderLoggingExtensionsTests.cs
src/Core/Logging/ILogger.cs
src/Core/Logging/LoggerBase.cs
src/Core/Logging/StringBuilderLoggingExtensions.cs
src/TestInfrastructure/Framework/TestLogger.cs

[SLVS-1783](https://sonarsource.atlassian.net/browse/SLVS-1783)
[SLVS-1783]: https://sonarsource.atlassian.net/browse/SLVS-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1783 Fix: FormatException for non-formatted logs

---

src/Core.UnitTests/Binding/ServerConnectionTests.cs
src/Core/Binding/ServerConnection.cs

[SLVS-1812](https://sonarsource.atlassian.net/browse/SLVS-1812)
[SLVS-1812]: https://sonarsource.atlassian.net/browse/SLVS-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1812 Adapt the SonarCloud model to support multi-region

---

src/ConnectedMode.UnitTests/Shared/SharedBindingConfigFileProviderTests.cs
src/ConnectedMode/Shared/SharedBindingConfigFileProvider.cs
src/ConnectedMode/Shared/SharedBindingConfigModel.cs
src/Integration.Vsix.UnitTests/Commands/ConnectedModeMenu/SaveSharedConnectionCommandTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/SaveSharedConnectionCommand.cs

[SLVS-1811](https://sonarsource.atlassian.net/browse/SLVS-1811)
[SLVS-1811]: https://sonarsource.atlassian.net/browse/SLVS-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1811 Adapt shared connected mode configuration to support multi-region for SQC

---

src/ConnectedMode.UnitTests/UI/ConnectedModeServicesTests.cs
src/ConnectedMode/UI/ConnectedModeServices.cs

[SLVS-1844](https://sonarsource.atlassian.net/browse/SLVS-1844)
[SLVS-1844]: https://sonarsource.atlassian.net/browse/SLVS-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1844 Add DogfoodService to ConnectedMode services

---

src/Integration.UnitTests/Service/ConnectionInformationTests.cs
src/SonarQube.Client.Tests/Models/ConnectionInformationTests.cs
src/SonarQube.Client/Models/ConnectionInformation.cs

[SLVS-1815](https://sonarsource.atlassian.net/browse/SLVS-1815)
[SLVS-1815]: https://sonarsource.atlassian.net/browse/SLVS-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1815 Adapt the ConnectionInformation to take into account multiple regions for SQC.

---

src/SLCore.UnitTests/Service/Issue/ChangeIssueStatusParamsTests.cs
src/SLCore.UnitTests/Service/Issue/CheckStatusChangePermittedParamsTests.cs
src/SLCore.UnitTests/Service/Issue/CheckStatusChangePermittedResponseTests.cs
src/SLCore/Service/Issue/ChangeIssueStatusParams.cs
src/SLCore/Service/Issue/CheckStatusChangePermittedParams.cs
src/SLCore/Service/Issue/CheckStatusChangePermittedResponse.cs
src/SLCore/Service/Issue/Models/ResolutionStatus.cs

[SLVS-1750](https://sonarsource.atlassian.net/browse/SLVS-1750)
[SLVS-1750]: https://sonarsource.atlassian.net/browse/SLVS-1750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1750 Add SlCore changeStatus, checkStatusChangePermitted RPC methods

---

src/ConnectedMode.UnitTests/ConnectionInfoTests.cs
src/ConnectedMode.UnitTests/ServerConnectionsRepositoryAdapterTests.cs
src/ConnectedMode.UnitTests/SlCoreConnectionAdapterTests.cs
src/ConnectedMode/ConnectionInfo.cs
src/ConnectedMode/ServerConnectionsRepositoryAdapter.cs
src/ConnectedMode/SlCoreConnectionAdapter.cs
src/SLCore/Service/Connection/Models/SonarCloudRegionExtensions.cs

[SLVS-1842](https://sonarsource.atlassian.net/browse/SLVS-1842)
[SLVS-1842]: https://sonarsource.atlassian.net/browse/SLVS-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1842 Adapt ServerConnectionsRepositoryAdapter and SlCoreConnectionAdapter to support multi-region

---

src/ConnectedMode.UnitTests/ConnectionInfoTests.cs
src/ConnectedMode.UnitTests/UI/ConnectionDisplay/ConnectionNameViewModelTests.cs
src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/ConnectionInfo.cs
src/ConnectedMode/UI/ConnectionDisplay/ConnectionInfoComponent.xaml
src/ConnectedMode/UI/ConnectionDisplay/ConnectionInfoComponent.xaml.cs
src/ConnectedMode/UI/ConnectionDisplay/ConnectionNameComponent.xaml
src/ConnectedMode/UI/ConnectionDisplay/ConnectionNameComponent.xaml.cs
src/ConnectedMode/UI/ConnectionDisplay/ConnectionNameViewModel.cs
src/ConnectedMode/UI/Credentials/CredentialsDialog.xaml
src/ConnectedMode/UI/DeleteConnection/DeleteConnectionDialog.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml

[SLVS-1848](https://sonarsource.atlassian.net/browse/SLVS-1848)
Part of SLVS-1804
[SLVS-1848]: https://sonarsource.atlassian.net/browse/SLVS-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1848 Add reusable ConnectionNameComponent, use it in ConnectionInfoComponent

---

src/ConnectedMode/UI/ConnectionDisplay/ConnectionInfoComponent.xaml
src/ConnectedMode/UI/Resources/Styles.xaml

[SLVS-1850](https://sonarsource.atlassian.net/browse/SLVS-1850)
[SLVS-1850]: https://sonarsource.atlassian.net/browse/SLVS-1850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1850 Fix vertical alignment in ConnectionInfoComponent usages

---

MarketPlaceFiles/VS2022/overview-2022.md

[DOC-1835](https://sonarsource.atlassian.net/browse/DOC-1835)
[DOC-1835]: https://sonarsource.atlassian.net/browse/DOC-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1835 rebrand docs URL

---

src/Integration.UnitTests/MefServices/MefSonarQubeServiceTests.cs
src/Integration.UnitTests/SLCore/SLCoreConstantsProviderTests.cs
src/Integration.UnitTests/UserAgentProviderTests.cs
src/Integration/MefServices/MefSonarQubeService.cs
src/Integration/SLCore/SLCoreConstantsProvider.cs
src/Integration/UserAgentProvider.cs

[SLVS-1832](https://sonarsource.atlassian.net/browse/SLVS-1832)
[SLVS-1832]: https://sonarsource.atlassian.net/browse/SLVS-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1832 Include the new brand name in the User-Agent

---

src/Integration.Vsix.UnitTests/Analysis/MuteIssueCommandTests.cs
src/Integration.Vsix/Analysis/MuteIssueCommand.cs

[SLVS-1210](https://sonarsource.atlassian.net/browse/SLVS-1210)
[SLVS-1210]: https://sonarsource.atlassian.net/browse/SLVS-1210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1210 MuteIssueCommand: Mute secrets

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1880](https://sonarsource.atlassian.net/browse/SLVS-1880)
[SLVS-1880]: https://sonarsource.atlassian.net/browse/SLVS-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1880 Upgrade SlCore to 10.15.0.80289

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1827](https://sonarsource.atlassian.net/browse/SLVS-1827)
[SLVS-1827]: https://sonarsource.atlassian.net/browse/SLVS-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1827 Update CFamily analyzer to 6.63.0.79828

---

src/SLCore.Listeners.UnitTests/Implementation/ConnectedModeSuggestionListenerTests.cs
src/SLCore.UnitTests/Listener/Binding/AssistCreatingConnectionParamsTests.cs
src/SLCore.UnitTests/Listener/Binding/SonarCloudConnectionParamsTests.cs
src/SLCore.UnitTests/Listener/Binding/SonarQubeConnectionParamsTests.cs
src/SLCore/Listener/Binding/SonarCloudConnectionParams.cs
src/SLCore/Listener/Binding/SonarQubeConnectionParams.cs

[SLVS-1773](https://sonarsource.atlassian.net/browse/SLVS-1773)
[SLVS-1773]: https://sonarsource.atlassian.net/browse/SLVS-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1773 Update AssistCreatingConnectionParams dto

---

src/ConnectedMode.UnitTests/UI/ConnectedModeUIManagerTests.cs
src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/UI/ConnectedModeUIManager.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/ConnectedMode/UI/TrustConnection/TrustConnectionDialog.xaml
src/ConnectedMode/UI/TrustConnection/TrustConnectionDialog.xaml.cs
src/Core.UnitTests/DocumentationLinksTests.cs
src/Core/DocumentationLinks.cs

[SLVS-1888](https://sonarsource.atlassian.net/browse/SLVS-1888)
Part of 
[SLVS-1888]: https://sonarsource.atlassian.net/browse/SLVS-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1888 Create "Trust Connection" dialog

---

src/ConnectedMode.UnitTests/UI/ConnectedModeUIManagerTests.cs
src/ConnectedMode/UI/ConnectedModeUIManager.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/ConnectedMode/UI/TrustConnection/TrustConnectionDialog.xaml
src/ConnectedMode/UI/TrustConnection/TrustConnectionDialog.xaml.cs
src/ConnectedMode/UI/TrustConnection/TrustConnectionViewModel.cs
src/SLCore.Listeners.UnitTests/Implementation/ConnectedModeSuggestionListenerTests.cs
src/SLCore.Listeners/Implementation/ConnectedModeSuggestionListener.cs

[SLVS-1895](https://sonarsource.atlassian.net/browse/SLVS-1895)
[SLVS-1895]: https://sonarsource.atlassian.net/browse/SLVS-1895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1895 Show CredentialsDialog when token is null on assistCreatingConnection

---

src/ConnectedMode.UnitTests/UI/AutomaticBindingRequestTests.cs
src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode/Resources.Designer.cs
src/ConnectedMode/Resources.resx
src/ConnectedMode/UI/AutomaticBindingRequest.cs
src/ConnectedMode/UI/ConnectedModeUIManager.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs

[SLVS-1905](https://sonarsource.atlassian.net/browse/SLVS-1905)
Part of SLVS-1789
[SLVS-1905]: https://sonarsource.atlassian.net/browse/SLVS-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1905 Adapt ManageBindingDialog for auto binding

---

src/Integration.Vsix.UnitTests/Analysis/IssueHandlerTests.cs
src/Integration.Vsix.UnitTests/ErrorList/IssuesSnapshotTests _GetValue.cs
src/Integration.Vsix/ErrorList/IssuesSnapshot.cs
src/IssueViz.Security.UnitTests/Taint/TaintIssueToIssueVisualizationConverterTests.cs
src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
src/IssueViz.Security/Taint/TaintIssueToIssueVisualizationConverter.cs
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
src/IssueViz.UnitTests/AnalysisIssueVisualizationConverterTests.cs
src/IssueViz.UnitTests/Editor/Common/TaggerTestHelper.cs
src/IssueViz.UnitTests/Editor/ErrorTagging/ErrorTaggerTests.cs
src/IssueViz.UnitTests/Models/AnalysisIssueVisualizationTests.cs
src/IssueViz/Editor/ErrorTagging/ErrorTagger.cs
src/IssueViz/Models/AnalysisIssueVisualization.cs
src/IssueViz/Models/AnalysisIssueVisualizationConverter.cs

[SLVS-1851](https://sonarsource.atlassian.net/browse/SLVS-1851)
[SLVS-1851]: https://sonarsource.atlassian.net/browse/SLVS-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1851 Drop IAnalysisIssueVisualization.IsSuppressed

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1898](https://sonarsource.atlassian.net/browse/SLVS-1898)
[SLVS-1898]: https://sonarsource.atlassian.net/browse/SLVS-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1898 Update embedded HTML analyzer to 3.19.0.5695

---

src/EmbeddedSonarAnalyzer.props
src/Roslyn.Suppressions/Roslyn.Suppressions/SupportedSuppressionBuilder.tt

[SLVS-1909](https://sonarsource.atlassian.net/browse/SLVS-1909)
[SLVS-1909]: https://sonarsource.atlassian.net/browse/SLVS-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1909 Upgrade sonar-dotnet-enterprise to 10.7.0.110445

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1916](https://sonarsource.atlassian.net/browse/SLVS-1916)
[SLVS-1916]: https://sonarsource.atlassian.net/browse/SLVS-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1916 Update SlCore version to 10.16.0.80440

---

src/ConnectedMode.UnitTests/Transition/MuteIssuesServiceTests.cs
src/ConnectedMode/Transition/MuteIssuesService.cs

[SLVS-1921](https://sonarsource.atlassian.net/browse/SLVS-1921)
Make sure Roslyn suppression storage is updated when comment fails, but issue is successfully muted on the server
[SLVS-1921]: https://sonarsource.atlassian.net/browse/SLVS-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1921 Make sure Roslyn suppression storage is updated when comment fails

---

src/Core/ISonarLintSettings.cs
src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlViewModelTests.cs
src/Integration.Vsix.UnitTests/Settings/SonarLintSettingsTests.cs
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
src/Integration.Vsix/Settings/GeneralOptionsDialogControlViewModel.cs
src/Integration.Vsix/Settings/SonarLintSettings.cs
src/TestInfrastructure/Framework/ConfigurableIntegrationSettings.cs

[SLVS-1929](https://sonarsource.atlassian.net/browse/SLVS-1929)
[SLVS-1929]: https://sonarsource.atlassian.net/browse/SLVS-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1929 Add region settings for SQC in Options page

---

.github/workflows/PullRequestClosed.yml

[SLVS-1934](https://sonarsource.atlassian.net/browse/SLVS-1934)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLVS-1934]: https://sonarsource.atlassian.net/browse/SLVS-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1934 Autoclose issues created by Jira integration

---

src/ConnectedMode.UnitTests/UI/Credentials/CredentialsViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ServerSelection/ServerSelectionViewModelTests.cs
src/Core.UnitTests/Binding/CloudServerRegionTests.cs
src/Core.UnitTests/Binding/ServerConnectionTests.cs
src/Core/Binding/CloudServerRegion.cs
src/Integration.UnitTests/Service/ConnectionInformationTests.cs
src/SLCore.UnitTests/State/ServerConnectionsProviderTests.cs
src/SonarQube.Client.Tests/Models/ConnectionInformationTests.cs

[SLVS-1931](https://sonarsource.atlassian.net/browse/SLVS-1931)
[SLVS-1931]: https://sonarsource.atlassian.net/browse/SLVS-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1931 Change US SonarQube Cloud URL to sonarqube.us

---

src/SLCore.IntegrationTests/ConcurrencyTestHelper.cs
src/SLCore.IntegrationTests/SLCoreTestRunner.cs

[SLVS-1918](https://sonarsource.atlassian.net/browse/SLVS-1918)
[SLVS-1918]: https://sonarsource.atlassian.net/browse/SLVS-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1918 Fix: SLCore timeouts in Integration tests

---

src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlViewModelTests.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
src/Integration.Vsix/Settings/GeneralOptionsDialogControlViewModel.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogPage.cs

[SLVS-1805](https://sonarsource.atlassian.net/browse/SLVS-1805)
[SLVS-1805]: https://sonarsource.atlassian.net/browse/SLVS-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1805 Remove dogfooding check for cloud region option.

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1936](https://sonarsource.atlassian.net/browse/SLVS-1936)
[SLVS-1936]: https://sonarsource.atlassian.net/browse/SLVS-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1936 Update SlCore to latest master

---

src/Integration.Vsix.UnitTests/Commands/PackageCommandManagerTests.cs
src/Integration.Vsix/Commands/ConnectedModeMenu/ConnectedModeMenu.vsct
src/Integration.Vsix/Commands/ConnectedModeMenu/ManageConnectionsCommand.cs
src/Integration.Vsix/Commands/PackageCommandManager.cs
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/SonarLintIntegrationPackage.cs

[SLVS-1937](https://sonarsource.atlassian.net/browse/SLVS-1937)
[SLVS-1937]: https://sonarsource.atlassian.net/browse/SLVS-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1937 Rename `Bind to` button in Connected Mode to better reflect the binding state

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1928](https://sonarsource.atlassian.net/browse/SLVS-1928)
[SLVS-1928]: https://sonarsource.atlassian.net/browse/SLVS-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1928: Update CFamily analyzer to 6.64.1.81116

---

.cirrus/sonarqube-cloud-analysis.sh

[SLVS-1923](https://sonarsource.atlassian.net/browse/SLVS-1923)
[SLVS-1923]: https://sonarsource.atlassian.net/browse/SLVS-1923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1923 Fix: SonarCloud project new code period is stuck on version 8.3

---

src/ConnectedMode.UnitTests/UI/Credentials/EditCredentialsViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/UI/Credentials/CredentialsDialog.xaml.cs
src/ConnectedMode/UI/Credentials/EditCredentialsDialog.cs
src/ConnectedMode/UI/Credentials/EditCredentialsViewModel.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsDialog.xaml.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs

[SLVS-1979](https://sonarsource.atlassian.net/browse/SLVS-1979)
Extract edit credentials logic into a common dialog and view model to make it reusable.
[SLVS-1979]: https://sonarsource.atlassian.net/browse/SLVS-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1979 Extract edit credentials logic into common place

---

src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

[SLVS-1891](https://sonarsource.atlassian.net/browse/SLVS-1891)
[SLVS-1891]: https://sonarsource.atlassian.net/browse/SLVS-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1891 Add release notes to Marketplace

---

src/SLCore.Listeners.UnitTests/ConnectionConfigurationListenerTests.cs
src/SLCore.Listeners/Implementation/ConnectionConfigurationListener.cs

[SLVS-1981](https://sonarsource.atlassian.net/browse/SLVS-1981)
Only show invalidToken goldbar for current connection in connected mode and for any connection in standalone
[SLVS-1981]: https://sonarsource.atlassian.net/browse/SLVS-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1981 Improve invalidToken goldbar UX for connected mode

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1983](https://sonarsource.atlassian.net/browse/SLVS-1983)
[SLVS-1983]: https://sonarsource.atlassian.net/browse/SLVS-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1983 Update CFamily analyzer to 6.65.0.81949

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1984](https://sonarsource.atlassian.net/browse/SLVS-1984)
[SLVS-1984]: https://sonarsource.atlassian.net/browse/SLVS-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1984 Update SonarText analyzer to 2.22.0.5855

---

src/EmbeddedSonarAnalyzer.props

[SLVS-1994](https://sonarsource.atlassian.net/browse/SLVS-1994)
[SLVS-1994]: https://sonarsource.atlassian.net/browse/SLVS-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1994 Update SLCore to 10.18.0.80725

---

src/Core.UnitTests/AnalysisSettingsSerializerTests.cs
src/Core.UnitTests/UserRuleSettings/UserSettingsProviderTests.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/AnalysisSettingsSerializer.cs
src/Core/UserRuleSettings/UserSettings.cs
src/Core/UserRuleSettings/UserSettingsProvider.cs
src/Integration.Vsix.UnitTests/Analysis/UserSettingsTests.cs
src/SLCore.UnitTests/Analysis/SLCoreRuleSettingsTests.cs
src/SLCore/Analysis/SLCoreRuleSettings.cs

[SLVS-1965](https://sonarsource.atlassian.net/browse/SLVS-1965)
Part of 
[SLVS-1965]: https://sonarsource.atlassian.net/browse/SLVS-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1965 Update RuleSettings class to declare file exclusions

---

src/ConnectedMode.UnitTests/UI/ManageBinding/ManageBindingViewModelTests.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml
src/ConnectedMode/UI/ManageBinding/ManageBindingDialog.xaml.cs
src/ConnectedMode/UI/ManageBinding/ManageBindingViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx

[SLVS-2001](https://sonarsource.atlassian.net/browse/SLVS-2001)
[SLVS-2001]: https://sonarsource.atlassian.net/browse/SLVS-2001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2001 Show warning message in Manage Binding dialog when token is invalid for selected connection

---

src/Core/DocumentationLinks.cs
src/Integration.Vsix.UnitTests/Settings/GeneralOptionsDialogControlViewModelTests.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml
src/Integration.Vsix/Settings/GeneralOptionsDialogControl.xaml.cs
src/Integration.Vsix/Settings/GeneralOptionsDialogControlViewModel.cs

Update Options page to reflect that the settings is no longer only for rules, but also for file exclusions

SLVS-1966 Update Options page

---

src/Core.UnitTests/AnalysisSettingsSerializerTests.cs
src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core/Helpers/CommaSeparatedStringArrayConverter.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/AnalysisSettingsSerializer.cs

[SLVS-1997](https://sonarsource.atlassian.net/browse/SLVS-1997)
[SLVS-1997]: https://sonarsource.atlassian.net/browse/SLVS-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1997 Parse settings.json comma separated sonarlint.analysisExcludesStandalone

---

src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/ConnectedMode/UI/TrustConnection/TrustConnectionDialog.xaml
src/Core/CoreStrings.Designer.cs
src/Core/CoreStrings.resx
src/Integration.UnitTests/Binding/NoBindingSuggestionNotificationTests.cs
src/Integration/Binding/NoBindingSuggestionNotification.cs
src/IssueViz.Security.UnitTests/Taint/TaintList/TaintIssuesControlViewModelTests.cs
src/IssueViz.Security/Taint/TaintList/TaintIssuesControl.xaml
src/IssueViz.Security/Taint/TaintList/ViewModels/TaintIssuesControlViewModel.cs
src/IssueViz/Editor/QuickActions/DeselectIssueVisualizationAction.cs
src/IssueViz/Editor/QuickActions/SelectIssueVisualizationAction.cs
src/IssueViz/Resources.Designer.cs
src/IssueViz/Resources.resx
src/SonarQube.Client.Tests/ServerInfoTests.cs
src/SonarQube.Client/ServerInfo.cs

[SLVS-2006](https://sonarsource.atlassian.net/browse/SLVS-2006)
[SLVS-2006]: https://sonarsource.atlassian.net/browse/SLVS-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2006 Rebranding missed items

---

SonarQube.VisualStudio.sln.DotSettings
src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixActionsSourceTests.cs
src/IssueViz.UnitTests/Editor/QuickActions/QuickFixes/QuickFixSuggestedActionTests.cs
src/IssueViz/Commands/IssueVizPackage.vsct
src/IssueViz/Editor/QuickActions/QuickFixes/QuickFixSuggestedAction.cs
src/IssueViz/Resources.Designer.cs
src/IssueViz/Resources.resx

[SLVS-2015](https://sonarsource.atlassian.net/browse/SLVS-2015)
[SLVS-2015]: https://sonarsource.atlassian.net/browse/SLVS-2015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2015 Replace long product name in commands with a shorter version.

---

src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode.UnitTests/UI/OrganizationSelection/ManualOrganizationSelectionViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ProjectSelection/ManualProjectSelectionViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ServerSelection/ServerSelectionViewModelTests.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs
src/ConnectedMode/UI/OrganizationSelection/ManualOrganizationSelectionViewModel.cs
src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/ConnectedMode/UI/ServerSelection/ServerSelectionViewModel.cs
src/Core.UnitTests/Binding/ServerConnectionTests.cs
src/Core.UnitTests/Helpers/StringExtensionsTests.cs
src/Core/Binding/ServerConnection.cs
src/Core/Helpers/StringExtensions.cs

[SLVS-1420](https://sonarsource.atlassian.net/browse/SLVS-1420)
[SLVS-1420]: https://sonarsource.atlassian.net/browse/SLVS-1420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1420 Connected mode: Prevent duplicate connection

---

src/Core.UnitTests/SonarCompositeRuleIdTests.cs
src/Core/SonarCompositeRuleId.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynFileExclusionsTests.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynRuleParametersTests.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynRuleStatusTests.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdaterTests.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynFileExclusions.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynRuleParameters.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynRuleStatus.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdater.cs

[SLVS-1969](https://sonarsource.atlassian.net/browse/SLVS-1969)
[SLVS-1969]: https://sonarsource.atlassian.net/browse/SLVS-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1969 Add standalone mode roslyn settings generation

---

src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs

[SLVS-1970](https://sonarsource.atlassian.net/browse/SLVS-1970)
[SLVS-1970]: https://sonarsource.atlassian.net/browse/SLVS-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1970 Trigger standalone roslyn settings update on settings change

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2032](https://sonarsource.atlassian.net/browse/SLVS-2032)
Part of SLVS-2030
[SLVS-2032]: https://sonarsource.atlassian.net/browse/SLVS-2032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2032 Update SLCore to 10.19.0.80884 master build

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2000](https://sonarsource.atlassian.net/browse/SLVS-2000)
[SLVS-2000]: https://sonarsource.atlassian.net/browse/SLVS-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2000 Update SonarJS analyzer to 10.22.0.32148

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2017](https://sonarsource.atlassian.net/browse/SLVS-2017)
[SLVS-2017]: https://sonarsource.atlassian.net/browse/SLVS-2017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2017 Upgrade sonar-dotnet-enterprise to 10.8.0.113526

---

src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynFileExclusionsTests.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdaterTests.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynFileExclusions.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdater.cs
src/SLCore.Listeners.UnitTests/Implementation/GetFileExclusionsListenerTests.cs
src/SLCore.Listeners/Implementation/GetFileExclusionsListener.cs

[SLVS-2062](https://sonarsource.atlassian.net/browse/SLVS-2062)
[SLVS-2063](https://sonarsource.atlassian.net/browse/SLVS-2063)
[SLVS-2062]: https://sonarsource.atlassian.net/browse/SLVS-2062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2063]: https://sonarsource.atlassian.net/browse/SLVS-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2062,SLVS-2063 Update file exclusion pattern handling

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2030](https://sonarsource.atlassian.net/browse/SLVS-2030)
[SLVS-2030]: https://sonarsource.atlassian.net/browse/SLVS-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2030 Update SLCore to 10.19 release

---

src/Core/Helpers/CommaSeparatedStringArrayConverter.cs

[SLVS-1997](https://sonarsource.atlassian.net/browse/SLVS-1997)
[SLVS-1997]: https://sonarsource.atlassian.net/browse/SLVS-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1997: Add missing file header

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2064](https://sonarsource.atlassian.net/browse/SLVS-2064)
[SLVS-2064]: https://sonarsource.atlassian.net/browse/SLVS-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2064 Update SlCore to 10.19.1.80951

---

src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix/Analysis/DisableRuleCommand.cs

[SLVS-2008](https://sonarsource.atlassian.net/browse/SLVS-2008)
[SLVS-2008]: https://sonarsource.atlassian.net/browse/SLVS-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2008 Enable the "disable rule" command for roslyn issues

---

src/Core/DocumentationLinks.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/ExclusionViewModelTest.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/Settings/FileExclusions/ExclusionViewModel.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogPage.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs
src/Integration.Vsix/SonarLintIntegrationPackage.cs

[SLVS-2027](https://sonarsource.atlassian.net/browse/SLVS-2027)
As part of this PR a new page has been added in the Options dialog. Filling the page with the exclusions defined in the `settings.json` and updating the file on clicking OK will be part of another PR.
[SLVS-2027]: https://sonarsource.atlassian.net/browse/SLVS-2027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2027 Provide UI for file exclusions

---

src/ConnectedMode/UI/SuccessMessage.xaml
src/ConnectedMode/UI/WarningMessage.xaml
src/Integration.Vsix.UnitTests/Settings/FileExclusions/ExclusionViewModelTest.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/Settings/FileExclusions/AddExclusionDialog.xaml
src/Integration.Vsix/Settings/FileExclusions/AddExclusionDialog.xaml.cs
src/Integration.Vsix/Settings/FileExclusions/EditExclusionDialog.cs
src/Integration.Vsix/Settings/FileExclusions/ExclusionViewModel.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs

[SLVS-2071](https://sonarsource.atlassian.net/browse/SLVS-2071)
[SLVS-2071]: https://sonarsource.atlassian.net/browse/SLVS-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2071 Add popup for adding and editing a new file exclusion

---

src/Core/IActiveSolutionTracker.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs
src/TestInfrastructure/NoOpThreadHandler.cs

[SLVS-2073](https://sonarsource.atlassian.net/browse/SLVS-2073)
[SLVS-2073]: https://sonarsource.atlassian.net/browse/SLVS-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2073 Fix threading in importing constructor of ActiveSolutionTracker

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2069](https://sonarsource.atlassian.net/browse/SLVS-2069)
[SLVS-2069]: https://sonarsource.atlassian.net/browse/SLVS-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2069 Update CFamily analyzer to 6.66.0.83483

---

src/ConnectedMode.UnitTests/StatefulServerBranchProviderTests.cs
src/ConnectedMode/StatefulServerBranchProvider.cs

[SLVS-1237](https://sonarsource.atlassian.net/browse/SLVS-1237)
[SLVS-1237]: https://sonarsource.atlassian.net/browse/SLVS-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1237 Make `StatefulServerBranchProvider` implementation thread safe

---

src/Core/Binding/IActiveSolutionBoundTracker.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs
src/TestInfrastructure/Framework/ConfigurableConfigurationProvider.cs
src/TestInfrastructure/MockableInitializationProcessor.cs
src/TestInfrastructure/NoOpThreadHandler.cs

[SLVS-2078](https://sonarsource.atlassian.net/browse/SLVS-2078)
[SLVS-2078]: https://sonarsource.atlassian.net/browse/SLVS-2078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2078 Fix threading in importing constructor of ActiveSolutionBoundTracker

---

src/ConnectedMode.UnitTests/BoundSolutionGitMonitorTests.cs
src/Core/Initialization/IInitializationProcessor.cs
src/Infrastructure.VS.UnitTests/Initialization/InitializationProcessorFactoryTests.cs
src/Infrastructure.VS.UnitTests/Initialization/InitializationProcessorTests.cs
src/Infrastructure.VS/Initialization/InitializationProcessor.cs
src/Infrastructure.VS/Initialization/InitializationProcessorFactory.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/TestInfrastructure/Helpers/MefTestHelpers.cs
src/TestInfrastructure/MockableInitializationProcessor.cs

[SLVS-2083](https://sonarsource.atlassian.net/browse/SLVS-2083)
Part of SLVS-2025
[SLVS-2083]: https://sonarsource.atlassian.net/browse/SLVS-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2083 Introduce InitializationProcessorFactory

---

src/ConnectedMode.UnitTests/ConnectionInfoTests.cs
src/ConnectedMode.UnitTests/UI/Credentials/EditCredentialsViewModelTests.cs
src/ConnectedMode.UnitTests/UI/ManageConnections/ManageConnectionsViewModelTest.cs
src/ConnectedMode/ConnectionInfo.cs
src/ConnectedMode/UI/Credentials/EditCredentialsViewModel.cs
src/ConnectedMode/UI/ManageConnections/ManageConnectionsViewModel.cs

[SLVS-2011](https://sonarsource.atlassian.net/browse/SLVS-2011)
[SLVS-2011]: https://sonarsource.atlassian.net/browse/SLVS-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2011 Fix deleting connection for SQC shows wrong references when same organization exists for different region

---

src/Core/Analysis/IAnalysisConfigMonitor.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs

[SLVS-2086](https://sonarsource.atlassian.net/browse/SLVS-2086)
Part of SLVS-2025
[SLVS-2086]: https://sonarsource.atlassian.net/browse/SLVS-2086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2086 Fix threading in importing constructor of AnalysisConfigMonitor

---

src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/UserSettings.cs

[SLVS-2097](https://sonarsource.atlassian.net/browse/SLVS-2097)
[SLVS-2098](https://sonarsource.atlassian.net/browse/SLVS-2098)
[SLVS-2097]: https://sonarsource.atlassian.net/browse/SLVS-2097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2098]: https://sonarsource.atlassian.net/browse/SLVS-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2097, SLVS-2098 Update user & analysis settings models

---

src/Core/Initialization/IRequireInitialization.cs
src/Infrastructure.VS.UnitTests/Initialization/InitializationProcessorTests.cs
src/Infrastructure.VS/Initialization/InitializationProcessor.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/TestInfrastructure/Framework/ConfigurableActiveSolutionTracker.cs

[SLVS-2093](https://sonarsource.atlassian.net/browse/SLVS-2093)
[SLVS-2093]: https://sonarsource.atlassian.net/browse/SLVS-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2093 Improve `IRequireInitialization` interface

---

src/Core/UserRuleSettings/UserSettings.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdaterTests.cs
src/Integration.Vsix.UnitTests/Analysis/UserSettingsTests.cs
src/Integration/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdater.cs

[SLVS-2060](https://sonarsource.atlassian.net/browse/SLVS-2060)
[SLVS-2103](https://sonarsource.atlassian.net/browse/SLVS-2103)
[SLVS-2060]: https://sonarsource.atlassian.net/browse/SLVS-2060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2103]: https://sonarsource.atlassian.net/browse/SLVS-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2060, SLVS-2103 Support new UserSettings in StandaloneRoslynSettingsUpdater

---

.cirrus.yaml

[SLVS-2106](https://sonarsource.atlassian.net/browse/SLVS-2106)
[SLVS-2106]: https://sonarsource.atlassian.net/browse/SLVS-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2106 Update branch name for AMI QA

---

src/ConnectedMode/UI/Resources/Styles.xaml
src/Integration.Vsix.UnitTests/Commands/PackageCommandManagerTests.cs
src/Integration.Vsix.UnitTests/Settings/OpenSettingsFileWpfCommandTests.cs
src/Integration.Vsix.UnitTests/Settings/SolutionSettings/SolutionSettingsViewModelTest.cs
src/Integration.Vsix/Commands/PackageCommandManager.cs
src/Integration.Vsix/Commands/SolutionSettingsCommand.cs
src/Integration.Vsix/Integration.Vsix.csproj
src/Integration.Vsix/Resources/Strings.Designer.cs
src/Integration.Vsix/Resources/Strings.resx
src/Integration.Vsix/Settings/DocumentOpener.cs
src/Integration.Vsix/Settings/OpenDocumentService.cs
src/Integration.Vsix/Settings/OpenSettingsFileWpfCommand.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsViewModel.cs
src/Integration.Vsix/SonarLint.vsct
src/Integration.Vsix/SonarLintIntegrationPackage.cs

[SLVS-2091](https://sonarsource.atlassian.net/browse/SLVS-2091)
[SLVS-2091]: https://sonarsource.atlassian.net/browse/SLVS-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2091 UI: Add possibility to set solution level settings

---

src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs

[SLVS-2102](https://sonarsource.atlassian.net/browse/SLVS-2102)
[SLVS-2102]: https://sonarsource.atlassian.net/browse/SLVS-2102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2102 Replace ActiveSolutionBoundTracker with UserSettingsProvider on AnalysisConfigMonitor

---

src/ConnectedMode/UI/Resources/Styles.xaml
src/Integration.Vsix/Commands/SolutionSettingsCommand.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogControl.xaml.cs
src/Integration.Vsix/Settings/SolutionSettings/AddAnalysisPropertyDialog.xaml
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesControl.xaml
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesControl.xaml.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml
src/IssueViz.Security/SharedUI/SharedResources.xaml

[SLVS-2110](https://sonarsource.atlassian.net/browse/SLVS-2110)
[SLVS-2110]: https://sonarsource.atlassian.net/browse/SLVS-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2110 Improve dark mode for DataGrid and TextBox in Solution Settings window

---

src/Core/UserRuleSettings/IUserSettingsProvider.cs
src/Integration.UnitTests/UserSettingsConfiguration/UserSettingsProviderTests.cs
src/Integration.Vsix.UnitTests/Settings/SolutionSettings/AnalysisPropertiesViewModelTests.cs
src/Integration.Vsix/Commands/SolutionSettingsCommand.cs
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesViewModel.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml.cs
src/Integration/UserSettingsConfiguration/UserSettingsProvider.cs

[SLVS-2100](https://sonarsource.atlassian.net/browse/SLVS-2100)
[SLVS-2100]: https://sonarsource.atlassian.net/browse/SLVS-2100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2100 UI: Show/Save analysis properties Add

---

src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core.UnitTests/UserRuleSettings/SolutionAnalysisSettingsTests.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/IUserSettingsProvider.cs
src/Core/UserRuleSettings/SolutionAnalysisSettings.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynFileExclusionsTests.cs
src/Integration.UnitTests/CSharpVB/StandaloneMode/StandaloneRoslynSettingsUpdaterTests.cs
src/Integration.UnitTests/UserSettingsConfiguration/UserSettingsProviderTests.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs
src/Integration/UserSettingsConfiguration/UserSettingsProvider.cs

[SLVS-2090](https://sonarsource.atlassian.net/browse/SLVS-2090)
[SLVS-2090]: https://sonarsource.atlassian.net/browse/SLVS-2090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2090 Add file exclusions to solution-level settings model

---

src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml.cs

[SLVS-2121](https://sonarsource.atlassian.net/browse/SLVS-2121)
[SLVS-2121]: https://sonarsource.atlassian.net/browse/SLVS-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2121 Save/Load solution-level file exclusions

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2101](https://sonarsource.atlassian.net/browse/SLVS-2101)
[SLVS-2116](https://sonarsource.atlassian.net/browse/SLVS-2116)
[SLVS-2101]: https://sonarsource.atlassian.net/browse/SLVS-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2116]: https://sonarsource.atlassian.net/browse/SLVS-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2101, SLVS-2116 Analyzer updates

---

src/Integration.Vsix.UnitTests/Settings/SolutionSettings/AnalysisPropertiesViewModelTests.cs
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesViewModel.cs

[SLVS-2118](https://sonarsource.atlassian.net/browse/SLVS-2118)
[SLVS-2118]: https://sonarsource.atlassian.net/browse/SLVS-2118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2118 Check for duplicate analysis properties

---

src/Integration.UnitTests/MefServices/ActiveSolutionTrackerTests.cs
src/Integration/MefServices/ActiveSolutionTracker.cs
src/Integration/Resources/Strings.Designer.cs
src/Integration/Resources/Strings.resx
src/TestInfrastructure/Framework/TestLogger.cs
src/TestInfrastructure/VsObjectModelMocks/SolutionMock.cs

[SLVS-2112](https://sonarsource.atlassian.net/browse/SLVS-2112)
[SLVS-2113](https://sonarsource.atlassian.net/browse/SLVS-2113)
[SLVS-2112]: https://sonarsource.atlassian.net/browse/SLVS-2112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2113]: https://sonarsource.atlassian.net/browse/SLVS-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2112, SLVS-2113 Handle dummy solutions in ActiveSolutionTracker

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2130](https://sonarsource.atlassian.net/browse/SLVS-2130)
[SLVS-2130]: https://sonarsource.atlassian.net/browse/SLVS-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2130 Update to SlCore 10.21.0.81131

---

src/Core.UnitTests/UserRuleSettings/AnalysisSettingsTests.cs
src/Core.UnitTests/UserRuleSettings/GlobalRawAnalysisSettingsTests.cs
src/Core.UnitTests/UserRuleSettings/SolutionRawAnalysisSettingsTests.cs
src/Core/UserRuleSettings/AnalysisSettings.cs
src/Core/UserRuleSettings/GlobalRawAnalysisSettings.cs
src/Core/UserRuleSettings/IUserSettingsProvider.cs
src/Core/UserRuleSettings/IUserSettingsStorage.cs
src/Core/UserRuleSettings/SolutionRawAnalysisSettings.cs
src/Integration.UnitTests/UserSettingsConfiguration/AnalysisSettingsSerializerTests.cs
src/Integration.UnitTests/UserSettingsConfiguration/GlobalSettingsStorageTest.cs
src/Integration.UnitTests/UserSettingsConfiguration/SolutionSettingsStorageTest.cs
src/Integration.UnitTests/UserSettingsConfiguration/UserSettingsProviderTests.cs
src/Integration.Vsix.UnitTests/Analysis/DisableRuleCommandTests.cs
src/Integration.Vsix.UnitTests/Settings/FileExclusions/FileExclusionsViewModelTests.cs
src/Integration.Vsix.UnitTests/Settings/SolutionSettings/AnalysisPropertiesViewModelTests.cs
src/Integration.Vsix/Analysis/DisableRuleCommand.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsDialogPage.cs
src/Integration.Vsix/Settings/FileExclusions/FileExclusionsViewModel.cs
src/Integration.Vsix/Settings/SolutionSettings/AnalysisPropertiesViewModel.cs
src/Integration.Vsix/Settings/SolutionSettings/SolutionSettingsDialog.xaml.cs
src/Integration/UserSettingsConfiguration/GlobalSettingsStorage.cs
src/Integration/UserSettingsConfiguration/SolutionSettingsStorage.cs
src/Integration/UserSettingsConfiguration/UserSettingsProvider.cs

[SLVS-2128](https://sonarsource.atlassian.net/browse/SLVS-2128)
[SLVS-2128]: https://sonarsource.atlassian.net/browse/SLVS-2128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2128 Split IUserSettingsProvider interface

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/IssueViz.Security.csproj
src/IssueViz.Security/IssuesStore/IIssuesStore.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz.Security/SharedUI/SharedResources.xaml

[SLVS-2120](https://sonarsource.atlassian.net/browse/SLVS-2120)
[SLVS-2120]: https://sonarsource.atlassian.net/browse/SLVS-2120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2120 Add new column for server status in HotspotsToolWindow

---

src/Integration.Vsix.UnitTests/SonarLintTagger/VsProjectInfoProviderTest.cs
src/Integration.Vsix/SonarLintTagger/VsProjectInfoProvider.cs

[SLVS-2135](https://sonarsource.atlassian.net/browse/SLVS-2135)
[SLVS-2135]: https://sonarsource.atlassian.net/browse/SLVS-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2135 Fix threading in mef-importing constructor of VsProjectInfoProvider

---

src/ConnectedMode/UI/Resources/Styles.xaml
src/Integration/Transition/MuteIssuesWindowService.cs
src/Integration/Transition/MuteWindowDialog.xaml
src/Integration/Transition/MuteWindowDialog.xaml.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/ReviewHotspotsViewModelTest.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/StatusViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHostpotWindow.xaml
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHostpotWindow.xaml.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHotspotsViewModel.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/StatusViewModel.cs
src/IssueViz.Security/IssueViz.Security.csproj
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

[SLVS-2141](https://sonarsource.atlassian.net/browse/SLVS-2141)
[SLVS-2141]: https://sonarsource.atlassian.net/browse/SLVS-2141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2141 Add Review Hotspot window

---

src/Core/Analysis/AnalysisIssue.cs
src/Core/Analysis/IAnalysisIssue.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHostpotStoreMonitorTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotTests.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/ReviewHotspotsViewModelTest.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/StatusViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/LocalHotspot.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHostpotWindow.xaml.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHotspotsViewModel.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/StatusViewModel.cs
src/SLCore.UnitTests/Common/Helpers/ModelConversionExtensionsTests.cs
src/SLCore.UnitTests/Listener/Analysis/RaiseFindingToAnalysisIssueConverterTests.cs
src/SLCore/Common/Helpers/ModelConversionExtensions.cs
src/SLCore/Listener/Analysis/RaiseFindingToAnalysisIssueConverter.cs

[SLVS-2142](https://sonarsource.atlassian.net/browse/SLVS-2142)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6218) in which the Review Hotspot window was added, because it adds a feature for the window
[SLVS-2142]: https://sonarsource.atlassian.net/browse/SLVS-2142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2142 Preselect current status in Review Hotspot window

---

src/Core/Analysis/IAnalysisIssue.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHostpotStoreMonitorTests.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/HotspotStatusExtensionMethodsTest.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/ReviewHotspotsServiceTest.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/ReviewHotspotsViewModelTest.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/StatusViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/HotspotStatusExtensionMethods.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/IReviewHotspotsService.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHotspotService.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHotspotsViewModel.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/SLCore.UnitTests/Common/Helpers/ModelConversionExtensionsTests.cs
src/SLCore/Common/Helpers/ModelConversionExtensions.cs

[SLVS-2140](https://sonarsource.atlassian.net/browse/SLVS-2140)
[SLVS-2140]: https://sonarsource.atlassian.net/browse/SLVS-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2140 Implement changing the status of a hotspot

---

MarketPlaceFiles/VS2022/overview-2022.md

[SLVS-2012](https://sonarsource.atlassian.net/browse/SLVS-2012)
[SLVS-2012]: https://sonarsource.atlassian.net/browse/SLVS-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2012 Update available languages in market place

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/ViewModels/LocationFilterViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsToolWindow.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/IHotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/LocationFilterViewModel.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

[SLVS-2124](https://sonarsource.atlassian.net/browse/SLVS-2124)
[SLVS-2124]: https://sonarsource.atlassian.net/browse/SLVS-2124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2124 Allow hotspots to be filtered by location

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security.UnitTests/Hotspots/ReviewHotspot/ReviewHotspotsServiceTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/IReviewHotspotsService.cs
src/IssueViz.Security/Hotspots/ReviewHotspot/ReviewHotspotService.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/SLCore.UnitTests/Service/Hotspot/OpenHotspotInBrowserParamsTest.cs
src/SLCore/Service/Hotspot/ChangeHotspotStatusParams.cs
src/SLCore/Service/Hotspot/CheckStatusChangePermittedParams.cs
src/SLCore/Service/Hotspot/CheckStatusChangePermittedResponse.cs
src/SLCore/Service/Hotspot/IHotspotSlCoreService.cs
src/SLCore/Service/Hotspot/OpenHotspotInBrowserParams.cs

[SLVS-2127](https://sonarsource.atlassian.net/browse/SLVS-2127)
[SLVS-2127]: https://sonarsource.atlassian.net/browse/SLVS-2127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2127 Add menu item to hotspot that allows viewing it in browser

---

src/Infrastructure.VS.UnitTests/ActiveDocumentTrackerTests.cs
src/Infrastructure.VS/DocumentEvents/ActiveDocumentTracker.cs

[SLVS-2134](https://sonarsource.atlassian.net/browse/SLVS-2134)
[SLVS-2134]: https://sonarsource.atlassian.net/browse/SLVS-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2134 Fix threading in mef-importing constructor of ActiveDocumentTracker

---

src/IssueViz.Security.UnitTests/Hotspots/HotspotsList/HotspotsControlViewModelTests.cs
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs

[SLVS-1993](https://sonarsource.atlassian.net/browse/SLVS-1993)
[SLVS-1993]: https://sonarsource.atlassian.net/browse/SLVS-1993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-1993 Fix QG

---

src/Core/DocumentEvents.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/IIssueTracker.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

[SLVS-2035](https://sonarsource.atlassian.net/browse/SLVS-2035)
[SLVS-2035]: https://sonarsource.atlassian.net/browse/SLVS-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2035 Extend IDocumentEvents to support more events

---

src/Integration.Vsix.UnitTests/CFamily/VcxProject/VCXCompilationDatabaseProviderTests.cs
src/Integration.Vsix.UnitTests/CFamily/VcxProject/VCXCompilationDatabaseStorageTests.cs
src/Integration.Vsix/CFamily/VcxProject/IVCXCompilationDatabaseStorage.cs
src/Integration.Vsix/CFamily/VcxProject/VCXCompilationDatabaseProvider.cs
src/Integration.Vsix/SonarLintDaemonPackage.cs

[SLVS-2077](https://sonarsource.atlassian.net/browse/SLVS-2077)
Part of 
[SLVS-2077]: https://sonarsource.atlassian.net/browse/SLVS-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2077 Support multi-entry VCX compilation databases

---

src/Integration.Vsix/SonarLintDaemonPackage.cs

[SLVS-2168](https://sonarsource.atlassian.net/browse/SLVS-2168)
[SLVS-2168]: https://sonarsource.atlassian.net/browse/SLVS-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2168 Fix null reference exception on dispose

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2290](https://sonarsource.atlassian.net/browse/SLVS-2290)
[SLVS-2290]: https://sonarsource.atlassian.net/browse/SLVS-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2290 Upgrade sonar-dotnet-enterprise to 10.11.0.117924

---

src/SLCore.UnitTests/SLCoreInstanceHandleTests.cs
src/SLCore.UnitTests/Service/Lifecycle/InitializeParamsTests.cs
src/SLCore/ISLCoreInstanceHandle.cs
src/SLCore/Service/Lifecycle/InitializeParams.cs

[SLVS-2031](https://sonarsource.atlassian.net/browse/SLVS-2031)
[SLVS-2031]: https://sonarsource.atlassian.net/browse/SLVS-2031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2031 Enable automatic analysis

---

src/SLCore.UnitTests/Service/File/DidCloseFileParamsTest.cs
src/SLCore.UnitTests/Service/File/DidOpenFileParamsTest.cs
src/SLCore/Service/File/DidCloseFileParams.cs
src/SLCore/Service/File/DidOpenFileParams.cs

[SLVS-2034](https://sonarsource.atlassian.net/browse/SLVS-2034)
[SLVS-2034]: https://sonarsource.atlassian.net/browse/SLVS-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2034 Add RPC methods `didOpenFile` and `didCloseFile`

---

src/ConnectedMode.UnitTests/BoundSolutionGitMonitorTests.cs
src/ConnectedMode/BoundSolutionGitMonitor.cs
src/Core/Binding/IBoundSolutionGitMonitor.cs
src/Core/GitEventsMonitor.cs
src/Integration.UnitTests/MefServices/ActiveSolutionBoundTrackerTests.cs
src/Integration/MefServices/ActiveSolutionBoundTracker.cs

[SLVS-2292](https://sonarsource.atlassian.net/browse/SLVS-2292)
Part of SLVS-1986
[SLVS-2292]: https://sonarsource.atlassian.net/browse/SLVS-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2292 Fix threading in mef-importing ctor of BoundSolutionGitMonitor

---

src/SLCore.UnitTests/Listener/Analysis/GetInferredAnalysisPropertiesParamsTests.cs
src/SLCore.UnitTests/Listener/Analysis/GetInferredAnalysisPropertiesResponseTests.cs
src/SLCore.UnitTests/Service/Analysis/DidChangeAnalysisPropertiesParamsTests.cs
src/SLCore/Service/Analysis/DidChangeAnalysisPropertiesParams.cs
src/SLCore/Service/Analysis/IUserAnalysisPropertiesService.cs

[SLVS-2301](https://sonarsource.atlassian.net/browse/SLVS-2301)
[SLVS-2301]: https://sonarsource.atlassian.net/browse/SLVS-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2301 add IUserAnalysisPropertiesService & DidSetUserAnalysisProperties

---

src/CFamily/CMake/CMakeCompilationDatabaseLocator.cs
src/Core/CFamily/IActiveCompilationDatabaseTracker.cs
src/Integration.Vsix.UnitTests/CFamily/ActiveCompilationDatabaseTrackerTests.cs
src/Integration.Vsix/CFamily/ActiveCompilationDatabaseTracker.cs
src/Integration.Vsix/SonarLintDaemonPackage.cs

[SLVS-2041](https://sonarsource.atlassian.net/browse/SLVS-2041)
[SLVS-2166](https://sonarsource.atlassian.net/browse/SLVS-2166)
[SLVS-2041]: https://sonarsource.atlassian.net/browse/SLVS-2041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2166]: https://sonarsource.atlassian.net/browse/SLVS-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2041, SLVS-2166 Update compilation database on config scope change

---

src/Core/Analysis/IAnalysisConfigMonitor.cs
src/Integration.Vsix.UnitTests/Analysis/AnalysisConfigMonitorTests.cs
src/Integration.Vsix/Analysis/AnalysisConfigMonitor.cs
src/Integration.Vsix/SonarLintDaemonPackage.cs

[SLVS-2312](https://sonarsource.atlassian.net/browse/SLVS-2312)
Part of 
[SLVS-2312]: https://sonarsource.atlassian.net/browse/SLVS-2312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2312 Instantiate IAnalysisConfigMonitor on startup + CAYC

---

src/Integration/CSharpVB/Install/SonarLintTargets.xml

[SLVS-2303](https://sonarsource.atlassian.net/browse/SLVS-2303)

SLVS-2303 Fix: SonarLint.targets file not specific enough

---

src/ConnectedMode.UnitTests/Transition/MuteIssuesServiceTests.cs
src/ConnectedMode/Transition/MuteIssuesService.cs
src/SLCore.Listeners.UnitTests/Implementation/Analysis/AnalysisListenerTests.cs
src/SLCore.Listeners/Implementation/Analysis/AnalysisListener.cs

[SLVS-2045](https://sonarsource.atlassian.net/browse/SLVS-2045)
[SLVS-2045]: https://sonarsource.atlassian.net/browse/SLVS-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2045 Remove no longer needed triggering of manual analysis

---

src/Core/DocumentEvents.cs
src/Integration.Vsix.UnitTests/Analysis/DocumentEventsHandlerTests.cs
src/Integration.Vsix/Analysis/DocumentEventsHandler.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

[SLVS-2305](https://sonarsource.atlassian.net/browse/SLVS-2305)
Part of 
[SLVS-2305]: https://sonarsource.atlassian.net/browse/SLVS-2305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2305 Register files opened before ConfigScope initialized

---

src/EmbeddedSonarAnalyzer.props
src/SLCore.IntegrationTests/FileAnalysisTestsRunner.cs
src/SLCore.IntegrationTests/Resources/TypeScriptWithBom.ts
src/SLCore.IntegrationTests/SLCore.IntegrationTests.csproj
src/SLCore.IntegrationTests/SimpleAnalysisTests.cs
src/SLCore/Common/Helpers/ClientFileDtoFactory.cs

[SLVS-2323](https://sonarsource.atlassian.net/browse/SLVS-2323)
Part of SLVS-2004
[SLVS-2323]: https://sonarsource.atlassian.net/browse/SLVS-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2323 Update SLCore to bom-bug-free version + integration test

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2313](https://sonarsource.atlassian.net/browse/SLVS-2313)
[SLVS-2319](https://sonarsource.atlassian.net/browse/SLVS-2319)
[SLVS-2313]: https://sonarsource.atlassian.net/browse/SLVS-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2319]: https://sonarsource.atlassian.net/browse/SLVS-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2313 SLVS-2319 Update analyzers

---

src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/VsProjectInfoProviderTest.cs
src/Integration.Vsix/SonarLintTagger/IIssueTracker.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs
src/Integration.Vsix/SonarLintTagger/VsProjectInfoProvider.cs
src/IssueViz.Security.UnitTests/Hotspots/LocalHotspotStoreTests.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs

[SLVS-2320](https://sonarsource.atlassian.net/browse/SLVS-2320)

SLVS-2320 Update analysis state on rename

---

src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

[SLVS-2329](https://sonarsource.atlassian.net/browse/SLVS-2329)
Part of SLVS-2004

SLVS-2329 Fix Quality Gate

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2328](https://sonarsource.atlassian.net/browse/SLVS-2328)

SLVS-2328 Update SLCore to 10.24.0.81415

---

src/SLCore/Analysis/SLCoreAnalyzer.cs
src/SLCore/Analysis/SlCoreUserAnalysisPropertiesSynchronizer.cs

[SLVS-2333](https://sonarsource.atlassian.net/browse/SLVS-2333)
Part of SLVS-2004

SLVS-2333 Fix QG

---

src/Core/DocumentEvents.cs
src/Integration.Vsix.UnitTests/Analysis/DocumentEventsHandlerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs
src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs

[SLVS-2326](https://sonarsource.atlassian.net/browse/SLVS-2326)
[SLVS-2326]: https://sonarsource.atlassian.net/browse/SLVS-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2326 Don't send file content for flushed files to SLCore

---

MarketPlaceFiles/VS2022/overview-2022.md
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest

[SLVS-2318](https://sonarsource.atlassian.net/browse/SLVS-2318)
[SLVS-2318]: https://sonarsource.atlassian.net/browse/SLVS-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2318 Update marketplace description

---

src/Core.UnitTests/FileMonitor/SingleFileMonitorTests.cs
src/Core/FileMonitor/SingleFileMonitor.cs
src/Core/Resources/Strings.Designer.cs
src/Core/Resources/Strings.resx

[SLVS-2288](https://sonarsource.atlassian.net/browse/SLVS-2288)
[SLVS-2288]: https://sonarsource.atlassian.net/browse/SLVS-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2288 Dispose empty folders created by SingleFileMonitor

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2355](https://sonarsource.atlassian.net/browse/SLVS-2355)
[SLVS-2355]: https://sonarsource.atlassian.net/browse/SLVS-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2355 Update SonarJS analyzer to 11.0.0.33655

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2356](https://sonarsource.atlassian.net/browse/SLVS-2356)
[SLVS-2356]: https://sonarsource.atlassian.net/browse/SLVS-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2356 Update to latest SlCore (10.25.0.81589)

---

src/Core/CFamily/IActiveCompilationDatabaseTracker.cs
src/Core/DocumentEvents.cs
src/Integration.Vsix.UnitTests/Analysis/DocumentEventsHandlerTests.cs
src/Integration.Vsix.UnitTests/CFamily/ActiveCompilationDatabaseTrackerTests.cs
src/Integration.Vsix/Analysis/DocumentEventsHandler.cs
src/Integration.Vsix/CFamily/ActiveCompilationDatabaseTracker.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

[SLVS-2350](https://sonarsource.atlassian.net/browse/SLVS-2350)
[SLVS-2350]: https://sonarsource.atlassian.net/browse/SLVS-2350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2350 Fix: Race condition with CFamily & compilation database

---

src/IssueViz.UnitTests/Selection/AnalysisIssueSelectionServiceTests.cs
src/IssueViz/Selection/AnalysisIssueSelectionService.cs

[SLVS-2385](https://sonarsource.atlassian.net/browse/SLVS-2385)
Part of SLVS-2341
[SLVS-2385]: https://sonarsource.atlassian.net/browse/SLVS-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2385 Fix threading in mef-importing ctor of AnalysisIssueSelectionService

---

src/ConnectedMode/ConnectedMode.csproj
src/ConnectedMode/UI/Resources/Browse.xaml
src/Core/WPF/PascalCaseEnumToSpacedStringConverter.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ServerViewModelTest.cs
src/IssueViz.Security/Hotspots/HotspotsList/HotspotsControl.xaml
src/IssueViz.Security/Hotspots/HotspotsList/ViewModels/HotspotsControlViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/IssueViz.Security/ReportView/ServerViewModel.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz.Security/SharedUI/SharedResources.xaml

[SLVS-2386](https://sonarsource.atlassian.net/browse/SLVS-2386)
[SLVS-2386]: https://sonarsource.atlassian.net/browse/SLVS-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2386 Add server navigation for SCA issues

---

src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRisksStoreTests.cs
src/IssueViz.Security/DependencyRisks/DependencyRisksStore.cs

[SLVS-2365](https://sonarsource.atlassian.net/browse/SLVS-2365)
[SLVS-2365]: https://sonarsource.atlassian.net/browse/SLVS-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2365 Create DependencyRisksStore

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2358](https://sonarsource.atlassian.net/browse/SLVS-2358)
[SLVS-2391](https://sonarsource.atlassian.net/browse/SLVS-2391)
[SLVS-2358]: https://sonarsource.atlassian.net/browse/SLVS-2358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2391]: https://sonarsource.atlassian.net/browse/SLVS-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2358, SLVS-2391 Analyzer updates

---

src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRiskViewModelTest.cs
src/IssueViz.Security.UnitTests/DependencyRisks/GroupDependencyRiskViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ServerViewModelTest.cs
src/IssueViz.Security/DependencyRisks/DependencyRiskViewModel.cs
src/IssueViz.Security/DependencyRisks/GroupDependencyRiskViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs

[SLVS-2371](https://sonarsource.atlassian.net/browse/SLVS-2371)
[SLVS-2371]: https://sonarsource.atlassian.net/browse/SLVS-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2371 Refresh dependency risks in UI when store is updated

---

src/IssueViz.Security.UnitTests/DependencyRisks/GroupDependencyRiskViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ServerViewModelTest.cs
src/IssueViz.Security/DependencyRisks/GroupDependencyRiskViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs

[SLVS-2437](https://sonarsource.atlassian.net/browse/SLVS-2437)
Part of SLVS-2359
[SLVS-2437]: https://sonarsource.atlassian.net/browse/SLVS-2437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2437 Switch to UI thread when handling DependencyRiskStore update events

---

src/SLCore.Listeners.UnitTests/Implementation/ScaIssuesListenerTests.cs
src/SLCore.Listeners/Implementation/ScaIssuesListener.cs

[SLVS-2368](https://sonarsource.atlassian.net/browse/SLVS-2368)
[SLVS-2368]: https://sonarsource.atlassian.net/browse/SLVS-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2368 Update dependency risks store

---

src/IssueViz.Security.UnitTests/DependencyRisks/ShowDependencyRiskInBrowserHandlerTests.cs
src/IssueViz.Security/DependencyRisks/ShowDependencyRiskInBrowserHandler.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx
src/IssueViz.Security/ServerIssuesSynchronizer.cs
src/SLCore.UnitTests/Service/DependencyRisks/OpenDependencyRiskInBrowserParamsTests.cs
src/SLCore/Service/DependencyRisks/OpenDependencyRiskInBrowserParams.cs

[SLVS-2372](https://sonarsource.atlassian.net/browse/SLVS-2372)
Part of 
[SLVS-2372]: https://sonarsource.atlassian.net/browse/SLVS-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2372 Implement server navigation

---

src/Core/Telemetry/ITelemetryManager.cs
src/Integration.UnitTests/Telemetry/TelemetryManagerTests.cs
src/Integration/Telemetry/TelemetryManager.cs
src/IssueViz.Security.UnitTests/DependencyRisks/GroupDependencyRiskViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/DependencyRisks/GroupDependencyRiskViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/SLCore/Service/Telemetry/ITelemetrySLCoreService.cs

[SLVS-2373](https://sonarsource.atlassian.net/browse/SLVS-2373)
Part of 
[SLVS-2373]: https://sonarsource.atlassian.net/browse/SLVS-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2373 Add telemetry for Dependency Risk local investigation

---

src/EmbeddedSonarAnalyzer.props
src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRisksStoreTests.cs
src/IssueViz.Security/DependencyRisks/DependencyRisksStore.cs
src/SLCore.Listeners.UnitTests/Implementation/DependencyRisksListenerTests.cs
src/SLCore.Listeners/Implementation/DependencyRisksListener.cs

[SLVS-2449](https://sonarsource.atlassian.net/browse/SLVS-2449)
Part of SLVS-2359
[SLVS-2449]: https://sonarsource.atlassian.net/browse/SLVS-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2449 Introduce DependencyRisksStore Update, remove Remove, update SLCore

---

src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs

[SLVS-2453](https://sonarsource.atlassian.net/browse/SLVS-2453)
Part of SLVS-2340
[SLVS-2453]: https://sonarsource.atlassian.net/browse/SLVS-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2453 Fix QG

---

src/SLCore.Listeners/Implementation/DependencyRisksListener.cs
src/SLCore/SLCoreStrings.Designer.cs
src/SLCore/SLCoreStrings.resx

[SLVS-2451](https://sonarsource.atlassian.net/browse/SLVS-2451)
Part of SLVS-2359
[SLVS-2451]: https://sonarsource.atlassian.net/browse/SLVS-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2451 Log dependency risk update count

---

src/Integration.Vsix.UnitTests/CFamily/CmdBuilderTests.cs
src/Integration.Vsix/CFamily/VcxProject/CmdBuilder.cs

[SLVS-2369](https://sonarsource.atlassian.net/browse/SLVS-2369)
Part of 
[SLVS-2369]: https://sonarsource.atlassian.net/browse/SLVS-2369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2369 Filter out white space path list options

---

src/ConnectedMode/UI/Resources/UiResources.Designer.cs
src/ConnectedMode/UI/Resources/UiResources.resx
src/Education.UnitTests/XamlGenerator/XamlGeneratorHelperTests.cs
src/Education/Resources.Designer.cs
src/Education/Resources.resx
src/Education/XamlGenerator/XamlGeneratorHelper.cs

[SLVS-2393](https://sonarsource.atlassian.net/browse/SLVS-2393)
[SLVS-2393]: https://sonarsource.atlassian.net/browse/SLVS-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2393 Remove Clean code occurrences

---

src/Integration.UnitTests/Transition/MuteViewModelTests.cs
src/Integration.UnitTests/Transition/StatusViewModelTests.cs
src/Integration/Transition/MuteViewModel.cs
src/Integration/Transition/StatusViewModel.cs
src/IssueViz.Security.UnitTests/ReviewStatus/ChangeStatusViewModelTest.cs
src/IssueViz.Security/ReviewStatus/ChangeStatusViewModel.cs
src/IssueViz.Security/ReviewStatus/ChangeStatusWindow.xaml
src/IssueViz.Security/ReviewStatus/ChangeStatusWindow.xaml.cs
src/IssueViz.Security/ReviewStatus/IStatusViewModel.cs

[SLVS-2458](https://sonarsource.atlassian.net/browse/SLVS-2458)
[SLVS-2458]: https://sonarsource.atlassian.net/browse/SLVS-2458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2458 Fix radio buttons from change status window can not be selected anymore in some conditions

---

README.MD

[SLVS-2460](https://sonarsource.atlassian.net/browse/SLVS-2460)
[SLVS-2460]: https://sonarsource.atlassian.net/browse/SLVS-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2460 Update GitHub repo descriptions

---

src/RoslynAnalyzerServer.UnitTests/Analysis/Configuration/RoslynAnalysisProfilesProviderTests.cs
src/RoslynAnalyzerServer/Analysis/Configuration/RoslynAnalysisProfilesProvider.cs

[SLVS-2483](https://sonarsource.atlassian.net/browse/SLVS-2483)
Part of SLVS-2406
[SLVS-2483]: https://sonarsource.atlassian.net/browse/SLVS-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2483 Add RoslynAnalysisProfilesProvider

---

.cirrus.yaml

[SLVS-2472](https://sonarsource.atlassian.net/browse/SLVS-2472)
[SLVS-2472]: https://sonarsource.atlassian.net/browse/SLVS-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2472 Fix IRIS Invocation

---

src/EmbeddedSonarAnalyzer.props
src/RoslynAnalyzerServer/Analysis/Wrappers/RoslynProjectWrapper.cs

[SLVS-2505](https://sonarsource.atlassian.net/browse/SLVS-2505)
[SLVS-2505]: https://sonarsource.atlassian.net/browse/SLVS-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2505 Make sure razor analysis for VB.NET files works

---

build/CopyDependencies/CopyDependencies.targets
build/DownloadDependencies/CommonProperties.props
build/DownloadDependencies/JarProcessing.targets
src/EmbeddedSonarAnalyzer.props

[SLVS-2403](https://sonarsource.atlassian.net/browse/SLVS-2403)
1.0.0.11 was chosen because it's the latest master branch version available from the plugin.
[SLVS-2403]: https://sonarsource.atlassian.net/browse/SLVS-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2403 Configure CI/CD pipeline

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2507](https://sonarsource.atlassian.net/browse/SLVS-2507)
[SLVS-2507]: https://sonarsource.atlassian.net/browse/SLVS-2507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2507 Update to latest SlCore

---

src/Core/DocumentEvents.cs
src/Integration.Vsix.UnitTests/Analysis/DocumentEventsHandlerTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TaggerProviderTests.cs
src/Integration.Vsix.UnitTests/SonarLintTagger/TextBufferIssueTrackerTests.cs
src/Integration.Vsix/Analysis/DocumentEventsHandler.cs
src/Integration.Vsix/SonarLintTagger/TaggerProvider.cs

[SLVS-2514](https://sonarsource.atlassian.net/browse/SLVS-2514)
[SLVS-2514]: https://sonarsource.atlassian.net/browse/SLVS-2514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2514 Introduce DocumentUpdated event

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2554](https://sonarsource.atlassian.net/browse/SLVS-2554)
Part of SLVS-2337
[SLVS-2554]: https://sonarsource.atlassian.net/browse/SLVS-2554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2554 Update SQVS Roslyn Plugin to 1.0.0.36 master build

---

src/Core.UnitTests/LanguageTests.cs
src/RoslynAnalyzerServer.UnitTests/Http/AnalysisRequestHandlerTest.cs
src/RoslynAnalyzerServer.UnitTests/Http/HttpRequestHandlerTest.cs
src/RoslynAnalyzerServer/Http/AnalysisRequestHandler.cs
src/RoslynAnalyzerServer/Http/HttpRequestHandler.cs
src/RoslynAnalyzerServer/Http/RoslynAnalysisHttpServer.cs
src/RoslynAnalyzerServer/Http/SecureStringExtensions.cs

[SLVS-2555](https://sonarsource.atlassian.net/browse/SLVS-2555)
Part of SLVS-2337
[SLVS-2555]: https://sonarsource.atlassian.net/browse/SLVS-2555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2555 Fix QG

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2549](https://sonarsource.atlassian.net/browse/SLVS-2549)
Part of 
[SLVS-2549]: https://sonarsource.atlassian.net/browse/SLVS-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2549 Update text to 2.28.0.7967

---

src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/IssueViz/IssueVisualizationControl/ViewModels/Commands/NavigateToRuleDescriptionCommand.cs

[SLVS-2526](https://sonarsource.atlassian.net/browse/SLVS-2526)
This targets the [PR](https://github.com/SonarSource/sonarlint-visualstudio/pull/6420) in which the hotspots have been added to the report view panel
[SLVS-2526]: https://sonarsource.atlassian.net/browse/SLVS-2526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2526 Implement show rule help

---

src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/IssueVizSecurityPackage.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs
src/IssueViz.Security/ReportView/Taints/TaintsReportViewModel.cs
src/IssueViz.Security/ReportView/ToolWindowNavigator.cs
src/IssueViz.Security/Resources.Designer.cs
src/IssueViz.Security/Resources.resx

[SLVS-2531](https://sonarsource.atlassian.net/browse/SLVS-2531)
[SLVS-2531]: https://sonarsource.atlassian.net/browse/SLVS-2531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2531 Implement "Show issue visualization" context menu item for taints

---

src/IssueViz.Security/ReportView/ReportViewControl.xaml

[SLVS-2547](https://sonarsource.atlassian.net/browse/SLVS-2547)
[SLVS-2547]: https://sonarsource.atlassian.net/browse/SLVS-2547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2547 Add virtualization for TreeView to improve performance

---

src/IssueViz.Security.UnitTests/ReportView/FilteringTests.cs
src/IssueViz.Security.UnitTests/ReportView/Filters/IssueTypeFilterToTextConverterTest.cs
src/IssueViz.Security.UnitTests/ReportView/Filters/ReportViewFilterViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security/DependencyRisks/GroupDependencyRiskViewModel.cs
src/IssueViz.Security/ReportView/Filters/IssueTypeFilterToTextConverter.cs
src/IssueViz.Security/ReportView/Filters/ReportViewFilterViewModel.cs
src/IssueViz.Security/ReportView/IGroupViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/ReportViewToolWindow.cs

[SLVS-2535](https://sonarsource.atlassian.net/browse/SLVS-2535)
[SLVS-2534]: https://sonarsource.atlassian.net/browse/SLVS-2534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2535]: https://sonarsource.atlassian.net/browse/SLVS-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2535 Implement filter by location

---

src/IssueViz.Security.UnitTests/DependencyRisks/GroupDependencyRiskViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/FilteringTests.cs
src/IssueViz.Security.UnitTests/ReportView/Filters/ReportViewFilterViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/GroupFileViewModelTest.cs
src/IssueViz.Security/DependencyRisks/GroupDependencyRiskViewModel.cs
src/IssueViz.Security/ReportView/Filters/ReportViewFilterViewModel.cs
src/IssueViz.Security/ReportView/GroupFileViewModel.cs
src/IssueViz.Security/ReportView/IIssueViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml

[SLVS-2537](https://sonarsource.atlassian.net/browse/SLVS-2537)
[SLVS-2537]: https://sonarsource.atlassian.net/browse/SLVS-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2537 Implement filter by severity

---

src/IssueViz.Security.UnitTests/ReportView/Filters/ReportViewFilterViewModelTest.cs
src/IssueViz.Security/ReportView/Filters/ReportViewFilterViewModel.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs

[SLVS-2584](https://sonarsource.atlassian.net/browse/SLVS-2584)
[SLVS-2584]: https://sonarsource.atlassian.net/browse/SLVS-2584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2584 Implement clear all filters button

---

src/IssueViz.Security.UnitTests/DependencyRisks/DependencyRisksReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/FilteringTests.cs
src/IssueViz.Security.UnitTests/ReportView/GroupFileViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/Hotspots/HotspotsReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/ReportViewModelTest.cs
src/IssueViz.Security.UnitTests/ReportView/Taints/TaintsReportViewModelTest.cs
src/IssueViz.Security/DependencyRisks/DependencyRisksReportViewModel.cs
src/IssueViz.Security/Hotspots/LocalHotspotsStore.cs
src/IssueViz.Security/ReportView/GroupFileViewModel.cs
src/IssueViz.Security/ReportView/Hotspots/HotspotsReportViewModel.cs
src/IssueViz.Security/ReportView/IssuesReportViewModelBase.cs
src/IssueViz.Security/ReportView/ReportViewControl.xaml.cs
src/IssueViz.Security/ReportView/ReportViewModel.cs
src/IssueViz.Security/ReportView/Taints/TaintsReportViewModel.cs

[SLVS-2585](https://sonarsource.atlassian.net/browse/SLVS-2585)
[SLVS-2585]: https://sonarsource.atlassian.net/browse/SLVS-2585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2585 Fix silent exceptions due lack of thread safety

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2567](https://sonarsource.atlassian.net/browse/SLVS-2567)
[SLVS-2587](https://sonarsource.atlassian.net/browse/SLVS-2587)
Part of 
[SLVS-2567]: https://sonarsource.atlassian.net/browse/SLVS-2567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLVS-2587]: https://sonarsource.atlassian.net/browse/SLVS-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2567, SLVS-2587 analyzer updates

---

src/EmbeddedSonarAnalyzer.props

[SLVS-2596](https://sonarsource.atlassian.net/browse/SLVS-2596)
Part of SLVS-2336
[SLVS-2596]: https://sonarsource.atlassian.net/browse/SLVS-2596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2596 Update SLCore to 10.33.0.82470

---

src/Core/DocumentationLinks.cs

[SLVS-2599](https://sonarsource.atlassian.net/browse/SLVS-2599)
Part of 
[SLVS-2599]: https://sonarsource.atlassian.net/browse/SLVS-2599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2599 Update to new docs links

---

SonarLint.VsTargetVersion.props
src/CFamily.UnitTests/CFamily.UnitTests.csproj
src/Core.UnitTests/Core.UnitTests.csproj
src/Core/DocumentationLinks.cs
src/Education.UnitTests/Education.UnitTests.csproj
src/Infrastructure.VS.UnitTests/Infrastructure.VS.UnitTests.csproj
src/Integration.UnitTests/Integration.UnitTests.csproj
src/Integration.Vsix.UnitTests/Integration.Vsix.UnitTests.csproj
src/Integration.Vsix/Manifests/VS2022/source.extension.vsixmanifest
src/Integration/UserAgentProvider.cs
src/IssueViz.Security.UnitTests/IssueViz.Security.UnitTests.csproj
src/IssueViz.UnitTests/IssueViz.UnitTests.csproj
src/Roslyn.Suppressions/Roslyn.Suppressions.UnitTests/Roslyn.Suppressions.UnitTests.csproj
src/Roslyn.Suppressions/Roslyn.Suppressions/SuppressorCodeGen.targets
src/SLCore.IntegrationTests/SLCore.IntegrationTests.csproj
src/SLCore.Listeners.UnitTests/SLCore.Listeners.UnitTests.csproj
src/SLCore.UnitTests/SLCore.UnitTests.csproj
src/SonarLint.Test.props
src/SonarQube.Client.Tests/SonarQube.Client.Tests.csproj
src/TestInfrastructure/TestInfrastructure.csproj
src/TestInfrastructure/TestParallelizationIntegrationTests.cs

[SLVS-2610](https://sonarsource.atlassian.net/browse/SLVS-2610)
Part of 
[SLVS-2610]: https://sonarsource.atlassian.net/browse/SLVS-2610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLVS-2610 Feature/hardening q4 1
